#### Logic for Basic Property Details Web Scraping

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
import time
import numpy as np
import pandas as pd
import os
import random

In [ ]:
# Initialize WebDriver

chrome_options = Options()
chrome_options.add_argument("--disable-http2")
chrome_options.add_argument("--incognito")
chrome_options.add_argument("--disable-blink-features=AutomationControlled")
chrome_options.add_argument("--ignore-certificate-errors")
chrome_options.add_argument("--enable-features=NetworkServiceInProcess")
chrome_options.add_argument("--disable-features=NetworkService")
chrome_options.add_argument(
    "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
)


driver = webdriver.Chrome(options=chrome_options)
url = "https://www.99acres.com/"
driver.get(url)

# Explicit Wait

wait = WebDriverWait(driver, 5)

def wait_for_page_to_load(driver, wait):
    """Wait until the page is fully loaded."""
    title = driver.title
    try:
        wait.until(lambda d: d.execute_script("return document.readyState") == 'complete')
    except:
        print(f"The webpage \"{title}\" did not get fully loaded.\n")
    else:
        print(f"The webpage \"{title}\" did get fully loaded.\n")

wait_for_page_to_load(driver, wait)


try:
    search_bar = wait.until(
        EC.presence_of_element_located((By.XPATH, '//*[@id="keyword2"]'))
    )
except:
    print("Timeout while locating Search Bar.\n")
else:
    search_bar.send_keys("Gurgaon")
    time.sleep(2)

try:
    valid_option = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="0"]'))
    )
except:
    print("Timeout while locating valid search option.\n")
else:
    valid_option.click()
    time.sleep(2)

try:
    search_button = wait.until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="searchform_search_btn"]'))
    )
except:
    print("Timeout while clicking on \"Search\" button.\n")
else:
    search_button.click()
    wait_for_page_to_load(driver, wait)

try:
    residential_apartments = wait.until(EC.element_to_be_clickable((By.XPATH, '//*[@id="1"]/span[2]')))
except:
    print("Timeout while clicking on \"Residential Apartment\" option.\n")
else:
    residential_apartments.click()
    time.sleep(2)

try:
    verified = wait.until(
        EC.element_to_be_clickable((By.XPATH, '/html[1]/body[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[1]/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/span[2]'))
    )
    verified.click()
    time.sleep(2)
except:
    print("Timeout while clicking on \"Verified\" filter.\n")

def handle_popup():
    try:
        popup_button = driver.find_element(By.XPATH, '//*[@id="app"]/div/div[3]/div/div[2]/button')
        popup_button.click()
        time.sleep(2)
    except NoSuchElementException:
        pass

# Navigate pages and extract data

all_properties = []  
page_count = 0

while True:
    page_count += 1
    print(f"\n--- PAGE {page_count} ---")
    print("time:", time.strftime('%Y-%m-%d %H:%M:%S'))
    print("session_id:", driver.session_id)

    # ---- ADD THROTTLING ----
    
    if page_count % 3 == 0:
        print("Throttling: sleeping 3s...")
        time.sleep(3)
    if page_count % 5 == 0:
        print("Throttling: sleeping 10s...")
        time.sleep(3)

    try:
        time.sleep(10)
        next_page_button = driver.find_element(By.XPATH, "//a[normalize-space()='Next Page >']")
    except:
        print(f"\n [COMPLETED] Scraping finished. Total pages navigated: {page_count}.\n")
        break
    else:
        try:
            driver.execute_script("window.scrollBy(0, arguments[0].getBoundingClientRect().top - 100);", next_page_button)
            time.sleep(10)

            main_container = driver.find_element(By.CSS_SELECTOR, 'div[data-label="SEARCH"]')
            property_containers = main_container.find_elements(By.CLASS_NAME, 'tupleNew__contentWrap')
            print(f"Number of Property Found on page {page_count}: {len(property_containers)}")

            for container in property_containers:
                property_data = {}
                try:
                    try:
                        property_data['property_name'] = container.find_element(By.CLASS_NAME, "tupleNew__propType").text
                    except:
                        property_data['property_name'] = np.nan
                    try:
                        property_data['link'] = container.find_element(By.CLASS_NAME, "tupleNew__propertyHeading.ellipsis").get_attribute("href")
                    except:
                        property_data['link'] = np.nan
                    try:
                        property_data['society'] = container.find_element(By.CLASS_NAME, "tupleNew__locationName").text
                    except:
                        property_data['society'] = np.nan
                    try:
                        property_data['price'] = container.find_element(By.CLASS_NAME, "tupleNew__priceValWrap").text
                    except:
                        property_data['price'] = np.nan
                    try:
                        property_data['area'] = container.find_element(By.CSS_SELECTOR, "div.tupleNew__perSqftWrap.ellipsis").text
                    except:
                        property_data['area'] = np.nan
                    try:
                        area1 = container.find_element(By.CLASS_NAME, "tupleNew__area1Type").text
                    except:
                        area1 = ""
                    try:
                        area2 = container.find_element(By.CLASS_NAME, "tupleNew__area2Type").text
                    except:
                        area2 = ""
                    try:
                        area_type = container.find_element(By.CLASS_NAME, "tupleNew__areaType").text
                    except:
                        area_type = ""

                    property_data['areawithtype'] = f"{area1} {area2} {area_type}".strip()
                    all_properties.append(property_data)

                except:
                    print("Not able to extract property details!!")

            next_page_button = wait.until(
                EC.presence_of_element_located((By.XPATH, "//a[normalize-space()='Next Page >']"))
                                            )
            driver.execute_script("arguments[0].click();", next_page_button)
            print("✔ Next page clicked successfully")
            time.sleep(5)

        except Exception as e:
            print("Timeout or error while clicking on Next Page:", e)

The webpage "India Real Estate Property Site - Buy Sell Rent Properties Portal - 99acres.com" did get fully loaded.

The webpage "Property in Gurgaon - Real Estate in Gurgaon" did get fully loaded.


--- PAGE 1 ---
time: 2025-10-29 15:02:04
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 1: 78
✔ Next page clicked successfully

--- PAGE 2 ---
time: 2025-10-29 15:03:28
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 2: 51
✔ Next page clicked successfully

--- PAGE 3 ---
time: 2025-10-29 15:04:37
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 3: 26
✔ Next page clicked successfully

--- PAGE 4 ---
time: 2025-10-29 15:05:24
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 4: 26
✔ Next page clicked successfully

--- PAGE 5 ---
time: 2025-10-29 15:06:09
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 10s...
Number of Property Found on page 5: 26
✔ Next page clicked successfully

--- PAGE 6 ---
time: 2025-10-29 15:06:57
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 6: 26
✔ Next page clicked successfully

--- PAGE 7 ---
time: 2025-10-29 15:07:48
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 7: 26
✔ Next page clicked successfully

--- PAGE 8 ---
time: 2025-10-29 15:08:34
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 8: 26
✔ Next page clicked successfully

--- PAGE 9 ---
time: 2025-10-29 15:09:20
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 9: 26
✔ Next page clicked successfully

--- PAGE 10 ---
time: 2025-10-29 15:10:10
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 10s...
Number of Property Found on page 10: 26
✔ Next page clicked successfully

--- PAGE 11 ---
time: 2025-10-29 15:11:00
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 11: 26
✔ Next page clicked successfully

--- PAGE 12 ---
time: 2025-10-29 15:11:47
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 12: 26
✔ Next page clicked successfully

--- PAGE 13 ---
time: 2025-10-29 15:12:39
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 13: 26
✔ Next page clicked successfully

--- PAGE 14 ---
time: 2025-10-29 15:13:25
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 14: 26
✔ Next page clicked successfully

--- PAGE 15 ---
time: 2025-10-29 15:14:11
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Throttling: sleeping 10s...
Number of Property Found on page 15: 26
✔ Next page clicked successfully

--- PAGE 16 ---
time: 2025-10-29 15:15:03
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 16: 26
✔ Next page clicked successfully

--- PAGE 17 ---
time: 2025-10-29 15:15:50
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 17: 26
✔ Next page clicked successfully

--- PAGE 18 ---
time: 2025-10-29 15:16:37
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 18: 26
✔ Next page clicked successfully

--- PAGE 19 ---
time: 2025-10-29 15:17:24
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 19: 26
✔ Next page clicked successfully

--- PAGE 20 ---
time: 2025-10-29 15:18:08
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 10s...
Number of Property Found on page 20: 26
✔ Next page clicked successfully

--- PAGE 21 ---
time: 2025-10-29 15:18:54
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 21: 26
✔ Next page clicked successfully

--- PAGE 22 ---
time: 2025-10-29 15:19:41
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 22: 26
✔ Next page clicked successfully

--- PAGE 23 ---
time: 2025-10-29 15:20:27
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 23: 26
✔ Next page clicked successfully

--- PAGE 24 ---
time: 2025-10-29 15:21:12
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 24: 26
✔ Next page clicked successfully

--- PAGE 25 ---
time: 2025-10-29 15:22:00
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 10s...
Number of Property Found on page 25: 26
✔ Next page clicked successfully

--- PAGE 26 ---
time: 2025-10-29 15:22:51
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 26: 26
✔ Next page clicked successfully

--- PAGE 27 ---
time: 2025-10-29 15:23:40
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 27: 26
✔ Next page clicked successfully

--- PAGE 28 ---
time: 2025-10-29 15:24:30
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 28: 25
✔ Next page clicked successfully

--- PAGE 29 ---
time: 2025-10-29 15:25:17
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 29: 26
✔ Next page clicked successfully

--- PAGE 30 ---
time: 2025-10-29 15:26:08
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Throttling: sleeping 10s...
Number of Property Found on page 30: 26
✔ Next page clicked successfully

--- PAGE 31 ---
time: 2025-10-29 15:27:00
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 31: 26
✔ Next page clicked successfully

--- PAGE 32 ---
time: 2025-10-29 15:27:46
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 32: 26
✔ Next page clicked successfully

--- PAGE 33 ---
time: 2025-10-29 15:28:32
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 33: 26
✔ Next page clicked successfully

--- PAGE 34 ---
time: 2025-10-29 15:29:22
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 34: 26
✔ Next page clicked successfully

--- PAGE 35 ---
time: 2025-10-29 15:30:13
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 10s...
Number of Property Found on page 35: 26
✔ Next page clicked successfully

--- PAGE 36 ---
time: 2025-10-29 15:31:04
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 36: 26
✔ Next page clicked successfully

--- PAGE 37 ---
time: 2025-10-29 15:31:53
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 37: 26
✔ Next page clicked successfully

--- PAGE 38 ---
time: 2025-10-29 15:32:39
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 38: 26
✔ Next page clicked successfully

--- PAGE 39 ---
time: 2025-10-29 15:33:26
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 39: 26
✔ Next page clicked successfully

--- PAGE 40 ---
time: 2025-10-29 15:34:20
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 10s...
Number of Property Found on page 40: 26
✔ Next page clicked successfully

--- PAGE 41 ---
time: 2025-10-29 15:35:10
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 41: 26
✔ Next page clicked successfully

--- PAGE 42 ---
time: 2025-10-29 15:36:00
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 42: 26
✔ Next page clicked successfully

--- PAGE 43 ---
time: 2025-10-29 15:36:51
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 43: 26
✔ Next page clicked successfully

--- PAGE 44 ---
time: 2025-10-29 15:37:38
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 44: 26
✔ Next page clicked successfully

--- PAGE 45 ---
time: 2025-10-29 15:38:29
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Throttling: sleeping 10s...
Number of Property Found on page 45: 26
✔ Next page clicked successfully

--- PAGE 46 ---
time: 2025-10-29 15:39:23
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 46: 26
✔ Next page clicked successfully

--- PAGE 47 ---
time: 2025-10-29 15:40:10
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Number of Property Found on page 47: 26
✔ Next page clicked successfully

--- PAGE 48 ---
time: 2025-10-29 15:41:03
session_id: f22cbee54a3175921fe4eeff7d0d30dd
Throttling: sleeping 3s...
Number of Property Found on page 48: 26
✔ Next page clicked successfully

--- PAGE 49 ---
time: 2025-10-29 15:41:53
session_id: f22cbee54a3175921fe4eeff7d0d30dd

 [COMPLETED] Scraping finished. Total pages navigated: 49.

In [16]:
all_properties

[{'property_name': '2 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-tata-gurgaon-gateway-sector-112-gurgaon-1580-sq-ft-spid-L84924514',
  'society': 'Tata Gurgaon Gateway',
  'price': '₹2.4 Cr',
  'area': '₹15,189 /sqft',
  'areawithtype': '1,580 sqft (147 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 104, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-hero-homes-sector-104-gurgaon-1689-sq-ft-spid-D85625548',
  'society': 'Hero Homes',
  'price': '₹2.38 Cr',
  'area': '₹14,091 /sqft',
  'areawithtype': '1,689 sqft (157 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 106, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-paras-dews-sector-106-gurgaon-1760-sq-ft-spid-I85922364',
  'society': 'Paras Dews',
  'price': '₹1.95 Cr',
  'area': '₹11,079 /sqft',
  'areawithtype': '1,760 sqft (164 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in DLF Phase 5, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-dlf-carlton-estate-dlf-phase-5-gurgaon-1365-sq-ft-spid-H84517400',
  'society': 'DLF Carlton Estate',
  'price': '₹3.25 Cr',
  'area': '₹23,809 /sqft',
  'areawithtype': '1,365 sqft (127 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 53, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-parsvnath-exotica-sector-53-gurgaon-3390-sq-ft-spid-S83698522',
  'society': 'Parsvnath Exotica',
  'price': '₹9.9 Cr',
  'area': '₹29,203 /sqft',
  'areawithtype': '3,390 sqft (315 sqm) Super Built-up Area'},
 {'property_name': '',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bestech-altura-sector-79-gurgaon-975-sq-ft-spid-H86173858',
  'society': '',
  'price': '',
  'area': '',
  'areawithtype': ''},
 {'property_name': '3 BHK Flat in Sector 109, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-ats-tourmaline-sector-109-gurgaon-2150-sq-ft-spid-E78249641',
  'society': 'ATS Tourmaline',
  'price': '₹2.57 Cr',
  'area': '₹18,623 /sqft',
  'areawithtype': '2,150 sqft (200 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 102, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-emaar-imperial-gardens-sector-102-gurgaon-2025-sq-ft-spid-K85040518',
  'society': 'Emaar Imperial Gardens',
  'price': '₹2.4 Cr',
  'area': '₹11,851 /sqft',
  'areawithtype': '2,025 sqft (188 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 102, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-emaar-imperial-gardens-sector-102-gurgaon-2025-sq-ft-spid-J84944584',
  'society': 'Emaar Imperial Gardens',
  'price': '₹2.37 Cr',
  'area': '₹11,703 /sqft',
  'areawithtype': '2,025 sqft (188 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bestech-park-view-grand-spa-sector-81-gurgaon-2660-sq-ft-spid-D85068646',
  'society': 'Bestech Park View Grand Spa',
  'price': '₹3.45 Cr',
  'area': '₹12,969 /sqft',
  'areawithtype': '2,660 sqft (247 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 85, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-pyramid-heights-sector-85-gurgaon-591-sq-ft-spid-F85395258',
  'society': 'Pyramid Heights',
  'price': '₹74 Lac',
  'area': '₹12,517 /sqft',
  'areawithtype': '591 sqft (55 sqm) Carpet Area'},
 {'property_name': '3 BHK Flat in Sector 108, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sobha-city-sector-108-gurgaon-2072-sq-ft-r1-spid-R82389998',
  'society': 'Sobha City',
  'price': '₹4.29 Cr',
  'area': '₹20,704 /sqft',
  'areawithtype': '2,072 sqft (193 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 62, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-pioneer-urban-presidia-sector-62-gurgaon-3890-sq-ft-spid-J84806838',
  'society': 'Pioneer Urban Presidia',
  'price': '₹9.65 Cr',
  'area': '₹24,807 /sqft',
  'areawithtype': '3,890 sqft (361 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 92, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-dlf-garden-city-floors-sector-92-gurgaon-2700-sq-ft-spid-T85267222',
  'society': 'DLF Garden City Floors',
  'price': '₹3.5 Cr',
  'area': '₹12,962 /sqft',
  'areawithtype': '2,700 sqft (251 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 109, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-ats-tourmaline-sector-109-gurgaon-1750-sq-ft-r1-spid-P81201127',
  'society': 'ATS Tourmaline',
  'price': '₹2.07 Cr',
  'area': '₹17,107 /sqft',
  'areawithtype': '1,750 sqft (163 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 69, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-tulip-violet-sector-69-gurgaon-2010-sq-ft-spid-T84849638',
  'society': 'Tulip Violet',
  'price': '₹3.3 Cr',
  'area': '₹18,333 /sqft',
  'areawithtype': '2,010 sqft (187 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 79, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bestech-altura-sector-79-gurgaon-2015-sq-ft-r1-spid-I83458576',
  'society': 'Bestech Altura',
  'price': '₹2.62 Cr',
  'area': '₹13,002 /sqft',
  'areawithtype': '2,015 sqft (187 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-dlf-the-ultima-sector-81-gurgaon-2103-sq-ft-spid-E81528981',
  'society': 'DLF The Ultima',
  'price': '₹3.57 Cr',
  'area': '₹16,975 /sqft',
  'areawithtype': '2,103 sqft (195 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 79, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bestech-altura-sector-79-gurgaon-2015-sq-ft-r1-spid-C82410956',
  'society': 'Bestech Altura',
  'price': '₹2.43 Cr',
  'area': '₹12,059 /sqft',
  'areawithtype': '2,015 sqft (187 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 70A, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-aipl-the-peaceful-homes-sector-70a-gurgaon-2150-sq-ft-r3-spid-N66661446',
  'society': 'AIPL The Peaceful Homes',
  'price': '₹3.55 Cr',
  'area': '₹16,511 /sqft',
  'areawithtype': '2,150 sqft (200 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 102, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shapoorji-pallonji-joyville-gurugram-sector-102-gurgaon-1852-sq-ft-spid-Q85232920',
  'society': 'Shapoorji Pallonji Joyville Gurugram',
  'price': '₹2.65 Cr',
  'area': '₹20,075 /sqft',
  'areawithtype': '1,852 sqft (172 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 89, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-greenopolis-sector-89-gurgaon-1910-sq-ft-spid-C85506040',
  'society': 'Greenopolis',
  'price': '₹1.8 Cr',
  'area': '₹9,424 /sqft',
  'areawithtype': '1,910 sqft (177 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 86, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-dlf-the-skycourt-sector-86-gurgaon-1929-sq-ft-spid-I85804622',
  'society': 'DLF The Skycourt',
  'price': '₹2.33 Cr',
  'area': '₹12,052 /sqft',
  'areawithtype': '1,929 sqft (179 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sohna, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-eldeco-acclaim-sohna-gurgaon-1269-sq-ft-spid-U85294604',
  'society': 'Eldeco Acclaim',
  'price': '₹1.32 Cr',
  'area': '₹10,401 /sqft',
  'areawithtype': '1,269 sqft (118 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 66, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-emaar-mgf-palm-terraces-sector-66-gurgaon-2100-sq-ft-spid-P84830654',
  'society': 'Emaar MGF Palm Terraces',
  'price': '₹3.75 Cr',
  'area': '₹17,857 /sqft',
  'areawithtype': '2,100 sqft (195 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 65, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-m3m-heights-sector-65-gurgaon-1261-sq-ft-spid-R85483240',
  'society': 'M3M Heights',
  'price': '₹2.48 Cr',
  'area': '₹19,666 /sqft',
  'areawithtype': '1,261 sqft (117 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 89, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-greenopolis-sector-89-gurgaon-1957-sq-ft-spid-N85506286',
  'society': 'Greenopolis',
  'price': '₹1.83 Cr',
  'area': '₹9,351 /sqft',
  'areawithtype': '1,957 sqft (182 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 108, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sobha-city-sector-108-gurgaon-2072-sq-ft-r8-spid-M67442410',
  'society': 'Sobha City',
  'price': '₹4.15 Cr',
  'area': '₹20,028 /sqft',
  'areawithtype': '2,072 sqft (193 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-experion-windchants-sector-112-gurgaon-2441-sq-ft-spid-N84901782',
  'society': 'Experion Windchants',
  'price': '₹3.8 Cr',
  'area': '₹15,567 /sqft',
  'areawithtype': '2,441 sqft (227 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-experion-windchants-sector-112-gurgaon-2441-sq-ft-spid-A84900926',
  'society': 'Experion Windchants',
  'price': '₹3.85 Cr',
  'area': '₹15,772 /sqft',
  'areawithtype': '2,441 sqft (227 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Nirvana Country, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-unitech-escape-nirvana-country-gurgaon-2066-sq-ft-spid-Q84615198',
  'society': 'Unitech Escape',
  'price': '₹3 Cr',
  'area': '₹14,520 /sqft',
  'areawithtype': '2,066 sqft (192 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-experion-windchants-sector-112-gurgaon-4848-sq-ft-spid-D84900518',
  'society': 'Experion Windchants',
  'price': '₹7.55 Cr',
  'area': '₹15,573 /sqft',
  'areawithtype': '4,848 sqft (450 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 104, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-ats-triumph-sector-104-gurgaon-3150-sq-ft-spid-K78440425',
  'society': 'ATS Triumph',
  'price': '₹3.85 Cr',
  'area': '₹12,222 /sqft',
  'areawithtype': '3,150 sqft (293 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bestech-park-view-grand-spa-sector-81-gurgaon-2660-sq-ft-spid-E86068204',
  'society': 'Bestech Park View Grand Spa',
  'price': '₹3.5 Cr',
  'area': '₹13,157 /sqft',
  'areawithtype': '2,660 sqft (247 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 82, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-vatika-the-seven-lamps-sector-82-gurgaon-1430-sq-ft-spid-P84977920',
  'society': 'Vatika The Seven Lamps',
  'price': '₹1.6 Cr',
  'area': '₹11,188 /sqft',
  'areawithtype': '1,430 sqft (133 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-dlf-the-ultima-sector-81-gurgaon-2872-sq-ft-spid-X81530551',
  'society': 'DLF The Ultima',
  'price': '₹4.97 Cr',
  'area': '₹17,305 /sqft',
  'areawithtype': '2,872 sqft (267 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 85, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-ss-the-leaf-sector-85-gurgaon-1741-sq-ft-spid-O85147390',
  'society': 'SS The Leaf',
  'price': '₹1.85 Cr',
  'area': '₹10,626 /sqft',
  'areawithtype': '1,741 sqft (162 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-experion-windchants-sector-112-gurgaon-4848-sq-ft-spid-R82586554',
  'society': 'Experion Windchants',
  'price': '₹8.1 Cr',
  'area': '₹16,707 /sqft',
  'areawithtype': '4,848 sqft (450 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-dlf-the-ultima-sector-81-gurgaon-2872-sq-ft-spid-O81529865',
  'society': 'DLF The Ultima',
  'price': '₹4.81 Cr',
  'area': '₹16,747 /sqft',
  'areawithtype': '2,872 sqft (267 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-bestech-spa-signature-sector-81-gurgaon-4200-sq-ft-spid-W83198666',
  'society': 'Bestech Spa Signature',
  'price': '₹5.3 Cr',
  'area': '₹12,619 /sqft',
  'areawithtype': '4,200 sqft (390 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 108, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sobha-city-sector-108-gurgaon-1711-sq-ft-spid-U84976254',
  'society': 'Sobha City',
  'price': '₹3.45 Cr',
  'area': '₹20,163 /sqft',
  'areawithtype': '1,711 sqft (159 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 86, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-dlf-the-skycourt-sector-86-gurgaon-1929-sq-ft-spid-H84605000',
  'society': 'DLF The Skycourt',
  'price': '₹2.26 Cr',
  'area': '₹11,689 /sqft',
  'areawithtype': '1,929 sqft (179 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 99, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-vatika-sovereign-park-sector-99-gurgaon-2780-sq-ft-spid-V82597940',
  'society': 'Vatika Sovereign Park',
  'price': '₹3.65 Cr',
  'area': '₹13,129 /sqft',
  'areawithtype': '2,780 sqft (258 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 92, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-sare-homes-sector-92-gurgaon-2248-sq-ft-spid-E85402802',
  'society': 'Sare Homes',
  'price': '₹2.2 Cr',
  'area': '₹9,786 /sqft',
  'areawithtype': '2,248 sqft (209 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 99A, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-pareena-coban-residences-sector-99a-gurgaon-1997-sq-ft-spid-U83991084',
  'society': 'Pareena Coban Residences',
  'price': '₹2.1 Cr',
  'area': '₹10,515 /sqft',
  'areawithtype': '1,997 sqft (186 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 65, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-m3m-golfestate-sector-65-gurgaon-2979-sq-ft-spid-F85028194',
  'society': 'M3M Golfestate',
  'price': '₹8 Cr',
  'area': '₹26,854 /sqft',
  'areawithtype': '2,979 sqft (277 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 37D, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-signature-global-city-37d-ph-2-sector-37d-gurgaon-1060-sq-ft-r1-spid-U80833251',
  'society': 'Signature Global City 37D Ph 2',
  'price': '₹1.4 Cr',
  'area': '₹13,207 /sqft',
  'areawithtype': '1,060 sqft (98 sqm) Carpet Area'},
 {'property_name': '3 BHK Flat in Nirvana Country, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-the-close-north-nirvana-country-gurgaon-2130-sq-ft-spid-M85178894',
  'society': 'The Close North',
  'price': '₹3.46 Cr',
  'area': '₹16,244 /sqft',
  'areawithtype': '2,130 sqft (198 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 104, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-hero-homes-sector-104-gurgaon-1689-sq-ft-spid-H85230422',
  'society': 'Hero Homes',
  'price': '₹2.4 Cr',
  'area': '₹14,209 /sqft',
  'areawithtype': '1,689 sqft (157 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 57, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bptp-freedom-park-life-sector-57-gurgaon-2293-sq-ft-spid-H85048878',
  'society': 'BPTP Freedom Park Life',
  'price': '₹3.4 Cr',
  'area': '₹14,827 /sqft',
  'areawithtype': '2,293 sqft (213 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 60, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-ireo-skyon-sector-60-gurgaon-2800-sq-ft-spid-W84942998',
  'society': 'Ireo Skyon',
  'price': '₹6.25 Cr',
  'area': '₹22,321 /sqft',
  'areawithtype': '2,800 sqft (260 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-experion-windchants-sector-112-gurgaon-4848-sq-ft-spid-T85705352',
  'society': 'Experion Windchants',
  'price': '₹7.38 Cr',
  'area': '₹15,222 /sqft',
  'areawithtype': '4,848 sqft (450 sqm) Super Built-up Area'},
 {'property_name': '2 BHK Flat in Sector 65, Gurgaon',
  'link': 'https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-m3m-heights-sector-65-gurgaon-1261-sq-ft-spid-O85620146',
  'society': 'M3M Heights',
  'price': '₹2.26 Cr',
  'area': '₹17,922 /sqft',
  'areawithtype': '1,261 sqft (117 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 102, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-emaar-imperial-gardens-sector-102-gurgaon-2000-sq-ft-r1-spid-T80940217',
  'society': 'Emaar Imperial Gardens',
  'price': '₹2.4 Cr',
  'area': '₹12,000 /sqft',
  'areawithtype': '2,000 sqft (186 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 47, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-bestech-park-view-spa-sector-47-gurgaon-3125-sq-ft-r1-spid-G82170132',
  'society': 'Bestech Park View Spa',
  'price': '₹7.35 Cr',
  'area': '₹23,520 /sqft',
  'areawithtype': '3,125 sqft (290 sqm) Super Built-up Area'},
 {'property_name': '4 BHK Flat in Sector 82, Gurgaon',
  'link': 'https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-mapsko-royale-ville-sector-82-gurgaon-3500-sq-ft-spid-T84704172',
  'society': 'Mapsko Royale Ville',
  'price': '₹4 Cr',
  'area': '₹12,028 /sqft',
  'areawithtype': '3,500 sqft (325 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 65, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-m3m-golfestate-sector-65-gurgaon-3866-sq-ft-spid-O84976294',
  'society': 'M3M Golfestate',
  'price': '₹8.25 Cr',
  'area': '₹21,339 /sqft',
  'areawithtype': '3,866 sqft (359 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 112, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-experion-windchants-sector-112-gurgaon-2802-sq-ft-r9-spid-J55763770',
  'society': 'Experion Windchants',
  'price': '₹4.92 Cr',
  'area': '₹17,558 /sqft',
  'areawithtype': '2,802 sqft (260 sqm) Super Built-up Area'},
 {'property_name': '3 BHK Flat in Sector 81, Gurgaon',
  'link': 'https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-dlf-the-ultima-sector-81-gurgaon-2092-sq-ft-spid-O84730646',
  'society': 'DLF The Ultima',

In [ ]:
Apartment_df = pd.DataFrame(all_properties)

In [ ]:
Apartment_df.to_csv(r'C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apart_basic_details.csv', index= False)

In [ ]:
residential_apar_basic_details = pd.read_csv(r'C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apart_basic_details.csv')

In [42]:
residential_apar_basic_details.duplicated().sum()

0

In [43]:
residential_apar_basic_details.shape

(2460, 6)

In [44]:
residential_apar_basic_details.isnull().sum()

property_name    0
link             0
society          0
price            0
area             0
areawithtype     0
dtype: int64

### Logic for Detailed Property Page

In [ ]:
# 1. HELPER FUNCTIONS

def wait_for_page_to_load(driver, timeout=15):
    WebDriverWait(driver, timeout).until(
        lambda d: d.execute_script("return document.readyState") == "complete"
    )


def get_text(driver, by, value):
    try:
        return driver.find_element(by, value).text.strip()
    except:
        return np.nan


def get_list(driver, css_selector):
    try:
        items = driver.find_elements(By.CSS_SELECTOR, css_selector)
        return [i.text.strip() for i in items if i.text.strip()]
    except:
        return []


# 2. SCRAPE SINGLE PROPERTY PAGE

def scrape_details(driver, link, retries=2):
    """
    Scrapes one property detail page.
    Returns dictionary.
    """

    for _ in range(retries):
        try:
            driver.get(link)
            wait_for_page_to_load(driver)

            data = {
                "link": link,
                "bedrooms": get_text(driver, By.ID, "bedRoomNum"),
                "bathrooms": get_text(driver, By.ID, "bathroomNum"),
                "balcony": get_text(driver, By.ID, "balconyNum"),
                "additional_room": get_text(driver, By.ID, "additionalRooms"),
                "floor_info": get_text(driver, By.ID, "floorNumLabel"),
                "facing": get_text(driver, By.ID, "facingLabel"),
                "property_age": get_text(driver, By.ID, "agePossessionLbl"),
                "property_id": get_text(driver, By.ID, "Prop_Id"),
                "furnishing_details": get_list(driver, "#FurnishDetails ul#features li div"),
                "features": get_list(driver, "div[data-label='FACILITIES'] ul#features li div")
            }

            return data

        except Exception:
            time.sleep(3)

    return {"link": link}


# 3. LOAD INPUT LINKS

input_csv = r"C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apart_basic_details.csv"
output_file = r"C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apart_detailed_page.xlsx"

df_links = pd.read_csv(input_csv)
links = df_links["link"].dropna().tolist()
total_links = len(links)

# Load existing output 

if os.path.exists(output_file):
    existing_df = pd.read_excel(output_file)
    processed_links = set(existing_df["link"])
else:
    existing_df = pd.DataFrame()
    processed_links = set()

start = int(input("Enter link number to start from (1 for beginning): ")) - 1


# 4. SETUP DRIVER 

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--window-size=1920,1080")
chrome_options.add_argument(
    "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

driver = webdriver.Chrome(options=chrome_options)


# 5. MAIN LOOP 

BATCH_SIZE = 50

try:
    while start < total_links:
        end = min(start + BATCH_SIZE, total_links)
        print(f"\nScraping links {start + 1} to {end} of {total_links}")

        batch_data = []

        for i in range(start, end):
            link = links[i]

            if link in processed_links:
                continue

            print(f"→ Processing {i + 1}/{total_links}")
            data = scrape_details(driver, link)
            batch_data.append(data)

            time.sleep(random.uniform(2, 4))

        if batch_data:
            new_df = pd.DataFrame(batch_data)

            if not existing_df.empty:
                combined_df = (
                    pd.concat([existing_df, new_df])
                    .drop_duplicates(subset=["link"], keep="last")
                    .reset_index(drop=True)
                )
            else:
                combined_df = new_df

            combined_df.to_excel(output_file, index=False)
            existing_df = combined_df
            processed_links.update(new_df["link"].tolist())

            print(f"Saved data up to link {end}")

        start = end

        if start < total_links:
            print("Cooling down...")
            time.sleep(20)

    print("\nAll links processed successfully!")

finally:
    driver.quit()
    print("Driver closed.")

Scraping links 1 to 50 of 2460
Cooling down...

Scraping links 51 to 100 of 2460
Cooling down...

Scraping links 101 to 150 of 2460
Cooling down...

Scraping links 151 to 200 of 2460
Cooling down...

Scraping links 201 to 250 of 2460
Cooling down...

Scraping links 251 to 300 of 2460
Cooling down...

Scraping links 301 to 350 of 2460
Cooling down...

Scraping links 351 to 400 of 2460
Cooling down...

Scraping links 401 to 450 of 2460
Cooling down...

Scraping links 451 to 500 of 2460
Cooling down...

Scraping links 501 to 550 of 2460
Cooling down...

Scraping links 551 to 600 of 2460
Cooling down...

Scraping links 601 to 650 of 2460
Cooling down...

Scraping links 651 to 700 of 2460
Cooling down...

Scraping links 701 to 750 of 2460
Cooling down...

Scraping links 751 to 800 of 2460
Cooling down...

Scraping links 801 to 850 of 2460
Cooling down...

Scraping links 851 to 900 of 2460
Cooling down...

Scraping links 901 to 950 of 2460
Cooling down...

Scraping links 951 to 1000 of 2460
Cooling down...

Scraping links 1001 to 1050 of 2460
Cooling down...

Scraping links 1051 to 1100 of 2460
Cooling down...

Scraping links 1101 to 1150 of 2460
Cooling down...

Scraping links 1151 to 1200 of 2460
Cooling down...

Scraping links 1201 to 1250 of 2460
Cooling down...

Scraping links 1251 to 1300 of 2460
Cooling down...

Scraping links 1301 to 1350 of 2460
Cooling down...

Scraping links 1351 to 1400 of 2460
Cooling down...

Scraping links 1401 to 1450 of 2460
Cooling down...

Scraping links 1451 to 1500 of 2460
Cooling down...

Scraping links 1501 to 1550 of 2460
Cooling down...

Scraping links 1551 to 1600 of 2460
Cooling down...

Scraping links 1601 to 1650 of 2460
Cooling down...

Scraping links 1651 to 1700 of 2460
Cooling down...

Scraping links 1701 to 1750 of 2460
Cooling down...

Scraping links 1751 to 1800 of 2460
Cooling down...

Scraping links 1801 to 1850 of 2460
Cooling down...

Scraping links 1851 to 1900 of 2460
Cooling down...

Scraping links 1901 to 1950 of 2460
Cooling down...

Scraping links 1951 to 2000 of 2460
Cooling down...

Scraping links 2001 to 2050 of 2460
Cooling down...

Scraping links 2051 to 2100 of 2460
Cooling down...

Scraping links 2101 to 2150 of 2460
Cooling down...

Scraping links 2151 to 2200 of 2460
Cooling down...

Scraping links 2201 to 2250 of 2460
Cooling down...

Scraping links 2251 to 2300 of 2460
Cooling down...

Scraping links 2301 to 2350 of 2460
Cooling down...

Scraping links 2351 to 2400 of 2460
Cooling down...

Scraping links 2401 to 2450 of 2460
Cooling down...

Scraping links 2451 to 2460 of 2460

All links processed successfully!
Driver closed.

In [46]:
residential_apar_basic_details

,property_name,link,society,price,area,areawithtype
0,"2 BHK Flat in Sector 112, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area"
1,"3 BHK Flat in Sector 37C, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ramprastha The View,₹1.29 Cr,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area"
2,"4 BHK Flat in Sector 84, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,SS Linden Floors,₹2.9 Cr,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area"
3,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram,₹2.65 Cr,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area"
4,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar Imperial Gardens,₹2.4 Cr,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area"
...,...,...,...,...,...,...
2455,"4 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Adani M2K Oyster Grande,₹3.6 Cr,"₹11,257 /sqft","3,198 sqft (297 sqm) Super Built-up Area"
2456,"3 BHK Flat in Sector 69, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Tulip Yellow,₹2.33 Cr,"₹13,673 /sqft","1,704 sqft (158 sqm) Super Built-up Area"
2457,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram,₹2.6 Cr,"₹14,038 /sqft","1,852 sqft (172 sqm) Super Built-up Area"
2458,"3 BHK Flat in Sector 82, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Mapsko Casa Bella,₹2.05 Cr,"₹10,459 /sqft","1,960 sqft (182 sqm) Super Built-up Area"
2459,"4 BHK Flat in Sector 107, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,M3M Woodshire,₹2.4 Cr,"₹8,739 /sqft","2,746 sqft (255 sqm) Super Built-up Area"

In [47]:
residential_apar_basic_details['property_id']  = residential_apar_basic_details['link'].str.split("spid-").str.get(1)
residential_apar_basic_details

,property_name,link,society,price,area,areawithtype,property_id
0,"2 BHK Flat in Sector 112, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",L84924514
1,"3 BHK Flat in Sector 37C, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ramprastha The View,₹1.29 Cr,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area",W81100115
2,"4 BHK Flat in Sector 84, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,SS Linden Floors,₹2.9 Cr,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area",M80850013
3,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram,₹2.65 Cr,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area",Q85232920
4,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar Imperial Gardens,₹2.4 Cr,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area",K85040518
...,...,...,...,...,...,...,...
2455,"4 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Adani M2K Oyster Grande,₹3.6 Cr,"₹11,257 /sqft","3,198 sqft (297 sqm) Super Built-up Area",G81998138
2456,"3 BHK Flat in Sector 69, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Tulip Yellow,₹2.33 Cr,"₹13,673 /sqft","1,704 sqft (158 sqm) Super Built-up Area",P84081948
2457,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram,₹2.6 Cr,"₹14,038 /sqft","1,852 sqft (172 sqm) Super Built-up Area",W78586891
2458,"3 BHK Flat in Sector 82, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Mapsko Casa Bella,₹2.05 Cr,"₹10,459 /sqft","1,960 sqft (182 sqm) Super Built-up Area",O24958549
2459,"4 BHK Flat in Sector 107, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,M3M Woodshire,₹2.4 Cr,"₹8,739 /sqft","2,746 sqft (255 sqm) Super Built-up Area",P84214334

In [ ]:
residential_apar_detailed_page = pd.read_csv(r"C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apart_detailed_page.csv")
residential_apar_detailed_page

,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,property_id,furnishing_details,features,nearby_location
0,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,L84924514,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'...","['Metro Hospital, Palam Vihar', 'Mount Carmel ..."
1,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,W81100115,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Elan Miracle Mall', 'Holiday Inn Gurugram Se..."
2,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,M80850013,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e...","['AapnoGhar', 'Modern Public School-kherki Dau..."
3,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,Q85232920,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Hyatt Place Gurgaon Udyog Vihar', 'The Espla..."
4,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,K85040518,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Sunrise University', 'Country Inn & Suites b..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2455,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,G81998138,"['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'...","['Gurgaon', 'SGT University', 'Indira Gandhi A..."
2456,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,P84081948,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Hyatt Regency Gurugram', 'De Adventure Park'..."
2457,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,W78586891,"['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',...","['IFFCO Chowk Metro Station', 'The Esplanade M..."
2458,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,O24958549,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['SkyJumper Trampoline Park', 'Pataudi Road', ..."
2459,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,P84214334,"['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'...","['Skylark Cricket Academy', 'Signum 107', 'The..."

In [50]:
residential_apar_detailed_page.duplicated().sum()

0

In [51]:
residential_apar_detailed_page.shape

(2460, 12)

In [52]:
residential_apartment_merge = residential_apar_basic_details.merge(residential_apar_detailed_page, on='property_id',how= 'inner')
residential_apartment_merge

,property_name,link_x,society,price,area,areawithtype,property_id,link_y,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
0,"2 BHK Flat in Sector 112, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'...","['Metro Hospital, Palam Vihar', 'Mount Carmel ..."
1,"3 BHK Flat in Sector 37C, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ramprastha The View,₹1.29 Cr,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area",W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Elan Miracle Mall', 'Holiday Inn Gurugram Se..."
2,"4 BHK Flat in Sector 84, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,SS Linden Floors,₹2.9 Cr,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area",M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e...","['AapnoGhar', 'Modern Public School-kherki Dau..."
3,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram,₹2.65 Cr,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area",Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Hyatt Place Gurgaon Udyog Vihar', 'The Espla..."
4,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar Imperial Gardens,₹2.4 Cr,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area",K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Sunrise University', 'Country Inn & Suites b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,"4 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Adani M2K Oyster Grande,₹3.6 Cr,"₹11,257 /sqft","3,198 sqft (297 sqm) Super Built-up Area",G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'...","['Gurgaon', 'SGT University', 'Indira Gandhi A..."
2456,"3 BHK Flat in Sector 69, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Tulip Yellow,₹2.33 Cr,"₹13,673 /sqft","1,704 sqft (158 sqm) Super Built-up Area",P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Hyatt Regency Gurugram', 'De Adventure Park'..."
2457,"3 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram,₹2.6 Cr,"₹14,038 /sqft","1,852 sqft (172 sqm) Super Built-up Area",W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',...","['IFFCO Chowk Metro Station', 'The Esplanade M..."
2458,"3 BHK Flat in Sector 82, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Mapsko Casa Bella,₹2.05 Cr,"₹10,459 /sqft","1,960 sqft (182 sqm) Super Built-up Area",O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['SkyJumper Trampoline Park', 'Pataudi Road', ..."
2459,"4 BHK Flat in Sector 107, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,M3M Woodshire,₹2.4 Cr,"₹8,739 /sqft","2,746 sqft (255 sqm) Super Built-up Area",P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'...","['Skylark Cricket Academy', 'Signum 107', 'The..."

In [53]:
residential_apartment_merge.isnull().sum()

property_name           0
link_x                  0
society                 0
price                   0
area                    0
areawithtype            0
property_id             0
link_y                  0
bedrooms                0
bathrooms               0
balcony                 0
additional_room       599
floor_info              0
facing                106
property_age            4
furnishing_details    403
features                3
nearby_location         0
dtype: int64

In [54]:
residential_apartment = residential_apartment_merge.drop(columns = ['link_x']).rename(columns ={'link_y':'link'})
residential_apartment

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
0,"2 BHK Flat in Sector 112, Gurgaon",Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'...","['Metro Hospital, Palam Vihar', 'Mount Carmel ..."
1,"3 BHK Flat in Sector 37C, Gurgaon",Ramprastha The View,₹1.29 Cr,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area",W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Elan Miracle Mall', 'Holiday Inn Gurugram Se..."
2,"4 BHK Flat in Sector 84, Gurgaon",SS Linden Floors,₹2.9 Cr,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area",M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e...","['AapnoGhar', 'Modern Public School-kherki Dau..."
3,"3 BHK Flat in Sector 102, Gurgaon",Shapoorji Pallonji Joyville Gurugram,₹2.65 Cr,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area",Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Hyatt Place Gurgaon Udyog Vihar', 'The Espla..."
4,"3 BHK Flat in Sector 102, Gurgaon",Emaar Imperial Gardens,₹2.4 Cr,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area",K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Sunrise University', 'Country Inn & Suites b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,"4 BHK Flat in Sector 102, Gurgaon",Adani M2K Oyster Grande,₹3.6 Cr,"₹11,257 /sqft","3,198 sqft (297 sqm) Super Built-up Area",G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'...","['Gurgaon', 'SGT University', 'Indira Gandhi A..."
2456,"3 BHK Flat in Sector 69, Gurgaon",Tulip Yellow,₹2.33 Cr,"₹13,673 /sqft","1,704 sqft (158 sqm) Super Built-up Area",P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Hyatt Regency Gurugram', 'De Adventure Park'..."
2457,"3 BHK Flat in Sector 102, Gurgaon",Shapoorji Pallonji Joyville Gurugram,₹2.6 Cr,"₹14,038 /sqft","1,852 sqft (172 sqm) Super Built-up Area",W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',...","['IFFCO Chowk Metro Station', 'The Esplanade M..."
2458,"3 BHK Flat in Sector 82, Gurgaon",Mapsko Casa Bella,₹2.05 Cr,"₹10,459 /sqft","1,960 sqft (182 sqm) Super Built-up Area",O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['SkyJumper Trampoline Park', 'Pataudi Road', ..."
2459,"4 BHK Flat in Sector 107, Gurgaon",M3M Woodshire,₹2.4 Cr,"₹8,739 /sqft","2,746 sqft (255 sqm) Super Built-up Area",P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'...","['Skylark Cricket Academy', 'Signum 107', 'The..."

In [55]:
residential_apartment.columns = residential_apartment.columns.str.lower()

In [56]:
residential_apartment.head()

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
0,"2 BHK Flat in Sector 112, Gurgaon",Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'...","['Metro Hospital, Palam Vihar', 'Mount Carmel ..."
1,"3 BHK Flat in Sector 37C, Gurgaon",Ramprastha The View,₹1.29 Cr,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area",W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Elan Miracle Mall', 'Holiday Inn Gurugram Se..."
2,"4 BHK Flat in Sector 84, Gurgaon",SS Linden Floors,₹2.9 Cr,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area",M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e...","['AapnoGhar', 'Modern Public School-kherki Dau..."
3,"3 BHK Flat in Sector 102, Gurgaon",Shapoorji Pallonji Joyville Gurugram,₹2.65 Cr,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area",Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Hyatt Place Gurgaon Udyog Vihar', 'The Espla..."
4,"3 BHK Flat in Sector 102, Gurgaon",Emaar Imperial Gardens,₹2.4 Cr,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area",K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Sunrise University', 'Country Inn & Suites b..."

In [57]:
residential_apartment.shape

(2460, 17)

In [ ]:
residential_apartment.to_csv(r"C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apartment.csv", index= False)

In [59]:
residential_apartment.head()

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
0,"2 BHK Flat in Sector 112, Gurgaon",Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'...","['Metro Hospital, Palam Vihar', 'Mount Carmel ..."
1,"3 BHK Flat in Sector 37C, Gurgaon",Ramprastha The View,₹1.29 Cr,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area",W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Elan Miracle Mall', 'Holiday Inn Gurugram Se..."
2,"4 BHK Flat in Sector 84, Gurgaon",SS Linden Floors,₹2.9 Cr,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area",M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e...","['AapnoGhar', 'Modern Public School-kherki Dau..."
3,"3 BHK Flat in Sector 102, Gurgaon",Shapoorji Pallonji Joyville Gurugram,₹2.65 Cr,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area",Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Hyatt Place Gurgaon Udyog Vihar', 'The Espla..."
4,"3 BHK Flat in Sector 102, Gurgaon",Emaar Imperial Gardens,₹2.4 Cr,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area",K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Sunrise University', 'Country Inn & Suites b..."