In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

### 1. Builder Floor Data Loading

In [2]:
df_bf = pd.read_csv('../../data/web_scraping/builder_floor_gurgaon.csv')
df_bf.sample(15)

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
2040,3 BHK Builder Floor in Sushant Lok 3 Extension...,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,3 Cr,₹1.47 L /sqyd,1836 sqft Super Area,NaN,3,3,2.0,"Sushant Lok 3 Extension, Gurgaon",4 of 4 Floors,East,Main Road,6,NaN,Unfurnished,"{""O"":1,""C"":1}","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...",Sector 57 \nGurgaon \nAll floor available \nNe...,"['Top Floor', 'Roof Rights', 'Newly Constructe...",28.426175,77.083650,Q89373783
7623,"4 BHK Builder Floor in Sector 52, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,2.75 Cr,"₹8,594 /sqft",3200 sqft Carpet Area,3200.0,4,4,2.0,"Sector 52, Gurgaon",1 of 4 Floors,0,"Park/Garden, Main Road",6,Y,Unfurnished,"{""C"":2}","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...",4bhk luxurious builder floor in gurgaon nearby...,"['Overlooking Park', 'Overlooking Main Road', ...",28.435472,77.082348,M84733344
1556,"3 BHK Builder Floor in Sector 63A, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,4 Cr,₹1.29 L /sqyd,2790 sqft Super Area,NaN,3,3,3.0,"Sector 63A, Gurgaon",1 of 4 Floors,0,NaN,5,NaN,Semi-Furnished,"{""C"":1}","['International Tech Park', 'SPAZE BUSINESS PA...",Sector 63a gurgaon is one of the sought after ...,['Visitor Parking Available'],28.392382,77.089173,A90085154
218,"4 BHK Builder Floor in Sector-33 Sohna, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Central Park Flower Valley,4.35 Cr,₹1.45 L /sqyd,2700 sqft Super Area,1664.0,4,4,3.0,"Sector-33 Sohna, Gurgaon",2 of 4 Floors,North-West,"Pool, Park/Garden, Club, Main Road, Others",6,Y,Unfurnished,"{""O"":2,""C"":2}","['NH 248A', 'GD Goenka Signature School', 'K. ...",Address: Residential ultra luxury floor\n Sect...,"['Stilt Parking', 'Corner Property', 'Gated So...",28.284246,77.069301,X88760386
3923,"4 BHK Builder Floor in Sector 67, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Ansal API Esencia,3.05 Cr,"₹9,531 /sqft",3200 sqft Carpet Area,3200.0,4,4,2.0,"Sector 67, Gurgaon",2 of 4 Floors,0,"Park/Garden, Main Road",6,Y,Unfurnished,"{""C"":2}","['Proposed Metro corridor', 'N.H-8', 'Golf Cou...",Premium 4 bhk builder floor | 350 sq. Yards | ...,"['Corner Property', 'Gated Society', 'Newly Co...",28.387664,77.059342,O87875328
3381,"4 BHK Builder Floor in DLF Phase 5, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,DLF The Grove,6.5 Cr,₹2.41 L /sqyd,2430 sqft Super Area,1550.0,4,4,3.0,"DLF Phase 5, Gurgaon",1 of 4 Floors,North-East,"Park/Garden, Main Road",6,NaN,Unfurnished,"{""C"":2}","['Central Plaza Mall', 'Sector 53-54', 'Suncit...",Check out this 4 bhk builder floor in dlf phas...,"['Gated Society', 'Newly Constructed', 'Overlo...",28.445306,77.104467,W89764526
922,"3 BHK Builder Floor in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Smart World Gems,1.58 Cr,"₹10,576 /sqft",1494 sqft Superbuiltup Area,NaN,3,3,2.0,"Sector 89, Gurgaon",2 of 4 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",5,Y,Unfurnished,"{""O"":1,""C"":1}","['Dwarka Expressway', 'Genesis Hospital Sector...",Introducing smart world gems: The epitome of l...,"['Overlooking Main Road', 'Recently Renovated'...",28.424779,76.949530,Q80842141
2697,"3 BHK Builder Floor in Block H, Sector-57,, Gu...",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqft,1800 sqft Carpet Area,1800.0,3,3,2.0,"Block H, Sector-57,, Gurgaon",4 of 4 Floors,0,NaN,1,NaN,0,"[""N""]","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...",This 3 bhk independent builder floor on the to...,NaN,28.427030,77.076000,U86361556
1793,"4 BHK Builder Floor in Sector 48, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Vipul World,3.62 Cr,₹1.5 L /sqyd,2165 sqft Super Area,1836.0,4,4,2.0,"Sector 48, Gurgaon",3 of 4 Floors,East,"Main Road, Park/Garden",6,Y,Unfurnished,"{""O"":1,""C"":2}","['Airia Mall', 'GD Goenka School', 'The Millen...",Looking for magnificent 4 bhk builder floors i...,"['Newly Constructed', 'Overlooking Park', 'Ove...",28.412173,77.036100,L89454430
9186,"4 BHK Builder Floor in Sector 40, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,4.1 Cr,₹1.56 L /sqyd,2367 sqft Super Area,NaN,4,4,2.0,"Sector 40, Gurgaon",3 of 4 Floors,North-East,Main Road,6,NaN,Unfurnished,"{""C"":2}","['Huda city centre metro station', 'Axis bank ...",4 bhk builder floor in sector 40 gurgaon enjoy...,"['North-East Facing', 'High Ceiling height', '...",28.448901,77.057885,C90964896
4441,"4 BHK Builder Floor in Block C, Sushant Lok Ph...",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,3.5 Cr,₹1.17 L /sqyd,2700 sqft Super Area,2295.0,4,4,2.0,"Block C, Sushant Lok Phase 1, Gurgaon",1 of 4 Floors,East,NaN,6,NaN,Unfurnished,"{""O"":1,""C"":2}","['Sector 42-43 metro station', 'Huda city cent...",Experience upscale living in this spacious 4 b...,"['High Ceiling height', 'Centrally Air Conditi...",28.455549,77.087757,J90484360
8658,"3 BHK Builder Floor in Sector 50, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Mayfield Gardens,3.09 Cr,₹1.17 L /sqyd,2367 sqft Super Area,2011.0,3,3,2.0,"Sector 50, Gurgaon",2 of 4 Floors,South,"Main Road, Pool, Club",6,NaN,Unfurnished,"{""O"":1,""C"":1}","['Millenium City Centre Gurgaon', 'S S Plaza',...",Discover smartly planned 3 bhk builder floor i...,"['Overlooking Main Road', 'Centrally Air Condi...",28.409069,77.065128,E88762372
7311,"4 BHK Builder Floor in Sector 45, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,4.1 Cr,₹1.2 L /sqyd,3078 sqft Super Area,1700.0,4,4,2.0,"Sector 45, Gurgaon",1 of 4 Floors,West,"Park/Garden, Main Road",6,NaN,Unfurnished,"{""C"":2}","['Standard chartered ATM', 'Hdfc bank ATM', 'A...",4 bhk luxury builder floor available for sale ...,"['Overlooking Main Road', 'High Ceiling height...",28.439111,77.068243,P90415422
2017,"3 BHK Builder Floor in Sector 57, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,2.49 Cr,₹1.22 L /sqyd,1836 sqft Super Area,1377.0,3,3,2.0,"Sector 57, Gurgaon",3 of 4 Floors,South,NaN,1,NaN,Unfurnished,"{""C"":1}","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...",Available for sale builder floor in sector 57 ...,"['Vaastu Compliant', 'Modular Kitchen', 'Visit...",28.424685,77.079262,E90384320
1022,"3 BHK Builder Floor in Sector 70A, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,BPTP Astaire Gardens,2.3 Cr,₹1.24 L /sqyd,1672 sqft Super Area,NaN,3,3,2.0,"Sector 70A, Gurgaon",3 of 4 Floors,0,NaN,6,NaN,Unfurnished,"{""C"":1}","['Kunskapsskolan International School', 'South...",Check out this 3 bhk builder floor in sector 7...,"['Centrally Air Conditioned', 'Vaastu Complian...",28.381555,77.022316,R90665272

In [3]:
df_bf.shape

(9210, 24)

In [4]:
df_bf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9210 entries, 0 to 9209
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    9210 non-null   object
 1   link             9210 non-null   object
 2   society          5847 non-null   object
 3   price            9210 non-null   object
 4   area             9118 non-null   object
 5   areaWithType     9210 non-null   object
 6   carpetArea       4370 non-null   float64
 7   bedRoom          9210 non-null   int64
 8   bathroom         9210 non-null   int64
 9   balcony          9209 non-null   float64
 10  address          9210 non-null   object
 11  floorNum         9210 non-null   object
 12  facing           9210 non-null   object
 13  overlooking      8159 non-null   object
 14  agePossession    9210 non-null   int64
 15  cornerProperty   3794 non-null   object
 16  furnishing       9210 non-null   object
 17  parking          9160 non-null   object
 18  nearbyLocations  9079 non-null   object
 19  description      9210 non-null   object
 20  features         9046 non-null   object
 21  latitude         9210 non-null   float64
 22  longitude        9210 non-null   float64
 23  property_id      9210 non-null   object
dtypes: float64(4), int64(3), object(17)
memory usage: 1.7+ MB

In [5]:
df_bf.describe(include='all')

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
count,9210,9210,5847,9210,9118,9210,4370.000000,9210.000000,9210.000000,9209.000000,9210,9210,9210,8159,9210.000000,3794,9210,9160,9079,9210,9046,9210.000000,9210.000000,9210
unique,411,9210,784,607,2542,1440,NaN,NaN,NaN,NaN,172,56,9,277,NaN,1,4,58,574,8315,5495,NaN,NaN,9210
top,"3 BHK Builder Floor in Sector 63A, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Emaar Emerald Hills,3.5 Cr,₹1.25 L /sqyd,2700 sqft Super Area,NaN,NaN,NaN,NaN,"Sector 57, Gurgaon",2 of 4 Floors,North,Main Road,NaN,Y,Unfurnished,"{""O"":1,""C"":2}","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...","At nss realtor, we believe your lifestyle shou...","['Centrally Air Conditioned', 'Modular Kitchen']",NaN,NaN,V90137564
freq,304,1,231,238,149,716,NaN,NaN,NaN,NaN,466,2595,2831,1710,NaN,3794,7802,2053,413,78,48,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,1662.603195,3.450271,3.526602,2.341405,NaN,NaN,NaN,NaN,4.393485,NaN,NaN,NaN,NaN,NaN,NaN,28.715048,76.570947,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1077.627218,0.652245,0.849136,0.737819,NaN,NaN,NaN,NaN,2.188034,NaN,NaN,NaN,NaN,NaN,NaN,4.252783,5.234925,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,850.000000,3.000000,3.000000,2.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.405670,77.046854,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1644.000000,3.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.422839,77.065761,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2273.250000,4.000000,4.000000,3.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.452387,77.083278,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,9700.000000,10.000000,10.000000,4.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,77.079763,77.269775,NaN

### 2. Builder Floor Data Cleaning

In [6]:
df_bf.isnull().sum()

property_name         0
link                  0
society            3363
price                 0
area                 92
areaWithType          0
carpetArea         4840
bedRoom               0
bathroom              0
balcony               1
address               0
floorNum              0
facing                0
overlooking        1051
agePossession         0
cornerProperty     5416
furnishing            0
parking              50
nearbyLocations     131
description           0
features            164
latitude              0
longitude             0
property_id           0
dtype: int64

In [7]:
missing_summary = (
    df_bf
    .isnull()
    .sum()
    .pipe(lambda s: round((s / len(df_bf)) * 100, 2))
    .reset_index()
    .rename(columns={'index': 'Feature', 0: 'Missing_Percentage'})
    .sort_values(by='Missing_Percentage', ascending=False)
)
missing_summary

            Feature  Missing_Percentage
15   cornerProperty               58.81
6        carpetArea               52.55
2           society               36.51
13      overlooking               11.41
20         features                1.78
18  nearbyLocations                1.42
4              area                1.00
17          parking                0.54
9           balcony                0.01
7           bedRoom                0.00
1              link                0.00
3             price                0.00
0     property_name                0.00
5      areaWithType                0.00
11         floorNum                0.00
8          bathroom                0.00
14    agePossession                0.00
12           facing                0.00
10          address                0.00
16       furnishing                0.00
19      description                0.00
21         latitude                0.00
22        longitude                0.00
23      property_id                0.00

In [8]:
df_bf.shape

(9210, 24)

### 3. Cleaning Individual Columns

#### 1. Society

In [9]:
df_bf['society'].value_counts()[:20]

society
Emaar Emerald Hills                      231
BPTP Astaire Gardens                     200
Smart World Gems                         167
Ansal API Esencia                        165
Malibu Towne                             154
Anant Raj                                148
Luxury Builder floor In South City 2     146
DLF Gardencity Enclave                   137
Ansal API Versalia                       137
M3M Soulitude                            124
Vipul World                              114
Sushant Lok 1 Builder Floors             111
DLF The Grove                             93
DLF Luxury Builder Floors                 87
Huda Flats                                80
Luxury Builder Floor In Sushant Lok 1     77
Smart World Orchard                       76
Private Builder Floor                     75
Signature Global Park 4                   69
Ansals Palam Vihar                        67
Name: count, dtype: int64

In [10]:
df_bf['society'].isnull().sum()

np.int64(3363)

#### 2. Price

In [11]:
df_bf = df_bf.rename(columns={
    'price': 'price_in_cr',
    'area': 'price_per_sqft'
})

In [12]:
df_bf['price_in_cr'].value_counts()[:20]

price_in_cr
3.5 Cr     238
3.25 Cr    196
4 Cr       193
3 Cr       183
4.5 Cr     167
2.5 Cr     158
4.25 Cr    150
3.1 Cr     149
2.75 Cr    135
3.75 Cr    125
2.9 Cr     124
5.5 Cr     119
2.65 Cr    117
2.6 Cr     115
2.85 Cr    113
3.4 Cr     112
3.3 Cr     111
3.6 Cr     110
2.8 Cr     110
3.2 Cr     110
Name: count, dtype: int64

In [13]:
df_bf['price_in_cr'].isnull().sum()

np.int64(0)

In [14]:
df_bf[df_bf['price_in_cr'] == 'Price on Request']

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
385,"3 BHK Builder Floor in Sector 65, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqyd,2250 sqft Super Area,NaN,3,2,2.0,"Sector 65, Gurgaon",2 of 2 Floors,0,Main Road,2,NaN,Unfurnished,"{""O"":1}","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...",Discover smartly planned 3 bhk builder floor i...,"['High Ceiling height', 'Centrally Air Conditi...",28.405670,77.070837,T90180912
2697,"3 BHK Builder Floor in Block H, Sector-57,, Gu...",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqft,1800 sqft Carpet Area,1800.0,3,3,2.0,"Block H, Sector-57,, Gurgaon",4 of 4 Floors,0,NaN,1,NaN,0,"[""N""]","['Hong Kong Bazaar Mall', 'Radhakrishna Shani ...",This 3 bhk independent builder floor on the to...,NaN,28.427030,77.076000,U86361556
3744,"3 BHK Builder Floor in Sector 93, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,ROF Insignia Park,Price on Request,₹0 /sqyd,1500 sqft Super Area,850.0,3,3,1.0,"Sector 93, Gurgaon",2 of 4 Floors,0,Main Road,1,NaN,Unfurnished,"{""C"":1}","['Newtown Square Mall', 'Dwarka Expy', 'Yaduva...",3 bhk builder floor in sector 93 gurgaon enjoy...,"['High Ceiling height', 'Centrally Air Conditi...",28.415281,76.932617,S90126012
4253,"4 BHK Builder Floor in Nirvana Country, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqyd,3200 sqft Super Area,2337.0,4,4,2.0,"Nirvana Country, Gurgaon",2 of 4 Floors,0,Main Road,6,NaN,Semi-Furnished,"{""C"":1}","['Raheja Mall', 'Radhakrishna Shani Mandir', '...",This 4 bhk builder floor located in nirvana co...,"['High Ceiling height', 'Separate entry for se...",28.420490,77.063280,R90135934
4839,"4 BHK Builder Floor in Sushant Lok Phase 1, Gu...",https://www.99acres.com/4-bhk-bedroom-independ...,Block no C2,Price on Request,₹0 /sqyd,3500 sqft Super Area,NaN,4,4,1.0,"Sushant Lok Phase 1, Gurgaon",G of 3 Floors,0,Main Road,1,NaN,Semi-Furnished,"{""C"":1}","['Huda city centre metro station', 'New Life C...","4 bhk builder floor in sushant lok phase 1, gu...","['High Ceiling height', 'Vaastu Compliant', 'C...",28.457243,77.078253,W90052400
5226,"4 BHK Builder Floor in DLF Phase 1, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqft,4500 sqft Superbuiltup Area,NaN,4,5,2.0,"DLF Phase 1, Gurgaon",3 of 4 Floors,South,NaN,6,NaN,Unfurnished,"{""C"":3}","['Guru dronacharya metro station', 'Dlf phase ...",Ultra luxurious builder floors at very prime l...,"['Centrally Air Conditioned', 'Modular Kitchen']",28.475491,77.103210,J87418614
5248,"3 BHK Builder Floor in DLF Phase 1, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqyd,2700 sqft Super Area,NaN,3,3,1.0,"DLF Phase 1, Gurgaon",2 of 4 Floors,0,Main Road,2,NaN,Semi-Furnished,"{""C"":1}","['Guru dronacharya metro station', 'Dlf phase ...",Dlf phase 1 is one of the sought after locatio...,"['Vaastu Compliant', 'Close to School']",28.475491,77.103210,X90215138
5524,"3 BHK Builder Floor in Palam Vihar, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqyd,2160 sqft Super Area,NaN,3,3,2.0,"Palam Vihar, Gurgaon",2 of 3 Floors,0,NaN,3,Y,Semi-Furnished,"{""C"":1}","['Palam Vihar Vyapar kendra', 'Palam triangle'...",Planning to purchase dream house in gurgaon? T...,"['High Ceiling height', 'Visitor Parking Avail...",28.512930,77.037736,Y90047646

In [15]:
df_bf[df_bf['price_in_cr'] == '70,000']

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
7745,"3 BHK Builder Floor in Malibu Town, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"70,000","₹70,000 /sqyd",9 sqft Super Area,NaN,3,3,3.0,"Malibu Town, Gurgaon",2 of 3 Floors,0,Main Road,1,NaN,Furnished,"[""N""]","['Raheja Mall', 'Standard chartered ATM', 'Ici...","Available immediately, this 3 bhk independent ...","['Centrally Air Conditioned', 'Vaastu Complian...",28.422656,77.045656,I90722352

In [16]:
column_cleaning = (
    df_bf
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') & (df_['price_in_cr'] != '70,000')
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
)

In [17]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
3.50    238
3.25    196
4.00    193
3.00    183
4.50    167
       ...
1.17      1
0.35      1
3.66      1
7.47      1
0.48      1
Name: count, Length: 596, dtype: int64

#### 3. Price Per Sqft

In [18]:
df_bf['price_per_sqft'].value_counts()

price_per_sqft
₹1.25 L /sqyd    149
₹1.33 L /sqyd    130
₹1.4 L /sqyd     129
₹1.2 L /sqyd     124
₹1 L /sqyd       119
                ...
₹84,490 /sqyd      1
₹86,717 /sqyd      1
₹10,910 /sqft      1
₹82,097 /sqyd      1
₹11,574 /sqyd      1
Name: count, Length: 2542, dtype: int64

In [19]:
column_cleaning['price_per_sqft']\
    .str.extract(r'/(.+)$', expand=False)\
    .str.strip()\
    .str.lower()\
    .value_counts(dropna=False)

price_per_sqft
sqyd    6896
sqft    2213
NaN       92
Name: count, dtype: int64

In [30]:
column_cleaning = (
    df_bf
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )
    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )
    .loc[
        lambda df_: (
            df_['price_in_cr'].notna()
            & (df_['price_in_cr'] != 'Price on Request')
            & (df_['price_in_cr'] != '70,000')
        )
    ]
    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                    float(str(value).replace('Cr', '').strip())
                    if 'Cr' in str(value)
                    else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
    .assign(
        price_per_sqft=lambda df_: (
            df_['price_per_sqft']
            .str.split('₹')
            .str.get(1)
            .str.split('/')
            .str.get(0)
            .str.replace('L', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.strip()
            .pipe(pd.to_numeric, errors='coerce')
            .mul(
                np.where(
                    df_['price_per_sqft'].str.contains('L', na=False),
                    100000,
                    1
                )
            )
            .div(
                np.where(
                    df_['price_per_sqft'].str.contains('/sqyd', case=False, na=False),
                    9,
                    1
                )
            )
            .round()
            .astype('Int64')
        )
    )
)

In [31]:
column_cleaning['price_per_sqft']

0       17222
1       12556
2       15975
3       12667
4       12667
        ...
9205    12667
9206    15444
9207    16863
9208    15873
9209     2824
Name: price_per_sqft, Length: 9201, dtype: Int64

In [32]:
validation_df = pd.DataFrame({
    'original': df_bf['price_per_sqft'],
    'converted': column_cleaning['price_per_sqft']
})

validation_df.sample(20, random_state=42)

           original  converted
248   ₹1.16 L /sqyd      12889
2087  ₹1.16 L /sqyd      12889
8326  ₹1.31 L /sqyd      14556
4447  ₹1.26 L /sqyd      14000
1941  ₹97,222 /sqyd      10802
3768  ₹1.13 L /sqyd      12556
8451  ₹12,021 /sqft      12021
1770  ₹90,741 /sqyd      10082
4601  ₹15,926 /sqft      15926
3685  ₹21,250 /sqft      21250
3377  ₹1.38 L /sqyd      15333
4042  ₹1.94 L /sqyd      21556
6951  ₹1.53 L /sqyd      17000
6915  ₹1.33 L /sqyd      14778
1195  ₹1.37 L /sqyd      15222
8620  ₹1.46 L /sqyd      16222
3194  ₹92,875 /sqyd      10319
4537  ₹14,815 /sqft      14815
6605  ₹1.15 L /sqyd      12778
3437  ₹2.55 L /sqyd      28333

In [33]:
column_cleaning['price_per_sqft'].describe()

count          9109.0
mean     14633.311011
std       7201.385971
min              57.0
25%           11667.0
50%           14111.0
75%           16667.0
max          249000.0
Name: price_per_sqft, dtype: Float64

These are almost certainly data-quality issues.

A ₹57/sqft builder floor in Gurgaon is unrealistic.

In [34]:
column_cleaning['price_per_sqft'].quantile(
    [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
)

0.01    1684.16
0.05     8606.6
0.25    11667.0
0.50    14111.0
0.75    16667.0
0.95    21444.0
0.99    28333.0
Name: price_per_sqft, dtype: Float64

In [35]:
validation_df = pd.DataFrame({
    'original': df_bf['price_per_sqft'],
    'converted': column_cleaning['price_per_sqft']
})

validation_df.loc[
    (validation_df['converted'] < 1000) |
    (validation_df['converted'] > 50000)
].sort_values('converted')

            original  converted
99        ₹510 /sqyd         57
5532    ₹1,250 /sqyd        139
1785    ₹7,403 /sqyd        823
1869    ₹7,863 /sqyd        874
7591    ₹8,148 /sqyd        905
7214    ₹8,333 /sqyd        926
6665    ₹8,395 /sqyd        933
7615    ₹8,837 /sqyd        982
1715    ₹8,928 /sqyd        992
8934    ₹8,929 /sqyd        992
3410   ₹50,909 /sqft      50909
3416   ₹53,030 /sqft      53030
1376   ₹5.17 L /sqyd      57444
3508   ₹5.22 L /sqyd      58000
8711   ₹6.21 L /sqyd      69000
173     ₹6.3 L /sqyd      70000
5827   ₹6.56 L /sqyd      72889
8831   ₹78,333 /sqft      78333
7645    ₹7.2 L /sqyd      80000
2609    ₹7.5 L /sqyd      83333
5144   ₹7.57 L /sqyd      84111
6534   ₹8.25 L /sqyd      91667
2069   ₹8.39 L /sqyd      93222
8772   ₹8.64 L /sqyd      96000
221    ₹8.68 L /sqyd      96444
5129   ₹9.17 L /sqyd     101889
993   ₹11.05 L /sqyd     122778
5887   ₹1.28 L /sqft     128000
9074     ₹12 L /sqyd     133333
8295  ₹12.55 L /sqyd     139444
1670  ₹12.56 L /sqyd     139556
8182  ₹12.75 L /sqyd     141667
3330   ₹1.44 L /sqft     144000
1069  ₹13.09 L /sqyd     145444
7244  ₹16.36 L /sqyd     181778
3996   ₹18.1 L /sqyd     201111
8366   ₹2.49 L /sqft     249000

In [36]:
column_cleaning.loc[
    column_cleaning['price_per_sqft'] < 1000
]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
99,"3 BHK Builder Floor in Sector-33 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,central park flower valley aqua front towers,2.55,57,450000 sqft Super Area,1789.0,3,3,3.0,"Sector-33 Sohna, Gurgaon",4 of 13 Floors,0,"Pool, Park/Garden, Others, Club, Main Road",1,NaN,Unfurnished,"{""C"":1}","['N.B.G.S.M College', 'The Westin Sohna Resort...",Central park offers a world of facilities and ...,"['Gated Society', 'Overlooking Main Road', 'Hi...",28.284873,77.079988,N81943634
1715,"3 BHK Builder Floor in Sector-33 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,central park flower valley flamingo floors,1.49,992,15020 sqft Super Area,NaN,3,3,2.0,"Sector-33 Sohna, Gurgaon",1 of 3 Floors,North,"Main Road, Park/Garden, Pool, Club",1,Y,Unfurnished,"{""O"":1}","['Spazedge IT Park', 'Omaxe City Centre', 'JMD...",9 sports academies\n\nMulti-Cuisine restaurant...,"['Overlooking Main Road', 'Recently Renovated'...",28.284098,77.076591,Q91532400
1785,"4 BHK Builder Floor in Sector 48, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,roots courtyard,2.40,823,29178 sqft Super Area,2280.0,4,4,4.0,"Sector 48, Gurgaon",2 of 2 Floors,North-East,"Pool, Park/Garden, Club, Main Road",6,Y,Semi-Furnished,"{""O"":1,""C"":1}","['Hans Business Park', 'Radisson Hotel', 'GD G...",Roots courtyard sector 48 gurgaon. Roots court...,"['Gated Society', 'Newly Constructed', 'Overlo...",28.415401,77.036579,X90035262
1869,"3 BHK Builder Floor in Sector 48, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,roots courtyard,1.70,874,19458 sqft Super Area,1400.0,3,3,3.0,"Sector 48, Gurgaon",2 of 2 Floors,North-East,"Main Road, Club, Park/Garden, Pool",1,Y,Semi-Furnished,"{""O"":1,""C"":1}","['Millennium City Centre Metro', 'Omaxe City C...",Roots courtyard sector 48 gurgaon. Roots court...,"['Corner Property', 'Gated Society', 'Overlook...",28.415401,77.036579,T90034916
5532,"2 BHK Builder Floor in Palam Vihar, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,ansal api spanish court,0.45,139,32400 sqft Super Area,NaN,2,2,1.0,"Palam Vihar, Gurgaon",2 of 5 Floors,0,NaN,6,NaN,Unfurnished,"{""C"":1}","['Palam Vihar Vyapar kendra', 'Palam triangle'...","A modern, well-Ventilated 2bhk apartment, perf...",['Modular Kitchen'],28.502961,77.028844,V88874356
6665,"2 BHK Builder Floor in H Block, Sector 82, Gur...",https://www.99acres.com/2-bhk-bedroom-independ...,NaN,1.36,933,14580 sqft Super Area,870.0,2,2,2.0,"H Block, Sector 82, Gurgaon",G of 3 Floors,North-West,Main Road,2,NaN,Unfurnished,"{""O"":1}","['Orris Community Center', 'Essar Petrol Pump'...","H block, sector 82 is one of the sought after ...",['Visitor Parking Available'],28.394655,76.953255,R91060964
7214,3 BHK Builder Floor in Block H Block D Sector ...,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,1.50,926,16200 sqft Super Area,1650.0,3,3,2.0,"Block H Block D Sector 46, Gurgaon",1 of 4 Floors,North,"Park/Garden, Club, Main Road, Pool",1,Y,Unfurnished,"{""O"":1,""C"":1}","['Axis bank ATM', 'State bank of india ATM', '...","Located in block h block d sector 46, gurgaon,...","['Gated Society', 'Overlooking Park', 'Overloo...",28.440150,77.059122,V90317066
7591,"4 BHK Builder Floor in Sector 52, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,ardee city,2.20,905,24300 sqft Super Area,1575.0,4,4,4.0,"Sector 52, Gurgaon",2 of 2 Floors,South,Main Road,3,Y,Unfurnished,"{""O"":1}","['sector 54 chowk', 'Ardee Mall', 'Gurugram Pu...",This is 4 bhk semi furnished flat is available...,"['High Ceiling height', 'Vaastu Compliant', 'M...",28.441588,77.079763,E90393606
7615,"3 BHK Builder Floor in Sector 52, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,ardee city,1.90,982,19350 sqft Super Area,1325.0,3,3,3.0,"Sector 52, Gurgaon",1 of 2 Floors,South,Main Road,3,NaN,Unfurnished,"{""O"":1}","['sector 54 chowk', 'Ardee Mall', 'Gurugram Pu...",This is 3 bhk semi furnished flat is available...,"['High Ceiling height', 'Vaastu Compliant', 'M...",28.441588,77.079763,V90391228
8934,"3 BHK Builder Floor in Sector 36 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,signature global park 4,1.00,992,10080 sqft Super Area,NaN,3,2,3.0,"Sector 36 Sohna, Gurgaon",2 of 4 Floors,North-East,"Pool, Park/Garden, Club, Main Road",1,NaN,Semi-Furnished,"{""C"":1}","['Badshahpur Sohna Rd Hwy', 'Vidya Niketan Sch...",Signature global park 4 & 5 offers modern amen...,"['Recently Renovated', 'North-East Facing', 'H...",28.288325,77.062485,Z91270792

#### 4. Bedroom

In [38]:
df_bf['bedRoom'].describe()

count    9210.000000
mean        3.450271
std         0.652245
min         1.000000
25%         3.000000
50%         3.000000
75%         4.000000
max        10.000000
Name: bedRoom, dtype: float64

In [37]:
df_bf['bedRoom'].unique()

array([ 3,  2,  4,  1,  5, 10,  6,  8,  9])

In [39]:
df_bf['bedRoom'].isnull().sum()

np.int64(0)

#### 5. Bathroom

In [41]:
df_bf['bathroom'].describe()

count    9210.000000
mean        3.526602
std         0.849136
min         1.000000
25%         3.000000
50%         4.000000
75%         4.000000
max        10.000000
Name: bathroom, dtype: float64

In [40]:
df_bf['bathroom'].unique()

array([ 3,  2,  4,  5,  6, 10,  1,  7,  8])

In [42]:
df_bf['bathroom'].isnull().sum()

np.int64(0)

#### 6. Balcony

In [44]:
df_bf['balcony'].describe()

count    9209.000000
mean        2.341405
std         0.737819
min         0.000000
25%         2.000000
50%         2.000000
75%         3.000000
max         4.000000
Name: balcony, dtype: float64

In [45]:
df_bf['balcony'].unique()

array([ 2.,  3.,  4.,  1.,  0., nan])

In [46]:
df_bf['balcony'].isnull().sum()

np.int64(1)

In [47]:
df_bf[df_bf['balcony'].isnull()]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
1239,"2 BHK Builder Floor in Sector 70A, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,BPTP Pedestal,1.58 Cr,"₹13,311 /sqft",1187 sqft Carpet Area,1187.0,2,3,NaN,"Sector 70A, Gurgaon",3 of 3 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Ninex Mall', 'Airia Mall', 'Meditree Market'...","Located in bptp pedestal, sector 70a, gurgaon,...",['Top Floor'],28.385196,77.021276,R91390746

- Zero balcony = Missing due to parsing issue might have to fill manually for these 25 missing balcony values.

#### 7. Facing

In [48]:
df_bf['facing'].value_counts()

facing
North         2831
North-East    2135
East          1404
0              910
South          846
North-West     463
West           279
South-East     227
South-West     115
Name: count, dtype: int64

In [49]:
df_bf['facing'].isnull().sum()

np.int64(0)

- 0 means Not Available

#### 8. Age Possession

In [50]:
df_bf['agePossession'].value_counts()

agePossession
6    5629
1    2213
2     571
5     472
3     325
Name: count, dtype: int64

In [51]:
df_bf['agePossession'].isnull().sum()

np.int64(0)

- Verified mapping from 99acres:
  - **0** = Undefined
  - **1** = 1 to 5 Year Old
  - **2** = 5 to 10 Year Old
  - **3** = 10+ Year Old
  - **5** = Under Construction
  - **6** = 0 to 1 Year Old (New)

#### 9. Carpet Area

In [53]:
df_bf['carpetArea'].describe()

count    4370.000000
mean     1662.603195
std      1077.627218
min         6.000000
25%       850.000000
50%      1644.000000
75%      2273.250000
max      9700.000000
Name: carpetArea, dtype: float64

In [52]:
df_bf['carpetArea'].isnull().sum()

np.int64(4840)

#### 10. Furnishing

In [54]:
df_bf['furnishing'].unique()

array(['Unfurnished', 'Semi-Furnished', '0', 'Furnished'], dtype=object)

- 0 means missing values

#### 11. Overlooking

In [55]:
df_bf['overlooking'].value_counts()

overlooking
Main Road                                                 1710
Park/Garden                                               1168
Park/Garden, Main Road                                    1076
Pool, Park/Garden, Club, Main Road                         674
Main Road, Park/Garden                                     394
Others                                                     356
Park/Garden, Club, Main Road                               269
Pool, Park/Garden, Club, Main Road, Others                 211
Main Road, Club, Park/Garden, Pool                         106
Park/Garden, Main Road, Others                             102
Main Road, Others                                           89
Park/Garden, Main Road, Club                                75
Park/Garden, Others                                         73
Pool, Park/Garden, Club                                     63
Park/Garden, Club                                           62
Club                                                        53
Club, Park/Garden, Pool, Main Road                          50
Pool, Park/Garden, Main Road, Club                          49
Pool, Park/Garden, Club, Others, Main Road                  49
Pool, Park/Garden, Main Road                                48
Park/Garden, Pool, Club, Main Road                          42
Others, Main Road                                           42
Pool, Main Road, Park/Garden, Club                          42
Park/Garden, Club, Main Road, Others                        38
Pool, Park/Garden                                           37
Park/Garden, Club, Main Road, Pool                          37
Main Road, Club, Park/Garden, Pool, Others                  35
Park/Garden, Others, Main Road                              35
Pool                                                        35
Others, Park/Garden                                         32
Main Road, Park/Garden, Club                                31
Main Road, Park/Garden, Others                              29
Park/Garden, Pool                                           27
Pool, Club, Park/Garden, Main Road                          27
Pool, Park/Garden, Club, Main Road, Others, Sea facing      25
Club, Park/Garden                                           22
Club, Main Road, Park/Garden                                22
Pool, Main Road, Park/Garden, Others, Club                  22
Main Road, Club, Park/Garden                                22
Main Road, Pool, Park/Garden, Club                          21
Club, Park/Garden, Main Road                                20
Pool, Park/Garden, Main Road, Club, Others                  19
Pool, Club, Main Road, Park/Garden                          18
Club, Pool, Park/Garden, Main Road                          18
Club, Main Road, Park/Garden, Pool                          18
Park/Garden, Club, Pool                                     17
Club, Park/Garden, Pool                                     17
Pool, Park/Garden, Club, Others, Main Road, Sea facing      17
Main Road, Club                                             17
Main Road, Others, Park/Garden                              16
Park/Garden, Pool, Main Road, Club                          16
Pool, Club, Main Road                                       14
Club, Park/Garden, Main Road, Pool                          14
Pool, Main Road                                             14
Club, Main Road                                             14
Park/Garden, Club, Pool, Main Road                          13
Pool, Club, Park/Garden, Main Road, Others                  13
Park/Garden, Pool, Club                                     12
Pool, Others, Park/Garden, Club, Main Road                  12
Pool, Main Road, Others, Park/Garden, Club                  11
Park/Garden, Pool, Main Road                                10
Others, Main Road, Park/Garden                              10
Pool, Park/Garden, Main Road, Others                         9
Main Road, Park/Garden, Pool, Club                           9
Pool, Club                                                   9
Others, Park/Garden, Main Road                               9
Park/Garden, Main Road, Sea facing                           9
Park/Garden, Main Road, Club, Pool                           9
Pool, Main Road, Park/Garden                                 8
Pool, Park/Garden, Club, Main Road, Sea facing               8
Main Road, Park/Garden, Pool                                 8
Park/Garden, Club, Others, Main Road                         8
Main Road, Club, Pool, Park/Garden                           8
Park/Garden, Pool, Club, Main Road, Others                   7
Club, Main Road, Park/Garden, Pool, Others                   7
Main Road, Pool, Club                                        7
Pool, Park/Garden, Main Road, Others, Sea facing, Club       7
Pool, Main Road, Sea facing                                  7
Main Road, Pool, Club, Park/Garden                           7
Main Road, Park/Garden, Club, Pool                           7
Pool, Main Road, Club, Park/Garden                           7
Club, Park/Garden, Pool, Others, Main Road                   6
Park/Garden, Main Road, Pool, Club                           6
Pool, Main Road, Park/Garden, Others                         6
Park/Garden, Club, Main Road, Pool, Others                   6
Club, Pool, Main Road, Park/Garden                           6
Sea facing, Main Road, Others, Pool, Club, Park/Garden       6
Park/Garden, Main Road, Others, Club                         6
Park/Garden, Club, Others                                    6
Club, Pool                                                   6
Main Road, Pool, Park/Garden                                 6
Park/Garden, Club, Main Road, Others, Pool                   5
Park/Garden, Main Road, Club, Pool, Others                   5
Pool, Park/Garden, Club, Main Road, Sea facing, Others       5
Pool, Park/Garden, Club, Sea facing, Others, Main Road       5
Others, Main Road, Club, Park/Garden, Pool                   5
Pool, Park/Garden, Main Road, Others, Club                   5
Park/Garden, Main Road, Pool, Club, Others                   5
Club, Park/Garden, Pool, Main Road, Others                   5
Pool, Club, Park/Garden                                      5
Pool, Main Road, Sea facing, Park/Garden, Others, Club       5
Pool, Park/Garden, Club, Others                              4
Pool, Park/Garden, Others, Club, Main Road                   4
Pool, Main Road, Park/Garden, Others, Club, Sea facing       4
Pool, Others, Main Road                                      4
Others, Club                                                 4
Main Road, Others, Club, Park/Garden, Pool                   4
Others, Pool, Park/Garden, Club, Main Road                   4
Pool, Park/Garden, Others, Main Road, Club                   4
Pool, Main Road, Club                                        4
Park/Garden, Club, Others, Main Road, Pool                   4
Park/Garden, Club, Pool, Others, Main Road                   4
Pool, Main Road, Others, Park/Garden, Club, Sea facing       3
Others, Main Road, Park/Garden, Club                         3
Pool, Main Road, Park/Garden, Club, Others                   3
Others, Main Road, Club                                      3
Park/Garden, Sea facing                                      3
Others, Club, Main Road                                      3
Main Road, Pool                                              3
Pool, Club, Others, Main Road, Park/Garden                   3
Club, Park/Garden, Main Road, Others                         3
Pool, Club, Main Road, Others, Park/Garden                   3
Pool, Club, Main Road, Others, Sea facing, Park/Garden       3
Club, Main Road, Pool, Park/Garden                           3
Sea facing, Main Road, Others, Pool, Park/Garden, Club       3
Pool, Main Road, Sea facing, Park/Garden, Others             3
Park/Garden, Main Road, Pool                                 3
Park/Garden, Others, Club, Main Road, Pool                   3
Park/Garden, Main Road, Club, Others                         3
Club, Others                                                 2
Park/Garden, Pool, Club, Others, Main Road                   2
Main Road, Park/Garden, Pool, Club, Others                   2
Main Road, Club, Others, Park/Garden                         2
Club, Others, Park/Garden, Pool, Main Road                   2
Park/Garden, Club, Others, Pool, Main Road, Sea facing       2
Pool, Main Road, Others, Park/Garden, Sea facing, Club       2
Main Road, Park/Garden, Club, Pool, Others                   2
Pool, Park/Garden, Club, Others, Sea facing, Main Road       2
Pool, Main Road, Park/Garden, Sea facing, Club               2
Pool, Main Road, Club, Park/Garden, Others                   2
Pool, Main Road, Sea facing, Others, Park/Garden             2
Others, Club, Park/Garden, Main Road                         2
Pool, Main Road, Sea facing, Others, Park/Garden, Club       2
Park/Garden, Pool, Others, Main Road, Club                   2
Main Road, Club, Others                                      2
Park/Garden, Pool, Club, Main Road, Others, Sea facing       2
Main Road, Club, Pool                                        2
Park/Garden, Others, Main Road, Club, Pool                   2
Main Road, Others, Club                                      2
Park/Garden, Others, Club, Pool, Main Road                   2
Sea facing, Club, Park/Garden, Others, Main Road, Pool       2
Park/Garden, Club, Pool, Main Road, Others                   2
Main Road, Park/Garden, Pool, Others                         2
Club, Pool, Main Road, Park/Garden, Others                   2
Main Road, Others, Park/Garden, Club                         2
Club, Others, Main Road, Park/Garden                         1
Park/Garden, Pool, Main Road, Others                         1
Park/Garden, Others, Sea facing, Club, Pool, Main Road       1
Club, Park/Garden, Main Road, Sea facing, Pool, Others       1
Park/Garden, Others, Pool, Main Road                         1
Pool, Main Road, Sea facing, Club, Park/Garden, Others       1
Club, Pool, Main Road                                        1
Pool, Main Road, Sea facing, Club                            1
Park/Garden, Main Road, Pool, Others                         1
Park/Garden, Main Road, Others, Sea facing, Club, Pool       1
Sea facing, Main Road, Others, Club, Pool, Park/Garden       1
Pool, Main Road, Others                                      1
Others, Club, Park/Garden, Pool, Main Road                   1
Others, Main Road, Pool, Club, Park/Garden                   1
Park/Garden, Main Road, Pool, Sea facing, Others, Club       1
Park/Garden, Main Road, Others, Pool, Sea facing, Club       1
Pool, Park/Garden, Main Road, Sea facing                     1
Main Road, Club, Sea facing                                  1
Club, Main Road, Others                                      1
Club, Main Road, Others, Park/Garden                         1
Park/Garden, Others, Club, Main Road                         1
Park/Garden, Main Road, Others, Club, Pool                   1
Park/Garden, Main Road, Pool, Others, Club                   1
Park/Garden, Club, Pool, Others                              1
Pool, Park/Garden, Main Road, Club, Sea facing               1
Park/Garden, Sea facing, Main Road, Club, Others             1
Pool, Park/Garden, Others, Sea facing, Main Road, Club       1
Sea facing, Park/Garden                                      1
Main Road, Pool, Others, Park/Garden, Club                   1
Park/Garden, Main Road, Sea facing, Club                     1
Park/Garden, Main Road, Others, Sea facing, Club             1
Main Road, Sea facing, Park/Garden                           1
Pool, Others, Park/Garden, Main Road, Club, Sea facing       1
Main Road, Pool, Club, Others                                1
Park/Garden, Main Road, Others, Pool                         1
Pool, Park/Garden, Others, Main Road                         1
Club, Main Road, Others, Pool, Park/Garden                   1
Main Road, Club, Pool, Park/Garden, Others                   1
Pool, Others, Main Road, Park/Garden                         1
Pool, Others, Main Road, Park/Garden, Club                   1
Others, Main Road, Club, Pool, Park/Garden                   1
Pool, Main Road, Club, Others                                1
Others, Pool                                                 1
Park/Garden, Sea facing, Main Road, Others                   1
Park/Garden, Pool, Main Road, Club, Sea facing, Others       1
Sea facing, Main Road                                        1
Park/Garden, Pool, Club, Main Road, Sea facing               1
Sea facing, Main Road, Others                                1
Sea facing, Others, Main Road                                1
Park/Garden, Club, Sea facing, Others, Pool, Main Road       1
Park/Garden, Main Road, Others, Club, Pool, Sea facing       1
Pool, Club, Others, Park/Garden, Main Road                   1
Pool, Others, Park/Garden, Main Road, Club                   1
Pool, Park/Garden, Sea facing, Main Road, Others             1
Main Road, Pool, Park/Garden, Club, Others                   1
Main Road, Club, Pool, Others, Park/Garden                   1
Pool, Park/Garden, Club, Sea facing, Main Road, Others       1
Park/Garden, Sea facing, Main Road                           1
Park/Garden, Others, Pool, Main Road, Sea facing             1
Park/Garden, Main Road, Sea facing, Others, Club, Pool       1
Pool, Main Road, Sea facing, Club, Park/Garden               1
Club, Others, Park/Garden, Main Road                         1
Park/Garden, Pool, Others, Club, Main Road                   1
Park/Garden, Others, Main Road, Club                         1
Pool, Club, Main Road, Park/Garden, Sea facing, Others       1
Pool, Main Road, Others, Club, Park/Garden                   1
Others, Pool, Park/Garden, Club                              1
Main Road, Park/Garden, Club, Others                         1
Others, Park/Garden, Sea facing                              1
Pool, Club, Park/Garden, Others, Main Road                   1
Pool, Main Road, Park/Garden, Others, Sea facing, Club       1
Main Road, Park/Garden, Sea facing                           1
Club, Park/Garden, Main Road, Pool, Others                   1
Main Road, Club, Others, Pool                                1
Park/Garden, Others, Club                                    1
Club, Pool, Park/Garden, Others, Main Road                   1
Others, Main Road, Park/Garden, Club, Pool                   1
Pool, Main Road, Park/Garden, Club, Sea facing, Others       1
Pool, Club, Park/Garden, Main Road, Others, Sea facing       1
Pool, Park/Garden, Others, Main Road, Sea facing, Club       1
Park/Garden, Club, Pool, Main Road, Sea facing               1
Park/Garden, Others, Main Road, Pool, Club                   1
Park/Garden, Main Road, Sea facing, Others                   1
Park/Garden, Main Road, Pool, Club, Sea facing, Others       1
Club, Pool, Park/Garden                                      1
Others, Club, Main Road, Park/Garden                         1
Others, Club, Main Road, Pool, Park/Garden, Sea facing       1
Pool, Others, Club, Main Road                                1
Others, Club, Park/Garden, Main Road, Sea facing             1
Park/Garden, Main Road, Pool, Club, Sea facing               1
Others, Club, Main Road, Sea facing                          1
Pool, Club, Others, Sea facing, Main Road, Park/Garden       1
Pool, Club, Main Road, Park/Garden, Others                   1
Park/Garden, Others, Pool, Main Road, Club                   1
Park/Garden, Pool, Main Road, Club, Others                   1
Main Road, Others, Pool, Park/Garden, Club, Sea facing       1
Others, Pool, Main Road, Park/Garden, Club                   1
Park/Garden, Main Road, Club, Sea facing                     1
Club, Sea facing, Others, Park/Garden, Main Road, Pool       1
Pool, Main Road, Sea facing, Park/Garden, Club               1
Main Road, Others, Club, Sea facing, Park/Garden, Pool       1
Park/Garden, Club, Pool, Others, Main Road, Sea facing       1
Park/Garden, Club, Main Road, Pool, Sea facing               1
Club, Park/Garden, Pool, Main Road, Others, Sea facing       1
Club, Pool, Others, Main Road, Park/Garden                   1
Club, Park/Garden, Pool, Others, Main Road, Sea facing       1
Sea facing                                                   1
Park/Garden, Main Road, Club, Pool, Sea facing               1
Park/Garden, Main Road, Club, Others, Pool                   1
Pool, Park/Garden, Others                                    1
Pool, Park/Garden, Main Road, Sea facing, Others             1
Pool, Others, Main Road, Sea facing                          1
Park/Garden, Others, Main Road, Pool                         1
Park/Garden, Club, Main Road, Pool, Sea facing, Others       1
Club, Pool, Sea facing, Main Road, Others, Park/Garden       1
Park/Garden, Others, Pool                                    1
Main Road, Park/Garden, Others, Pool                         1
Pool, Club, Main Road, Sea facing, Park/Garden               1
Pool, Park/Garden, Others, Main Road, Sea facing             1
Club, Others, Park/Garden, Main Road, Pool                   1
Club, Park/Garden, Sea facing, Main Road, Others, Pool       1
Park/Garden, Pool, Main Road, Club, Others, Sea facing       1
Name: count, dtype: int64

In [56]:
df_bf['overlooking'].isnull().sum()

np.int64(1051)

#### 12. Corner Property

In [57]:
df_bf['cornerProperty'].value_counts()

cornerProperty
Y    3794
Name: count, dtype: int64

In [58]:
df_bf['cornerProperty'].isnull().sum()

np.int64(5416)

#### 13. Floor Number

In [59]:
df_bf['floorNum'].value_counts()[:20]

floorNum
2 of 4 Floors    2595
1 of 4 Floors    2156
4 of 4 Floors    1441
3 of 4 Floors    1429
2 of 2 Floors     252
1 of 3 Floors     225
2 of 3 Floors     207
1 of 2 Floors     207
G of 3 Floors     206
G of 2 Floors     173
3 of 3 Floors     125
G of 4 Floors      69
G of 1 Floors      23
1 of 1 Floors      13
2 of 5 Floors      12
3 of 5 Floors      11
1 of 5 Floors      10
4 of 5 Floors       9
L of 4 Floors       5
B of 4 Floors       3
Name: count, dtype: int64

- Builder floors typically have 3-4 floors total. Floor number is especially important for pricing (ground floor premium).

#### 14. Area With Type

In [60]:
df_bf['areaWithType'].value_counts()[:20]

areaWithType
2700 sqft Super Area     716
3240 sqft Super Area     351
1620 sqft Super Area     303
2430 sqft Super Area     298
2160 sqft Super Area     293
4500 sqft Super Area     284
2367 sqft Super Area     237
1836 sqft Super Area     207
1800 sqft Super Area     183
1935 sqft Super Area     181
2250 sqft Super Area     146
1611 sqft Super Area     136
3600 sqft Super Area     108
2844 sqft Super Area     107
2700 sqft Carpet Area    104
4518 sqft Super Area     101
3762 sqft Super Area      92
3078 sqft Super Area      85
3150 sqft Super Area      76
2475 sqft Super Area      68
Name: count, dtype: int64

#### 15. Address (Locality)

In [61]:
df_bf['address'].value_counts()[:20]

address
Sector 57, Gurgaon                  466
Sector 63A, Gurgaon                 414
DLF Phase 2, Gurgaon                360
Sushant Lok Phase 1, Gurgaon        340
South City 2, Gurgaon               328
Sector 89, Gurgaon                  325
Sector 65, Gurgaon                  314
Malibu Town, Gurgaon                309
Sector 70A, Gurgaon                 291
Palam Vihar, Gurgaon                224
Nirvana Country, Gurgaon            221
Sector 46, Gurgaon                  207
DLF Phase 1, Gurgaon                207
Sector 67, Gurgaon                  203
Sector 93, Gurgaon                  179
Sector 67A, Gurgaon                 172
Sector 48, Gurgaon                  163
DLF Phase 4, Gurgaon                154
Sector-33 Sohna, Gurgaon            148
Sushant Lok 3 Extension, Gurgaon    144
Name: count, dtype: int64

In [62]:
df_bf['address'].nunique()

172

#### 16. Parking

In [63]:
df_bf['parking'].value_counts()[:20]

parking
{"O":1,"C":2}    2053
{"C":2}          1934
{"C":1}          1224
{"O":1,"C":1}    1209
{"O":1}           675
{"O":2,"C":2}     543
{"O":1,"C":3}     350
["N"]             273
{"O":2}           181
{"C":3}           173
{"O":2,"C":3}     121
{"O":2,"C":1}      93
{"O":2,"C":4}      50
{"O":3}            34
{"C":4}            31
{"O":3,"C":3}      25
{"O":4,"C":3}      23
{"O":1,"C":4}      22
{"O":3,"C":2}      18
{"O":3,"C":1}      16
Name: count, dtype: int64

- Parking parsing (C=Covered, O=Open, N=None) will be done in feature engineering.

#### 17. Features, Description, Nearby, Lat/Long

In [64]:
print(f"Features nulls: {df_bf['features'].isnull().sum()}")
print(f"Description nulls: {df_bf['description'].isnull().sum()}")
print(f"NearbyLocations nulls: {df_bf['nearbyLocations'].isnull().sum()}")
print(f"Latitude nulls: {df_bf['latitude'].isnull().sum()}")
print(f"Longitude nulls: {df_bf['longitude'].isnull().sum()}")

Features nulls: 164
Description nulls: 0
NearbyLocations nulls: 131
Latitude nulls: 0
Longitude nulls: 0

### Final Cleaning Pipeline

In [3]:
AGE_POSSESSION_MAP = {
    1: '1 to 5 Year Old', 2: '5 to 10 Year Old',
    3: '10+ Year Old', 5: 'Under Construction', 6: '0 to 1 Year Old'
}

column_cleaning = (
    df_bf
    .rename(columns={
    'price': 'price_in_cr',
    'area': 'price_per_sqft'
})

    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )
    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )
    .loc[
        lambda df_: (
            df_['price_in_cr'].notna()
            & (df_['price_in_cr'] != 'Price on Request')
            & (df_['price_in_cr'] != '70,000')
        )
    ]
    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                    float(str(value).replace('Cr', '').strip())
                    if 'Cr' in str(value)
                    else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
    .assign(
        price_per_sqft=lambda df_: (
            df_['price_per_sqft']
            .str.split('₹')
            .str.get(1)
            .str.split('/')
            .str.get(0)
            .str.replace('L', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.strip()
            .pipe(pd.to_numeric, errors='coerce')
            .mul(
                np.where(
                    df_['price_per_sqft'].str.contains('L', na=False),
                    100000,
                    1
                )
            )
            .div(
                np.where(
                    df_['price_per_sqft'].str.contains('/sqyd', case=False, na=False),
                    9,
                    1
                )
            )
            .round()
            .astype('Int64')
        )
    
    , facing=lambda df_: df_['facing']
                                .replace('0', "Not Available")
                                .str
                                .lower()
    , furnishing=lambda df_: df_['furnishing']
                                .replace('0', "Not Available")
                                .str
                                .lower()
    , agePossession=lambda df_: df_['agePossession'].map(AGE_POSSESSION_MAP).fillna('Undefined')
    ))

print(f'Shape: {column_cleaning.shape}')
print(f'\nNull counts:')
print(column_cleaning.isnull().sum())
column_cleaning.head()

Shape: (9201, 24)

Null counts:
property_name         0
link                  0
society            3356
price_in_cr           0
price_per_sqft       92
areaWithType          0
carpetArea         4834
bedRoom               0
bathroom              0
balcony               1
address               0
floorNum              0
facing                0
overlooking        1048
agePossession         0
cornerProperty     5408
furnishing            0
parking              50
nearbyLocations     131
description           0
features            163
latitude              0
longitude             0
property_id           0
dtype: int64

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"3 BHK Builder Floor in Sector-33 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,central park flower valley flamingo floors,2.97,17222,1728 sqft Super Area,NaN,3,3,2.0,"Sector-33 Sohna, Gurgaon",3 of 4 Floors,east,"Pool, Park/Garden, Club, Main Road",Under Construction,NaN,unfurnished,"{""C"":2}","['Spazedge IT Park', 'Omaxe City Centre', 'JMD...",Independent builder floor premium\nHere is an ...,"['Overlooking Park', 'Overlooking Main Road', ...",28.283817,77.077636,V90137564
1,"3 BHK Builder Floor in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,ats bonheur avenue,1.53,12556,1214 sqft Super Area,1105.0,3,2,2.0,"Sohna, Gurgaon",2 of 4 Floors,north-east,"Others, Main Road, Park/Garden, Club",0 to 1 Year Old,Y,unfurnished,"{""O"":1,""C"":1}","['Airia Mall', 'Badshahpur Sohna Road Highway'...",3 bhk luxury floor at sohna road south gurgaon...,"['Overlooking Park', 'Overlooking Main Road', ...",28.285526,77.064149,H90017582
2,"3 BHK Builder Floor in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,signature global daxin vistas,2.04,15975,1277 sqft Carpet Area,1277.0,3,3,3.0,"Sohna, Gurgaon",3 of 4 Floors,north-east,"Main Road, Park/Garden, Club",Under Construction,NaN,semi-furnished,"{""C"":2}","['National Highway 248A', 'Tau Devilal Stadium...",Welcome to a home that instantly stands out fr...,"['North-East Facing', 'Vaastu Compliant', 'Vis...",28.332976,77.067894,D86965890
3,"3 BHK Builder Floor in Sector-35 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,green valley independent floors,1.68,12667,1323 sqft Super Area,NaN,3,3,2.0,"Sector-35 Sohna, Gurgaon",2 of 4 Floors,east,Park/Garden,Under Construction,NaN,unfurnished,"{""C"":1}","['S.R.S. Hospital and Critical Care Unit', 'Th...","Located in green valley independent floors, se...","['Gated Society', 'Overlooking Park', 'North F...",28.419477,76.999628,I90695536
4,"3 BHK Builder Floor in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,signature global daxin vistas,2.35,12667,1850 sqft Super Area,1221.0,3,3,2.0,"Sohna, Gurgaon",1 of 4 Floors,south,"Club, Main Road, Park/Garden",Under Construction,NaN,semi-furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...","This 1st-Floor, low-Rise builder floor in sign...","['Gated Society', 'Overlooking Park', 'Overloo...",28.332976,77.067894,E90903990

In [5]:
from IPython.display import display

# Work on a copy of the cleaned data
df_dedupe = column_cleaning.copy()

# --- Chosen dedup key (Option A, refined) ---
# Rows with identical values for ALL these columns are treated as the SAME flat,
# reposted by different agents.
DEDUP_KEY = ['property_name', 'society', 'price_in_cr',
             'areaWithType', 'floorNum', 'facing', 'overlooking']

# How many rows would this key remove?
n_drop = df_dedupe.duplicated(subset=DEDUP_KEY).sum()
print(f"Total rows        : {len(df_dedupe)}")
print(f"Duplicates to drop: {n_drop} ({100 * n_drop / len(df_dedupe):.1f}%)")

Total rows        : 9201
Duplicates to drop: 33 (0.4%)

In [6]:
# Columns that make it easy to judge if two rows are the same flat
VIEW = ['society', 'areaWithType', 'floorNum', 'facing', 'overlooking',
        'bedRoom', 'bathroom', 'carpetArea', 'price_in_cr', 'property_name', 'link']

def show_duplicates(key=DEDUP_KEY, n_groups=8):
    """Print the first few groups of rows flagged as duplicates by `key`."""
    dupes = df_dedupe[df_dedupe.duplicated(subset=key, keep=False)]
    n_total = dupes.groupby(key, dropna=False).ngroups
    print(n_total, "duplicate groups,", len(dupes), "rows involved")
    print()
    for i, (_, group) in enumerate(dupes.groupby(key, dropna=False), start=1):
        if i > n_groups:
            break
        print(f"--- group {i}  ({len(group)} rows) ---")
        display(group[VIEW])

show_duplicates()

33 duplicate groups, 66 rows involved

--- group 1  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
4236,NaN,1728 sqft Super Area,1 of 2 Floors,north-east,"Pool, Park/Garden, Club, Main Road",2,2,NaN,1.79,"2 BHK Builder Floor in Nirvana Country, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...
4237,NaN,1728 sqft Super Area,1 of 2 Floors,north-east,"Pool, Park/Garden, Club, Main Road",2,2,NaN,1.79,"2 BHK Builder Floor in Nirvana Country, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...

--- group 2  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
2639,NaN,2160 sqft Super Area,3 of 3 Floors,north-east,Main Road,3,2,NaN,1.75,"3 BHK Builder Floor in B1 Block Sector 57, Gur...",https://www.99acres.com/3-bhk-bedroom-independ...
2673,NaN,2160 sqft Super Area,3 of 3 Floors,north-east,Main Road,3,2,1400.0,1.75,"3 BHK Builder Floor in B1 Block Sector 57, Gur...",https://www.99acres.com/3-bhk-bedroom-independ...

--- group 3  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
4921,NaN,1935 sqft Super Area,1 of 4 Floors,north-east,"Pool, Park/Garden, Club, Main Road",3,3,213.0,4.2,"3 BHK Builder Floor in Block C, Sushant Lok Ph...",https://www.99acres.com/3-bhk-bedroom-independ...
4922,NaN,1935 sqft Super Area,1 of 4 Floors,north-east,"Pool, Park/Garden, Club, Main Road",3,3,213.0,4.2,"3 BHK Builder Floor in Block C, Sushant Lok Ph...",https://www.99acres.com/3-bhk-bedroom-independ...

--- group 4  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
8050,NaN,1935 sqft Super Area,G of 3 Floors,not available,NaN,3,3,NaN,2.3,"3 BHK Builder Floor in Block N, Mayfield garde...",https://www.99acres.com/3-bhk-bedroom-independ...
8076,NaN,1935 sqft Super Area,G of 3 Floors,not available,NaN,3,3,NaN,2.3,"3 BHK Builder Floor in Block N, Mayfield garde...",https://www.99acres.com/3-bhk-bedroom-independ...

--- group 5  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
3435,dlf exclusive floors,2400 sqft Super Area,1 of 2 Floors,north-east,Park/Garden,3,3,1400.0,3.5,"3 BHK Builder Floor in DLF Phase 5, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...
3521,dlf exclusive floors,2400 sqft Super Area,1 of 2 Floors,north-east,Park/Garden,3,4,1800.0,3.5,"3 BHK Builder Floor in DLF Phase 5, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...

--- group 6  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
8940,signature global park 4,1081 sqft Super Area,3 of 4 Floors,north-east,"Pool, Park/Garden, Club, Main Road",3,2,NaN,1.0,"3 BHK Builder Floor in Sector 36 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...
8972,signature global park 4,1081 sqft Super Area,3 of 4 Floors,north-east,"Pool, Park/Garden, Club, Main Road",3,2,NaN,1.0,"3 BHK Builder Floor in Sector 36 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...

--- group 7  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
7312,NaN,1800 sqft Super Area,3 of 4 Floors,east,Main Road,3,3,1300.0,2.85,"3 BHK Builder Floor in Sector 45, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...
7393,NaN,1800 sqft Super Area,3 of 4 Floors,east,Main Road,3,3,1350.0,2.85,"3 BHK Builder Floor in Sector 45, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...

--- group 8  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
7949,orchid island,2250 sqft Super Area,3 of 3 Floors,north,Main Road,3,3,245.0,2.8,"3 BHK Builder Floor in Sector 51, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...
7964,orchid island,2250 sqft Super Area,3 of 3 Floors,north,Main Road,3,3,245.0,2.8,"3 BHK Builder Floor in Sector 51, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...