In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)

C:\Users\Jay Patel\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

### 1. Independent House Data Loading

In [2]:
df_house = pd.read_csv(r"C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\independent_house.csv")
df_house

,property_name,society,price,area,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,areawithtype,furnishing_details,features,nearby_location
0,"4 Bedroom House in Sector 4, Gurgaon","Sector 4, Gurgaon",₹6.6 Cr,"₹14,667 /sqft",N80213331,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,2 Floors,South,10+ Year Old,4500 sqft (418.06 sqm) Plot Area,"['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']","['Palam Vihar Vyapar kendra', 'Palam vihar rai..."
1,"6 Bedroom House in DLF Phase 1, Gurgaon",North East & Park Facing Corner 18 meter wide ...,₹25 Cr,"₹22,727 /sqft",Q84155382,https://www.99acres.com/6-bhk-bedroom-independ...,6 Bedrooms,10 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,11000 sqft (1021.93 sqm) Plot Area,"['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Anahat Hospital', 'Sikandarpur rmrg metro st..."
2,"2 Bedroom House in Sector 15 Part 2, Gurgaon","Sector 15 Part 2, Gurgaon",₹18.99 Cr,"₹42,031 /sqft",S82406206,https://www.99acres.com/2-bhk-bedroom-independ...,2 Bedrooms,2 Bathrooms,No Balcony,NaN,NaN,NaN,NaN,4518 sqft (419.74 sqm) Plot Area,[],NaN,"['govt sec school', 'Ahmed Hospital Multi Spec..."
3,"3 Bedroom House in Jhajjar Road, Gurgaon","Green Heritage Villas, Jhajjar",₹3.39 Cr,"₹3,766 /sqft",J84873064,https://www.99acres.com/3-bhk-bedroom-independ...,3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,9000 sqft (836.13 sqm) Plot Area,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",[]
4,"5 Bedroom House in Sector 109, Gurgaon",Sobha International City Phase 3,₹14 Cr,"₹38,889 /sqft",Q83769064,https://www.99acres.com/5-bhk-bedroom-independ...,5 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,3600 sqft (334.45 sqm) Plot Area,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Palam Vihar Vyapar kendra', 'Palam vihar rai..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2263,"3 Bedroom House in Sector 49, Gurgaon",Eros Rosewood City,₹4.5 Cr,"₹32,680 /sqft",V81604971,https://www.99acres.com/3-bhk-bedroom-independ...,3 Bedrooms,3 Bathrooms,1 Balcony,NaN,2 Floors,NaN,5 to 10 Year Old,1377 sqft (127.93 sqm) Plot Area,[],NaN,"['Silver Oak Universal', 'Leelavati Hospital',..."
2264,"4 Bedroom House in Pratap Nagar, Gurgaon",383/13 Partap nagar,₹1.1 Cr,"₹6,077 /sqft",Q81598269,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,2 Bathrooms,No Balcony,NaN,2 Floors,East,Under Construction,1810 sqft (168.15 sqm) Plot Area,NaN,"['Water Storage', 'Park']",[]
2265,"4 Bedroom House in DLF Phase 3, Gurgaon",National Media Centre,₹7 Cr,"₹32,407 /sqft",Q81594211,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,2160 sqft (200.67 sqm) Plot Area,"['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito...","['Deutsche bank', 'Dental Cure and Care Centre..."
2266,"2 Bedroom House in Devilal Colony, Gurgaon","Devilal Colony, Gurgaon",₹70 Lac,"₹76,923 /sqft",D81585663,https://www.99acres.com/2-bhk-bedroom-independ...,2 Bedrooms,1 Bathroom,1 Balcony,NaN,1 Floors,West,10+ Year Old,91 sqft (8.45 sqm) Plot Area,NaN,NaN,"['Prateek Nursing Home And Polyclinic', 'Shubh..."
2267,"5 Bedroom House in Sector 53, Gurgaon","Sector 53, Gurgaon",₹4 Cr,"₹17,778 /sqft",H47319641,https://www.99acres.com/5-bhk-bedroom-independ...,5 Bedrooms,5 Bathrooms,2 Balconies,Study Room,3 Floors,NaN,1 to 5 Year Old,2250 sqft (209.03 sqm) Plot Area,NaN,"['Private Garden / Terrace', 'Water Storage', ...","['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5..."

In [3]:
df_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2268 entries, 0 to 2267
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       2268 non-null   object
 1   society             2268 non-null   object
 2   price               2268 non-null   object
 3   area                2262 non-null   object
 4   property_id         2268 non-null   object
 5   link                2268 non-null   object
 6   bedrooms            2268 non-null   object
 7   bathrooms           2268 non-null   object
 8   balcony             2268 non-null   object
 9   additional_room     1736 non-null   object
 10  floor_info          2162 non-null   object
 11  facing              1884 non-null   object
 12  property_age        2163 non-null   object
 13  areawithtype        2268 non-null   object
 14  furnishing_details  1920 non-null   object
 15  features            1933 non-null   object
 16  nearby_location     2268 non-null   object
dtypes: object(17)
memory usage: 301.3+ KB

In [4]:
df_house.describe()

,property_name,society,price,area,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,areawithtype,furnishing_details,features,nearby_location
count,2268,2268,2268,2262,2268,2268,2268,2268,2268,1736,2162,1884,2163,2268,1920,1933,2268
unique,922,602,463,1418,2268,2268,29,29,5,94,22,8,5,868,1535,1064,832
top,"5 Bedroom House in Sector 109, Gurgaon",Emaar MGF Marbella,₹12 Cr,"₹44,444 /sqft",N80213331,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",3 Floors,North-East,5 to 10 Year Old,4500 sqft (418.06 sqm) Plot Area,[],"['Feng Shui / Vaastu Compliant', 'Private Gard...",[]
freq,41,58,44,27,1,1,538,499,1029,219,830,512,682,107,182,158,135

In [5]:
df_house.shape

(2268, 17)

In [11]:
df_house.isnull().sum()

property_name           0
society                 0
price                   0
area                    6
property_id             0
link                    0
bedrooms                0
bathrooms               0
balcony                 0
additional_room       532
floor_info            106
facing                384
property_age          106
areawithtype            0
furnishing_details    348
features              335
nearby_location         0
dtype: int64

### 2. Independent House Cleaning

In [12]:
df_house.columns

Index(['property_name', 'society', 'price', 'area', 'property_id', 'link',
       'bedrooms', 'bathrooms', 'balcony', 'additional_room', 'floor_info',
       'facing', 'property_age', 'areawithtype', 'furnishing_details',
       'features', 'nearby_location'],
      dtype='object')

In [13]:
df_house = df_house[['property_id','property_name', 'link', 'society', 'price', 'area',
       'areawithtype', 'bedrooms', 'bathrooms', 'balcony', 'additional_room',
       'floor_info', 'facing', 'property_age', 'nearby_location',
        'furnishing_details', 'features']]
df_house

,property_id,property_name,link,society,price,area,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",₹6.6 Cr,"₹14,667 /sqft",4500 sqft (418.06 sqm) Plot Area,4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,₹25 Cr,"₹22,727 /sqft",11000 sqft (1021.93 sqm) Plot Area,6 Bedrooms,10 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",₹18.99 Cr,"₹42,031 /sqft",4518 sqft (419.74 sqm) Plot Area,2 Bedrooms,2 Bathrooms,No Balcony,NaN,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",₹3.39 Cr,"₹3,766 /sqft",9000 sqft (836.13 sqm) Plot Area,3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,₹14 Cr,"₹38,889 /sqft",3600 sqft (334.45 sqm) Plot Area,5 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,₹4.5 Cr,"₹32,680 /sqft",1377 sqft (127.93 sqm) Plot Area,3 Bedrooms,3 Bathrooms,1 Balcony,NaN,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,₹1.1 Cr,"₹6,077 /sqft",1810 sqft (168.15 sqm) Plot Area,4 Bedrooms,2 Bathrooms,No Balcony,NaN,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,₹7 Cr,"₹32,407 /sqft",2160 sqft (200.67 sqm) Plot Area,4 Bedrooms,4 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",₹70 Lac,"₹76,923 /sqft",91 sqft (8.45 sqm) Plot Area,2 Bedrooms,1 Bathroom,1 Balcony,NaN,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",₹4 Cr,"₹17,778 /sqft",2250 sqft (209.03 sqm) Plot Area,5 Bedrooms,5 Bathrooms,2 Balconies,Study Room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [14]:
missing_summary = (df_house
                    .isnull()
                    .sum()
                    .pipe(lambda d: d/(len(df_house)) * 100)
                    .reset_index()
                    .rename(columns={"index":"Feature/Column Name",0:"Missing Pct"})
                    .sort_values(by='Missing Pct', ascending=False)
)

In [15]:
missing_summary

   Feature/Column Name  Missing Pct
10     additional_room    23.446452
12              facing    16.923755
15  furnishing_details    15.337153
16            features    14.764213
13        property_age     4.671662
11          floor_info     4.671662
5                 area     0.264434
9              balcony     0.000000
14     nearby_location     0.000000
0          property_id     0.000000
1        property_name     0.000000
7             bedrooms     0.000000
6         areawithtype     0.000000
4                price     0.000000
3              society     0.000000
2                 link     0.000000
8            bathrooms     0.000000

### 3. Individual Column Cleaning

#### 1. Property Name

In [16]:
df_house['property_name'].isnull().sum()

0

#### 2. Society

In [ ]:
df_house['society'].value_counts()

society
Emaar MGF Marbella         58
Vipul Tatvam Villa         50
Ansals Palam Vihar         50
DLF Phase 1, Gurgaon       44
DLF Phase 2, Gurgaon       43
                           ..
SECTOR 40                   1
Experion The Westerlies     1
Luxury Villa                1
q block sector 40           1
Sector 53, Gurgaon          1
Name: count, Length: 602, dtype: int64

In [21]:
df_house['society'].isnull().sum()

0

#### 2. Price_in_Cr

In [22]:
df_house = df_house.rename(columns ={
    'price' : 'price_in_cr',
    'area'  :'price_per_sqft'
})

In [23]:
df_house['price_in_cr'].value_counts()

price_in_cr
₹12 Cr              44
₹15 Cr              42
₹9 Cr               42
₹7.5 Cr             40
₹8.5 Cr             39
₹6.5 Cr             35
₹14 Cr              33
₹12.5 Cr            33
₹25 Cr              33
₹11 Cr              31
₹3.5 Cr             30
₹9.5 Cr             30
₹17 Cr              29
₹7 Cr               27
₹5.5 Cr             26
₹8 Cr               26
₹5 Cr               25
₹4.5 Cr             25
₹10 Cr              24
₹6 Cr               24
₹1.2 Cr             21
₹18 Cr              21
₹11.5 Cr            19
₹4.25 Cr            19
₹13 Cr              19
₹2.5 Cr             19
₹1.5 Cr             18
₹10.5 Cr            17
₹5.25 Cr            17
₹16 Cr              17
₹14.5 Cr            17
₹1.35 Cr            16
₹8.75 Cr            16
₹7.25 Cr            16
₹21 Cr              15
₹75 Lac             15
₹13.5 Cr            14
₹15.5 Cr            13
₹2.25 Cr            13
₹95 Lac             13
₹2.2 Cr             13
₹8.25 Cr            13
₹3.1 Cr             12
₹90 Lac             12
₹3 Cr               12
₹11.25 Cr           12
₹4 Cr               12
₹1.3 Cr             12
₹1.1 Cr             12
₹80 Lac             12
₹70 Lac             12
₹2 Cr               12
₹1.4 Cr             11
₹1.7 Cr             11
₹19 Cr              11
₹2.4 Cr             11
₹55 Lac             11
₹22 Cr              11
₹3.35 Cr            11
₹18.5 Cr            11
₹3.25 Cr            11
₹20 Cr              11
₹2.3 Cr             10
₹7.75 Cr            10
₹4.3 Cr             10
₹65 Lac             10
₹2.6 Cr             10
₹9.25 Cr            10
₹16.5 Cr            10
₹10.75 Cr            9
₹1.25 Cr             9
₹4.75 Cr             9
₹1.65 Cr             9
₹3.6 Cr              9
₹60 Lac              9
₹6.25 Cr             9
₹1 Cr                9
₹3.4 Cr              9
₹4.1 Cr              9
₹2.1 Cr              8
₹2.15 Cr             8
₹7.6 Cr              8
₹5.1 Cr              8
₹11.75 Cr            8
₹3.3 Cr              8
₹2.8 Cr              8
₹1.6 Cr              8
₹9.75 Cr             7
₹3.75 Cr             7
₹23.5 Cr             7
₹7.7 Cr              7
₹28 Cr               7
₹4.6 Cr              7
₹50 Lac              7
₹6.6 Cr              7
₹17.5 Cr             7
₹5.7 Cr              7
₹3.8 Cr              7
₹24 Cr               7
₹7.15 Cr             7
₹6.2 Cr              6
₹1.75 Cr             6
₹4.4 Cr              6
₹6.75 Cr             6
₹4.8 Cr              6
₹35 Lac              6
₹4.65 Cr             6
₹7.2 Cr              6
₹16.25 Cr            6
₹5.8 Cr              6
₹7.49 Cr             6
₹2.9 Cr              6
₹2.7 Cr              6
₹6.1 Cr              6
₹5.9 Cr              6
₹9.4 Cr              6
₹22.5 Cr             6
₹7.85 Cr             6
₹3.2 Cr              6
₹6.9 Cr              6
Price on Request     6
₹30 Cr               5
₹78 Lac              5
₹35 Cr               5
₹12.25 Cr            5
₹2.75 Cr             5
₹2.85 Cr             5
₹6.3 Cr              5
₹4.7 Cr              5
₹1.85 Cr             5
₹6.7 Cr              5
₹2.65 Cr             5
₹5.6 Cr              4
₹98 Lac              4
₹13.25 Cr            4
₹8.35 Cr             4
₹19.5 Cr             4
₹42 Lac              4
₹9.1 Cr              4
₹3.7 Cr              4
₹99 Lac              4
₹5.75 Cr             4
₹1.9 Cr              4
₹1.8 Cr              4
₹7.3 Cr              4
₹3.65 Cr             4
₹85 Lac              4
₹23 Cr               4
₹3.55 Cr             4
₹6.45 Cr             4
₹12.75 Cr            4
₹3.9 Cr              4
₹7.9 Cr              4
₹4.2 Cr              4
₹6.35 Cr             4
₹10.6 Cr             4
₹3.15 Cr             4
₹69 Lac              3
₹89 Lac              3
₹5.15 Cr             3
₹10.7 Cr             3
₹6.15 Cr             3
₹19.25 Cr            3
₹3.45 Cr             3
₹27 Cr               3
₹9.8 Cr              3
₹8.3 Cr              3
₹14.49 Cr            3
₹8.9 Cr              3
₹1.45 Cr             3
₹77 Lac              3
₹5.65 Cr             3
₹7.4 Cr              3
₹11.9 Cr             3
₹1.05 Cr             3
₹9.2 Cr              3
₹4.95 Cr             3
₹82 Lac              3
₹10.2 Cr             3
₹48 Lac              3
₹4.45 Cr             3
₹4.9 Cr              3
₹24.5 Cr             3
₹7.95 Cr             3
₹10.25 Cr            3
₹79 Lac              3
₹1.15 Cr             3
₹8.15 Cr             3
₹7.1 Cr              3
₹13.75 Cr            3
₹3.05 Cr             3
₹9.3 Cr              3
₹3.85 Cr             3
₹1.95 Cr             3
₹5.85 Cr             3
₹10.3 Cr             2
₹2.38 Cr             2
₹30 Lac              2
₹72 Lac              2
₹2.45 Cr             2
₹14.25 Cr            2
₹15.75 Cr            2
₹12.9 Cr             2
₹7.65 Cr             2
₹5.55 Cr             2
₹14.75 Cr            2
₹40 Lac              2
₹12.99 Cr            2
₹1.59 Cr             2
₹58 Lac              2
₹10.9 Cr             2
₹1.79 Cr             2
₹10.15 Cr            2
₹7.45 Cr             2
₹6.55 Cr             2
₹7.8 Cr              2
₹6.85 Cr             2
₹4.21 Cr             2
₹2.95 Cr             2
₹8.95 Cr             2
₹5.95 Cr             2
₹32 Cr               2
₹37 Cr               2
₹4.15 Cr             2
₹20.5 Cr             2
₹8.4 Cr              2
₹6.49 Cr             2
₹17.75 Cr            2
₹57 Lac              2
₹9.65 Cr             2
₹17.25 Cr            2
₹68 Lac              2
₹10.4 Cr             2
₹64 Lac              2
₹5.3 Cr              2
₹7.35 Cr             2
₹76 Lac              2
₹4.35 Cr             2
₹12.15 Cr            2
₹9.85 Cr             2
₹40 Cr               2
₹1.19 Cr             2
₹6.82 Cr             2
₹14.65 Cr            2
₹67 Lac              2
₹2.35 Cr             2
₹1.52 Cr             2
₹6.65 Cr             2
₹12.49 Cr            2
₹7.19 Cr             2
₹28.5 Cr             2
₹25.5 Cr             2
₹2.18 Cr             2
₹1.27 Cr             2
₹10.8 Cr             2
₹10.99 Cr            2
₹9.35 Cr             1
₹9.37 Cr             1
₹55 Cr               1
₹10.45 Cr            1
₹13.9 Cr             1
₹15.25 Cr            1
₹13.95 Cr            1
₹19.9 Cr             1
₹6.42 Cr             1
₹22.9 Cr             1
₹10.72 Cr            1
₹9.6 Cr              1
₹4.85 Cr             1
₹61 Lac              1
₹62 Lac              1
₹11.65 Cr            1
₹21.75 Cr            1
₹3.73 Cr             1
₹1.11 Cr             1
₹2.22 Cr             1
₹12.6 Cr             1
₹8.6 Cr              1
₹97.12 Lac           1
₹5.81 Cr             1
₹1.23 Cr             1
₹12.3 Cr             1
₹12.4 Cr             1
₹4.68 Cr             1
₹15.7 Cr             1
₹6.8 Cr              1
₹9.39 Cr             1
₹1.84 Cr             1
₹5.21 Cr             1
₹37 Lac              1
₹29.5 Cr             1
₹57 Cr               1
₹25.5 Lac            1
₹1.02 Cr             1
₹37.5 Lac            1
₹18.99 Cr            1
₹2.59 Cr             1
₹5.89 Cr             1
₹25 Lac              1
₹26 Lac              1
₹18.85 Cr            1
₹2.03 Cr             1
₹2.44 Cr             1
₹24 Lac              1
₹2.55 Cr             1
₹5.35 Cr             1
₹71 Lac              1
₹17 Lac              1
₹1.78 Cr             1
₹28.5 Lac            1
₹1.12 Cr             1
₹1.21 Cr             1
₹2.32 Cr             1
₹1.99 Cr             1
₹29.95 Cr            1
₹1.98 Cr             1
₹94.99 Lac           1
₹74.5 Lac            1
₹3.39 Cr             1
₹76.75 Lac           1
₹48 Cr               1
₹11.7 Cr             1
₹46 Cr               1
₹10.77 Cr            1
₹2.76 Cr             1
₹4.55 Cr             1
₹3.67 Cr             1
₹15.15 Cr            1
₹30.8 Lac            1
₹26.5 Cr             1
₹5.4 Cr              1
₹10.05 Cr            1
₹3.29 Cr             1
₹28.75 Cr            1
₹45 Lac              1
₹28 Lac              1
₹4.09 Cr             1
₹52 Lac              1
₹20 Lac              1
₹4.05 Cr             1
₹63 Lac              1
₹39 Lac              1
₹73 Lac              1
₹18.95 Lac           1
₹80 Cr               1
₹56 Lac              1
₹15.8 Cr             1
₹10.65 Cr            1
₹12.45 Cr            1
₹16.1 Cr             1
₹13.85 Cr            1
₹6.18 Cr             1
₹20.75 Cr            1
₹14.6 Cr             1
₹2.05 Cr             1
₹17.99 Cr            1
₹17.9 Cr             1
₹1.16 Cr             1
₹11.99 Cr            1
₹6.29 Cr             1
₹8.2 Cr              1
₹14.48 Cr            1
₹3.99 Cr             1
₹4.92 Cr             1
₹5.05 Cr             1
₹11.45 Cr            1
₹97 Lac              1
₹1.24 Cr             1
₹1.26 Cr             1
₹84.99 Lac           1
₹6.95 Cr             1
₹79.85 Lac           1
₹7.56 Cr             1
₹1.68 Cr             1
₹15.1 Cr             1
₹64.78 Lac           1
₹8.8 Cr              1
₹7.68 Cr             1
₹16.55 Cr            1
₹13.8 Cr             1
₹7.99 Cr             1
₹49 Lac              1
₹20.95 Cr            1
₹6.57 Cr             1
₹9.45 Cr             1
₹6.28 Cr             1
₹83.9 Lac            1
₹20.98 Cr            1
₹1.54 Cr             1
₹14.2 Cr             1
₹12.65 Cr            1
₹1.92 Cr             1
₹5.67 Cr             1
₹16.75 Cr            1
₹1.32 Cr             1
₹4.13 Cr             1
₹11.05 Cr            1
₹17.05 Cr            1
₹1.42 Cr             1
₹1.31 Cr             1
₹10.95 Cr            1
₹12.1 Cr             1
₹21.5 Cr             1
₹29.31 Cr            1
₹7.23 Cr             1
₹3.95 Cr             1
₹1.29 Cr             1
₹19.75 Cr            1
₹88 Lac              1
₹15.4 Cr             1
₹11.85 Cr            1
₹5.99 Cr             1
₹12.84 Cr            1
₹12.8 Cr             1
₹12.18 Cr            1
₹12.2 Cr             1
₹11.1 Cr             1
₹3.27 Cr             1
₹8.24 Cr             1
₹97.99 Lac           1
₹15.2 Cr             1
₹14.4 Cr             1
₹29.75 Cr            1
₹23.9 Cr             1
₹33 Cr               1
₹16.49 Cr            1
₹26 Cr               1
₹15.65 Cr            1
₹15.3 Cr             1
₹12.22 Cr            1
₹34 Cr               1
₹15.05 Cr            1
₹11.49 Cr            1
₹8.7 Cr              1
₹6.4 Cr              1
₹14.52 Cr            1
₹14.8 Cr             1
₹18.75 Cr            1
₹15.9 Cr             1
₹7.55 Cr             1
₹19.6 Cr             1
₹17.49 Cr            1
₹24.9 Cr             1
₹10.49 Cr            1
₹8.1 Cr              1
₹18.25 Cr            1
₹1.08 Cr             1
₹10.53 Cr            1
₹20.9 Cr             1
₹9.9 Cr              1
₹5.45 Cr             1
₹7.71 Cr             1
₹37.5 Cr             1
₹18.7 Cr             1
₹14.85 Cr            1
₹6.99 Cr             1
₹1.55 Cr             1
₹13.73 Cr            1
₹17.15 Cr            1
₹11.58 Cr            1
₹43 Cr               1
₹9.95 Cr             1
₹25.65 Cr            1
₹41 Lac              1
Name: count, dtype: int64

In [24]:
column_cleaning = (df_house.assign
                   (
                       price_in_cr = lambda df_:df_['price_in_cr']
                                            .str.replace('₹','')
                   ))
column_cleaning['price_in_cr'].unique()

array(['6.6 Cr', '25 Cr', '18.99 Cr', '3.39 Cr', '14 Cr', '2.25 Cr',
       '4.5 Cr', '12 Cr', '11 Cr', '3.4 Cr', '2.9 Cr', '11.75 Cr',
       '9.1 Cr', '7.65 Cr', '22.5 Cr', '7.75 Cr', '8.75 Cr', '13 Cr',
       '8.5 Cr', '3.6 Cr', '18 Cr', '7.49 Cr', '7.15 Cr', '8.2 Cr',
       '9 Cr', '5.9 Cr', '5.7 Cr', '7.5 Cr', '13.85 Cr', '9.5 Cr',
       '8.8 Cr', '1.75 Cr', '17.5 Cr', '15 Cr', '3.35 Cr', '24.5 Cr',
       '2.3 Cr', '13.25 Cr', '12.9 Cr', '21.5 Cr', '6.5 Cr', '7.95 Cr',
       '10.95 Cr', '13.5 Cr', '3.85 Cr', '12.5 Cr', '9.25 Cr', '8 Cr',
       '10 Cr', '11.25 Cr', '2.35 Cr', '3.25 Cr', '9.3 Cr', '3.5 Cr',
       '15.75 Cr', '24 Cr', '23 Cr', '18.5 Cr', '10.5 Cr', '30 Cr',
       '5.95 Cr', '11.5 Cr', '7.9 Cr', '16 Cr', '3.8 Cr', '7 Cr',
       '5.55 Cr', '5.5 Cr', '19 Cr', '1.54 Cr', '7.19 Cr', '2.2 Cr',
       '12.75 Cr', '1.6 Cr', '79 Lac', '5.25 Cr', '21 Cr', '1.35 Cr',
       '9.45 Cr', '6.49 Cr', '8.25 Cr', '2.1 Cr', '1.4 Cr', '1.95 Cr',
       '2.4 Cr', '75 Lac', '80 Lac', '1.5 Cr', '70 Lac', '1.8 Cr',
       '20.95 Cr', '49 Lac', '3.2 Cr', '2.65 Cr', '4.9 Cr', '1.65 Cr',
       '17 Cr', '7.99 Cr', '2 Cr', '4.25 Cr', '1.2 Cr', '6.57 Cr',
       '60 Lac', '1.7 Cr', '6.65 Cr', '2.75 Cr', '5 Cr', '5.85 Cr',
       '3.7 Cr', '6.55 Cr', '4.1 Cr', '2.8 Cr', '3.1 Cr', '6.28 Cr',
       '10.25 Cr', '14.5 Cr', '83.9 Lac', '20.98 Cr', '2.6 Cr', '5.75 Cr',
       '12.49 Cr', '2.45 Cr', '14.2 Cr', '3 Cr', '12.65 Cr', '72 Lac',
       '6.45 Cr', '1.92 Cr', '5.67 Cr', '4 Cr', '4.2 Cr', '6 Cr',
       '8.4 Cr', '16.75 Cr', '2.5 Cr', '3.9 Cr', '3.65 Cr', '85 Lac',
       '22 Cr', '2.95 Cr', '1.15 Cr', '1.32 Cr', '4.13 Cr', '90 Lac',
       '11.05 Cr', '7.25 Cr', '4.7 Cr', '8.15 Cr', '1.9 Cr', '7.1 Cr',
       '12.25 Cr', '16.25 Cr', '17.05 Cr', '13.75 Cr', '16.5 Cr',
       '1.42 Cr', '3.05 Cr', '9.75 Cr', '25.5 Cr', '95 Lac', '1.31 Cr',
       '10.75 Cr', '1.1 Cr', '76 Lac', '6.1 Cr', '4.3 Cr', '5.3 Cr',
       '12.1 Cr', '6.3 Cr', '1 Cr', '29.31 Cr', '7.23 Cr', '17.75 Cr',
       '20 Cr', '10.9 Cr', '6.25 Cr', '6.7 Cr', '13.8 Cr', '16.55 Cr',
       '2.15 Cr', '4.75 Cr', '82 Lac', '4.8 Cr', '7.68 Cr', '20.5 Cr',
       '1.25 Cr', '1.3 Cr', '6.2 Cr', '15.5 Cr', '23.5 Cr', '6.18 Cr',
       '5.8 Cr', '14.65 Cr', '20.75 Cr', '14.6 Cr', '1.85 Cr', '1.59 Cr',
       '5.6 Cr', '17.25 Cr', '9.4 Cr', '10.4 Cr', '2.05 Cr', '17.99 Cr',
       '4.6 Cr', '8.9 Cr', '8.3 Cr', '17.9 Cr', '12.15 Cr', '1.16 Cr',
       '77 Lac', '1.19 Cr', '11.99 Cr', '5.65 Cr', '7.4 Cr', '11.9 Cr',
       '19.5 Cr', '6.29 Cr', '10.8 Cr', '3.75 Cr', '14.48 Cr', '16.1 Cr',
       '7.85 Cr', '3.99 Cr', '5.05 Cr', '11.45 Cr', '6.82 Cr', '97 Lac',
       '1.24 Cr', '1.26 Cr', '84.99 Lac', '2.7 Cr', '6.95 Cr', '7.6 Cr',
       '79.85 Lac', '7.7 Cr', '9.2 Cr', '7.56 Cr', '4.95 Cr', '1.68 Cr',
       '14.75 Cr', '15.1 Cr', '64.78 Lac', '7.3 Cr', '3.95 Cr', '1.29 Cr',
       '19.75 Cr', '9.8 Cr', '7.2 Cr', '10.15 Cr', '7.45 Cr', '10.6 Cr',
       '7.8 Cr', '14.8 Cr', '6.85 Cr', '35 Cr', '4.65 Cr', '15.9 Cr',
       '7.55 Cr', '32 Cr', '19.6 Cr', '14.49 Cr', '17.49 Cr', '24.9 Cr',
       '2.85 Cr', '10.49 Cr', '6.75 Cr', '4.4 Cr', '67 Lac', '8.1 Cr',
       '18.25 Cr', '37 Cr', '1.08 Cr', '10.53 Cr', '20.9 Cr', '12.99 Cr',
       '9.9 Cr', '89 Lac', '10.7 Cr', '5.45 Cr', '10.65 Cr', '5.1 Cr',
       '4.45 Cr', '7.71 Cr', '37.5 Cr', '9.85 Cr', '4.35 Cr', '7.35 Cr',
       '18.7 Cr', '68 Lac', '14.85 Cr', '6.99 Cr', '1.55 Cr', '3.3 Cr',
       '6.35 Cr', '13.73 Cr', '17.15 Cr', '11.58 Cr', '9.65 Cr', '6.9 Cr',
       '43 Cr', '9.95 Cr', '25.65 Cr', '18.75 Cr', '14.52 Cr', '8.95 Cr',
       '3.55 Cr', '88 Lac', '6.4 Cr', '15.4 Cr', '27 Cr', '11.85 Cr',
       '4.15 Cr', '3.15 Cr', '5.99 Cr', '12.84 Cr', 'Price on Request',
       '12.8 Cr', '12.18 Cr', '12.2 Cr', '11.1 Cr', '3.27 Cr', '28 Cr',
       '14.25 Cr', '8.24 Cr', '1.05 Cr', '97.99 Lac', '15.2 Cr',
       '14.4 Cr', '28.5 Cr', '29.75 Cr', '10.99 Cr', '23.9 Cr', '8.35 Cr',
       '33 Cr', '16.49 Cr', '26 Cr', '15.65 Cr', '6.15 Cr', '15.3 Cr',
       '12.22 Cr', '34 Cr', '15.05 Cr', '11.49 Cr', '3.45 Cr', '8.7 Cr',
       '4.92 Cr', '12.45 Cr', '18.85 Cr', '15.8 Cr', '5.21 Cr', '4.21 Cr',
       '97.12 Lac', '5.15 Cr', '11.65 Cr', '22.9 Cr', '4.85 Cr',
       '19.25 Cr', '21.75 Cr', '3.73 Cr', '40 Cr', '2.22 Cr', '2.18 Cr',
       '12.6 Cr', '8.6 Cr', '1.45 Cr', '9.6 Cr', '1.23 Cr', '12.3 Cr',
       '12.4 Cr', '10.3 Cr', '15.7 Cr', '6.8 Cr', '9.39 Cr', '10.2 Cr',
       '5.81 Cr', '10.72 Cr', '13.95 Cr', '9.37 Cr', '15.25 Cr',
       '13.9 Cr', '9.35 Cr', '10.45 Cr', '6.42 Cr', '55 Cr', '19.9 Cr',
       '65 Lac', '48 Cr', '46 Cr', '10.77 Cr', '2.76 Cr', '4.55 Cr',
       '15.15 Cr', '26.5 Cr', '5.4 Cr', '10.05 Cr', '69 Lac', '11.7 Cr',
       '28.75 Cr', '57 Cr', '52 Lac', '20 Lac', '63 Lac', '35 Lac',
       '39 Lac', '73 Lac', '48 Lac', '58 Lac', '56 Lac', '45 Lac',
       '40 Lac', '76.75 Lac', '55 Lac', '42 Lac', '50 Lac', '30 Lac',
       '2.59 Cr', '2.38 Cr', '57 Lac', '5.89 Cr', '25 Lac', '26 Lac',
       '2.03 Cr', '1.52 Cr', '1.27 Cr', '2.44 Cr', '2.55 Cr', '5.35 Cr',
       '17 Lac', '64 Lac', '1.78 Cr', '2.32 Cr', '1.99 Cr', '29.95 Cr',
       '1.98 Cr', '94.99 Lac', '99 Lac', '4.09 Cr', '74.5 Lac', '98 Lac',
       '1.21 Cr', '1.12 Cr', '28.5 Lac', '1.02 Cr', '24 Lac', '37.5 Lac',
       '71 Lac', '1.79 Cr', '80 Cr', '18.95 Lac', '4.05 Cr', '78 Lac',
       '28 Lac', '3.29 Cr', '30.8 Lac', '3.67 Cr', '25.5 Lac', '29.5 Cr',
       '37 Lac', '1.84 Cr', '62 Lac', '61 Lac', '1.11 Cr', '4.68 Cr',
       '41 Lac'], dtype=object)

In [25]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
12 Cr               44
15 Cr               42
9 Cr                42
7.5 Cr              40
8.5 Cr              39
6.5 Cr              35
14 Cr               33
12.5 Cr             33
25 Cr               33
11 Cr               31
3.5 Cr              30
9.5 Cr              30
17 Cr               29
7 Cr                27
5.5 Cr              26
8 Cr                26
5 Cr                25
4.5 Cr              25
10 Cr               24
6 Cr                24
1.2 Cr              21
18 Cr               21
11.5 Cr             19
4.25 Cr             19
13 Cr               19
2.5 Cr              19
1.5 Cr              18
10.5 Cr             17
5.25 Cr             17
16 Cr               17
14.5 Cr             17
1.35 Cr             16
8.75 Cr             16
7.25 Cr             16
21 Cr               15
75 Lac              15
13.5 Cr             14
15.5 Cr             13
2.25 Cr             13
95 Lac              13
2.2 Cr              13
8.25 Cr             13
3.1 Cr              12
90 Lac              12
3 Cr                12
11.25 Cr            12
4 Cr                12
1.3 Cr              12
1.1 Cr              12
80 Lac              12
70 Lac              12
2 Cr                12
1.4 Cr              11
1.7 Cr              11
19 Cr               11
2.4 Cr              11
55 Lac              11
22 Cr               11
3.35 Cr             11
18.5 Cr             11
3.25 Cr             11
20 Cr               11
2.3 Cr              10
7.75 Cr             10
4.3 Cr              10
65 Lac              10
2.6 Cr              10
9.25 Cr             10
16.5 Cr             10
10.75 Cr             9
1.25 Cr              9
4.75 Cr              9
1.65 Cr              9
3.6 Cr               9
60 Lac               9
6.25 Cr              9
1 Cr                 9
3.4 Cr               9
4.1 Cr               9
2.1 Cr               8
2.15 Cr              8
7.6 Cr               8
5.1 Cr               8
11.75 Cr             8
3.3 Cr               8
2.8 Cr               8
1.6 Cr               8
9.75 Cr              7
3.75 Cr              7
23.5 Cr              7
7.7 Cr               7
28 Cr                7
4.6 Cr               7
50 Lac               7
6.6 Cr               7
17.5 Cr              7
5.7 Cr               7
3.8 Cr               7
24 Cr                7
7.15 Cr              7
6.2 Cr               6
1.75 Cr              6
4.4 Cr               6
6.75 Cr              6
4.8 Cr               6
35 Lac               6
4.65 Cr              6
7.2 Cr               6
16.25 Cr             6
5.8 Cr               6
7.49 Cr              6
2.9 Cr               6
2.7 Cr               6
6.1 Cr               6
5.9 Cr               6
9.4 Cr               6
22.5 Cr              6
7.85 Cr              6
3.2 Cr               6
6.9 Cr               6
Price on Request     6
30 Cr                5
78 Lac               5
35 Cr                5
12.25 Cr             5
2.75 Cr              5
2.85 Cr              5
6.3 Cr               5
4.7 Cr               5
1.85 Cr              5
6.7 Cr               5
2.65 Cr              5
5.6 Cr               4
98 Lac               4
13.25 Cr             4
8.35 Cr              4
19.5 Cr              4
42 Lac               4
9.1 Cr               4
3.7 Cr               4
99 Lac               4
5.75 Cr              4
1.9 Cr               4
1.8 Cr               4
7.3 Cr               4
3.65 Cr              4
85 Lac               4
23 Cr                4
3.55 Cr              4
6.45 Cr              4
12.75 Cr             4
3.9 Cr               4
7.9 Cr               4
4.2 Cr               4
6.35 Cr              4
10.6 Cr              4
3.15 Cr              4
69 Lac               3
89 Lac               3
5.15 Cr              3
10.7 Cr              3
6.15 Cr              3
19.25 Cr             3
3.45 Cr              3
27 Cr                3
9.8 Cr               3
8.3 Cr               3
14.49 Cr             3
8.9 Cr               3
1.45 Cr              3
77 Lac               3
5.65 Cr              3
7.4 Cr               3
11.9 Cr              3
1.05 Cr              3
9.2 Cr               3
4.95 Cr              3
82 Lac               3
10.2 Cr              3
48 Lac               3
4.45 Cr              3
4.9 Cr               3
24.5 Cr              3
7.95 Cr              3
10.25 Cr             3
79 Lac               3
1.15 Cr              3
8.15 Cr              3
7.1 Cr               3
13.75 Cr             3
3.05 Cr              3
9.3 Cr               3
3.85 Cr              3
1.95 Cr              3
5.85 Cr              3
10.3 Cr              2
2.38 Cr              2
30 Lac               2
72 Lac               2
2.45 Cr              2
14.25 Cr             2
15.75 Cr             2
12.9 Cr              2
7.65 Cr              2
5.55 Cr              2
14.75 Cr             2
40 Lac               2
12.99 Cr             2
1.59 Cr              2
58 Lac               2
10.9 Cr              2
1.79 Cr              2
10.15 Cr             2
7.45 Cr              2
6.55 Cr              2
7.8 Cr               2
6.85 Cr              2
4.21 Cr              2
2.95 Cr              2
8.95 Cr              2
5.95 Cr              2
32 Cr                2
37 Cr                2
4.15 Cr              2
20.5 Cr              2
8.4 Cr               2
6.49 Cr              2
17.75 Cr             2
57 Lac               2
9.65 Cr              2
17.25 Cr             2
68 Lac               2
10.4 Cr              2
64 Lac               2
5.3 Cr               2
7.35 Cr              2
76 Lac               2
4.35 Cr              2
12.15 Cr             2
9.85 Cr              2
40 Cr                2
1.19 Cr              2
6.82 Cr              2
14.65 Cr             2
67 Lac               2
2.35 Cr              2
1.52 Cr              2
6.65 Cr              2
12.49 Cr             2
7.19 Cr              2
28.5 Cr              2
25.5 Cr              2
2.18 Cr              2
1.27 Cr              2
10.8 Cr              2
10.99 Cr             2
9.35 Cr              1
9.37 Cr              1
55 Cr                1
10.45 Cr             1
13.9 Cr              1
15.25 Cr             1
13.95 Cr             1
19.9 Cr              1
6.42 Cr              1
22.9 Cr              1
10.72 Cr             1
9.6 Cr               1
4.85 Cr              1
61 Lac               1
62 Lac               1
11.65 Cr             1
21.75 Cr             1
3.73 Cr              1
1.11 Cr              1
2.22 Cr              1
12.6 Cr              1
8.6 Cr               1
97.12 Lac            1
5.81 Cr              1
1.23 Cr              1
12.3 Cr              1
12.4 Cr              1
4.68 Cr              1
15.7 Cr              1
6.8 Cr               1
9.39 Cr              1
1.84 Cr              1
5.21 Cr              1
37 Lac               1
29.5 Cr              1
57 Cr                1
25.5 Lac             1
1.02 Cr              1
37.5 Lac             1
18.99 Cr             1
2.59 Cr              1
5.89 Cr              1
25 Lac               1
26 Lac               1
18.85 Cr             1
2.03 Cr              1
2.44 Cr              1
24 Lac               1
2.55 Cr              1
5.35 Cr              1
71 Lac               1
17 Lac               1
1.78 Cr              1
28.5 Lac             1
1.12 Cr              1
1.21 Cr              1
2.32 Cr              1
1.99 Cr              1
29.95 Cr             1
1.98 Cr              1
94.99 Lac            1
74.5 Lac             1
3.39 Cr              1
76.75 Lac            1
48 Cr                1
11.7 Cr              1
46 Cr                1
10.77 Cr             1
2.76 Cr              1
4.55 Cr              1
3.67 Cr              1
15.15 Cr             1
30.8 Lac             1
26.5 Cr              1
5.4 Cr               1
10.05 Cr             1
3.29 Cr              1
28.75 Cr             1
45 Lac               1
28 Lac               1
4.09 Cr              1
52 Lac               1
20 Lac               1
4.05 Cr              1
63 Lac               1
39 Lac               1
73 Lac               1
18.95 Lac            1
80 Cr                1
56 Lac               1
15.8 Cr              1
10.65 Cr             1
12.45 Cr             1
16.1 Cr              1
13.85 Cr             1
6.18 Cr              1
20.75 Cr             1
14.6 Cr              1
2.05 Cr              1
17.99 Cr             1
17.9 Cr              1
1.16 Cr              1
11.99 Cr             1
6.29 Cr              1
8.2 Cr               1
14.48 Cr             1
3.99 Cr              1
4.92 Cr              1
5.05 Cr              1
11.45 Cr             1
97 Lac               1
1.24 Cr              1
1.26 Cr              1
84.99 Lac            1
6.95 Cr              1
79.85 Lac            1
7.56 Cr              1
1.68 Cr              1
15.1 Cr              1
64.78 Lac            1
8.8 Cr               1
7.68 Cr              1
16.55 Cr             1
13.8 Cr              1
7.99 Cr              1
49 Lac               1
20.95 Cr             1
6.57 Cr              1
9.45 Cr              1
6.28 Cr              1
83.9 Lac             1
20.98 Cr             1
1.54 Cr              1
14.2 Cr              1
12.65 Cr             1
1.92 Cr              1
5.67 Cr              1
16.75 Cr             1
1.32 Cr              1
4.13 Cr              1
11.05 Cr             1
17.05 Cr             1
1.42 Cr              1
1.31 Cr              1
10.95 Cr             1
12.1 Cr              1
21.5 Cr              1
29.31 Cr             1
7.23 Cr              1
3.95 Cr              1
1.29 Cr              1
19.75 Cr             1
88 Lac               1
15.4 Cr              1
11.85 Cr             1
5.99 Cr              1
12.84 Cr             1
12.8 Cr              1
12.18 Cr             1
12.2 Cr              1
11.1 Cr              1
3.27 Cr              1
8.24 Cr              1
97.99 Lac            1
15.2 Cr              1
14.4 Cr              1
29.75 Cr             1
23.9 Cr              1
33 Cr                1
16.49 Cr             1
26 Cr                1
15.65 Cr             1
15.3 Cr              1
12.22 Cr             1
34 Cr                1
15.05 Cr             1
11.49 Cr             1
8.7 Cr               1
6.4 Cr               1
14.52 Cr             1
14.8 Cr              1
18.75 Cr             1
15.9 Cr              1
7.55 Cr              1
19.6 Cr              1
17.49 Cr             1
24.9 Cr              1
10.49 Cr             1
8.1 Cr               1
18.25 Cr             1
1.08 Cr              1
10.53 Cr             1
20.9 Cr              1
9.9 Cr               1
5.45 Cr              1
7.71 Cr              1
37.5 Cr              1
18.7 Cr              1
14.85 Cr             1
6.99 Cr              1
1.55 Cr              1
13.73 Cr             1
17.15 Cr             1
11.58 Cr             1
43 Cr                1
9.95 Cr              1
25.65 Cr             1
41 Lac               1
Name: count, dtype: int64

In [26]:
df_house[df_house['price_in_cr']=='Price on Request']

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
1021,O59710486,"12 Bedroom House in Malibu Town, Gurgaon",https://www.99acres.com/12-bhk-bedroom-indepen...,Malibu Towne,Price on Request,NaN,7200 sqft (668.9 sqm) Plot Area,12 Bedrooms,12 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room",3 Floors,NaN,0 to 1 Year Old,"['Dr. Naresh Pandita', 'Genius', 'Wellness Eye...","['12 Wardrobe', '12 Fan', '12 Geyser', '12 Lig...","['High Ceiling Height', 'Maintenance Staff', '..."
1727,P84897020,5 Bedroom House in Block J Ashok Vihar phase 3...,https://www.99acres.com/5-bhk-bedroom-independ...,"Block J Ashok Vihar phase 3 extension, Gurgaon",Price on Request,NaN,900 sqft (83.61 sqm) Plot Area,5 Bedrooms,5 Bathrooms,1 Balcony,Store Room,2 Floors,NaN,5 to 10 Year Old,"[""DR KAPOOR'S Dental Care and Implant Centre"",...","['1 Wardrobe', '1 Light', '1 Modular Kitchen',...",['No open drainage around']
1831,B84332166,"7 Bedroom House in Patel Nagar, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,"Patel Nagar, Gurgaon",Price on Request,NaN,1631 sqft (151.52 sqm) Plot Area,7 Bedrooms,8 Bathrooms,3 Balconies,Pooja Room,1 Floors,North,0 to 1 Year Old,"['Pasricha Hospital and Maternity Home', 'Ahoo...",NaN,"['Water Storage', 'Rain Water Harvesting']"
1878,N68848866,"12 Bedroom House in Malibu Town, Gurgaon",https://www.99acres.com/12-bhk-bedroom-indepen...,Malibu Towne,Price on Request,NaN,7200 sqft (668.9 sqm) Plot Area,12 Bedrooms,17 Bathrooms,3+ Balconies,"Study Room,Store Room,Pooja Room,Servant Room",4 Floors,West,5 to 10 Year Old,"['Carmesi Corporate', 'Icici bank', 'India Oil...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
2036,D18376277,"4 Bedroom House in Sector 31, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 31, Gurgaon",Price on Request,NaN,4518 sqft (419.74 sqm) Built-up Area,4 Bedrooms,4 Bathrooms,No Balcony,NaN,NaN,NaN,1 to 5 Year Old,"['Citi bank ATM', 'District library gurgaon', ...",[],"['Power Back-up', 'Water Storage']"
2129,Q4798149,"4 Bedroom House in Nirvana Country, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Nirvana Country, Gurgaon",Price on Request,NaN,3750 sqft (348.39 sqm) Built-up Area,4 Bedrooms,6 Bathrooms,No Balcony,NaN,NaN,NaN,1 to 5 Year Old,"['Unitech Business Park', 'Carmesi Corporate',...",[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [27]:
column_cleaning = (

    df_house

        .assign(
            
        price_in_cr = lambda df_:df_['price_in_cr']
                .str
                .replace('₹','')
                )

        .assign(
                price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                .apply(lambda value: (float(str(value)
                .replace('Cr', '')
                .strip()) if 'Cr' in str(value)
                else float(str(value)
                .replace('Lac', '')
                .strip()) / 100
                ) if value not in ['Price on Request', None, np.nan] else np.nan
                        )
            ),2)
            )
)     

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,"₹14,667 /sqft",4500 sqft (418.06 sqm) Plot Area,4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,"₹22,727 /sqft",11000 sqft (1021.93 sqm) Plot Area,6 Bedrooms,10 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,"₹42,031 /sqft",4518 sqft (419.74 sqm) Plot Area,2 Bedrooms,2 Bathrooms,No Balcony,NaN,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,"₹3,766 /sqft",9000 sqft (836.13 sqm) Plot Area,3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,"₹38,889 /sqft",3600 sqft (334.45 sqm) Plot Area,5 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,"₹32,680 /sqft",1377 sqft (127.93 sqm) Plot Area,3 Bedrooms,3 Bathrooms,1 Balcony,NaN,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,"₹6,077 /sqft",1810 sqft (168.15 sqm) Plot Area,4 Bedrooms,2 Bathrooms,No Balcony,NaN,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,"₹32,407 /sqft",2160 sqft (200.67 sqm) Plot Area,4 Bedrooms,4 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,"₹76,923 /sqft",91 sqft (8.45 sqm) Plot Area,2 Bedrooms,1 Bathroom,1 Balcony,NaN,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,"₹17,778 /sqft",2250 sqft (209.03 sqm) Plot Area,5 Bedrooms,5 Bathrooms,2 Balconies,Study Room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [28]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
12.00    44
15.00    42
9.00     42
7.50     40
8.50     39
6.50     35
14.00    33
12.50    33
25.00    33
11.00    31
3.50     30
9.50     30
17.00    29
7.00     27
5.50     26
8.00     26
4.50     25
5.00     25
10.00    24
6.00     24
18.00    21
1.20     21
4.25     19
13.00    19
2.50     19
11.50    19
1.50     18
14.50    17
10.50    17
16.00    17
5.25     17
7.25     16
8.75     16
1.35     16
21.00    15
0.75     15
13.50    14
0.95     14
2.20     13
15.50    13
8.25     13
0.80     13
2.25     13
11.25    12
3.00     12
4.00     12
0.70     12
2.00     12
3.10     12
0.90     12
1.30     12
1.10     12
2.40     11
20.00    11
0.65     11
3.35     11
19.00    11
1.40     11
1.70     11
3.25     11
22.00    11
18.50    11
0.55     11
4.30     10
2.30     10
2.60     10
9.25     10
7.75     10
16.50    10
0.60      9
1.25      9
4.10      9
3.60      9
4.75      9
1.00      9
1.65      9
10.75     9
3.40      9
6.25      9
3.30      8
7.60      8
1.60      8
2.80      8
2.10      8
2.15      8
11.75     8
5.10      8
23.50     7
4.60      7
7.70      7
3.75      7
0.50      7
9.75      7
28.00     7
6.60      7
3.80      7
17.50     7
24.00     7
5.70      7
7.15      7
0.35      6
7.85      6
7.49      6
22.50     6
2.70      6
2.90      6
5.90      6
16.25     6
7.20      6
9.40      6
6.75      6
5.80      6
4.65      6
6.20      6
1.75      6
4.40      6
6.90      6
6.10      6
3.20      6
4.80      6
0.85      5
6.30      5
4.70      5
30.00     5
0.98      5
2.65      5
12.25     5
1.85      5
6.70      5
2.85      5
0.78      5
2.75      5
35.00     5
0.42      4
5.60      4
4.20      4
0.99      4
3.15      4
12.75     4
3.70      4
10.60     4
1.90      4
1.80      4
8.35      4
6.35      4
7.30      4
3.55      4
19.50     4
3.65      4
23.00     4
7.90      4
6.45      4
0.77      4
13.25     4
3.90      4
9.10      4
5.75      4
27.00     3
0.69      3
0.82      3
10.70     3
14.49     3
8.90      3
0.89      3
9.20      3
11.90     3
7.40      3
4.95      3
9.80      3
5.65      3
8.30      3
0.48      3
10.20     3
4.90      3
24.50     3
6.15      3
10.25     3
8.15      3
7.10      3
13.75     3
0.79      3
3.05      3
1.05      3
1.15      3
5.85      3
3.85      3
9.30      3
3.45      3
19.25     3
1.45      3
4.45      3
7.95      3
1.95      3
5.15      3
14.75     2
0.97      2
0.72      2
10.99     2
0.58      2
5.55      2
28.50     2
12.49     2
2.45      2
7.65      2
9.65      2
0.40      2
1.79      2
7.45      2
7.19      2
9.85      2
10.15     2
40.00     2
7.80      2
4.35      2
6.85      2
6.55      2
8.95      2
6.49      2
32.00     2
37.00     2
6.65      2
7.35      2
0.67      2
6.82      2
10.90     2
0.28      2
0.30      2
10.40     2
14.25     2
17.25     2
1.59      2
15.75     2
1.27      2
14.65     2
25.50     2
2.35      2
4.21      2
0.76      2
20.50     2
5.30      2
0.64      2
17.75     2
1.52      2
2.18      2
0.26      2
2.95      2
8.40      2
12.90     2
12.99     2
10.80     2
0.57      2
5.95      2
12.15     2
2.38      2
10.30     2
1.19      2
0.68      2
4.15      2
9.35      1
15.25     1
10.45     1
6.42      1
18.85     1
13.90     1
12.30     1
9.37      1
9.60      1
4.85      1
22.90     1
21.75     1
11.65     1
3.73      1
2.22      1
12.60     1
8.60      1
1.23      1
13.95     1
5.21      1
12.40     1
15.80     1
15.70     1
6.80      1
9.39      1
5.81      1
10.72     1
55.00     1
1.78      1
19.90     1
80.00     1
1.99      1
29.95     1
1.98      1
4.09      1
0.74      1
1.21      1
1.12      1
1.02      1
0.24      1
0.38      1
0.71      1
0.19      1
4.92      1
4.05      1
3.29      1
0.31      1
3.67      1
29.50     1
0.37      1
1.84      1
0.62      1
0.61      1
1.11      1
4.68      1
2.32      1
0.17      1
48.00     1
0.52      1
46.00     1
10.77     1
2.76      1
4.55      1
15.15     1
26.50     1
5.40      1
10.05     1
11.70     1
28.75     1
57.00     1
0.20      1
5.35      1
0.63      1
0.39      1
0.73      1
0.56      1
0.45      1
2.59      1
5.89      1
0.25      1
2.03      1
2.44      1
2.55      1
12.45     1
1.24      1
8.70      1
1.16      1
29.31     1
7.23      1
13.80     1
16.55     1
7.68      1
6.18      1
20.75     1
14.60     1
2.05      1
17.99     1
17.90     1
11.99     1
1.31      1
6.29      1
14.48     1
16.10     1
3.99      1
5.05      1
11.45     1
1.26      1
6.95      1
7.56      1
1.68      1
15.10     1
12.10     1
1.42      1
1.29      1
7.99      1
18.99     1
3.39      1
8.20      1
13.85     1
8.80      1
21.50     1
10.95     1
1.54      1
9.45      1
20.95     1
0.49      1
6.57      1
17.05     1
6.28      1
0.84      1
20.98     1
14.20     1
12.65     1
1.92      1
5.67      1
16.75     1
1.32      1
4.13      1
11.05     1
3.95      1
19.75     1
11.49     1
8.24      1
0.88      1
6.40      1
15.40     1
11.85     1
5.99      1
12.84     1
12.80     1
12.18     1
12.20     1
11.10     1
3.27      1
15.20     1
18.75     1
14.40     1
29.75     1
23.90     1
33.00     1
16.49     1
26.00     1
15.65     1
15.30     1
12.22     1
34.00     1
15.05     1
14.52     1
25.65     1
14.80     1
9.90      1
15.90     1
7.55      1
19.60     1
17.49     1
24.90     1
10.49     1
8.10      1
18.25     1
1.08      1
10.53     1
20.90     1
5.45      1
9.95      1
10.65     1
7.71      1
37.50     1
18.70     1
14.85     1
6.99      1
1.55      1
13.73     1
17.15     1
11.58     1
43.00     1
0.41      1
Name: count, dtype: int64

In [36]:
column_cleaning['price_in_cr'].isnull().sum()

6

#### 3. Price_Per_Sqft

In [31]:
column_cleaning['price_per_sqft']

0       ₹14,667 /sqft
1       ₹22,727 /sqft
2       ₹42,031 /sqft
3        ₹3,766 /sqft
4       ₹38,889 /sqft
            ...
2264    ₹32,680 /sqft
2265     ₹6,077 /sqft
2266    ₹32,407 /sqft
2267    ₹76,923 /sqft
2268    ₹17,778 /sqft
Name: price_per_sqft, Length: 2269, dtype: object

In [32]:
column_cleaning = (df_house
                .assign(
                price_per_sqft = lambda df_:df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()))

In [33]:
column_cleaning['price_per_sqft'].value_counts()

price_per_sqft
44444    27
41667    23
55556    22
33333    21
27778    20
         ..
37600     1
52307     1
12674     1
5741      1
76923     1
Name: count, Length: 1419, dtype: int64

In [42]:
column_cleaning = (
    
    df_house
        .query("price_in_cr != 'Price on Request' and price_per_sqft != 'Price on Request'")

        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr=lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft=lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                )


)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,14667,4500 sqft (418.06 sqm) Plot Area,4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,22727,11000 sqft (1021.93 sqm) Plot Area,6 Bedrooms,10 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,42031,4518 sqft (419.74 sqm) Plot Area,2 Bedrooms,2 Bathrooms,No Balcony,NaN,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,3766,9000 sqft (836.13 sqm) Plot Area,3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,38889,3600 sqft (334.45 sqm) Plot Area,5 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,32680,1377 sqft (127.93 sqm) Plot Area,3 Bedrooms,3 Bathrooms,1 Balcony,NaN,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,6077,1810 sqft (168.15 sqm) Plot Area,4 Bedrooms,2 Bathrooms,No Balcony,NaN,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,32407,2160 sqft (200.67 sqm) Plot Area,4 Bedrooms,4 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,76923,91 sqft (8.45 sqm) Plot Area,2 Bedrooms,1 Bathroom,1 Balcony,NaN,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,17778,2250 sqft (209.03 sqm) Plot Area,5 Bedrooms,5 Bathrooms,2 Balconies,Study Room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [43]:
column_cleaning.shape

(2263, 17)

#### 4. Bedroom

In [47]:
column_cleaning['bedrooms'].unique()

array(['4 Bedrooms', '6 Bedrooms', '2 Bedrooms', '3 Bedrooms',
       '5 Bedrooms', '13 Bedrooms', '9 Bedrooms', '11 Bedrooms',
       '7 Bedrooms', '18 Bedrooms', '8 Bedrooms', '12 Bedrooms',
       '1 Bedroom', '20 Bedrooms', '17 Bedrooms', '21 Bedrooms',
       '16 Bedrooms', '19 Bedrooms', '10 Bedrooms', '22 Bedrooms',
       '14 Bedrooms', '15 Bedrooms', '24 Bedrooms', '35 Bedrooms',
       '36 Bedrooms', '23 Bedrooms', '28 Bedrooms', '32 Bedrooms',
       '48 Bedrooms'], dtype=object)

In [48]:
(column_cleaning['bedrooms']
                .str
                .split(" ")
                .str
                .get(0))

0       4
1       6
2       2
3       3
4       5
       ..
2264    3
2265    4
2266    4
2267    2
2268    5
Name: bedrooms, Length: 2263, dtype: object

In [50]:
column_cleaning = (
    
    df_house
        .query("price_in_cr != 'Price on Request' and price_per_sqft != 'Price on Request'")

        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                )
        .assign(
            bedrooms = lambda df_: pd.to_numeric(df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
        )
            
        )

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,14667,4500 sqft (418.06 sqm) Plot Area,4,4 Bathrooms,2 Balconies,Study Room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,22727,11000 sqft (1021.93 sqm) Plot Area,6,10 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,42031,4518 sqft (419.74 sqm) Plot Area,2,2 Bathrooms,No Balcony,NaN,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,3766,9000 sqft (836.13 sqm) Plot Area,3,4 Bathrooms,3 Balconies,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,38889,3600 sqft (334.45 sqm) Plot Area,5,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,32680,1377 sqft (127.93 sqm) Plot Area,3,3 Bathrooms,1 Balcony,NaN,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,6077,1810 sqft (168.15 sqm) Plot Area,4,2 Bathrooms,No Balcony,NaN,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,32407,2160 sqft (200.67 sqm) Plot Area,4,4 Bathrooms,2 Balconies,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,76923,91 sqft (8.45 sqm) Plot Area,2,1 Bathroom,1 Balcony,NaN,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,17778,2250 sqft (209.03 sqm) Plot Area,5,5 Bathrooms,2 Balconies,Study Room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [51]:
column_cleaning['bedrooms'].isnull().sum()

0

#### 5. Bathroom

In [52]:
column_cleaning['bathrooms'].unique()

array(['4 Bathrooms', '10 Bathrooms', '2 Bathrooms', '6 Bathrooms',
       '3 Bathrooms', '14 Bathrooms', '5 Bathrooms', '7 Bathrooms',
       '12 Bathrooms', '11 Bathrooms', '19 Bathrooms', '8 Bathrooms',
       '9 Bathrooms', '1 Bathroom', '20 Bathrooms', '17 Bathrooms',
       '15 Bathrooms', '22 Bathrooms', '18 Bathrooms', '16 Bathrooms',
       '28 Bathrooms', '13 Bathrooms', '35 Bathrooms', '36 Bathrooms',
       '24 Bathrooms', '23 Bathrooms', '32 Bathrooms', '50 Bathrooms',
       '21 Bathrooms'], dtype=object)

In [53]:
(column_cleaning['bathrooms']
            .str
            .split(" ")
            .str
            .get(0)
)

0        4
1       10
2        2
3        4
4        6
        ..
2264     3
2265     2
2266     4
2267     1
2268     5
Name: bathrooms, Length: 2263, dtype: object

In [54]:
column_cleaning = (
    
    df_house
        .query("price_in_cr != 'Price on Request' and price_per_sqft != 'Price on Request'")

        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                )
        .assign(
            bedrooms = lambda df_: pd.to_numeric(df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                )

        .assign(
            bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                )
            
        )

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,14667,4500 sqft (418.06 sqm) Plot Area,4,4,2 Balconies,Study Room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,22727,11000 sqft (1021.93 sqm) Plot Area,6,10,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,42031,4518 sqft (419.74 sqm) Plot Area,2,2,No Balcony,NaN,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,3766,9000 sqft (836.13 sqm) Plot Area,3,4,3 Balconies,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,38889,3600 sqft (334.45 sqm) Plot Area,5,6,3+ Balconies,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,32680,1377 sqft (127.93 sqm) Plot Area,3,3,1 Balcony,NaN,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,6077,1810 sqft (168.15 sqm) Plot Area,4,2,No Balcony,NaN,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,32407,2160 sqft (200.67 sqm) Plot Area,4,4,2 Balconies,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,76923,91 sqft (8.45 sqm) Plot Area,2,1,1 Balcony,NaN,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,17778,2250 sqft (209.03 sqm) Plot Area,5,5,2 Balconies,Study Room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [55]:
column_cleaning['bathrooms'].isnull().sum()

0

#### 5. Balcony

In [56]:
column_cleaning['balcony'].unique()

array(['2 Balconies', '3+ Balconies', 'No Balcony', '3 Balconies',
       '1 Balcony'], dtype=object)

In [57]:
(column_cleaning['balcony']
            .str
            .split(" ")
            .str
            .get(0)
            .replace("No",0))

0        2
1       3+
2        0
3        3
4       3+
        ..
2264     1
2265     0
2266     2
2267     1
2268     2
Name: balcony, Length: 2263, dtype: object

In [58]:
column_cleaning = (
    
    df_house
        .query("price_in_cr != 'Price on Request' and price_per_sqft != 'Price on Request'")

        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                )
        .assign(
            bedrooms = lambda df_: pd.to_numeric(df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                )

        .assign(
            bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                )
        .assign(
            balcony = lambda df_: df_['balcony']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                                        .replace("No",0)
                )
            
)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,14667,4500 sqft (418.06 sqm) Plot Area,4,4,2,Study Room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,22727,11000 sqft (1021.93 sqm) Plot Area,6,10,3+,"Pooja Room,Study Room,Servant Room,Store Room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,42031,4518 sqft (419.74 sqm) Plot Area,2,2,0,NaN,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,3766,9000 sqft (836.13 sqm) Plot Area,3,4,3,"Study Room,Servant Room,Store Room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,38889,3600 sqft (334.45 sqm) Plot Area,5,6,3+,"Pooja Room,Study Room,Servant Room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,32680,1377 sqft (127.93 sqm) Plot Area,3,3,1,NaN,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,6077,1810 sqft (168.15 sqm) Plot Area,4,2,0,NaN,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,32407,2160 sqft (200.67 sqm) Plot Area,4,4,2,"Study Room,Servant Room,Store Room,Pooja Room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,76923,91 sqft (8.45 sqm) Plot Area,2,1,1,NaN,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,17778,2250 sqft (209.03 sqm) Plot Area,5,5,2,Study Room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

#### 6. AdditionalRoom

In [59]:
(column_cleaning['additional_room']
            .fillna('not available')
            .str
            .lower())

0                                          study room
1       pooja room,study room,servant room,store room
2                                       not available
3                  study room,servant room,store room
4                  pooja room,study room,servant room
                            ...
2264                                    not available
2265                                    not available
2266    study room,servant room,store room,pooja room
2267                                    not available
2268                                       study room
Name: additional_room, Length: 2263, dtype: object

In [ ]:
column_cleaning = (
    
    df_house
        .query("price_in_cr != 'Price on Request' and price_per_sqft != 'Price on Request'")

        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                

            ,
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
            ,
            bedrooms = lambda df_: pd.to_numeric(df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                

            ,
            bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                
            ,
            balcony = lambda df_: df_['balcony']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                                        .replace("No",0)
                
            ,
            additional_room = lambda df_: df_['additional_room']
                                        .fillna('not available')
                                        .str
                                        .lower()
)
)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,14667,4500 sqft (418.06 sqm) Plot Area,4,4,2,study room,2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,22727,11000 sqft (1021.93 sqm) Plot Area,6,10,3+,"pooja room,study room,servant room,store room",4 Floors,North-East,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,42031,4518 sqft (419.74 sqm) Plot Area,2,2,0,not available,NaN,NaN,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,3766,9000 sqft (836.13 sqm) Plot Area,3,4,3,"study room,servant room,store room",2 Floors,South,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,38889,3600 sqft (334.45 sqm) Plot Area,5,6,3+,"pooja room,study room,servant room",2 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,32680,1377 sqft (127.93 sqm) Plot Area,3,3,1,not available,2 Floors,NaN,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,6077,1810 sqft (168.15 sqm) Plot Area,4,2,0,not available,2 Floors,East,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,32407,2160 sqft (200.67 sqm) Plot Area,4,4,2,"study room,servant room,store room,pooja room",2 Floors,NaN,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,76923,91 sqft (8.45 sqm) Plot Area,2,1,1,not available,1 Floors,West,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,17778,2250 sqft (209.03 sqm) Plot Area,5,5,2,study room,3 Floors,NaN,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [61]:
column_cleaning['additional_room'].isnull().sum()

0

### 7. Facing

In [62]:
column_cleaning['facing']

0            South
1       North-East
2              NaN
3            South
4             East
           ...
2264           NaN
2265          East
2266           NaN
2267          West
2268           NaN
Name: facing, Length: 2263, dtype: object

In [63]:
column_cleaning['facing'].value_counts()

facing
North-East    512
East          479
North         304
West          182
North-West    141
South-East    108
South          91
South-West     66
Name: count, dtype: int64

In [64]:
column_cleaning['facing'].isnull().sum()

380

In [65]:
(column_cleaning['facing']
                                .fillna("Not Available")
                                .str
                                .lower())

0               south
1          north-east
2       not available
3               south
4                east
            ...
2264    not available
2265             east
2266    not available
2267             west
2268    not available
Name: facing, Length: 2263, dtype: object

In [66]:
column_cleaning = (
    
    df_house
        .query("price_in_cr != 'Price on Request' and price_per_sqft != 'Price on Request'")

        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                

            ,
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
            ,
            bedrooms = lambda df_: pd.to_numeric(df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                

            ,
            bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0))
                
            ,
            balcony = lambda df_: df_['balcony']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                                        .replace("No",0)
                
            ,
            additional_room = lambda df_: df_['additional_room']
                                        .fillna('not available')
                                        .str
                                        .lower()
            ,
            facing  =  lambda df_: df_['facing']
                                        .fillna("Not Available")
                                        .str
                                        .lower()
)
)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,N80213331,"4 Bedroom House in Sector 4, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,"Sector 4, Gurgaon",6.60,14667,4500 sqft (418.06 sqm) Plot Area,4,4,2,study room,2 Floors,south,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...","['5 Fan', '10 Light', '1 Chimney', '1 Modular ...","['Park', 'Rain Water Harvesting']"
1,Q84155382,"6 Bedroom House in DLF Phase 1, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,North East & Park Facing Corner 18 meter wide ...,25.00,22727,11000 sqft (1021.93 sqm) Plot Area,6,10,3+,"pooja room,study room,servant room,store room",4 Floors,north-east,1 to 5 Year Old,"['Anahat Hospital', 'Sikandarpur rmrg metro st...","['1 Water Purifier', '13 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2,S82406206,"2 Bedroom House in Sector 15 Part 2, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Sector 15 Part 2, Gurgaon",18.99,42031,4518 sqft (419.74 sqm) Plot Area,2,2,0,not available,NaN,not available,NaN,"['govt sec school', 'Ahmed Hospital Multi Spec...",[],NaN
3,J84873064,"3 Bedroom House in Jhajjar Road, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,"Green Heritage Villas, Jhajjar",3.39,3766,9000 sqft (836.13 sqm) Plot Area,3,4,3,"study room,servant room,store room",2 Floors,south,1 to 5 Year Old,[],"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,Q83769064,"5 Bedroom House in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Sobha International City Phase 3,14.00,38889,3600 sqft (334.45 sqm) Plot Area,5,6,3+,"pooja room,study room,servant room",2 Floors,east,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam vihar rai...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,V81604971,"3 Bedroom House in Sector 49, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Eros Rosewood City,4.50,32680,1377 sqft (127.93 sqm) Plot Area,3,3,1,not available,2 Floors,not available,5 to 10 Year Old,"['Silver Oak Universal', 'Leelavati Hospital',...",[],NaN
2265,Q81598269,"4 Bedroom House in Pratap Nagar, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,383/13 Partap nagar,1.10,6077,1810 sqft (168.15 sqm) Plot Area,4,2,0,not available,2 Floors,east,Under Construction,[],NaN,"['Water Storage', 'Park']"
2266,Q81594211,"4 Bedroom House in DLF Phase 3, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,National Media Centre,7.00,32407,2160 sqft (200.67 sqm) Plot Area,4,4,2,"study room,servant room,store room,pooja room",2 Floors,not available,10+ Year Old,"['Deutsche bank', 'Dental Cure and Care Centre...","['3 Wardrobe', '6 Fan', '1 Fridge', '4 Geyser'...","['Maintenance Staff', 'Water Storage', 'Visito..."
2267,D81585663,"2 Bedroom House in Devilal Colony, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,"Devilal Colony, Gurgaon",0.70,76923,91 sqft (8.45 sqm) Plot Area,2,1,1,not available,1 Floors,west,10+ Year Old,"['Prateek Nursing Home And Polyclinic', 'Shubh...",NaN,NaN
2268,H47319641,"5 Bedroom House in Sector 53, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,"Sector 53, Gurgaon",4.00,17778,2250 sqft (209.03 sqm) Plot Area,5,5,2,study room,3 Floors,not available,1 to 5 Year Old,"['Hdfc ATM', 'Indusind bank ATM', 'Sector 53-5...",NaN,"['Private Garden / Terrace', 'Water Storage', ..."

In [69]:
column_cleaning.isnull().sum()

property_id             0
property_name           0
link                    0
society                 0
price_in_cr             0
price_per_sqft          0
areawithtype            0
bedrooms                0
bathrooms               0
balcony                 0
additional_room         0
floor_info            104
facing                  0
property_age          106
nearby_location         0
furnishing_details    347
features              335
dtype: int64