In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)

### 1. Independent Builder Floor Data Loading

In [2]:
df_builder_floor= pd.read_csv("../../data/web_scraping/independent_builder_floor.csv")
df_builder_floor

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
0,4 BHK Independent Builder Floor in Sushant Lok...,Brand New Builder Floor,₹3.85 Cr,"₹14,259 /sqft","2,700 sqft (251 sqm) Super Built-up Area",O85021804,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Bahrisons library', 'Hanuman Mandir', 'New L..."
1,"4 BHK Independent Builder Floor in Sector 102,...",BPTP Amstoria,₹3.4 Cr,"₹17,000 /sqft","2,000 sqft (186 sqm) Carpet Area",V85303340,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi...","['Conscient One Mall', ""Domino's Pizza"", 'Daul..."
2,4 BHK Independent Builder Floor in A Block Sus...,"A Block Sushant Lok Phase 1, Gurgaon",₹3.66 Cr,"₹13,811 /sqft","2,650 sqft (246 sqm) Super Built-up Area",O83672012,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Bahrisons library', 'Hanuman Mandir', 'New L..."
3,4 BHK Independent Builder Floor in DLF Phase 2...,"DLF Phase 2, Gurgaon",₹5.25 Cr,"₹19,444 /sqft","2,700 sqft (251 sqm) Carpet Area",K85623978,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,5 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi...","['Gurgaon Central Mall', 'Hanuman Mandir', 'PV..."
4,4 BHK Independent Builder Floor in DLF Phase 2...,PARK FACING FLOOR,₹5 Cr,"₹12,500 /sqft","4,000 sqft (372 sqm) Carpet Area",E85624224,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,5 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi...","['Gurgaon Central Mall', 'PVR Cinames', 'Priva..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,"4 BHK Independent Builder Floor in Sector 46, ...",Private Builder Floor,₹3 Cr,"₹10,000 /sqft","3,000 sqft (279 sqm) Super Built-up Area",G78860067,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F...","['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ..."
1248,4 BHK Independent Builder Floor in Sushant Lok...,Sushant Lok 1 Builder Floors,₹5 Cr,"₹22,727 /sqft","2,200 sqft (204 sqm) Carpet Area",S85218742,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',...","['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa..."
1249,4 BHK Independent Builder Floor in Sushant Lok...,"Sushant Lok Phase 1, Gurgaon",₹5.85 Cr,"₹20,892 /sqft","2,800 sqft (260 sqm) Carpet Area",R85216914,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa..."
1250,"4 BHK Independent Builder Floor in Sector 84, ...",SS Linden Floors,₹2.92 Cr,"₹10,428 /sqft","2,800 sqft (260 sqm) Built-up Area",B84531164,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'...","['Agri Business Management Collage', 'Manesar ..."
1251,"4 BHK Independent Builder Floor in Sector 63A,...",Anant Raj Estates,₹3.8 Cr,"₹15,932 /sqft","2,385 sqft (222 sqm) Super Built-up Area",F84618392,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te...","['De Adventure Park', 'Vatika Business Centre'..."

In [3]:
df_builder_floor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252 entries, 0 to 1251
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       1252 non-null   object
 1   society             1252 non-null   object
 2   price               1252 non-null   object
 3   area                1252 non-null   object
 4   areawithtype        1252 non-null   object
 5   property_id         1252 non-null   object
 6   link                1252 non-null   object
 7   bedrooms            1252 non-null   object
 8   bathrooms           1252 non-null   object
 9   balcony             1252 non-null   object
 10  additional_room     1126 non-null   object
 11  floor_info          1252 non-null   object
 12  facing              1185 non-null   object
 13  property_age        1251 non-null   object
 14  furnishing_details  1180 non-null   object
 15  features            1214 non-null   object
 16  nearby_location     1252 non-null   object
dtypes: object(17)
memory usage: 166.4+ KB

In [4]:
df_builder_floor.describe()

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
count,1252,1252,1252,1252,1252,1252,1252,1252,1252,1252,1126,1252,1185,1251,1180,1214,1252
unique,205,296,273,874,374,1252,1252,5,7,5,65,33,8,4,1032,649,618
top,4 BHK Independent Builder Floor in DLF Phase 1...,"Palam Vihar, Gurgaon",₹3.5 Cr,"₹13,888 /sqft","2,700 sqft (251 sqm) Super Built-up Area",O85021804,https://www.99acres.com/4-bhk-bedroom-independ...,4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,[],"['Feng Shui / Vaastu Compliant', 'Water purifi...","['Max, Fortis', 'Pathways', 'Golf Course Road'..."
freq,66,64,37,13,74,1,1,727,591,917,223,372,401,825,37,144,38

In [5]:
df_builder_floor.isnull().sum()

property_name           0
society                 0
price                   0
area                    0
areawithtype            0
property_id             0
link                    0
bedrooms                0
bathrooms               0
balcony                 0
additional_room       126
floor_info              0
facing                 67
property_age            1
furnishing_details     72
features               38
nearby_location         0
dtype: int64

### 2. Independent Builder Floor Cleaning

In [6]:
df_builder_floor.columns

Index(['property_name', 'society', 'price', 'area', 'areawithtype',
       'property_id', 'link', 'bedrooms', 'bathrooms', 'balcony',
       'additional_room', 'floor_info', 'facing', 'property_age',
       'furnishing_details', 'features', 'nearby_location'],
      dtype='object')

In [7]:
df_builder_floor = df_builder_floor[['property_id','property_name', 'link', 'society', 'price', 'area',
       'areawithtype', 'bedrooms', 'bathrooms', 'balcony', 'additional_room',
       'floor_info', 'facing', 'property_age', 'nearby_location',
        'furnishing_details', 'features']]
df_builder_floor

,property_id,property_name,link,society,price,area,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,₹3.85 Cr,"₹14,259 /sqft","2,700 sqft (251 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,₹3.4 Cr,"₹17,000 /sqft","2,000 sqft (186 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",₹3.66 Cr,"₹13,811 /sqft","2,650 sqft (246 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",₹5.25 Cr,"₹19,444 /sqft","2,700 sqft (251 sqm) Carpet Area",4 Bedrooms,5 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,₹5 Cr,"₹12,500 /sqft","4,000 sqft (372 sqm) Carpet Area",4 Bedrooms,5 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,₹3 Cr,"₹10,000 /sqft","3,000 sqft (279 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,₹5 Cr,"₹22,727 /sqft","2,200 sqft (204 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",₹5.85 Cr,"₹20,892 /sqft","2,800 sqft (260 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,₹2.92 Cr,"₹10,428 /sqft","2,800 sqft (260 sqm) Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,₹3.8 Cr,"₹15,932 /sqft","2,385 sqft (222 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

In [8]:
missing_summary = (df_builder_floor
                    .isnull()
                    .sum()
                    .pipe(lambda d: d/(len(df_builder_floor)) * 100)
                    .reset_index()
                    .rename(columns={"index":"Feature/Column Name",0:"Missing Pct"})
                    .sort_values(by='Missing Pct', ascending=False)
)

In [9]:
missing_summary

   Feature/Column Name  Missing Pct
10     additional_room    10.063898
15  furnishing_details     5.750799
12              facing     5.351438
16            features     3.035144
13        property_age     0.079872
0          property_id     0.000000
1        property_name     0.000000
3              society     0.000000
2                 link     0.000000
8            bathrooms     0.000000
7             bedrooms     0.000000
6         areawithtype     0.000000
5                 area     0.000000
4                price     0.000000
9              balcony     0.000000
11          floor_info     0.000000
14     nearby_location     0.000000

### 3. Individual Column Cleaning

#### 1. Property Name

In [10]:
df_builder_floor['property_name'].isnull().sum()

np.int64(0)

#### 2. Society

In [11]:
df_builder_floor['society'].value_counts()

society
Palam Vihar, Gurgaon                                 64
Smart World Gems                                     46
Ansal API Esencia                                    42
Ansal API Versalia                                   38
Block C, Sushant Lok Phase 1, Gurgaon                31
Sector 23, Gurgaon                                   30
Sector 57, Gurgaon                                   29
DLF Phase 2, Gurgaon                                 28
DLF Phase 1, Gurgaon                                 25
Anant Raj Estates                                    24
Private Builder Floor                                23
M3M Soulitude                                        21
Sushant Lok Phase 1, Gurgaon                         20
DLF Garden City Floors                               20
Malibu Town, Gurgaon                                 18
Ansals Palam Vihar                                   17
Sector 45, Gurgaon                                   16
DLF Phase 1 Ultra Luxury Builder Floors              15
South City 1, Gurgaon                                15
Emaar Emerald Hills                                  14
DLF Phase 4, Gurgaon                                 14
South City 2, Gurgaon                                12
Luxury Builder floor In South City 2                 12
B Block Sushant Lok Phase 1, Gurgaon                 12
Sushant Lok 3 Extension, Gurgaon                     11
Vatika Independent Floors                            11
BPTP Green Oaks                                      11
DLF Gardencity Enclave                               10
DLF Luxury Builder Floors                            10
BPTP Astaire Gardens                                  9
Central Park Flower Valley Cerise Floors              9
Nirvana Country, Gurgaon                              9
Sushant Lok Phase 3, Gurgaon                          9
Malibu Towne                                          9
Unitech South City 2                                  9
Sushant Lok 1 Builder Floors                          9
Sector 7, Gurgaon                                     8
Vipul World                                           8
Signature Global Park                                 8
Signature Global City                                 8
Birla Navya                                           8
Sushant Lok Phase 2, Gurgaon                          7
SS Linden Floors                                      7
Adani Brahma Samsara Vilasa                           7
A Block Sushant Lok Phase 1, Gurgaon                  7
Central Park Flower Valley Flamingo Floors            7
Sushant Lok 2,Sector 55, Gurgaon                      7
Sector 46, Gurgaon                                    7
Sector 63A, Gurgaon                                   7
Block C2 Sector 3, Gurgaon                            7
All Punjabi Welfare Association                       6
Block N, Mayfield garden, Gurgaon                     6
Block A South City 2, Gurgaon                         6
Sector 67A, Gurgaon                                   6
Mayfield Gardens                                      6
Sector 51, Gurgaon                                    6
Hero Homes                                            6
Ansal Sushant Residency                               6
Brand New Builder Floor                               6
Block-A, DLF City Phase 1, Gurgaon                    6
Ansal Sushant Lok 2                                   6
Huda Flats                                            5
Ardee City                                            5
DLF Phase - 1                                         5
DLF The Grove                                         5
Block B Sushant Lok 3, Gurgaon                        5
Ardee City, Gurgaon                                   5
Ansal Plaza                                           5
Huda Sector 46                                        5
Ultra Luxurious Builder Floor                         4
DLF Floors Phase 3                                    4
Block J Pocket C Palam Vihar, Gurgaon                 4
Uppal Southend                                        4
Block E Greenwood City, Gurgaon                       4
TOP FLOOR TERRACE GARDEN                              4
Luxury Builder Floor In Sushant Lok 1                 4
PARK FACING FLOOR                                     3
Block P South city 1, Gurgaon                         3
BPTP Amstoria                                         3
north east facing                                     3
Vatika India Next                                     3
Sector 9, Gurgaon                                     3
DLF Phase 4 Luxury Builder Floors                     3
Block C Palam Vihar, Gurgaon                          3
Block C Sushant Lok Phase - 3, Gurgaon                3
Central Park Flower Valley Aqua Front Towers          3
Top Terrace                                           3
DLF Phase -1                                          3
Oriental Homes                                        3
Sector 40, Gurgaon                                    3
Ultra Luxury Builder Floor In Malibu Town             3
Ansal Homes                                           3
Luxury Homes By Horiizon Ventures                     3
Brand new ultra luxury builder floor                  3
Ultra Luxury Builder Floor                            3
Sector 27, Gurgaon                                    3
Mayfield Garden, Gurgaon                              3
Sector 4, Gurgaon                                     3
Emaar MGF Emerald Floors Premier                      3
Unitech Deerwood Chase                                3
Tata Primanti                                         3
Block G Sector-57, Gurgaon                            2
U Block DLF Phase 3, Gurgaon                          2
Sector 65, Gurgaon                                    2
DLF City Phase 1                                      2
DLF City Plots Phase 2                                2
Paramount Luxury Floors                               2
Sector 31, Gurgaon                                    2
Unitech Greenwood City                                2
Block M DLF phase 2, Gurgaon                          2
Silverglades The Melia                                2
Niho Scottish Mall                                    2
Sector 57                                             2
Sector 47, Gurgaon                                    2
Central Park Flower Valley                            2
Whiteland Blissville                                  2
Flora Avenue 33                                       2
Smart World Orchard                                   2
DLF Phase - 2                                         2
Adani Brahma Samsara                                  2
Block C Ardee City, Gurgaon                           2
Pocket E Sector 2 Palam Vihar, Gurgaon                2
B1 Block Sector 57, Gurgaon                           2
Vatika Iris Floors                                    2
Sector 70A, Gurgaon                                   2
DLF Amaltas Drive                                     2
Uppals Southend, Gurgaon                              2
C block Sector 43, Gurgaon                            2
V Block DLF Phase 3, Gurgaon                          2
Huda Sector 45                                        2
Suncity, Gurgaon                                      2
Sector 15 Part 2, Gurgaon                             2
Silver Oaks Estates                                   2
G block DLF City Phase 1, Gurgaon                     2
Sector 52, Gurgaon                                    2
DLF Cyber City, Gurgaon                               2
DLF PHASE - 1                                         2
B Block, Mayfield Garden, Gurgaon                     2
Sector 55, Gurgaon                                    2
sushant lok 3                                         2
DLF Gardencity                                        2
Block N South City 1, Gurgaon                         2
Super Luxury Fabulous Construction                    2
Vatika Primrose Floors                                2
AKASHNEEM MARG                                        1
G block south city                                    1
Independent Floor by Vibrant Builders                 1
Suncity Vatsal Valley                                 1
Sector 67, Gurgaon                                    1
Sector 91, Gurgaon                                    1
ULTRA LUXURY NAMO HOMES BUILDER FLOOR                 1
Block F, Sushant Lok Phase III, Gurgaon               1
Luxury Builder Floor                                  1
Ansal, Ultra Luxury Builder Floor                     1
Private Builder FLoor                                 1
Central Park The Orchard                              1
Sector 23A, Gurgaon                                   1
Sushant Lok, Gurgaon                                  1
Trehan Luxury Floors 71                               1
DLF Exclusive Floors                                  1
Supermart-1, Gurgaon                                  1
palam vihar                                           1
Ultra Luxury Builder Floor In Malibu town             1
SECTOR 50 AVENUE EXTENTION ROAD                       1
GPS Atulyam Homes                                     1
Sector 81, Gurgaon                                    1
MKS County                                            1
Sec 56 Block C                                        1
ROF Insignia Park                                     1
BPTP Pedestal                                         1
Sector 9A, Gurgaon                                    1
SUPER LUXURY FLOOR CHEAPEST DEAL                      1
DLF Phase 5, Gurgaon                                  1
TOP FLOOR TERRACE                                     1
Super Luxury Brand New                                1
DLF Central Arcade                                    1
DUPLEX GROUND FLOOR                                   1
DUPLEX PENTHOUSE 5BHK                                 1
300SQYD FLOOR CHEAPEST DEAL                           1
TOP FLOOR DUPLEX PENTHOUSE 5BHK                       1
VASTU COMPLAINT                                       1
ARJUN MARG DLF 1                                      1
BEST PRICE DEAL                                       1
DESIGNER PARK FACING                                  1
C Block Mayfield Garden, Gurgaon                      1
Block C Greenwood City, Gurgaon                       1
Pocket I Nirvana Country, Gurgaon                     1
Super Luxury Park facing                              1
Sector 15 Part 1, Gurgaon                             1
Raheja Vedaanta                                       1
Elegant Home by Horiizon Ventures                     1
DLF Builder Floors                                    1
DLF Regal Gardens                                     1
Central Park Flower Valley Clover Floors              1
Luxury Builder Homes by Horiizon Ventures             1
Signature Global City 37D Ph 2                        1
Independent Floors at DLF City Phase 4                1
418SQYD VALUE FOR MONEY DEAL                          1
Hongkong bazaar                                       1
DLF City Plots                                        1
Signature Global City 63A                             1
RWA Sector 46                                         1
220 n block mayfield garden                           1
T Block, DLF Phase 3, Gurgaon                         1
Sushant lok 3                                         1
Unitech Escape                                        1
DLF Phase - 4                                         1
Block E DLF City Phase 1, Gurgaon                     1
Today Blossoms 2                                      1
Sector 89, Gurgaon                                    1
ultra luxury builder floor                            1
Greenwood City, Gurgaon                               1
Exclusive Builder Floor                               1
Ultra-Luxury Floors                                   1
Huda Sector 47                                        1
Park facing Budget friendly                           1
Block K South City 1, Gurgaon                         1
Sushant lok                                           1
DLF INDEPENDENT FLOORS                                1
Block S Uppals Southend, Gurgaon                      1
Sector 84, Gurgaon                                    1
Luxury Builder floor In Nirvana Country               1
Premium Luxury DLF City Floors                        1
Block H, Sector-57,, Gurgaon                          1
builder Floor sec 46                                  1
Sector 61, Gurgaon                                    1
Orchid Island                                         1
Brand New Ultra Luxurious Builder Floor               1
Block H Dlf phase 1                                   1
Super Luxury Mindblowing                              1
Vatika P Block                                        1
Block F Sector 57, Gurgaon                            1
ULTRA LUXURIOUS BUILDER FLOOR DLF PHASE 2             1
Sushant Lok - 1                                       1
Vaastu-Compliant                                      1
South Zone RWA                                        1
Lotus Floors                                          1
Ultra Luxury Builder Floor In Sushant Lok-3           1
BNB Nature Valley                                     1
B Block Pocket B Palam Vihar, Gurgaon                 1
Central Park Flower Valley Mikasa Plots               1
Adani M2K Oyster Grande                               1
park Facing Floor DLF                                 1
DLF Ultra Luxury Builder Floors                       1
Sector 43, Gurgaon                                    1
Ultra Luxury Builder floor In Nirvana Country         1
Namo Homes ultra luxury independent builder floor     1
Luxury Builder Floors dlf phase 2                     1
Block M South City 1, Gurgaon                         1
DLF Alameda                                           1
Green Meadows, DLF Phase 4                            1
Laburnum Victory Floors                               1
Sector 70, Gurgaon                                    1
G Block                                               1
luxurious builder floor 12mtr road north facing       1
Vatika Emilia Floors                                  1
Florence Residency                                    1
Avenue-49                                             1
Galleria Market, Gurgaon                              1
wide road                                             1
sector 47                                             1
A BLOCK                                               1
CORNER GREEN BELT                                     1
BEST PRICE DEALS                                      1
Sector 2, Gurgaon                                     1
Palam Vihar Society                                   1
300SQYD FLOOR VALUE FOR MONEY DEAL                    1
sushant lok -1 A block                                1
Ace Palm Floors                                       1
Eros Rosewood City                                    1
Sector 93, Gurgaon                                    1
m3m mall                                              1
Luxurious Builder floor In South City 2               1
49th Avenue                                           1
Super Luxury Two Side Open                            1
Ireo City Plots                                       1
Green Meadows                                         1
A Block Sector 55                                     1
avenue 49                                             1
A Block Sushant Lok Phase - 3, Gurgaon                1
S Block DLF Phase 3, Gurgaon                          1
sector 49                                             1
South City, Gurgaon                                   1
Sector 10, Gurgaon                                    1
Ansals Boom Plaza                                     1
Sector 49, Gurgaon                                    1
Block I South City 1, Gurgaon                         1
Nirvana Cedar Crest                                   1
Sector-35 Sohna, Gurgaon                              1
vatika P block                                        1
Block D sector 56, Gurgaon                            1
Block E sector 56, Gurgaon                            1
SS Almeria                                            1
Block H South city 2, Gurgaon                         1
TOP FLOOR 5BHK                                        1
Dlf Phase 4 Brand New Builder Floor                   1
Name: count, dtype: int64

In [12]:
df_builder_floor['society'].isnull().sum()

np.int64(0)

#### 2. Price_in_Cr

In [13]:
df_builder_floor = df_builder_floor.rename(columns ={
    'price' : 'price_in_cr',
    'area'  :'price_per_sqft'
})

In [14]:
df_builder_floor['price_in_cr'].value_counts()

price_in_cr
₹3.5 Cr       37
₹3.25 Cr      31
₹3 Cr         31
₹4.25 Cr      27
₹4 Cr         27
₹3.3 Cr       26
₹2.9 Cr       24
₹4.5 Cr       22
₹4.1 Cr       22
₹2.7 Cr       22
₹3.4 Cr       21
₹2.6 Cr       20
₹2.65 Cr      20
₹3.75 Cr      20
₹3.2 Cr       19
₹2.85 Cr      19
₹3.1 Cr       18
₹3.8 Cr       17
₹3.15 Cr      17
₹6.5 Cr       16
₹2.95 Cr      16
₹2.5 Cr       16
₹2.8 Cr       16
₹2.75 Cr      15
₹3.9 Cr       15
₹2.3 Cr       14
₹1.65 Cr      13
₹3.6 Cr       12
₹5 Cr         12
₹5.5 Cr       12
₹3.7 Cr       11
₹2.45 Cr      11
₹6 Cr         11
₹5.25 Cr      11
₹3.65 Cr      11
₹1.62 Cr      10
₹3.85 Cr      10
₹2.55 Cr       9
₹2.4 Cr        9
₹2.99 Cr       9
₹3.35 Cr       9
₹2 Cr          9
₹4.2 Cr        9
₹3.95 Cr       9
₹6.25 Cr       8
₹2.2 Cr        8
₹4.75 Cr       8
₹3.05 Cr       8
₹1.35 Cr       8
₹4.4 Cr        8
₹1.7 Cr        7
₹4.35 Cr       7
₹1.64 Cr       7
₹2.25 Cr       7
₹3.45 Cr       7
₹1.75 Cr       6
₹5.9 Cr        6
₹8 Cr          6
₹1.6 Cr        6
₹4.65 Cr       6
₹5.75 Cr       6
₹5.8 Cr        6
₹5.85 Cr       6
₹3.49 Cr       5
₹2.15 Cr       5
₹2.35 Cr       5
₹4.15 Cr       5
₹6.1 Cr        5
₹6.75 Cr       5
₹1.95 Cr       5
₹6.3 Cr        5
₹4.85 Cr       5
₹4.7 Cr        4
₹4.95 Cr       4
₹1.3 Cr        4
₹1.99 Cr       4
₹1.63 Cr       4
₹5.95 Cr       4
₹1.9 Cr        4
₹3.55 Cr       4
₹1.58 Cr       4
₹1.4 Cr        4
₹6.2 Cr        4
₹4.8 Cr        4
₹2.05 Cr       4
₹5.45 Cr       4
₹7 Cr          4
₹1.59 Cr       4
₹1.55 Cr       4
₹4.45 Cr       4
₹2.68 Cr       3
₹2.56 Cr       3
₹2.51 Cr       3
₹1.56 Cr       3
₹4.49 Cr       3
₹2.66 Cr       3
₹2.62 Cr       3
₹2.96 Cr       3
₹5.3 Cr        3
₹5.1 Cr        3
₹2.61 Cr       3
₹7.5 Cr        3
₹1.33 Cr       3
₹4.55 Cr       3
₹1.68 Cr       3
₹1.32 Cr       3
₹7.25 Cr       3
₹1.45 Cr       3
₹6.8 Cr        3
₹4.3 Cr        3
₹4.21 Cr       3
₹2.69 Cr       3
₹1.18 Cr       3
₹1.5 Cr        3
₹5.65 Cr       3
₹4.9 Cr        2
₹1.15 Cr       2
₹1.71 Cr       2
₹2.49 Cr       2
₹13.5 Cr       2
₹1.46 Cr       2
₹6.15 Cr       2
₹1.2 Cr        2
₹2.79 Cr       2
₹9 Cr          2
₹4.11 Cr       2
₹4.6 Cr        2
₹12 Cr         2
₹2.54 Cr       2
₹4.05 Cr       2
₹5.2 Cr        2
₹7.3 Cr        2
₹8.5 Cr        2
₹3.99 Cr       2
₹2.52 Cr       2
₹5.35 Cr       2
₹2.16 Cr       2
₹1.85 Cr       2
₹3.62 Cr       2
₹2.92 Cr       2
₹2.22 Cr       2
₹2.98 Cr       2
₹2.71 Cr       2
₹7.45 Cr       2
₹6.4 Cr        2
₹6.19 Cr       2
₹8.75 Cr       2
₹2.89 Cr       2
₹1.29 Cr       2
₹3.39 Cr       2
₹2.18 Cr       2
₹12.85 Cr      1
₹6.9 Cr        1
₹6.49 Cr       1
₹1.97 Cr       1
₹4.28 Cr       1
₹1.1 Cr        1
₹1.57 Cr       1
₹7.49 Cr       1
₹2.11 Cr       1
₹6.39 Cr       1
₹17.75 Cr      1
₹2.64 Cr       1
₹2.67 Cr       1
₹2.29 Cr       1
₹2.21 Cr       1
₹4.19 Cr       1
₹2.43 Cr       1
₹1 Cr          1
₹2.78 Cr       1
₹1.39 Cr       1
₹3.88 Cr       1
₹2.19 Cr       1
₹1.81 Cr       1
₹1.92 Cr       1
₹3.29 Cr       1
₹4.31 Cr       1
₹3.66 Cr       1
₹3.18 Cr       1
₹4.71 Cr       1
₹1.28 Cr       1
₹11.01 Cr      1
₹7.15 Cr       1
₹4.33 Cr       1
₹3.91 Cr       1
₹3.98 Cr       1
₹2.58 Cr       1
₹2.34 Cr       1
₹8.3 Cr        1
₹3.69 Cr       1
₹6.65 Cr       1
₹13.95 Cr      1
₹1.82 Cr       1
₹1.51 Cr       1
₹5.29 Cr       1
₹10.9 Cr       1
₹2.1 Cr        1
₹1.93 Cr       1
₹6.7 Cr        1
₹10.85 Cr      1
₹2.09 Cr       1
₹6.45 Cr       1
₹3.12 Cr       1
₹7.1 Cr        1
₹1.74 Cr       1
₹3.58 Cr       1
₹11 Cr         1
₹6.74 Cr       1
₹3.14 Cr       1
₹2.48 Cr       1
₹1.34 Cr       1
₹1.42 Cr       1
₹1.98 Cr       1
₹11.5 Cr       1
₹1.36 Cr       1
₹5.55 Cr       1
₹95 Lac        1
₹6.6 Cr        1
₹4.62 Cr       1
₹2.04 Cr       1
₹5.34 Cr       1
₹74.85 Lac     1
₹5.4 Cr        1
₹10 Cr         1
₹1.41 Cr       1
₹3.02 Cr       1
₹5.89 Cr       1
₹1.48 Cr       1
₹4.29 Cr       1
₹3.44 Cr       1
₹3.33 Cr       1
₹3.24 Cr       1
₹3.89 Cr       1
₹4.99 Cr       1
₹4.89 Cr       1
₹3.87 Cr       1
₹8.9 Cr        1
₹9.35 Cr       1
₹10.15 Cr      1
₹9.45 Cr       1
₹3.13 Cr       1
₹1.38 Cr       1
₹5.7 Cr        1
₹7.95 Cr       1
₹1.23 Cr       1
₹7.48 Cr       1
₹2.53 Cr       1
₹2.74 Cr       1
₹2.91 Cr       1
₹2.77 Cr       1
₹3.48 Cr       1
₹6.98 Cr       1
₹2.42 Cr       1
₹1.25 Cr       1
₹3.81 Cr       1
₹12.99 Cr      1
₹1.05 Cr       1
₹1.22 Cr       1
₹2.72 Cr       1
₹1.43 Cr       1
₹75 Lac        1
₹3.28 Cr       1
₹1.73 Cr       1
₹4.42 Cr       1
₹3.23 Cr       1
₹2.33 Cr       1
₹3.82 Cr       1
₹80.5 Lac      1
₹1.96 Cr       1
₹3.72 Cr       1
₹3.19 Cr       1
₹4.01 Cr       1
₹5.02 Cr       1
Name: count, dtype: int64

In [15]:
column_cleaning = (df_builder_floor.assign
                   (
                       price_in_cr = lambda df_:df_['price_in_cr']
                                            .str.replace('₹','')
                   ))
column_cleaning['price_in_cr'].unique()

array(['3.85 Cr', '3.4 Cr', '3.66 Cr', '5.25 Cr', '5 Cr', '4.1 Cr',
       '4.4 Cr', '5.9 Cr', '3.8 Cr', '4.35 Cr', '4.71 Cr', '4.5 Cr',
       '6 Cr', '5.5 Cr', '4 Cr', '3 Cr', '3.1 Cr', '3.95 Cr', '6.5 Cr',
       '3.18 Cr', '4.15 Cr', '8 Cr', '4.25 Cr', '4.33 Cr', '8.5 Cr',
       '2.54 Cr', '3.91 Cr', '6.1 Cr', '11.01 Cr', '3.99 Cr', '4.75 Cr',
       '7.15 Cr', '3.2 Cr', '3.45 Cr', '3.9 Cr', '2.2 Cr', '2.96 Cr',
       '3.89 Cr', '5.3 Cr', '3.24 Cr', '2.8 Cr', '3.65 Cr', '1.63 Cr',
       '5.95 Cr', '6.25 Cr', '2.18 Cr', '8.9 Cr', '2.75 Cr', '3.44 Cr',
       '3.33 Cr', '2.3 Cr', '3.3 Cr', '1.65 Cr', '4.7 Cr', '2.7 Cr',
       '2.71 Cr', '2.85 Cr', '3.05 Cr', '1.7 Cr', '3.75 Cr', '1.62 Cr',
       '6.19 Cr', '3.15 Cr', '2.6 Cr', '2.45 Cr', '2.99 Cr', '1.46 Cr',
       '1.74 Cr', '6.3 Cr', '2.9 Cr', '3.5 Cr', '4.21 Cr', '5.75 Cr',
       '11 Cr', '2.49 Cr', '13.5 Cr', '4.3 Cr', '5.85 Cr', '6.8 Cr',
       '7.1 Cr', '3.25 Cr', '2.5 Cr', '1.45 Cr', '1.64 Cr', '7.25 Cr',
       '1.6 Cr', '4.65 Cr', '1.32 Cr', '3.12 Cr', '6.45 Cr', '2.65 Cr',
       '2.55 Cr', '2.95 Cr', '1.35 Cr', '13.95 Cr', '5.8 Cr', '4.2 Cr',
       '1.55 Cr', '2.16 Cr', '7.3 Cr', '4.45 Cr', '7.49 Cr', '5.45 Cr',
       '5.35 Cr', '12.85 Cr', '1.95 Cr', '1.59 Cr', '7 Cr', '3.6 Cr',
       '6.9 Cr', '4.28 Cr', '2 Cr', '2.51 Cr', '1.1 Cr', '2.52 Cr',
       '1.97 Cr', '6.75 Cr', '6.2 Cr', '4.85 Cr', '3.7 Cr', '1.56 Cr',
       '6.49 Cr', '4.49 Cr', '3.58 Cr', '3.14 Cr', '2.69 Cr', '1.18 Cr',
       '6.74 Cr', '1.4 Cr', '8.75 Cr', '2.35 Cr', '1.15 Cr', '3.49 Cr',
       '1.68 Cr', '2.4 Cr', '2.09 Cr', '10.85 Cr', '1.93 Cr', '2.25 Cr',
       '6.7 Cr', '1.58 Cr', '2.1 Cr', '4.8 Cr', '10.9 Cr', '5.29 Cr',
       '4.9 Cr', '1.51 Cr', '4.11 Cr', '5.89 Cr', '3.55 Cr', '7.5 Cr',
       '9 Cr', '3.02 Cr', '1.2 Cr', '1.71 Cr', '1.82 Cr', '1.48 Cr',
       '12 Cr', '1.9 Cr', '6.15 Cr', '2.15 Cr', '1.75 Cr', '4.29 Cr',
       '3.35 Cr', '10 Cr', '4.6 Cr', '1.41 Cr', '1.33 Cr', '74.85 Lac',
       '6.6 Cr', '5.4 Cr', '5.34 Cr', '2.04 Cr', '4.62 Cr', '95 Lac',
       '2.79 Cr', '5.55 Cr', '1.3 Cr', '11.5 Cr', '1.36 Cr', '1.98 Cr',
       '4.55 Cr', '1.42 Cr', '1.34 Cr', '2.48 Cr', '3.13 Cr', '1.99 Cr',
       '10.15 Cr', '9.35 Cr', '6.4 Cr', '7.45 Cr', '9.45 Cr', '1.23 Cr',
       '3.87 Cr', '2.98 Cr', '4.95 Cr', '7.48 Cr', '4.99 Cr', '4.89 Cr',
       '3.62 Cr', '2.92 Cr', '7.95 Cr', '5.65 Cr', '2.22 Cr', '2.61 Cr',
       '5.1 Cr', '5.7 Cr', '1.85 Cr', '1.38 Cr', '2.74 Cr', '2.62 Cr',
       '2.91 Cr', '2.53 Cr', '2.89 Cr', '1.29 Cr', '1.5 Cr', '2.77 Cr',
       '3.48 Cr', '3.39 Cr', '6.98 Cr', '2.42 Cr', '1.25 Cr', '3.81 Cr',
       '12.99 Cr', '1 Cr', '1.28 Cr', '4.19 Cr', '2.43 Cr', '2.78 Cr',
       '1.39 Cr', '2.19 Cr', '3.88 Cr', '1.81 Cr', '1.92 Cr', '3.29 Cr',
       '2.68 Cr', '2.05 Cr', '4.31 Cr', '17.75 Cr', '2.67 Cr', '2.66 Cr',
       '2.29 Cr', '2.56 Cr', '2.64 Cr', '5.2 Cr', '2.21 Cr', '2.58 Cr',
       '2.34 Cr', '4.05 Cr', '8.3 Cr', '3.69 Cr', '6.65 Cr', '2.11 Cr',
       '6.39 Cr', '1.57 Cr', '3.98 Cr', '1.05 Cr', '1.22 Cr', '2.72 Cr',
       '1.43 Cr', '75 Lac', '3.28 Cr', '1.73 Cr', '4.42 Cr', '3.23 Cr',
       '2.33 Cr', '3.82 Cr', '80.5 Lac', '1.96 Cr', '3.72 Cr', '3.19 Cr',
       '4.01 Cr', '5.02 Cr'], dtype=object)

In [16]:
column_cleaning = (df_builder_floor.assign
                   (
                       price_in_cr = lambda df_:df_['price_in_cr']
                                            .str.replace('₹','')
                   ))
column_cleaning['price_in_cr'].unique()

array(['3.85 Cr', '3.4 Cr', '3.66 Cr', '5.25 Cr', '5 Cr', '4.1 Cr',
       '4.4 Cr', '5.9 Cr', '3.8 Cr', '4.35 Cr', '4.71 Cr', '4.5 Cr',
       '6 Cr', '5.5 Cr', '4 Cr', '3 Cr', '3.1 Cr', '3.95 Cr', '6.5 Cr',
       '3.18 Cr', '4.15 Cr', '8 Cr', '4.25 Cr', '4.33 Cr', '8.5 Cr',
       '2.54 Cr', '3.91 Cr', '6.1 Cr', '11.01 Cr', '3.99 Cr', '4.75 Cr',
       '7.15 Cr', '3.2 Cr', '3.45 Cr', '3.9 Cr', '2.2 Cr', '2.96 Cr',
       '3.89 Cr', '5.3 Cr', '3.24 Cr', '2.8 Cr', '3.65 Cr', '1.63 Cr',
       '5.95 Cr', '6.25 Cr', '2.18 Cr', '8.9 Cr', '2.75 Cr', '3.44 Cr',
       '3.33 Cr', '2.3 Cr', '3.3 Cr', '1.65 Cr', '4.7 Cr', '2.7 Cr',
       '2.71 Cr', '2.85 Cr', '3.05 Cr', '1.7 Cr', '3.75 Cr', '1.62 Cr',
       '6.19 Cr', '3.15 Cr', '2.6 Cr', '2.45 Cr', '2.99 Cr', '1.46 Cr',
       '1.74 Cr', '6.3 Cr', '2.9 Cr', '3.5 Cr', '4.21 Cr', '5.75 Cr',
       '11 Cr', '2.49 Cr', '13.5 Cr', '4.3 Cr', '5.85 Cr', '6.8 Cr',
       '7.1 Cr', '3.25 Cr', '2.5 Cr', '1.45 Cr', '1.64 Cr', '7.25 Cr',
       '1.6 Cr', '4.65 Cr', '1.32 Cr', '3.12 Cr', '6.45 Cr', '2.65 Cr',
       '2.55 Cr', '2.95 Cr', '1.35 Cr', '13.95 Cr', '5.8 Cr', '4.2 Cr',
       '1.55 Cr', '2.16 Cr', '7.3 Cr', '4.45 Cr', '7.49 Cr', '5.45 Cr',
       '5.35 Cr', '12.85 Cr', '1.95 Cr', '1.59 Cr', '7 Cr', '3.6 Cr',
       '6.9 Cr', '4.28 Cr', '2 Cr', '2.51 Cr', '1.1 Cr', '2.52 Cr',
       '1.97 Cr', '6.75 Cr', '6.2 Cr', '4.85 Cr', '3.7 Cr', '1.56 Cr',
       '6.49 Cr', '4.49 Cr', '3.58 Cr', '3.14 Cr', '2.69 Cr', '1.18 Cr',
       '6.74 Cr', '1.4 Cr', '8.75 Cr', '2.35 Cr', '1.15 Cr', '3.49 Cr',
       '1.68 Cr', '2.4 Cr', '2.09 Cr', '10.85 Cr', '1.93 Cr', '2.25 Cr',
       '6.7 Cr', '1.58 Cr', '2.1 Cr', '4.8 Cr', '10.9 Cr', '5.29 Cr',
       '4.9 Cr', '1.51 Cr', '4.11 Cr', '5.89 Cr', '3.55 Cr', '7.5 Cr',
       '9 Cr', '3.02 Cr', '1.2 Cr', '1.71 Cr', '1.82 Cr', '1.48 Cr',
       '12 Cr', '1.9 Cr', '6.15 Cr', '2.15 Cr', '1.75 Cr', '4.29 Cr',
       '3.35 Cr', '10 Cr', '4.6 Cr', '1.41 Cr', '1.33 Cr', '74.85 Lac',
       '6.6 Cr', '5.4 Cr', '5.34 Cr', '2.04 Cr', '4.62 Cr', '95 Lac',
       '2.79 Cr', '5.55 Cr', '1.3 Cr', '11.5 Cr', '1.36 Cr', '1.98 Cr',
       '4.55 Cr', '1.42 Cr', '1.34 Cr', '2.48 Cr', '3.13 Cr', '1.99 Cr',
       '10.15 Cr', '9.35 Cr', '6.4 Cr', '7.45 Cr', '9.45 Cr', '1.23 Cr',
       '3.87 Cr', '2.98 Cr', '4.95 Cr', '7.48 Cr', '4.99 Cr', '4.89 Cr',
       '3.62 Cr', '2.92 Cr', '7.95 Cr', '5.65 Cr', '2.22 Cr', '2.61 Cr',
       '5.1 Cr', '5.7 Cr', '1.85 Cr', '1.38 Cr', '2.74 Cr', '2.62 Cr',
       '2.91 Cr', '2.53 Cr', '2.89 Cr', '1.29 Cr', '1.5 Cr', '2.77 Cr',
       '3.48 Cr', '3.39 Cr', '6.98 Cr', '2.42 Cr', '1.25 Cr', '3.81 Cr',
       '12.99 Cr', '1 Cr', '1.28 Cr', '4.19 Cr', '2.43 Cr', '2.78 Cr',
       '1.39 Cr', '2.19 Cr', '3.88 Cr', '1.81 Cr', '1.92 Cr', '3.29 Cr',
       '2.68 Cr', '2.05 Cr', '4.31 Cr', '17.75 Cr', '2.67 Cr', '2.66 Cr',
       '2.29 Cr', '2.56 Cr', '2.64 Cr', '5.2 Cr', '2.21 Cr', '2.58 Cr',
       '2.34 Cr', '4.05 Cr', '8.3 Cr', '3.69 Cr', '6.65 Cr', '2.11 Cr',
       '6.39 Cr', '1.57 Cr', '3.98 Cr', '1.05 Cr', '1.22 Cr', '2.72 Cr',
       '1.43 Cr', '75 Lac', '3.28 Cr', '1.73 Cr', '4.42 Cr', '3.23 Cr',
       '2.33 Cr', '3.82 Cr', '80.5 Lac', '1.96 Cr', '3.72 Cr', '3.19 Cr',
       '4.01 Cr', '5.02 Cr'], dtype=object)

In [17]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
3.5 Cr       37
3.25 Cr      31
3 Cr         31
4.25 Cr      27
4 Cr         27
3.3 Cr       26
2.9 Cr       24
4.5 Cr       22
4.1 Cr       22
2.7 Cr       22
3.4 Cr       21
2.6 Cr       20
2.65 Cr      20
3.75 Cr      20
3.2 Cr       19
2.85 Cr      19
3.1 Cr       18
3.8 Cr       17
3.15 Cr      17
6.5 Cr       16
2.95 Cr      16
2.5 Cr       16
2.8 Cr       16
2.75 Cr      15
3.9 Cr       15
2.3 Cr       14
1.65 Cr      13
3.6 Cr       12
5 Cr         12
5.5 Cr       12
3.7 Cr       11
2.45 Cr      11
6 Cr         11
5.25 Cr      11
3.65 Cr      11
1.62 Cr      10
3.85 Cr      10
2.55 Cr       9
2.4 Cr        9
2.99 Cr       9
3.35 Cr       9
2 Cr          9
4.2 Cr        9
3.95 Cr       9
6.25 Cr       8
2.2 Cr        8
4.75 Cr       8
3.05 Cr       8
1.35 Cr       8
4.4 Cr        8
1.7 Cr        7
4.35 Cr       7
1.64 Cr       7
2.25 Cr       7
3.45 Cr       7
1.75 Cr       6
5.9 Cr        6
8 Cr          6
1.6 Cr        6
4.65 Cr       6
5.75 Cr       6
5.8 Cr        6
5.85 Cr       6
3.49 Cr       5
2.15 Cr       5
2.35 Cr       5
4.15 Cr       5
6.1 Cr        5
6.75 Cr       5
1.95 Cr       5
6.3 Cr        5
4.85 Cr       5
4.7 Cr        4
4.95 Cr       4
1.3 Cr        4
1.99 Cr       4
1.63 Cr       4
5.95 Cr       4
1.9 Cr        4
3.55 Cr       4
1.58 Cr       4
1.4 Cr        4
6.2 Cr        4
4.8 Cr        4
2.05 Cr       4
5.45 Cr       4
7 Cr          4
1.59 Cr       4
1.55 Cr       4
4.45 Cr       4
2.68 Cr       3
2.56 Cr       3
2.51 Cr       3
1.56 Cr       3
4.49 Cr       3
2.66 Cr       3
2.62 Cr       3
2.96 Cr       3
5.3 Cr        3
5.1 Cr        3
2.61 Cr       3
7.5 Cr        3
1.33 Cr       3
4.55 Cr       3
1.68 Cr       3
1.32 Cr       3
7.25 Cr       3
1.45 Cr       3
6.8 Cr        3
4.3 Cr        3
4.21 Cr       3
2.69 Cr       3
1.18 Cr       3
1.5 Cr        3
5.65 Cr       3
4.9 Cr        2
1.15 Cr       2
1.71 Cr       2
2.49 Cr       2
13.5 Cr       2
1.46 Cr       2
6.15 Cr       2
1.2 Cr        2
2.79 Cr       2
9 Cr          2
4.11 Cr       2
4.6 Cr        2
12 Cr         2
2.54 Cr       2
4.05 Cr       2
5.2 Cr        2
7.3 Cr        2
8.5 Cr        2
3.99 Cr       2
2.52 Cr       2
5.35 Cr       2
2.16 Cr       2
1.85 Cr       2
3.62 Cr       2
2.92 Cr       2
2.22 Cr       2
2.98 Cr       2
2.71 Cr       2
7.45 Cr       2
6.4 Cr        2
6.19 Cr       2
8.75 Cr       2
2.89 Cr       2
1.29 Cr       2
3.39 Cr       2
2.18 Cr       2
12.85 Cr      1
6.9 Cr        1
6.49 Cr       1
1.97 Cr       1
4.28 Cr       1
1.1 Cr        1
1.57 Cr       1
7.49 Cr       1
2.11 Cr       1
6.39 Cr       1
17.75 Cr      1
2.64 Cr       1
2.67 Cr       1
2.29 Cr       1
2.21 Cr       1
4.19 Cr       1
2.43 Cr       1
1 Cr          1
2.78 Cr       1
1.39 Cr       1
3.88 Cr       1
2.19 Cr       1
1.81 Cr       1
1.92 Cr       1
3.29 Cr       1
4.31 Cr       1
3.66 Cr       1
3.18 Cr       1
4.71 Cr       1
1.28 Cr       1
11.01 Cr      1
7.15 Cr       1
4.33 Cr       1
3.91 Cr       1
3.98 Cr       1
2.58 Cr       1
2.34 Cr       1
8.3 Cr        1
3.69 Cr       1
6.65 Cr       1
13.95 Cr      1
1.82 Cr       1
1.51 Cr       1
5.29 Cr       1
10.9 Cr       1
2.1 Cr        1
1.93 Cr       1
6.7 Cr        1
10.85 Cr      1
2.09 Cr       1
6.45 Cr       1
3.12 Cr       1
7.1 Cr        1
1.74 Cr       1
3.58 Cr       1
11 Cr         1
6.74 Cr       1
3.14 Cr       1
2.48 Cr       1
1.34 Cr       1
1.42 Cr       1
1.98 Cr       1
11.5 Cr       1
1.36 Cr       1
5.55 Cr       1
95 Lac        1
6.6 Cr        1
4.62 Cr       1
2.04 Cr       1
5.34 Cr       1
74.85 Lac     1
5.4 Cr        1
10 Cr         1
1.41 Cr       1
3.02 Cr       1
5.89 Cr       1
1.48 Cr       1
4.29 Cr       1
3.44 Cr       1
3.33 Cr       1
3.24 Cr       1
3.89 Cr       1
4.99 Cr       1
4.89 Cr       1
3.87 Cr       1
8.9 Cr        1
9.35 Cr       1
10.15 Cr      1
9.45 Cr       1
3.13 Cr       1
1.38 Cr       1
5.7 Cr        1
7.95 Cr       1
1.23 Cr       1
7.48 Cr       1
2.53 Cr       1
2.74 Cr       1
2.91 Cr       1
2.77 Cr       1
3.48 Cr       1
6.98 Cr       1
2.42 Cr       1
1.25 Cr       1
3.81 Cr       1
12.99 Cr      1
1.05 Cr       1
1.22 Cr       1
2.72 Cr       1
1.43 Cr       1
75 Lac        1
3.28 Cr       1
1.73 Cr       1
4.42 Cr       1
3.23 Cr       1
2.33 Cr       1
3.82 Cr       1
80.5 Lac      1
1.96 Cr       1
3.72 Cr       1
3.19 Cr       1
4.01 Cr       1
5.02 Cr       1
Name: count, dtype: int64

In [18]:
df_builder_floor[df_builder_floor['price_in_cr']=='Price on Request']

Empty DataFrame
Columns: [property_id, property_name, link, society, price_in_cr, price_per_sqft, areawithtype, bedrooms, bathrooms, balcony, additional_room, floor_info, facing, property_age, nearby_location, furnishing_details, features]
Index: []

In [19]:
column_cleaning = (

        df_builder_floor
        .assign(
            
        price_in_cr = lambda df_:df_['price_in_cr']
                .str
                .replace('₹','')
                )

        .assign(
                price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                .apply(lambda value: (float(str(value)
                .replace('Cr', '')
                .strip()) if 'Cr' in str(value)
                else float(str(value)
                .replace('Lac', '')
                .strip()) / 100
                ) if value not in ['Price on Request', None, np.nan] else np.nan
                        )
            ),2)
            )
)     

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,"₹14,259 /sqft","2,700 sqft (251 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,"₹17,000 /sqft","2,000 sqft (186 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,"₹13,811 /sqft","2,650 sqft (246 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,"₹19,444 /sqft","2,700 sqft (251 sqm) Carpet Area",4 Bedrooms,5 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,"₹12,500 /sqft","4,000 sqft (372 sqm) Carpet Area",4 Bedrooms,5 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,"₹10,000 /sqft","3,000 sqft (279 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,"₹22,727 /sqft","2,200 sqft (204 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,"₹20,892 /sqft","2,800 sqft (260 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,"₹10,428 /sqft","2,800 sqft (260 sqm) Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,"₹15,932 /sqft","2,385 sqft (222 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

In [20]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
3.50     37
3.00     31
3.25     31
4.00     27
4.25     27
3.30     26
2.90     24
4.50     22
4.10     22
2.70     22
3.40     21
2.60     20
3.75     20
2.65     20
2.85     19
3.20     19
3.10     18
3.80     17
3.15     17
2.50     16
6.50     16
2.95     16
2.80     16
3.90     15
2.75     15
2.30     14
1.65     13
5.50     12
5.00     12
3.60     12
2.45     11
3.70     11
3.65     11
5.25     11
6.00     11
1.62     10
3.85     10
2.55      9
2.40      9
2.00      9
4.20      9
2.99      9
3.35      9
3.95      9
3.05      8
6.25      8
1.35      8
2.20      8
4.75      8
4.40      8
1.64      7
1.70      7
3.45      7
2.25      7
4.35      7
1.60      6
4.65      6
5.80      6
5.75      6
8.00      6
5.90      6
5.85      6
1.75      6
4.15      5
1.95      5
3.49      5
2.35      5
4.85      5
6.10      5
2.15      5
6.30      5
6.75      5
4.95      4
4.70      4
4.80      4
1.90      4
4.45      4
1.58      4
3.55      4
1.63      4
5.95      4
1.99      4
1.30      4
2.05      4
5.45      4
1.55      4
7.00      4
1.59      4
1.40      4
6.20      4
1.33      3
5.65      3
1.50      3
5.10      3
2.62      3
5.30      3
2.96      3
4.55      3
2.61      3
1.32      3
7.25      3
1.45      3
4.49      3
2.51      3
1.18      3
7.50      3
4.21      3
4.30      3
6.80      3
2.69      3
1.68      3
1.56      3
2.68      3
2.66      3
2.56      3
8.50      2
3.99      2
2.54      2
5.20      2
2.18      2
2.92      2
2.22      2
1.29      2
1.85      2
3.39      2
0.75      2
4.60      2
13.50     2
4.90      2
4.11      2
1.20      2
9.00      2
1.71      2
2.49      2
12.00     2
6.15      2
1.46      2
2.52      2
1.15      2
8.75      2
2.16      2
7.30      2
5.35      2
4.05      2
2.89      2
2.71      2
6.19      2
2.98      2
3.62      2
7.45      2
6.40      2
2.79      2
2.19      1
2.21      1
2.64      1
2.29      1
17.75     1
2.67      1
4.31      1
3.29      1
4.71      1
1.28      1
1.00      1
7.15      1
11.01     1
3.91      1
3.18      1
4.33      1
3.66      1
1.92      1
1.81      1
3.88      1
2.78      1
1.39      1
2.43      1
4.19      1
2.58      1
10.90     1
5.29      1
6.70      1
1.93      1
10.85     1
2.09      1
6.74      1
1.10      1
3.14      1
3.58      1
6.49      1
1.82      1
3.02      1
1.51      1
5.89      1
11.00     1
1.74      1
2.10      1
1.97      1
4.28      1
6.90      1
12.85     1
6.65      1
1.57      1
6.39      1
2.11      1
3.98      1
7.49      1
2.34      1
8.30      1
3.69      1
0.95      1
4.62      1
2.04      1
5.34      1
5.40      1
6.60      1
1.41      1
10.00     1
7.10      1
4.29      1
13.95     1
6.45      1
3.12      1
1.48      1
2.48      1
5.55      1
3.24      1
3.89      1
9.45      1
9.35      1
3.13      1
10.15     1
1.34      1
8.90      1
3.87      1
1.23      1
3.44      1
3.33      1
1.98      1
1.42      1
11.50     1
1.36      1
7.95      1
7.48      1
4.99      1
4.89      1
2.74      1
1.38      1
2.53      1
5.70      1
2.91      1
2.77      1
3.48      1
6.98      1
2.42      1
1.25      1
3.81      1
12.99     1
1.05      1
1.22      1
2.72      1
1.43      1
3.28      1
1.73      1
4.42      1
3.23      1
2.33      1
3.82      1
0.80      1
1.96      1
3.72      1
3.19      1
4.01      1
5.02      1
Name: count, dtype: int64

In [21]:
column_cleaning['price_in_cr'].isnull().sum()

np.int64(0)

#### 3. Price_Per_Sqft

In [22]:
column_cleaning['price_per_sqft']

0       ₹14,259 /sqft
1       ₹17,000 /sqft
2       ₹13,811 /sqft
3       ₹19,444 /sqft
4       ₹12,500 /sqft
            ...
1247    ₹10,000 /sqft
1248    ₹22,727 /sqft
1249    ₹20,892 /sqft
1250    ₹10,428 /sqft
1251    ₹15,932 /sqft
Name: price_per_sqft, Length: 1252, dtype: object

In [23]:
column_cleaning = (df_builder_floor
                .assign(
                price_per_sqft = lambda df_:df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()))

In [24]:
column_cleaning['price_per_sqft'].value_counts()

price_per_sqft
13888    13
11111    13
13333    13
12222    11
10000    11
         ..
17473     1
19493     1
13451     1
10689     1
14338     1
Name: count, Length: 874, dtype: int64

In [25]:
column_cleaning = (
    
    df_builder_floor
    
        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr=lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft=lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                )


)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,14259,"2,700 sqft (251 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,17000,"2,000 sqft (186 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,13811,"2,650 sqft (246 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,19444,"2,700 sqft (251 sqm) Carpet Area",4 Bedrooms,5 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,12500,"4,000 sqft (372 sqm) Carpet Area",4 Bedrooms,5 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,10000,"3,000 sqft (279 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,22727,"2,200 sqft (204 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,20892,"2,800 sqft (260 sqm) Carpet Area",4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,10428,"2,800 sqft (260 sqm) Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,15932,"2,385 sqft (222 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

#### 4. Bedroom

In [26]:
column_cleaning['bedrooms'].unique()

array(['4 Bedrooms', '3 Bedrooms', '5 Bedrooms', '2 Bedrooms',
       '9 Bedrooms'], dtype=object)

In [27]:
(column_cleaning['bedrooms']
                .str
                .split(" ")
                .str
                .get(0))

0       4
1       4
2       4
3       4
4       4
       ..
1247    4
1248    4
1249    4
1250    4
1251    4
Name: bedrooms, Length: 1252, dtype: object

In [28]:
column_cleaning = (
    
    df_builder_floor
    
        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                
            ,
            bedrooms = lambda df_:df_['bedrooms']
                                          .str
                                        .split(" ")
                                        .str
                                        .get(0)
                )

)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,14259,"2,700 sqft (251 sqm) Super Built-up Area",4,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,17000,"2,000 sqft (186 sqm) Carpet Area",4,4 Bathrooms,3+ Balconies,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,13811,"2,650 sqft (246 sqm) Super Built-up Area",4,4 Bathrooms,2 Balconies,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,19444,"2,700 sqft (251 sqm) Carpet Area",4,5 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,12500,"4,000 sqft (372 sqm) Carpet Area",4,5 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,10000,"3,000 sqft (279 sqm) Super Built-up Area",4,4 Bathrooms,2 Balconies,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,22727,"2,200 sqft (204 sqm) Carpet Area",4,4 Bathrooms,3 Balconies,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,20892,"2,800 sqft (260 sqm) Carpet Area",4,4 Bathrooms,3+ Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,10428,"2,800 sqft (260 sqm) Built-up Area",4,4 Bathrooms,2 Balconies,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,15932,"2,385 sqft (222 sqm) Super Built-up Area",4,4 Bathrooms,3 Balconies,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

In [29]:
column_cleaning['bedrooms'].isnull().sum()

np.int64(0)

#### 5. Bathroom

In [30]:
column_cleaning['bathrooms'].unique()

array(['4 Bathrooms', '5 Bathrooms', '3 Bathrooms', '2 Bathrooms',
       '6 Bathrooms', '9 Bathrooms', '7 Bathrooms'], dtype=object)

In [31]:
(column_cleaning['bathrooms']
            .str
            .split(" ")
            .str
            .get(0)
)

0       4
1       4
2       4
3       5
4       5
       ..
1247    4
1248    4
1249    4
1250    4
1251    4
Name: bathrooms, Length: 1252, dtype: object

In [32]:
column_cleaning = (
    
    df_builder_floor
    
        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                
            ,
            bedrooms = lambda df_:df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            bathrooms = lambda df_:df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                )
)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,14259,"2,700 sqft (251 sqm) Super Built-up Area",4,4,2 Balconies,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,17000,"2,000 sqft (186 sqm) Carpet Area",4,4,3+ Balconies,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,13811,"2,650 sqft (246 sqm) Super Built-up Area",4,4,2 Balconies,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,19444,"2,700 sqft (251 sqm) Carpet Area",4,5,3 Balconies,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,12500,"4,000 sqft (372 sqm) Carpet Area",4,5,2 Balconies,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,10000,"3,000 sqft (279 sqm) Super Built-up Area",4,4,2 Balconies,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,22727,"2,200 sqft (204 sqm) Carpet Area",4,4,3 Balconies,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,20892,"2,800 sqft (260 sqm) Carpet Area",4,4,3+ Balconies,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,10428,"2,800 sqft (260 sqm) Built-up Area",4,4,2 Balconies,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,15932,"2,385 sqft (222 sqm) Super Built-up Area",4,4,3 Balconies,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

#### 5. Balcony

In [33]:
column_cleaning['balcony'].unique()

array(['2 Balconies', '3+ Balconies', '3 Balconies', '1 Balcony',
       'No Balcony'], dtype=object)

In [34]:
(column_cleaning['balcony']
            .str
            .split(" ")
            .str
            .get(0)
            .replace("No",0))

0        2
1       3+
2        2
3        3
4        2
        ..
1247     2
1248     3
1249    3+
1250     2
1251     3
Name: balcony, Length: 1252, dtype: object

In [35]:
column_cleaning = (
    
    df_builder_floor
    
        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                
            ,
            bedrooms = lambda df_:df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            bathrooms = lambda df_:df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            balcony = lambda df_:df_['balcony']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                                        .replace("No",0)
                
                
                )
)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,14259,"2,700 sqft (251 sqm) Super Built-up Area",4,4,2,Servant Room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,17000,"2,000 sqft (186 sqm) Carpet Area",4,4,3+,NaN,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,13811,"2,650 sqft (246 sqm) Super Built-up Area",4,4,2,Study Room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,19444,"2,700 sqft (251 sqm) Carpet Area",4,5,3,"Pooja Room,Study Room,Servant Room,Others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,12500,"4,000 sqft (372 sqm) Carpet Area",4,5,2,"Pooja Room,Study Room,Servant Room,Others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,10000,"3,000 sqft (279 sqm) Super Built-up Area",4,4,2,Servant Room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,22727,"2,200 sqft (204 sqm) Carpet Area",4,4,3,Servant Room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,20892,"2,800 sqft (260 sqm) Carpet Area",4,4,3+,Servant Room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,10428,"2,800 sqft (260 sqm) Built-up Area",4,4,2,Servant Room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,15932,"2,385 sqft (222 sqm) Super Built-up Area",4,4,3,Servant Room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

#### 6. AdditionalRoom

In [36]:
(column_cleaning['additional_room']
            .fillna('not available')
            .str
            .lower())

0                                    servant room
1                                   not available
2                                      study room
3       pooja room,study room,servant room,others
4       pooja room,study room,servant room,others
                          ...
1247                                 servant room
1248                                 servant room
1249                                 servant room
1250                                 servant room
1251                                 servant room
Name: additional_room, Length: 1252, dtype: object

In [37]:
column_cleaning = (
    
    df_builder_floor
    
        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                
            ,
            bedrooms = lambda df_:df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            bathrooms = lambda df_:df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            balcony = lambda df_:df_['balcony']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                                        .replace("No",0)
            ,
            additional_room = lambda df_: df_['additional_room']
                                        .fillna('not available')
                                        .str
                                        .lower()
                
                
                )
)

column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,14259,"2,700 sqft (251 sqm) Super Built-up Area",4,4,2,servant room,2nd of 4 Floors,North-East,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,17000,"2,000 sqft (186 sqm) Carpet Area",4,4,3+,not available,1st of 4 Floors,North-East,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,13811,"2,650 sqft (246 sqm) Super Built-up Area",4,4,2,study room,1st of 4 Floors,East,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,19444,"2,700 sqft (251 sqm) Carpet Area",4,5,3,"pooja room,study room,servant room,others",2nd of 4 Floors,East,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,12500,"4,000 sqft (372 sqm) Carpet Area",4,5,2,"pooja room,study room,servant room,others",3rd of 4 Floors,East,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,10000,"3,000 sqft (279 sqm) Super Built-up Area",4,4,2,servant room,1st of 4 Floors,North-East,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,22727,"2,200 sqft (204 sqm) Carpet Area",4,4,3,servant room,Ground of 4 Floors,West,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,20892,"2,800 sqft (260 sqm) Carpet Area",4,4,3+,servant room,2nd of 4 Floors,East,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,10428,"2,800 sqft (260 sqm) Built-up Area",4,4,2,servant room,2nd of 4 Floors,North,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,15932,"2,385 sqft (222 sqm) Super Built-up Area",4,4,3,servant room,4th of 4 Floors,North-East,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

In [38]:
column_cleaning['additional_room'].isnull().sum()

np.int64(0)

### 7. Facing

In [39]:
column_cleaning['facing']

0       North-East
1       North-East
2             East
3             East
4             East
           ...
1247    North-East
1248          West
1249          East
1250         North
1251    North-East
Name: facing, Length: 1252, dtype: object

In [40]:
column_cleaning['facing'].value_counts()

facing
East          401
North-East    303
North         179
West          115
North-West     65
South-East     52
South          46
South-West     24
Name: count, dtype: int64

In [41]:
column_cleaning['facing'].isnull().sum()

np.int64(67)

In [42]:
(column_cleaning['facing']
                                .fillna("Not Available")
                                .str
                                .lower())

0       north-east
1       north-east
2             east
3             east
4             east
           ...
1247    north-east
1248          west
1249          east
1250         north
1251    north-east
Name: facing, Length: 1252, dtype: object

In [43]:
column_cleaning = (
    
    df_builder_floor
    
        .assign(
            price_in_cr = lambda df_: df_['price_in_cr']
                                        .str
                                        .replace('₹', '', regex=False)
                )

      
        .assign(
            price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
                                        .apply(lambda value: (float(str(value)
                                        .replace('Cr', '')
                                        .strip())
                                        if 'Cr' in str(value)
                                        else float(str(value)
                                        .replace('Lac', '')
                                        .strip()) / 100)
                                        if value not in ['Price on Request', None, np.nan] 
                                        else np.nan)),2)
                )

     
        .assign(
            price_per_sqft = lambda df_: pd.to_numeric(df_['price_per_sqft']
                                        .astype(str)
                                        .str
                                        .split("₹")
                                        .str
                                        .get(1)
                                        .str
                                        .replace("/sqft", "", regex=False)
                                        .str
                                        .replace(",", "", regex=False)
                                        .str
                                        .strip())
                
            ,
            bedrooms = lambda df_:df_['bedrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            bathrooms = lambda df_:df_['bathrooms']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
            ,
            balcony = lambda df_:df_['balcony']
                                        .str
                                        .split(" ")
                                        .str
                                        .get(0)
                                        .replace("No",0)
            ,
            additional_room = lambda df_: df_['additional_room']
                                        .fillna('not available')
                                        .str
                                        .lower()
            ,
            facing = lambda df_:df_['facing']
                                        .fillna("not available")
                                        .str
                                        .lower()
            )

)


column_cleaning

,property_id,property_name,link,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,O85021804,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Brand New Builder Floor,3.85,14259,"2,700 sqft (251 sqm) Super Built-up Area",4,4,2,servant room,2nd of 4 Floors,north-east,0 to 1 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
1,V85303340,"4 BHK Independent Builder Floor in Sector 102,...",https://www.99acres.com/4-bhk-bedroom-independ...,BPTP Amstoria,3.40,17000,"2,000 sqft (186 sqm) Carpet Area",4,4,3+,not available,1st of 4 Floors,north-east,1 to 5 Year Old,"['Conscient One Mall', ""Domino's Pizza"", 'Daul...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
2,O83672012,4 BHK Independent Builder Floor in A Block Sus...,https://www.99acres.com/4-bhk-bedroom-independ...,"A Block Sushant Lok Phase 1, Gurgaon",3.66,13811,"2,650 sqft (246 sqm) Super Built-up Area",4,4,2,study room,1st of 4 Floors,east,1 to 5 Year Old,"['Bahrisons library', 'Hanuman Mandir', 'New L...","['3 Fan', '1 Fridge', '5 Geyser', '1 Stove', '...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3,K85623978,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,"DLF Phase 2, Gurgaon",5.25,19444,"2,700 sqft (251 sqm) Carpet Area",4,5,3,"pooja room,study room,servant room,others",2nd of 4 Floors,east,1 to 5 Year Old,"['Gurgaon Central Mall', 'Hanuman Mandir', 'PV...","['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
4,E85624224,4 BHK Independent Builder Floor in DLF Phase 2...,https://www.99acres.com/4-bhk-bedroom-independ...,PARK FACING FLOOR,5.00,12500,"4,000 sqft (372 sqm) Carpet Area",4,5,2,"pooja room,study room,servant room,others",3rd of 4 Floors,east,0 to 1 Year Old,"['Gurgaon Central Mall', 'PVR Cinames', 'Priva...","['11 Wardrobe', '13 Fan', '1 Exhaust Fan', '8 ...","['Feng Shui / Vaastu Compliant', 'Water purifi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,G78860067,"4 BHK Independent Builder Floor in Sector 46, ...",https://www.99acres.com/4-bhk-bedroom-independ...,Private Builder Floor,3.00,10000,"3,000 sqft (279 sqm) Super Built-up Area",4,4,2,servant room,1st of 4 Floors,north-east,0 to 1 Year Old,"['Dr. Aruna Kalra', 'Raheja Mall', 'Delhi Publ...","['8 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Water purifier', 'Security / Fire Alarm', 'F..."
1248,S85218742,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,5.00,22727,"2,200 sqft (204 sqm) Carpet Area",4,4,3,servant room,Ground of 4 Floors,west,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Micr...","['Security / Fire Alarm', 'Intercom Facility',..."
1249,R85216914,4 BHK Independent Builder Floor in Sushant Lok...,https://www.99acres.com/4-bhk-bedroom-independ...,"Sushant Lok Phase 1, Gurgaon",5.85,20892,"2,800 sqft (260 sqm) Carpet Area",4,4,3+,servant room,2nd of 4 Floors,east,0 to 1 Year Old,"['Kotak mahindra bank ATM', 'CCD', 'Belgian Wa...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Security / Fire Alarm', 'Intercom Facility',..."
1250,B84531164,"4 BHK Independent Builder Floor in Sector 84, ...",https://www.99acres.com/4-bhk-bedroom-independ...,SS Linden Floors,2.92,10428,"2,800 sqft (260 sqm) Built-up Area",4,4,2,servant room,2nd of 4 Floors,north,0 to 1 Year Old,"['Agri Business Management Collage', 'Manesar ...","['4 Wardrobe', '4 Geyser', '6 AC', '1 Modular ...","['Water purifier', 'Centrally Air Conditioned'..."
1251,F84618392,"4 BHK Independent Builder Floor in Sector 63A,...",https://www.99acres.com/4-bhk-bedroom-independ...,Anant Raj Estates,3.80,15932,"2,385 sqft (222 sqm) Super Built-up Area",4,4,3,servant room,4th of 4 Floors,north-east,0 to 1 Year Old,"['De Adventure Park', 'Vatika Business Centre'...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Private Garden / Te..."

In [44]:
column_cleaning.isnull().sum()

property_id            0
property_name          0
link                   0
society                0
price_in_cr            0
price_per_sqft         0
areawithtype           0
bedrooms               0
bathrooms              0
balcony                0
additional_room        0
floor_info             0
facing                 0
property_age           1
nearby_location        0
furnishing_details    72
features              38
dtype: int64