In [20]:
import pandas as pd
import numpy as np
import os
import json
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

### 1. Independent House Data Loading

In [21]:
df_house = pd.read_csv('../../data/web_scraping/independent_house_gurgaon.csv')
df_house.sample(15)

,property_name,link,society,price,area,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
919,"3 Bedroom House for sale in Sector 47, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,4 Cr,₹4 L /sqyd,900 sqft Super Area,NaN,400000.0,3,3,4.0,"Sector 47, Gurgaon",NaN,North-East,Others,2,NaN,Unfurnished,"{""O"":1,""C"":1}","['Raheja Mall', 'Standard chartered ATM', 'Ici...",100sqyd independent-House available for sale \...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.426613,77.054558,L91436726
25,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,International City by Sobha Phase 1,10.98 Cr,"₹34,887 /sqft",3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,X91215798
681,22 Bedroom House for sale in Sushant Lok Phase...,https://www.99acres.com/22-bhk-bedroom-indepen...,NaN,7.5 Cr,₹6.25 L /sqyd,1080 sqft Super Area,NaN,625000.0,22,22,4.0,"Sushant Lok Phase 1, Gurgaon",NaN,North-East,Main Road,6,NaN,Furnished,"[""N""]","['Huda city centre metro station', 'New Life C...",This 22 bhk house for sale in sushant lok phas...,"['Private Garden / Terrace', 'Park']",28.457243,77.078253,H90655172
1493,"4 Bedroom House for sale in Rosewood City, Gur...",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,3.5 Cr,₹5 L /sqyd,630 sqft Super Area,NaN,500000.0,4,4,2.0,"Rosewood City, Gurgaon",NaN,East,Others,1,NaN,Furnished,"{""O"":2,""C"":2}","['Sri Radhe Krishna Temple', 'Standard charter...",Planning to buy an individual house in gurgaon...,NaN,28.409021,77.054554,B90080762
716,"3 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Vatika India Next,5.5 Cr,₹2.29 L /sqyd,2160 sqft Super Area,NaN,229167.0,3,3,2.0,"Sector 82, Gurgaon",NaN,North-East,"Park/Garden, Pool, Club, Main Road, Others",2,Y,Unfurnished,"{""O"":2}","['Sapphire 83 Mall', 'Dwarka expressway', 'Del...",Vatika signature villas luxury living in secto...,none,28.395781,76.956044,Q90989954
1728,"4 Bedroom House for sale in DLF Phase 5, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,DLF The Grove,6.45 Cr,₹2.39 L /sqyd,2430 sqft Super Area,NaN,238889.0,4,4,2.0,"DLF Phase 5, Gurgaon",NaN,North,"Pool, Park/Garden",6,NaN,Unfurnished,"{""O"":1,""C"":2}","['Central Plaza Mall', 'Sector 53-54', 'Suncit...",Located in the heart of gurgaon phase 5 golf c...,NaN,28.444722,77.104646,H91527578
1749,"3 Bedroom House for sale in Sector 93, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Signature Global City 93,1.86 Cr,₹1.39 L /sqyd,1200 sqft Super Area,NaN,139128.0,3,3,3.0,"Sector 93, Gurgaon",NaN,0,NaN,6,NaN,Unfurnished,"{""C"":1}","['Pataudi Road', 'Holiday Inn Gurugram Sector ...",Are you planning to buy your dream home? You c...,NaN,28.410299,76.927691,T90257742
2026,"2 Bedroom House for sale in Arjun Nagar, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,NaN,46 Lac,"₹12,778 /sqft",360 sqft Carpet Area,360.0,12778.0,2,2,1.0,"Arjun Nagar, Gurgaon",NaN,0,NaN,1,NaN,Semi-Furnished,NaN,NaN,"This 2 bhk house for sale in arjun nagar, a we...",NaN,0.000000,0.000000,L89543060
9,"7 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,International City by SOBHA Phase 2,20.9 Cr,₹4.18 L /sqyd,4500 sqft Super Area,NaN,418000.0,7,6,4.0,"Sector 109, Gurgaon",NaN,North,Others,1,NaN,Semi-Furnished,"{""O"":2,""C"":2}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",This 7 bhk house for sale in sector 109 gurgao...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.516717,76.996553,W90519296
544,"6 Bedroom House for sale in Sector 4, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,NaN,5.5 Cr,₹1.88 L /sqyd,2628 sqft Super Area,NaN,188356.0,6,4,3.0,"Sector 4, Gurgaon",NaN,North,NaN,3,Y,Unfurnished,"{""O"":2,""C"":2}","['Chintapurni Mandir', 'State bank ATM', 'Kr D...",Prime single storey house | 292 sq. Yards | se...,"['False Ceiling Lighting', 'Water Storage', 'V...",28.473969,77.008314,A89635598
1136,"3 Bedroom House for sale in Jyoti Park, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,1.1 Cr,₹1.75 L /sqyd,567 sqft Super Area,NaN,174603.0,3,3,1.0,"Jyoti Park, Gurgaon",NaN,South,NaN,1,NaN,Unfurnished,"{""O"":1,""C"":1}","['State bank ATM', 'Dr. Madan Clinic', 'Shiv M...",Wishing to settle down in an individual house ...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.461194,77.012117,F91033460
374,"3 Bedroom House for sale in Nirvana Country, G...",https://www.99acres.com/3-bhk-bedroom-independ...,Unitech Deerwood Chase,9.8 Cr,₹4.08 L /sqyd,2160 sqft Super Area,NaN,408333.0,3,2,2.0,"Nirvana Country, Gurgaon",NaN,South,Others,3,NaN,Unfurnished,"{""O"":3}","['Sector 55-56 Metro Station', 'Raheja Mall', ...",Simplex villa available for sale in nirvana co...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.415354,77.062557,A89641564
1657,"3 Bedroom House for sale in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,Smart World Gems,1.62 Cr,"₹10,843 /sqft",1494 sqft Carpet Area,1494.0,10843.0,3,3,2.0,"Sector 89, Gurgaon",NaN,North-East,"Main Road, Club",6,Y,Semi-Furnished,"{""O"":1,""C"":1}","['Dwarka Expressway', 'Genesis Hospital Sector...",The best project smart jems sector 89 \nVery n...,NaN,28.421303,76.950062,P90684810
1639,"3 Bedroom House for sale in Sector 51, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,M2K Symphony Floors,2.25 Cr,NaN,2250 sqft Super Area,1350.0,NaN,3,2,2.0,"Sector 51, Gurgaon",NaN,North,"Park/Garden, Main Road",2,NaN,Furnished,"{""C"":1}","['Radhakrishna Shani Mandir', 'Axis bank ATM',...",This 3 bhk independent villa in m2k symphony f...,NaN,28.431970,77.066282,O91128550
835,"3 Bedroom House for sale in Sector 40, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,8 Cr,₹3.04 L /sqyd,2367 sqft Super Area,NaN,304183.0,3,3,2.0,"Sector 40, Gurgaon",NaN,South,NaN,3,Y,0,"{""O"":1}","['Huda city centre metro station', 'Axis bank ...",263 sq. Yd. Independent house available for sa...,['Water Storage'],28.448901,77.057885,H90472012

In [22]:
df_house.shape

(2054, 25)

In [23]:
df_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2054 entries, 0 to 2053
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2054 non-null   object
 1   link             2054 non-null   object
 2   society          1038 non-null   object
 3   price            2054 non-null   object
 4   area             2039 non-null   object
 5   areaWithType     2054 non-null   object
 6   carpetArea       398 non-null    float64
 7   pricePerSqft     2039 non-null   float64
 8   bedRoom          2054 non-null   int64
 9   bathroom         2054 non-null   int64
 10  balcony          2015 non-null   float64
 11  address          2054 non-null   object
 12  floorNum         0 non-null      float64
 13  facing           2054 non-null   object
 14  overlooking      1521 non-null   object
 15  agePossession    2054 non-null   int64
 16  cornerProperty   543 non-null    object
 17  furnishing       2054 non-null   object
 18  parking          2013 non-null   object
 19  nearbyLocations  1992 non-null   object
 20  description      2054 non-null   object
 21  features         1455 non-null   object
 22  latitude         2054 non-null   float64
 23  longitude        2054 non-null   float64
 24  property_id      2054 non-null   object
dtypes: float64(6), int64(3), object(16)
memory usage: 401.3+ KB

In [24]:
df_house.describe(include='all')

,property_name,link,society,price,area,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
count,2054,2054,1038,2054,2039,2054,398.000000,2.039000e+03,2054.000000,2054.000000,2015.000000,2054,0.0,2054,1521,2054.000000,543,2054,2013,1992,2054,1455,2054.000000,2054.000000,2054
unique,768,2054,325,463,758,520,NaN,NaN,NaN,NaN,NaN,199,NaN,9,156,NaN,1,4,80,387,1921,558,NaN,NaN,2054
top,"5 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,International City by Sobha Phase 1,5.5 Cr,₹4 L /sqyd,900 sqft Super Area,NaN,NaN,NaN,NaN,NaN,"Sector 109, Gurgaon",NaN,North-East,Main Road,NaN,Y,Unfurnished,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","Thoughtfully planned with spacious rooms, good...",none,NaN,NaN,L87277236
freq,50,1,53,42,26,112,NaN,NaN,NaN,NaN,NaN,110,NaN,501,369,NaN,543,1233,269,53,10,431,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,2624.764724,3.638398e+05,5.587634,5.483447,3.015881,NaN,NaN,NaN,NaN,2.592502,NaN,NaN,NaN,NaN,NaN,NaN,29.524253,75.400960,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,2556.958847,5.127709e+05,4.470596,4.543610,1.130399,NaN,NaN,NaN,NaN,1.747300,NaN,NaN,NaN,NaN,NaN,NaN,7.931046,9.427081,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,10.110000,0.000000e+00,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,450.000000,1.543560e+05,3.000000,3.000000,2.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.420689,77.009667,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1615.000000,2.900000e+05,5.000000,4.000000,3.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.450259,77.051970,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,4200.000000,4.000000e+05,6.000000,6.000000,4.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.477940,77.076593,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,12000.000000,7.500000e+06,99.000000,99.000000,4.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,77.057310,77.228165,NaN

In [25]:
df_house.drop(columns=['property_name', 'society','price','area'])

,link,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,https://www.99acres.com/5-bhk-bedroom-independ...,3600 sqft Super Area,NaN,362500.0,5,7,4.0,"Sector 109, Gurgaon",NaN,North,"Pool, Park/Garden, Club, Main Road",1,Y,Semi-Furnished,"{""O"":1,""C"":3}","['Palam Vihar Vyapar kendra', 'Kalyan Hospital...",Check out this 5 bhk house for sale in sector ...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.513497,77.004111,L87277236
1,https://www.99acres.com/4-bhk-bedroom-independ...,5400 sqft Super Area,5175.0,140000.0,4,4,4.0,"Sector 109, Gurgaon",NaN,North-East,"Main Road, Others, Club, Park/Garden, Pool",1,Y,Unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city is a premium luxury v...,"['Centrally Air Conditioned', 'Security / Fire...",28.515220,76.997752,U90119426
2,https://www.99acres.com/4-bhk-bedroom-independ...,5400 sqft Super Area,NaN,172500.0,4,4,3.0,"Sector 109, Gurgaon",NaN,East,"Pool, Park/Garden, Club, Main Road, Others",1,NaN,Unfurnished,"{""O"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city | ready to move\n 4bh...,"['Security / Fire Alarm', 'Vaastu Compliant', ...",28.509743,77.005068,M77295073
3,https://www.99acres.com/6-bhk-bedroom-independ...,4500 sqft Super Area,490.0,410000.0,6,6,4.0,"Sector 109, Gurgaon",NaN,North-East,"Others, Main Road, Club, Park/Garden, Pool",1,Y,Unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city is a premium luxury v...,"['Centrally Air Conditioned', 'Security / Fire...",28.514088,77.003366,B90120220
4,https://www.99acres.com/4-bhk-bedroom-independ...,2430 sqft Super Area,180.0,370370.0,4,4,2.0,"Sector 109, Gurgaon",NaN,North,Main Road,1,NaN,Unfurnished,"{""O"":2}","['The Shikshiyan School', 'Dharampeth Main Roa...",The flat is over 270 sq.Yd. Super built up are...,"['Private Garden / Terrace', 'High Ceiling Hei...",28.511604,77.007325,T90277756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,https://www.99acres.com/5-bhk-bedroom-independ...,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,H91668606
2050,https://www.99acres.com/5-bhk-bedroom-independ...,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,U91247428
2051,https://www.99acres.com/5-bhk-bedroom-independ...,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,Z91333184
2052,https://www.99acres.com/5-bhk-bedroom-independ...,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,A90966806
2053,https://www.99acres.com/6-bhk-bedroom-independ...,1449 sqft Super Area,120.0,316770.0,6,6,4.0,"Ardee City, Gurgaon",NaN,North-West,Main Road,2,NaN,Unfurnished,"{""O"":3,""C"":1}","['Huda city centre metro station', 'Hanuman Ma...",A ready to move house is available for sale. 2...,NaN,28.442230,77.078030,K91666140

### 2. Independent House Data Cleaning

In [26]:
df_house.columns

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'carpetArea', 'pricePerSqft', 'bedRoom', 'bathroom', 'balcony',
       'address', 'floorNum', 'facing', 'overlooking', 'agePossession',
       'cornerProperty', 'furnishing', 'parking', 'nearbyLocations',
       'description', 'features', 'latitude', 'longitude', 'property_id'],
      dtype='object')

In [27]:
df_house.isnull().sum()

property_name         0
link                  0
society            1016
price                 0
area                 15
areaWithType          0
carpetArea         1656
pricePerSqft         15
bedRoom               0
bathroom              0
balcony              39
address               0
floorNum           2054
facing                0
overlooking         533
agePossession         0
cornerProperty     1511
furnishing            0
parking              41
nearbyLocations      62
description           0
features            599
latitude              0
longitude             0
property_id           0
dtype: int64

In [28]:
missing_summary = (
    df_house
    .isnull()
    .sum()
    .pipe(lambda s: round((s / len(df_house)) * 100, 2))
    .reset_index()
    .rename(columns={'index': 'Feature', 0: 'Missing_Percentage'})
    .sort_values(by='Missing_Percentage', ascending=False)
)
missing_summary

            Feature  Missing_Percentage
12         floorNum              100.00
6        carpetArea               80.62
16   cornerProperty               73.56
2           society               49.46
21         features               29.16
14      overlooking               25.95
19  nearbyLocations                3.02
18          parking                2.00
10          balcony                1.90
7      pricePerSqft                0.73
4              area                0.73
8           bedRoom                0.00
3             price                0.00
0     property_name                0.00
5      areaWithType                0.00
1              link                0.00
11          address                0.00
15    agePossession                0.00
13           facing                0.00
9          bathroom                0.00
17       furnishing                0.00
20      description                0.00
22         latitude                0.00
23        longitude                0.00
24      property_id                0.00

In [29]:
df_house.shape

(2054, 25)

### 3. Cleaning Individual Columns

#### 1. Society

In [30]:
df_house['society'].value_counts()

society
International City by Sobha Phase 1                  53
Emaar MGF Marbella                                   49
International City by SOBHA Phase 2                  40
Unitech Uniworld Resorts                             34
Vipul Tatvam Villa                                   27
Ansals Palam Vihar                                   26
Vatika Signature Villas                              25
Tata Primanti                                        18
Eldeco Mansionz                                      15
Sobha International City Phase 3                     14
Unitech Deerwood Chase                               13
DLF City Plots                                       13
Vipul World                                          13
DLF City Plots Phase 2                               13
Ansal                                                12
Unitech Espace                                       11
Eros Rosewood City                                   11
Emaar MGF The Vilas                                  11
Bptp Visionnaire                                     11
SS Aaron Ville                                       10
Vatika Emilia Floors                                 10
Unitech Nirvana Country 2                            10
Ansal Plaza                                          10
Malibu Towne                                         10
Bestech Park View Ananda                              9
DLF Gardencity Enclave                                9
Signature Global City 92                              8
Ansal Sushant Lok 2                                   8
Assotech Blith                                        8
Independent Villa                                     7
Signature Global City 79B                             7
Unitech Alder Grove                                   7
Experion Windchants                                   7
Huda Sector 46                                        7
Uppal Southend                                        7
BPTP Amstoria                                         7
Sushant Lok 1 Builder Floors                          6
Huda Flats                                            6
Emaar Emerald Hills                                   6
Trehan Luxury Floors 71                               6
Vatika India Next                                     6
M3M Soulitude                                         6
Emaar The Palm Springs                                6
BPTP Astaire Gardens                                  5
Ansal Sushant Lok Plots                               5
RWA Sector 46                                         5
Cyber City                                            4
DLF Luxury Builder Floors                             4
Sector 47                                             4
Unitech Vista Villas                                  4
SS Linden Floors                                      4
Smart World Gems                                      4
Spacious Villa                                        4
Mayfield Gardens                                      4
Anant Raj                                             4
Ansal Heights                                         4
Satya The Legend                                      4
Central Park Flower Valley Fleur Villas               4
Central Park Flower Valley                            4
All Punjabi Welfare Association                       4
The Laburnum                                          4
Mapsko Casa Bella                                     4
Signature Global City 81                              4
DLF City Plots Phase 3                                4
Puri Diplomatic Greens                                3
Shyam Kunj                                            3
Ansals Florence Marvel                                3
Kashish Manor One                                     3
Unitech Escape                                        3
Suncity Township                                      3
M3M Antalya Hills                                     3
Spacious Villa                                        3
Eros Rosewood Villas                                  3
Ultra Luxury Builder Floor                            3
Vatika Iris Floors                                    3
Luxury Villa                                          3
MRS 16 Acres                                          3
Unitech Espace Premiere Villas                        3
Nitara One Good Earth                                 3
Sector 57                                             3
Independent Villa                                     3
DLF Floors Phase 3                                    3
DLF City Independent Floors Phase 1 and 2             3
Ardee City                                            3
SS Almeria                                            3
sector 40                                             3
Unitech Greenwood City                                3
ATS Triumph                                           3
Block C                                               3
Unitech South City 2                                  3
Villa in DLF                                          3
Spacious Layout Villa                                 3
NORTH EAST FACING                                     2
Sector 23A                                            2
Progressive RWA                                       2
Godrej Summit                                         2
Sector 21 RWA                                         2
Huda Staff Colony                                     2
sector 45                                             2
Vatika Primrose Floors                                2
Vatika Independent Floors                             2
Huda Sector 47                                        2
DLF Pink Town House                                   2
HUDA                                                  2
South City 1                                          2
National Media Centre                                 2
Garden Villas                                         2
VILLA IN SUNCITY                                      2
Villa in Suncity                                      2
huda                                                  2
Vatika India Next Plots                               2
Sobha International City Phase 4                      2
Ansal Homes                                           2
DLF The Grove                                         2
Urban Estate Residents Welfare Association            2
DLF Phase 1 Ultra Luxury Builder Floors               2
Ultra-Luxury Villa                                    2
Signature Global City 93                              2
Sector 14 RWA                                         2
Vatika City Homes                                     2
DLF                                                   2
Ansal API Spanish Court                               2
Unitech Nirvana Birch Court                           2
Palam Vihar Society                                   2
Celebrity Homes                                       2
Ready To Move Villa                                   2
Birla Navya                                           2
Housing Board Colony                                  2
Villa in SL1                                          2
Shanti Kunj                                           2
Godrej Nature Plus                                    2
Signature Global Park                                 2
Lion Infra Green Valley                               2
Bestech Park View Grand Spa                           2
Ansal Housing                                         1
Himalayan Society                                     1
country club Manesar                                  1
HUDA HSVP SECTOR 21                                   1
individual house sector 21                            1
House No 140                                          1
Central Park                                          1
Gupta house, 98/5 , Jacumpura, Gurgaon                1
shiv colony bhondsi                                   1
Pareena Mi Casa                                       1
shri ram enclave maruti kunj                          1
Sector 45                                             1
Sector 45                                             1
Indivisual Floors                                     1
Sector 40                                             1
Greenwood City                                        1
HUDA Sector 40                                        1
Malibu town                                           1
maruti                                                1
society                                               1
RWA Sector 47 Gurgaon                                 1
Sector47                                              1
HUDA  BUIL-TUP HOUSE                                  1
Independent Floor at DLF City                         1
V BLOCK                                               1
60 SQ RD PLOT SIZE                                    1
Villa in DLF 3                                        1
sector - 40                                           1
indipendent House, sector 40                          1
50 Gaj 2 floor new house                              1
Ultra Luxury Kothi                                    1
Ambience Lagoon                                       1
Independent house todapur                             1
Duplex Villa in DLF 3                                 1
DLF, Beautiful Duplex House Design                    1
builder house sec 52                                  1
Sector 52                                             1
RWA Sector 52                                         1
Huda Housing Board Society                            1
AT                                                    1
NOTYH EAST FACING                                     1
INDEPENDENT HOUSE FLOOR DLF PHASE 2 GURGAON           1
Villa in DLF 2                                        1
Sector 46                                             1
Rosewood City                                         1
ultra Luxury builder floor sector 46                  1
North east facing                                     1
ganpati enclave                                       1
Jat colony Sector 6                                   1
Antriksh Heights                                      1
M3M The Marina                                        1
Dlf 3 Apartment                                       1
Villa in DLF Phase 2                                  1
HSVP/HUDA                                             1
SS Southend                                           1
Housing Board Haryana                                 1
Vipul World Floors                                    1
Block A Palam Vihar                                   1
g block palam vihar                                   1
Unitech Fresco                                        1
Villa in DLF phase 2                                  1
Villa in DLF 2                                        1
DLF Phase 2                                           1
Sector 31                                             1
Sun City                                              1
House No. 557                                         1
Raheja Atlantis                                       1
SECTOR 9A                                             1
Ravi Nager basai road                                 1
diwan enclave rithoj road bhondsi                     1
Vimal Enclave, nirmal darbar                          1
gdge                                                  1
Chawla DS Residency                                   1
devnagar part 2 55 feet road                          1
sector 39                                             1
Green Meadows                                         1
Luxury Villa                                          1
INDEPENDENT VILLA                                     1
DLF Phase 4 Luxury Builder Floors                     1
Ardee Palm Grove Villas                               1
Green Meadows                                         1
VIlla in DLF 4                                        1
VILLA IN DLF 4                                        1
DLF Hibiscus Lane                                     1
DLF Phase 4 luxury kothi                              1
DLF City Plots Phase 4                                1
DLF Ridgewood Estate                                  1
Friends colony sohna                                  1
Signature Global Daxin Vistas                         1
Central Park Flower Valley Cerise Floors              1
IRWO Rail Vihar                                       1
ASET Sohna Greens                                     1
ansal                                                 1
Sushant Lok 1                                         1
Surya CGHS                                            1
Whispering Meadows                                    1
B Block                                               1
Ireo Project                                          1
Paras Ekam Homes                                      1
vatika westi resort farm house                        1
Ganga Tathastu                                        1
Ward no 6                                             1
Boutique Villa                                        1
independent building                                  1
Good Block                                            1
South City1                                           1
Budget friendly Villa                                 1
Unitech Palms South City 1                            1
Lal kuan                                              1
Central Park Flower Valley Flamingo Floors            1
Budget Friendly Villa                                 1
Ansal buildup                                         1
builder floors                                        1
SECTOR 57                                             1
Independent House                                     1
DESIGNER FLOORWISE FULL BUILDING                      1
Independent Kothi In SL1                              1
N A                                                   1
DESIGNER FLOORWISE                                    1
18 Mtr wide road                                      1
Sushant lok 1 kothi ,sushant lok 1                    1
Villa in Sushant Lok                                  1
Independent villa                                     1
luxury kothi sushant lok1                             1
Sushant Lok1                                          1
ansal villa                                           1
Block - C2                                            1
Sector 38 RWA                                         1
Rodeo Drive                                           1
Fresco Tower                                          1
Q1 Block                                              1
Eros City Square                                      1
sector 49 rosewood                                    1
Villa in South City                                   1
Unitech Singleton Floors                              1
Q block                                               1
South City 2                                          1
South city 2                                          1
Q1 Block South City 2                                 1
Villa in Rosewood city                                1
Niho Scottish Castle 2                                1
Luxury Builder floor In South City 2                  1
Ready to Move Villa                                   1
sushant lok 2                                         1
Kadipur Residential Colony                            1
Rajendra park sec 105                                 1
Sector 105                                            1
GLS Avenue 51                                         1
M2K Symphony Floors                                   1
MGF The Vilas                                         1
Mahalaxmi Garden, Street no 5                         1
Sagar Enclave                                         1
mayfield garden n block                               1
Orchid Island                                         1
Sector 38                                             1
Kendriya Vihar                                        1
sector 38                                             1
Sector51                                              1
Sector 51                                             1
DLF 1                                                 1
dlf phase 1                                           1
Luxurious Kothi in DLF                                1
Independent Floors at DLF City Phase 1                1
Woodstock Floors                                      1
Unitech Nirvana country                               1
Nirvana Villa, Sector 50, Gurgaon                     1
Unitech Aspen Greens                                  1
A block palam vihar                                   1
Ansal Florence Super                                  1
Sushant lok 3                                         1
Ansals Florence Villa                                 1
florance villa                                        1
sector4                                               1
Luxury DLF City Floors                                1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
DLF Exclusive Floors                                  1
Oriental Homes                                        1
Ansal Oriental Villas                                 1
Ansals Boom Plaza                                     1
RWA SECTOR 5                                          1
Adani Brahma Samsara Vilasa                           1
M3M Golf Hills                                        1
DLF Park Place                                        1
Signature Global City 63A                             1
Laburnum Victory Floors                               1
Adani Samsara Avasa                                   1
Friends Colony                                        1
dev nagar part 1                                      1
individual floor Bhondsi                              1
Block B                                               1
Sector 104, phase-1                                   1
Name: count, dtype: int64

In [41]:
column_cleaning = (
    df_house
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()))
column_cleaning['society'].value_counts()

society
international city by sobha phase 1                  53
emaar mgf marbella                                   49
international city by sobha phase 2                  40
unitech uniworld resorts                             34
vipul tatvam villa                                   27
ansals palam vihar                                   26
vatika signature villas                              25
tata primanti                                        18
eldeco mansionz                                      15
sobha international city phase 3                     14
dlf city plots                                       13
ansal                                                13
dlf city plots phase 2                               13
vipul world                                          13
unitech deerwood chase                               13
independent villa                                    12
eros rosewood city                                   11
emaar mgf the vilas                                  11
bptp visionnaire                                     11
unitech espace                                       11
ansal plaza                                          10
vatika emilia floors                                 10
malibu towne                                         10
unitech nirvana country 2                            10
ss aaron ville                                       10
bestech park view ananda                              9
dlf gardencity enclave                                9
signature global city 92                              8
ansal sushant lok 2                                   8
assotech blith                                        8
bptp amstoria                                         7
signature global city 79b                             7
spacious villa                                        7
huda sector 46                                        7
unitech alder grove                                   7
uppal southend                                        7
experion windchants                                   7
m3m soulitude                                         6
vatika india next                                     6
sushant lok 1 builder floors                          6
huda flats                                            6
trehan luxury floors 71                               6
emaar emerald hills                                   6
emaar the palm springs                                6
rwa sector 46                                         5
bptp astaire gardens                                  5
ansal sushant lok plots                               5
ansal heights                                         4
central park flower valley                            4
central park flower valley fleur villas               4
dlf luxury builder floors                             4
villa in suncity                                      4
sector 40                                             4
unitech vista villas                                  4
cyber city                                            4
anant raj                                             4
mayfield gardens                                      4
sector 47                                             4
sector 45                                             4
huda                                                  4
mapsko casa bella                                     4
satya the legend                                      4
sector 57                                             4
all punjabi welfare association                       4
dlf city plots phase 3                                4
the laburnum                                          4
signature global city 81                              4
smart world gems                                      4
ss linden floors                                      4
luxury villa                                          4
suncity township                                      3
ansals florence marvel                                3
puri diplomatic greens                                3
ultra luxury builder floor                            3
vatika iris floors                                    3
unitech south city 2                                  3
ss almeria                                            3
eros rosewood villas                                  3
kashish manor one                                     3
north east facing                                     3
nitara one good earth                                 3
mrs 16 acres                                          3
unitech espace premiere villas                        3
dlf floors phase 3                                    3
ats triumph                                           3
shyam kunj                                            3
m3m antalya hills                                     3
dlf city independent floors phase 1 and 2             3
ardee city                                            3
unitech escape                                        3
villa in dlf                                          3
unitech greenwood city                                3
block c                                               3
ready to move villa                                   3
spacious layout villa                                 3
sobha international city phase 4                      2
ansal homes                                           2
dlf phase 1 ultra luxury builder floors               2
celebrity homes                                       2
palam vihar society                                   2
unitech nirvana birch court                           2
housing board colony                                  2
urban estate residents welfare association            2
progressive rwa                                       2
sector 23a                                            2
shanti kunj                                           2
south city 1                                          2
ultra-luxury villa                                    2
dlf                                                   2
vatika independent floors                             2
vatika primrose floors                                2
vatika india next plots                               2
vatika city homes                                     2
bestech park view grand spa                           2
sector 38                                             2
ansal api spanish court                               2
green meadows                                         2
south city 2                                          2
dlf pink town house                                   2
national media centre                                 2
budget friendly villa                                 2
huda sector 47                                        2
godrej nature plus                                    2
lion infra green valley                               2
signature global park                                 2
villa in sl1                                          2
villa in dlf 4                                        2
garden villas                                         2
signature global city 93                              2
huda staff colony                                     2
sector 14 rwa                                         2
dlf the grove                                         2
birla navya                                           2
godrej summit                                         2
sector 21 rwa                                         2
villa in dlf 2                                        2
villa in dlf phase 2                                  2
dlf phase 2                                           1
dlf 3 apartment                                       1
gupta house, 98/5 , jacumpura, gurgaon                1
50 gaj 2 floor new house                              1
central park                                          1
huda hsvp sector 21                                   1
individual house sector 21                            1
country club manesar                                  1
himalayan society                                     1
ansal housing                                         1
m3m the marina                                        1
shiv colony bhondsi                                   1
at                                                    1
shri ram enclave maruti kunj                          1
pareena mi casa                                       1
house no 140                                          1
rosewood city                                         1
sector 46                                             1
ultra luxury builder floor sector 46                  1
hsvp/huda                                             1
individual floor bhondsi                              1
dev nagar part 1                                      1
sector 104, phase-1                                   1
block b                                               1
independent house floor dlf phase 2 gurgaon           1
rwa sector 5                                          1
adani brahma samsara vilasa                           1
laburnum victory floors                               1
signature global city 63a                             1
adani samsara avasa                                   1
friends colony                                        1
dlf park place                                        1
m3m golf hills                                        1
society                                               1
rwa sector 47 gurgaon                                 1
sector47                                              1
independent floor at dlf city                         1
sushant lok 1                                         1
central park flower valley flamingo floors            1
friends colony sohna                                  1
sector 9a                                             1
house no. 557                                         1
raheja atlantis                                       1
sector 31                                             1
sun city                                              1
surya cghs                                            1
sector 39                                             1
devnagar part 2 55 feet road                          1
diwan enclave rithoj road bhondsi                     1
vimal enclave, nirmal darbar                          1
ravi nager basai road                                 1
dlf phase 4 luxury builder floors                     1
sushant lok 1 kothi ,sushant lok 1                    1
villa in sushant lok                                  1
luxury kothi sushant lok1                             1
sushant lok1                                          1
ansal villa                                           1
block - c2                                            1
dlf ridgewood estate                                  1
dlf city plots phase 4                                1
dlf phase 4 luxury kothi                              1
dlf hibiscus lane                                     1
ambience lagoon                                       1
huda housing board society                            1
rwa sector 52                                         1
ardee palm grove villas                               1
builder house sec 52                                  1
sector 52                                             1
v block                                               1
villa in dlf 3                                        1
60 sq rd plot size                                    1
dlf, beautiful duplex house design                    1
duplex villa in dlf 3                                 1
independent house todapur                             1
malibu town                                           1
chawla ds residency                                   1
gdge                                                  1
niho scottish castle 2                                1
villa in rosewood city                                1
q1 block south city 2                                 1
q block                                               1
unitech singleton floors                              1
villa in south city                                   1
lal kuan                                              1
kadipur residential colony                            1
sushant lok 2                                         1
luxury builder floor in south city 2                  1
ganga tathastu                                        1
ward no 6                                             1
boutique villa                                        1
independent building                                  1
good block                                            1
south city1                                           1
unitech palms south city 1                            1
luxurious kothi in dlf                                1
dlf phase 1                                           1
dlf 1                                                 1
huda sector 40                                        1
greenwood city                                        1
maruti                                                1
huda  buil-tup house                                  1
ultra luxury kothi                                    1
indivisual floors                                     1
indipendent house, sector 40                          1
sector - 40                                           1
whispering meadows                                    1
b block                                               1
18 mtr wide road                                      1
signature global daxin vistas                         1
central park flower valley cerise floors              1
irwo rail vihar                                       1
aset sohna greens                                     1
ireo project                                          1
paras ekam homes                                      1
vatika westi resort farm house                        1
gls avenue 51                                         1
mahalaxmi garden, street no 5                         1
rajendra park sec 105                                 1
sector 105                                            1
sagar enclave                                         1
sushant lok 3                                         1
sector51                                              1
sector 51                                             1
orchid island                                         1
mayfield garden n block                               1
m2k symphony floors                                   1
kendriya vihar                                        1
sector 49 rosewood                                    1
unitech fresco                                        1
jat colony sector 6                                   1
ganpati enclave                                       1
designer floorwise                                    1
designer floorwise full building                      1
independent kothi in sl1                              1
n a                                                   1
florance villa                                        1
builder floors                                        1
ansal buildup                                         1
independent house                                     1
arjun marg/ sector- 26 phase- 1/ golf course road     1
luxury dlf city floors                                1
sector4                                               1
ansal florence super                                  1
eros city square                                      1
q1 block                                              1
fresco tower                                          1
rodeo drive                                           1
sector 38 rwa                                         1
nirvana villa, sector 50, gurgaon                     1
unitech aspen greens                                  1
woodstock floors                                      1
unitech nirvana country                               1
g block palam vihar                                   1
mgf the vilas                                         1
a block palam vihar                                   1
ss southend                                           1
vipul world floors                                    1
housing board haryana                                 1
block a palam vihar                                   1
notyh east facing                                     1
ansals florence villa                                 1
ansal oriental villas                                 1
ansals boom plaza                                     1
oriental homes                                        1
antriksh heights                                      1
independent floors at dlf city phase 1                1
dlf exclusive floors                                  1
Name: count, dtype: int64

In [42]:
df_house['society'].isnull().sum()

np.int64(1016)

#### 2. Price

In [43]:
df_house = df_house.rename(columns={
    'price': 'price_in_cr',
    'area': 'price_per_sqft'
})

In [44]:
df_house['price_in_cr'].value_counts()

price_in_cr
5.5 Cr               42
10 Cr                37
6.5 Cr               34
9 Cr                 33
15 Cr                31
10.5 Cr              30
6 Cr                 29
7 Cr                 28
4 Cr                 27
8.5 Cr               27
8 Cr                 27
7.5 Cr               26
13 Cr                26
11 Cr                25
14 Cr                25
12 Cr                23
12.5 Cr              23
5 Cr                 22
9.5 Cr               21
3.5 Cr               21
1.5 Cr               20
2.5 Cr               19
8.25 Cr              19
6.25 Cr              19
4.5 Cr               19
21 Cr                19
14.5 Cr              18
16 Cr                18
18 Cr                18
2 Cr                 17
70 Lac               16
15.5 Cr              14
3.75 Cr              14
7.25 Cr              13
13.5 Cr              13
3.25 Cr              13
2.6 Cr               13
1 Cr                 13
2.25 Cr              13
2.15 Cr              12
2.75 Cr              12
11.5 Cr              12
3 Cr                 12
7.75 Cr              12
6.75 Cr              12
1.6 Cr               12
16.5 Cr              12
17 Cr                12
4.25 Cr              11
11.25 Cr             11
2.7 Cr               11
2.9 Cr               11
1.8 Cr               11
20 Cr                11
5.25 Cr              11
24 Cr                10
3.3 Cr               10
25 Cr                10
3.6 Cr               10
75 Lac               10
22 Cr                10
2.2 Cr                9
18.5 Cr               9
1.25 Cr               9
9.25 Cr               9
1.1 Cr                9
6.9 Cr                8
2.85 Cr               8
60 Lac                8
3.9 Cr                8
4.4 Cr                8
95 Lac                8
80 Lac                8
4.3 Cr                8
3.2 Cr                8
55 Lac                8
1.9 Cr                8
5.75 Cr               7
3.85 Cr               7
8.75 Cr               7
2.4 Cr                7
1.2 Cr                7
2.8 Cr                7
4.7 Cr                6
5.8 Cr                6
1.35 Cr               6
1.65 Cr               6
3.55 Cr               6
5.6 Cr                6
6.45 Cr               6
50 Lac                6
7.3 Cr                6
6.6 Cr                6
17.5 Cr               6
9.75 Cr               5
4.9 Cr                5
3.4 Cr                5
3.1 Cr                5
40 Lac                5
3.7 Cr                5
8.4 Cr                5
8.49 Cr               5
23 Cr                 5
19.5 Cr               5
26 Cr                 5
11.75 Cr              5
4.6 Cr                5
5.3 Cr                5
5.45 Cr               5
5.4 Cr                5
2.65 Cr               5
28 Cr                 5
1.3 Cr                5
6.2 Cr                5
12.75 Cr              5
1.95 Cr               4
8.95 Cr               4
13.1 Cr               4
30 Cr                 4
13.9 Cr               4
1.55 Cr               4
12.75  - 14.5 Cr      4
5.7 Cr                4
7.6 Cr                4
5.35 Cr               4
7.4 Cr                4
45 Lac                4
4.75 Cr               4
1.45 Cr               4
1.56 Cr               4
5.15 Cr               4
90 Lac                4
1.15 Cr               4
38 Cr                 4
45 Cr                 4
1.85 Cr               4
3.35 Cr               4
9.3 Cr                4
5.1 Cr                4
19 Cr                 4
4.35 Cr               4
2.3 Cr                4
72 Lac                3
5.2 Cr                3
3.8 Cr                3
8.2 Cr                3
38 Lac                3
20.5 Cr               3
6.93 Cr               3
17.57  - 25.57 Cr     3
12.47 Cr              3
65 Lac                3
10.9 Cr               3
85 Lac                3
7.2 Cr                3
9.35 Cr               3
15.25 Cr              3
10.98 Cr              3
1.05 Cr               3
6.99 Cr               3
1.12 Cr               3
7.1 Cr                3
2.35 Cr               3
9.9 Cr                3
1.62 Cr               3
2.1 Cr                3
1.75 Cr               3
12.8 Cr               3
4.85 Cr               3
4.1 Cr                3
7.15 Cr               3
9.95 Cr               3
78 Lac                3
3.65 Cr               3
7.9 Cr                3
10.75 Cr              3
22.5 Cr               3
8.3 Cr                3
1.7 Cr                3
6.3 Cr                3
29.16 Cr              3
4.95 Cr               3
33.92  - 42.24 Cr     3
8.99 Cr               3
32 Cr                 3
8.9 Cr                3
10.6 Cr               3
6.49 Cr               3
13.6 Cr               3
30 Lac                3
4.15 Cr               3
3.45 Cr               3
9.6 Cr                3
9.15 Cr               3
27 Cr                 3
13.95 Cr              2
3.15 Cr               2
13.99 Cr              2
10.3 Cr               2
1.22 Cr               2
43 Lac                2
23 Lac                2
9.65 Cr               2
6.65 Cr               2
12.25 Cr              2
42 Lac                2
7.85 Cr               2
12.9 Cr               2
52 Lac                2
1.68 Cr               2
92 Lac                2
4.8 Cr                2
8.8 Cr                2
1.4 Cr                2
8.51  - 9.07 Cr       2
2.45 Cr               2
13.25 Cr              2
23.5 Cr               2
8.15 Cr               2
3.95 Cr               2
2.55 Cr               2
5.65 Cr               2
17.75 Cr              2
4.2 Cr                2
5.85 Cr               2
6.35 Cr               2
10.4 Cr               2
2.05 Cr               2
7.8 Cr                2
12.4 Cr               2
98 Lac                2
7.7 Cr                2
7.5  - 9.09 Cr        2
5.48 Cr               2
9.8 Cr                2
1.08 Cr               2
16.7 Cr               2
12.7 Cr               2
3.89 Cr               2
6.1 Cr                2
6.4 Cr                2
10.65 Cr              2
16.25 Cr              2
14.75 Cr              2
Price on Request      2
7.95 Cr               2
5.51 Cr               2
40 Cr                 2
69 Lac                2
14.25 Cr              2
10.2 Cr               2
16.75 Cr              2
9.51 Cr               2
46 Lac                2
1.57 Cr               2
10.25 Cr              2
9.2 Cr                2
27.5 Cr               2
9.98 Cr               1
1.37 Cr               1
10.35 Cr              1
20.9 Cr               1
21.1 Cr               1
14.3 Cr               1
11.49 Cr              1
1.86 Cr               1
1.82 Cr               1
1.84 Cr               1
8.69 Cr               1
9.53 Cr               1
14.6 Cr               1
14.65 Cr              1
14.1 Cr               1
83 Lac                1
50 Cr                 1
39 Lac                1
36 Lac                1
1.48 Cr               1
10.15 Cr              1
8.7 Cr                1
4.14 Cr               1
1.66 Cr               1
1.63 Cr               1
1.34 Cr               1
14.55 Cr              1
4.94 Cr               1
6.7 Cr                1
62 Lac                1
2.58 Cr               1
16.49 Cr              1
3.49 Cr               1
6.26 Cr               1
1.51 Cr               1
22.51 Cr              1
31.8 Cr               1
6.05 Cr               1
4.72 Cr               1
2.77 Cr               1
21.25 Cr              1
20.95 Cr              1
1.64 Cr               1
9.39 Cr               1
1.69 Cr               1
1.33 Cr               1
93 Lac                1
3.26 Cr               1
31 Cr                 1
7.89 Cr               1
5.55 Cr               1
10.76 Cr              1
17.7 Cr               1
1.88 Cr               1
5.22 Cr               1
24.95 Cr              1
13.85 Cr              1
19.25 Cr              1
11.85 Cr              1
11.37 Cr              1
9.79 Cr               1
15.9 Cr               1
10.1 Cr               1
1.83 Cr               1
11.11 Cr              1
7.65 Cr               1
8.48 Cr               1
7.79 Cr               1
7.52 Cr               1
12.35 Cr              1
5.36 Cr               1
5.95 Cr               1
96 Lac                1
56 Cr                 1
7.91 Cr               1
6.55 Cr               1
3.39 Cr               1
48 Lac                1
4.24 Cr               1
2.01 Cr               1
8.6 Cr                1
8.65 Cr               1
7.55 Cr               1
8.56 Cr               1
10.55 Cr              1
7.03 Cr               1
7.35 Cr               1
7.63 Cr               1
3.82 Cr               1
11.7 Cr               1
60 Cr                 1
33 Cr                 1
5.05 Cr               1
9.1 Cr                1
2.63 Cr               1
13.15 Cr              1
12.95 Cr              1
12.99 Cr              1
32 Lac                1
8.32 Cr               1
4.46 Cr               1
13.05 Cr              1
15.89 Cr              1
4.18 Cr               1
42 Cr                 1
13.55 Cr              1
10.8 Cr               1
5.49 Cr               1
96.5 Lac              1
5.67 Cr               1
6.15 Cr               1
14.45 Cr              1
12.59 Cr              1
22.91 Cr              1
18.75 Cr              1
23.25 Cr              1
4.49 Cr               1
1.79 Cr               1
3.21 Cr               1
4.31 Cr               1
4.22 Cr               1
44 Lac                1
8.52 Cr               1
7.48 Cr               1
12.12 Cr              1
7.12 Cr               1
3.92 Cr               1
13.38 Cr              1
26.3 Cr               1
7.99 Cr               1
1.41 Cr               1
1.09 Cr               1
11.26 Cr              1
15.8 Cr               1
4.83 Cr               1
2.11 Cr               1
7.56 Cr               1
4.84 Cr               1
5.98 Cr               1
2.49 Cr               1
4.05 Cr               1
7 Lac                 1
6.85 Cr               1
6.57 Cr               1
1.42 Cr               1
1.38 Cr               1
1.32 Cr               1
1.07 Cr               1
86 Lac                1
93.15 Lac             1
2.12 Cr               1
11.1 Cr               1
1.36 Cr               1
1.28 Cr               1
18.25 Cr              1
21.5 Cr               1
15.15 Cr              1
46 Cr                 1
47 Cr                 1
48 Cr                 1
29 Cr                 1
14.8 Cr               1
17.3 Cr               1
25.25 Cr              1
75 Cr                 1
23.99 Cr              1
22.49 Cr              1
12.65 Cr              1
25.95 Cr              1
9.82 Cr               1
11.95 Cr              1
3.42 Cr               1
59 Lac                1
22.5 Lac              1
5.9 Cr                1
6.8 Cr                1
18.99 Cr              1
35 Cr                 1
67 Lac                1
41.9 Lac              1
14.99 Cr              1
13.59 Cr              1
7.24 Cr               1
2.99 Cr               1
1.13 Cr               1
27.54 Cr              1
18.54 Cr              1
15.47 Cr              1
13.75 Cr              1
16.95 Cr              1
12.3 Cr               1
4.04 Cr               1
5.76 Cr               1
3.05 Cr               1
6.32 Cr               1
25 Lac                1
35 Lac                1
1.53 Cr               1
7.45 Cr               1
7.57 Cr               1
8.62 Cr               1
2.47 Cr               1
3.24 Cr               1
76 Lac                1
20 Lac                1
Name: count, dtype: int64

In [45]:
df_house['price_in_cr'].isnull().sum()

np.int64(0)

In [46]:
df_house[df_house['price_in_cr'] == 'Price on Request']

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
512,"1 Bedroom House for sale in Badshahpur, Gurgaon",https://www.99acres.com/1-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqyd,5643 sqft Super Area,NaN,0.0,1,1,0.0,"Badshahpur, Gurgaon",NaN,0,NaN,2,NaN,Unfurnished,"[""N""]",NaN,"Semi-Furnished, at badshahpur location gurgaon",none,0.00000,0.000000,B88960066
1248,"1 Bedroom House for sale in Sector 9, Gurgaon",https://www.99acres.com/1-bhk-bedroom-independ...,NaN,Price on Request,₹0 /sqyd,1449 sqft Super Area,NaN,0.0,1,1,2.0,"Sector 9, Gurgaon",NaN,0,NaN,2,NaN,Semi-Furnished,"{""O"":1}","['State bank ATM', 'Esic Hospital Gurugram', '...",Near esi hospital \nPacking \nPark,none,28.46213,77.001746,C91230184

In [47]:
df_house['price_in_cr'].unique()

array(['14.5 Cr', '8.4 Cr', '10.35 Cr', '20.5 Cr', '10 Cr', '13.9 Cr',
       '15 Cr', '17.57  - 25.57 Cr', '21.25 Cr', '20.9 Cr', '21.1 Cr',
       '21 Cr', '9 Cr', '14.3 Cr', '10.98 Cr', '9.25 Cr', '13.85 Cr',
       '12 Cr', '16 Cr', '14.25 Cr', '20.95 Cr', '10.2 Cr', '8.5 Cr',
       '9.15 Cr', '14.1 Cr', '9.51 Cr', '9.5 Cr', '19 Cr', '20 Cr',
       '14 Cr', '25 Cr', '9.53 Cr', '1.5 Cr', '11 Cr', '10.5 Cr',
       '14.6 Cr', '14.65 Cr', '9.75 Cr', '9.6 Cr', '27 Cr', '23 Cr',
       '10.15 Cr', '8.7 Cr', '10.25 Cr', '9.2 Cr', '8.69 Cr', '15.5 Cr',
       '10.3 Cr', '15.25 Cr', '17 Cr', '8 Cr', '10.75 Cr', '22.5 Cr',
       '9.3 Cr', '12.12 Cr', '6.65 Cr', '22 Cr', '14.99 Cr', '12.25 Cr',
       '4.25 Cr', '13.99 Cr', '9.35 Cr', '13.59 Cr', '16.5 Cr',
       '13.75 Cr', '13.95 Cr', '16.95 Cr', '13 Cr', '13.5 Cr', '9.65 Cr',
       '6.45 Cr', '28 Cr', '27.54 Cr', '18.54 Cr', '15.47 Cr', '3.7 Cr',
       '7.25 Cr', '7 Cr', '8.49 Cr', '6.25 Cr', '13.38 Cr', '5.75 Cr',
       '13.1 Cr', '18 Cr', '5.5 Cr', '5.45 Cr', '5.4 Cr', '5.35 Cr',
       '8.3 Cr', '7.9 Cr', '7.6 Cr', '6 Cr', '6.5 Cr', '5.7 Cr', '5.2 Cr',
       '5.3 Cr', '7.5 Cr', '3.9 Cr', '7.4 Cr', '6.9 Cr', '5.6 Cr',
       '3.92 Cr', '2.8 Cr', '8.25 Cr', '4.4 Cr', '7.12 Cr', '5.1 Cr',
       '5.25 Cr', '4 Cr', '24 Cr', '8.8 Cr', '8.75 Cr', '12.75 Cr',
       '23.5 Cr', '7.65 Cr', '12.5 Cr', '8.48 Cr', '7.79 Cr', '7.52 Cr',
       '7.55 Cr', '8.56 Cr', '10.55 Cr', '8.52 Cr', '7.48 Cr', '3.35 Cr',
       '2.5 Cr', '3 Cr', '2.9 Cr', '8.6 Cr', '11.25 Cr', '8.65 Cr',
       '2 Cr', '2.85 Cr', '8.95 Cr', '2.05 Cr', '78 Lac', '4.24 Cr',
       '2.25 Cr', '1.95 Cr', '2.01 Cr', '2.35 Cr', '1.8 Cr', '7.3 Cr',
       '18.5 Cr', '12.7 Cr', '6.35 Cr', '3.2 Cr', '4.35 Cr', '2.15 Cr',
       '2.75 Cr', '7.95 Cr', '1.75 Cr', '1.83 Cr', '1.15 Cr', '6.75 Cr',
       '4.1 Cr', '7.15 Cr', '1.85 Cr', '7.75 Cr', '3.5 Cr', '5 Cr',
       '3.3 Cr', '1.6 Cr', '1.62 Cr', '2.1 Cr', '11.5 Cr', '16.7 Cr',
       '9.8 Cr', '16.25 Cr', '9.79 Cr', '6.6 Cr', '15.9 Cr', '14.75 Cr',
       '10.1 Cr', '6.2 Cr', '14.8 Cr', '56 Cr', '7.91 Cr', '5.51 Cr',
       '19.25 Cr', '40 Cr', '6.49 Cr', '4.5 Cr', '21.5 Cr', '19.5 Cr',
       '15.15 Cr', '38 Cr', '46 Cr', '47 Cr', '48 Cr', '29 Cr',
       '25.25 Cr', '8.99 Cr', '75 Cr', '23.99 Cr', '22.49 Cr', '12.65 Cr',
       '25.95 Cr', '18.25 Cr', '33.92  - 42.24 Cr', '29.16 Cr', '1.2 Cr',
       '26 Cr', '24.95 Cr', '17.3 Cr', '17.5 Cr', '12.9 Cr', '50 Lac',
       'Price on Request', '1.1 Cr', '3.75 Cr', '5.48 Cr', '5.8 Cr',
       '6.55 Cr', '7.8 Cr', '3.45 Cr', '3.6 Cr', '3.4 Cr', '3.42 Cr',
       '5.22 Cr', '6.3 Cr', '4.95 Cr', '4.75 Cr', '4.9 Cr', '3.25 Cr',
       '11.37 Cr', '7.85 Cr', '9.82 Cr', '4.7 Cr', '2.6 Cr', '11.95 Cr',
       '13.6 Cr', '2.3 Cr', '6.4 Cr', '11.85 Cr', '5.15 Cr', '10.65 Cr',
       '30 Lac', '4.15 Cr', '6.1 Cr', '4.6 Cr', '11.11 Cr', '4.46 Cr',
       '10.4 Cr', '30 Cr', '13.05 Cr', '15.89 Cr', '45 Cr', '7.7 Cr',
       '2.4 Cr', '9.9 Cr', '32 Cr', '7.5  - 9.09 Cr', '3.89 Cr', '1.7 Cr',
       '1.25 Cr', '1.35 Cr', '5.36 Cr', '8.9 Cr', '5.95 Cr', '1.08 Cr',
       '96 Lac', '98 Lac', '2.2 Cr', '10.6 Cr', '1.45 Cr', '3.39 Cr',
       '48 Lac', '2.7 Cr', '12.4 Cr', '12.35 Cr', '33 Cr', '90 Lac',
       '5.05 Cr', '2.55 Cr', '3.85 Cr', '7.2 Cr', '5.65 Cr', '3.8 Cr',
       '7.03 Cr', '7.35 Cr', '3.65 Cr', '7.63 Cr', '3.82 Cr', '11.7 Cr',
       '11.75 Cr', '60 Cr', '12.8 Cr', '12.95 Cr', '12.99 Cr', '2.65 Cr',
       '32 Lac', '60 Lac', '5.85 Cr', '8.32 Cr', '4.85 Cr', '4.18 Cr',
       '42 Cr', '13.55 Cr', '9.1 Cr', '2.63 Cr', '9.95 Cr', '13.15 Cr',
       '3.55 Cr', '8.2 Cr', '1.79 Cr', '3.95 Cr', '4.3 Cr', '10.8 Cr',
       '4.2 Cr', '5.49 Cr', '13.25 Cr', '10.9 Cr', '12.59 Cr', '22.91 Cr',
       '18.75 Cr', '23.25 Cr', '8.15 Cr', '4.49 Cr', '3.1 Cr', '2.45 Cr',
       '85 Lac', '4.22 Cr', '1 Cr', '80 Lac', '70 Lac', '44 Lac',
       '55 Lac', '1.65 Cr', '75 Lac', '1.3 Cr', '1.9 Cr', '3.21 Cr',
       '65 Lac', '4.31 Cr', '5.9 Cr', '6.8 Cr', '4.83 Cr', '2.11 Cr',
       '7.56 Cr', '4.84 Cr', '4.8 Cr', '5.98 Cr', '6.85 Cr', '6.57 Cr',
       '45 Lac', '95 Lac', '1.42 Cr', '59 Lac', '38 Lac', '22.5 Lac',
       '42 Lac', '67 Lac', '72 Lac', '1.22 Cr', '43 Lac', '23 Lac',
       '41.9 Lac', '7 Lac', '1.55 Cr', '96.5 Lac', '5.67 Cr', '6.15 Cr',
       '14.45 Cr', '17.75 Cr', '18.99 Cr', '35 Cr', '14.55 Cr', '4.94 Cr',
       '6.7 Cr', '9.98 Cr', '1.05 Cr', '1.53 Cr', '7.45 Cr', '7.57 Cr',
       '1.51 Cr', '22.51 Cr', '31.8 Cr', '3.15 Cr', '12.3 Cr', '40 Lac',
       '4.04 Cr', '5.76 Cr', '7.1 Cr', '11.26 Cr', '15.8 Cr', '2.58 Cr',
       '16.75 Cr', '16.49 Cr', '3.49 Cr', '6.26 Cr', '2.49 Cr', '4.05 Cr',
       '26.3 Cr', '1.4 Cr', '8.51  - 9.07 Cr', '7.99 Cr', '1.41 Cr',
       '1.09 Cr', '1.07 Cr', '1.68 Cr', '83 Lac', '62 Lac', '2.99 Cr',
       '6.99 Cr', '1.12 Cr', '1.13 Cr', '1.36 Cr', '1.37 Cr', '4.14 Cr',
       '1.66 Cr', '1.63 Cr', '1.34 Cr', '1.38 Cr', '1.32 Cr', '1.28 Cr',
       '1.64 Cr', '92 Lac', '86 Lac', '93.15 Lac', '2.12 Cr', '52 Lac',
       '11.1 Cr', '11.49 Cr', '27.5 Cr', '1.86 Cr', '1.56 Cr', '1.82 Cr',
       '1.57 Cr', '1.84 Cr', '7.24 Cr', '6.05 Cr', '4.72 Cr', '2.77 Cr',
       '50 Cr', '46 Lac', '39 Lac', '36 Lac', '1.48 Cr', '9.39 Cr',
       '1.69 Cr', '1.33 Cr', '93 Lac', '69 Lac', '3.26 Cr', '31 Cr',
       '7.89 Cr', '5.55 Cr', '10.76 Cr', '17.7 Cr', '1.88 Cr', '3.05 Cr',
       '6.32 Cr', '25 Lac', '35 Lac', '8.62 Cr', '2.47 Cr', '3.24 Cr',
       '76 Lac', '20 Lac', '12.75  - 14.5 Cr', '6.93 Cr', '12.47 Cr'],
      dtype=object)

In [48]:
df_house.loc[
    df_house['price_in_cr'].str.contains('-', na=False),
    'price_in_cr'
].unique()

array(['17.57  - 25.57 Cr', '33.92  - 42.24 Cr', '7.5  - 9.09 Cr',
       '8.51  - 9.07 Cr', '12.75  - 14.5 Cr'], dtype=object)

In [49]:
df_house.loc[
    df_house['price_in_cr'].str.contains('-', na=False),
    'price_in_cr'
]

7       17.57  - 25.57 Cr
11      17.57  - 25.57 Cr
42      17.57  - 25.57 Cr
467     33.92  - 42.24 Cr
468     33.92  - 42.24 Cr
472     33.92  - 42.24 Cr
711        7.5  - 9.09 Cr
742        7.5  - 9.09 Cr
1584      8.51  - 9.07 Cr
1586      8.51  - 9.07 Cr
2040     12.75  - 14.5 Cr
2041     12.75  - 14.5 Cr
2042     12.75  - 14.5 Cr
2043     12.75  - 14.5 Cr
Name: price_in_cr, dtype: object

In [50]:
range_rows = df_house[
    df_house['price_in_cr']
        .str.contains('-', na=False)
]

range_rows

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
7,"5 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,International City by Sobha Phase 1,17.57 - 25.57 Cr,"₹42,833 /sqft",5036-7330 sqft Builtup Area,NaN,42833.0,5,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,P91403824
11,"5 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,International City by Sobha Phase 1,17.57 - 25.57 Cr,"₹42,833 /sqft",5036-7330 sqft Builtup Area,NaN,42833.0,5,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,B91215802
42,"5 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,International City by Sobha Phase 1,17.57 - 25.57 Cr,"₹42,833 /sqft",5036-7330 sqft Builtup Area,NaN,42833.0,5,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,Q90868424
467,"5 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,33.92 - 42.24 Cr,"₹58,401 /sqft",6520-8120 sqft Builtup Area,NaN,58401.0,5,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,R91504088
468,"5 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,33.92 - 42.24 Cr,"₹58,401 /sqft",6520-8120 sqft Builtup Area,NaN,58401.0,5,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,S91403098
472,"5 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,33.92 - 42.24 Cr,"₹58,401 /sqft",6520-8120 sqft Builtup Area,NaN,58401.0,5,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,R91260540
711,"5 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Vatika Signature Villas,7.5 - 9.09 Cr,"₹22,699 /sqft",3654-4428 sqft Builtup Area,NaN,22699.0,5,0,NaN,"Sector 82, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Sapphire 83 Shopping Mall', 'Hyatt Regency H...","Vatika signature villas in sector-82 gurgaon, ...",none,28.395356,76.956383,S91290408
742,"5 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Vatika Signature Villas,7.5 - 9.09 Cr,"₹22,699 /sqft",3654-4428 sqft Builtup Area,NaN,22699.0,5,0,NaN,"Sector 82, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Sapphire 83 Shopping Mall', 'Hyatt Regency H...","Vatika signature villas in sector-82 gurgaon, ...",none,28.395356,76.956383,U91212002
1584,"5 Bedroom House for sale in Sector 81, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Bestech Park View Ananda,8.51 - 9.07 Cr,"₹16,039 /sqft",5480-5840 sqft Builtup Area,NaN,16039.0,5,0,NaN,"Sector 81, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Miracles Apollo Cradle /Spectra Hospital', ""...","Bestech park view ananda in sector-81 gurgaon,...",NaN,28.390872,76.952720,A90786272
1586,"5 Bedroom House for sale in Sector 81, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,Bestech Park View Ananda,8.51 - 9.07 Cr,"₹15,529 /sqft",5480-5840 sqft,NaN,15529.0,5,0,NaN,"Sector 81, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Miracles Apollo Cradle /Spectra Hospital', ""...","Bestech park view ananda in sector-81 gurgaon,...",NaN,28.390872,76.952720,M91306454
2040,"4 Bedroom House for sale in Sector 112, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Experion Windchants,12.75 - 14.5 Cr,"₹19,836 /sqft",6350-7400 sqft Builtup Area,NaN,19836.0,4,0,NaN,"Sector 112, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['First Step Play School', 'Jai Sai Ram Hospit...","Experion windchants in sector 112, gurgaon by ...",NaN,28.518336,77.015785,V91278468
2041,"4 Bedroom House for sale in Sector 112, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Experion Windchants,12.75 - 14.5 Cr,"₹19,836 /sqft",6350-7400 sqft Builtup Area,NaN,19836.0,4,0,NaN,"Sector 112, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['First Step Play School', 'Jai Sai Ram Hospit...","Experion windchants in sector 112, gurgaon by ...",NaN,28.518336,77.015785,V91316260
2042,"4 Bedroom House for sale in Sector 112, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Experion Windchants,12.75 - 14.5 Cr,"₹19,836 /sqft",6350-7400 sqft Builtup Area,NaN,19836.0,4,0,NaN,"Sector 112, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['First Step Play School', 'Jai Sai Ram Hospit...","Experion windchants in sector 112, gurgaon by ...",NaN,28.518336,77.015785,K91623526
2043,"4 Bedroom House for sale in Sector 112, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,Experion Windchants,12.75 - 14.5 Cr,"₹19,836 /sqft",6350-7400 sqft Builtup Area,NaN,19836.0,4,0,NaN,"Sector 112, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['First Step Play School', 'Jai Sai Ram Hospit...","Experion windchants in sector 112, gurgaon by ...",NaN,28.518336,77.015785,C91665070

In [51]:
column_cleaning = (
    df_house
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (~df_['price_in_cr'].str.contains('-', na=False))   # drop range listings (multi-unit projects)
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            4
        )
    )
)

In [52]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
5.5000     42
10.0000    37
6.5000     34
9.0000     33
15.0000    31
10.5000    30
6.0000     29
7.0000     28
8.0000     27
4.0000     27
8.5000     27
7.5000     26
13.0000    26
11.0000    25
14.0000    25
12.5000    23
12.0000    23
5.0000     22
9.5000     21
3.5000     21
1.5000     20
2.5000     19
8.2500     19
6.2500     19
4.5000     19
21.0000    19
18.0000    18
16.0000    18
14.5000    18
2.0000     17
0.7000     16
15.5000    14
3.7500     14
3.2500     13
13.5000    13
1.0000     13
7.2500     13
2.6000     13
2.2500     13
1.6000     12
7.7500     12
3.0000     12
11.5000    12
2.1500     12
16.5000    12
17.0000    12
2.7500     12
6.7500     12
5.2500     11
1.8000     11
2.7000     11
2.9000     11
20.0000    11
11.2500    11
4.2500     11
3.6000     10
0.7500     10
24.0000    10
3.3000     10
22.0000    10
25.0000    10
1.1000      9
18.5000     9
2.2000      9
9.2500      9
1.2500      9
0.6000      8
2.8500      8
1.9000      8
0.9500      8
0.5500      8
3.2000      8
4.3000      8
3.9000      8
4.4000      8
6.9000      8
0.8000      8
3.8500      7
2.8000      7
2.4000      7
1.2000      7
8.7500      7
5.7500      7
7.3000      6
6.4500      6
1.6500      6
5.6000      6
3.5500      6
1.3500      6
5.8000      6
17.5000     6
0.5000      6
4.7000      6
6.6000      6
23.0000     5
3.4000      5
8.4000      5
28.0000     5
4.9000      5
4.6000      5
26.0000     5
9.7500      5
6.2000      5
8.4900      5
2.6500      5
5.4500      5
3.7000      5
12.7500     5
5.4000      5
11.7500     5
19.5000     5
3.1000      5
5.3000      5
1.3000      5
0.4000      5
8.9500      4
5.1000      4
5.3500      4
13.1000     4
7.6000      4
7.4000      4
5.7000      4
0.4500      4
1.5600      4
9.3000      4
13.9000     4
1.5500      4
1.4500      4
5.1500      4
19.0000     4
4.7500      4
2.3000      4
3.3500      4
4.3500      4
1.9500      4
30.0000     4
45.0000     4
1.8500      4
0.9000      4
1.1500      4
38.0000     4
7.9000      3
8.2000      3
9.9500      3
12.4700     3
6.9900      3
6.9300      3
1.1200      3
0.6500      3
0.8500      3
10.9000     3
20.5000     3
10.7500     3
22.5000     3
9.3500      3
15.2500     3
7.1000      3
1.0500      3
0.3800      3
0.7200      3
5.2000      3
2.3500      3
4.1000      3
7.1500      3
3.8000      3
1.7500      3
1.6200      3
2.1000      3
12.8000     3
7.2000      3
0.7800      3
4.8500      3
8.3000      3
3.6500      3
9.9000      3
1.7000      3
4.9500      3
6.3000      3
13.6000     3
8.9900      3
6.4900      3
29.1600     3
0.3000      3
4.1500      3
8.9000      3
32.0000     3
10.6000     3
3.4500      3
9.6000      3
27.0000     3
9.1500      3
10.9800     3
12.4000     2
16.7000     2
7.8000      2
9.8000      2
14.2500     2
16.2500     2
10.2000     2
3.8900      2
9.5100      2
7.8500      2
5.8500      2
10.4000     2
6.4000      2
1.0800      2
5.5100      2
8.8000      2
40.0000     2
0.9800      2
0.6900      2
23.5000     2
7.7000      2
12.9000     2
5.4800      2
10.6500     2
6.1000      2
12.7000     2
0.4600      2
14.7500     2
6.3500      2
7.9500      2
2.5500      2
5.6500      2
13.2500     2
8.1500      2
2.4500      2
3.9500      2
4.2000      2
2.0500      2
17.7500     2
0.4200      2
1.2200      2
0.4300      2
0.2300      2
4.8000      2
6.6500      2
12.2500     2
13.9900     2
13.9500     2
10.2500     2
9.2000      2
10.3000     2
16.7500     2
1.4000      2
3.1500      2
0.5200      2
27.5000     2
1.5700      2
0.9200      2
9.6500      2
1.6800      2
14.6500     1
1.8400      1
7.2400      1
6.0500      1
4.7200      1
3.2400      1
19.2500     1
21.5000     1
15.1500     1
46.0000     1
47.0000     1
48.0000     1
11.8500     1
9.7900      1
15.9000     1
10.1000     1
14.8000     1
56.0000     1
7.9100      1
3.4200      1
5.2200      1
11.3700     1
9.8200      1
11.9500     1
0.7600      1
0.2000      1
21.2500     1
24.9500     1
17.3000     1
6.5500      1
2.0100      1
1.8300      1
5.3600      1
5.9500      1
0.9600      1
3.3900      1
0.4800      1
11.1100     1
4.4600      1
13.0500     1
15.8900     1
29.0000     1
25.2500     1
75.0000     1
23.9900     1
22.4900     1
12.6500     1
25.9500     1
18.2500     1
7.6500      1
8.4800      1
7.7900      1
7.5200      1
7.5500      1
8.5600      1
10.5500     1
8.5200      1
8.3200      1
4.1800      1
42.0000     1
13.5500     1
9.1000      1
7.1200      1
7.6300      1
3.8200      1
11.7000     1
60.0000     1
12.9500     1
12.9900     1
0.3200      1
12.3500     1
33.0000     1
5.0500      1
20.9000     1
21.1000     1
7.0300      1
7.3500      1
4.2200      1
0.4400      1
3.2100      1
4.3100      1
5.9000      1
6.8000      1
4.8300      1
2.1100      1
14.3000     1
12.5900     1
22.9100     1
18.7500     1
23.2500     1
13.8500     1
4.4900      1
20.9500     1
3.9200      1
2.6300      1
13.1500     1
1.7900      1
14.1000     1
10.8000     1
1.8800      1
5.4900      1
7.4800      1
8.6000      1
8.6500      1
3.0500      1
4.2400      1
18.5400     1
15.4700     1
13.3800     1
4.9400      1
6.7000      1
9.9800      1
1.5300      1
7.4500      1
7.5700      1
1.5100      1
22.5100     1
0.9650      1
5.6700      1
6.1500      1
14.4500     1
6.3200      1
18.9900     1
35.0000     1
14.5500     1
0.2250      1
0.2500      1
0.6700      1
0.3500      1
8.6200      1
2.4700      1
0.4190      1
0.0700      1
7.5600      1
4.8400      1
2.7700      1
5.9800      1
6.8500      1
6.5700      1
1.4200      1
0.5900      1
0.9300      1
14.9900     1
3.2600      1
31.0000     1
13.5900     1
13.7500     1
7.8900      1
2.5800      1
7.9900      1
10.1500     1
8.7000      1
5.5500      1
10.7600     1
8.6900      1
17.7000     1
12.1200     1
50.0000     1
16.4900     1
3.4900      1
6.2600      1
2.4900      1
4.0500      1
26.3000     1
0.3900      1
31.8000     1
0.3600      1
12.3000     1
4.0400      1
5.7600      1
11.2600     1
15.8000     1
16.9500     1
1.4800      1
11.1000     1
11.4900     1
9.3900      1
1.8600      1
1.8200      1
1.6900      1
0.6200      1
1.3800      1
1.3200      1
1.2800      1
1.6400      1
1.3300      1
0.8600      1
0.9315      1
2.1200      1
2.9900      1
1.1300      1
1.3600      1
1.3700      1
4.1400      1
1.6600      1
1.6300      1
1.3400      1
9.5300      1
27.5400     1
1.4100      1
1.0900      1
1.0700      1
14.6000     1
0.8300      1
10.3500     1
Name: count, dtype: int64

In [54]:
column_cleaning['price_in_cr'].describe()

count    2038.000000
mean        8.291673
std         7.167099
min         0.070000
25%         3.217500
50%         6.600000
75%        11.250000
max        75.000000
Name: price_in_cr, dtype: float64

In [55]:
column_cleaning[column_cleaning['price_in_cr']> 30]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
406,"10 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,56.0,₹5.54 L /sqyd,9090 sqft Super Area,NaN,554455.0,10,7,4.0,"DLF Phase 1, Gurgaon",NaN,0,"Park/Garden, Pool, Main Road",1,NaN,Unfurnished,"{""O"":3,""C"":4}","['Dlf phase 1 metro station', 'Sector 42-43 me...",Modern duplex villa | with lift | 4 years old ...,"['Security / Fire Alarm', 'Vaastu Compliant', ...",28.464758,77.096014,S91239302
422,"7 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,independent villa,40.0,"₹42,105 /sqft",9500 sqft Builtup Area,8600.0,42105.0,7,8,4.0,"DLF Phase 1, Gurgaon",NaN,North-East,Main Road,1,NaN,Unfurnished,"{""O"":2,""C"":3}","['Guru dronacharya metro station', 'Dlf phase ...",500 sq yards luxury villa for sale in dlf phas...,"['Centrally Air Conditioned', 'Security / Fire...",28.475491,77.103210,C87934462
437,"7 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,NaN,38.0,₹7.57 L /sqyd,4518 sqft Super Area,NaN,756972.0,7,9,4.0,"DLF Phase 1, Gurgaon",NaN,North,Main Road,1,NaN,Unfurnished,"{""O"":2,""C"":2}","['Guru dronacharya metro station', 'Dlf phase ...",Check out this 7 bhk house for sale in dlf pha...,"['Vaastu Compliant', 'Centrally Air Conditione...",28.475491,77.103210,J91412314
438,"7 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,dlf city plots,46.0,₹4.5 L /sqyd,9198 sqft Super Area,NaN,450098.0,7,8,4.0,"DLF Phase 1, Gurgaon",NaN,South-East,"Main Road, Others, Park/Garden",2,NaN,Unfurnished,"{""O"":2,""C"":5}","['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",This is a house built on classical design base...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.475081,77.108819,Z84512934
439,"7 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,arjun marg/ sector- 26 phase- 1/ golf course road,47.0,₹4.7 L /sqyd,9000 sqft Super Area,NaN,470000.0,7,9,4.0,"DLF Phase 1, Gurgaon",NaN,North-East,"Main Road, Park/Garden",2,NaN,Unfurnished,"{""O"":3,""C"":4}","['Guru dronacharya metro station', 'Dlf phase ...",Ultra modern super luxury duplex bungalow with...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.475491,77.103210,Z57944624
442,"4 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,dlf city plots,48.0,₹4.7 L /sqyd,9198 sqft Super Area,NaN,469667.0,4,7,4.0,"DLF Phase 1, Gurgaon",NaN,North,"Others, Park/Garden, Main Road",3,NaN,Unfurnished,"{""O"":3,""C"":5}","['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",Available for sell 1022 sq yd villa with swimm...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.475081,77.108819,I84072172
448,"20 Bedroom House for sale in DLF Phase 1, Gurgaon",https://www.99acres.com/20-bhk-bedroom-indepen...,NaN,75.0,₹7.5 L /sqyd,9000 sqft Super Area,NaN,750000.0,20,20,4.0,"DLF Phase 1, Gurgaon",NaN,North,"Park/Garden, Club, Others, Main Road, Sea facing",1,Y,Unfurnished,"{""O"":2,""C"":3}","['Guru dronacharya metro station', 'Dlf phase ...",1000 square yards brand new independent house ...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.475491,77.103210,N88942722
455,"7 Bedroom House for sale in Block-A, DLF City ...",https://www.99acres.com/7-bhk-bedroom-independ...,NaN,38.0,₹7.57 L /sqyd,4518 sqft Super Area,NaN,756972.0,7,10,4.0,"Block-A, DLF City Phase 1, Gurgaon",NaN,South,Main Road,6,NaN,Unfurnished,"{""O"":2,""C"":8}","['Dlf phase 1 metro station', 'Sikandarpur met...",Ultra-Luxury 7 bhk victorian-Style kothi avail...,"['Security / Fire Alarm', 'Vaastu Compliant', ...",28.474700,77.089706,S88383476
689,24 Bedroom House for sale in B Block Sushant L...,https://www.99acres.com/24-bhk-bedroom-indepen...,NaN,45.0,₹5.45 L /sqyd,7425 sqft Super Area,NaN,545455.0,24,24,4.0,"B Block Sushant Lok Phase 1, Gurgaon",NaN,North-East,Others,1,Y,Unfurnished,"{""C"":2}","['Iffco chowk metro station', 'Huda city centr...",This upscale residence offers a refined living...,"['Centrally Air Conditioned', 'High Ceiling He...",28.466154,77.077396,O91363746
692,12 Bedroom House for sale in Sushant Lok Phase...,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,45.0,"₹61,350 /sqft",7335 sqft Carpet Area,815.0,61350.0,12,12,2.0,"Sushant Lok Phase 1, Gurgaon",NaN,North,Main Road,1,NaN,Unfurnished,"{""O"":4,""C"":10}","['Huda city centre metro station', 'Sector 42-...",Are you planning to buy your dream home? You c...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.455618,77.083076,B90496790
702,6 Bedroom House for sale in B Block Sushant Lo...,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,45.0,₹5.52 L /sqyd,7335 sqft Super Area,NaN,552147.0,6,6,3.0,"B Block Sushant Lok Phase 1, Gurgaon",NaN,0,NaN,1,NaN,Furnished,"{""C"":10}","['Iffco chowk metro station', 'Huda city centr...",Property is in the prime location. Please cont...,none,28.466154,77.077396,H87850108
707,21 Bedroom House for sale in A Block Sushant L...,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,32.0,₹3.33 L /sqyd,8640 sqft Super Area,NaN,333333.0,21,22,4.0,"A Block Sushant Lok Phase 1, Gurgaon",NaN,North-East,"Main Road, Club, Park/Garden",2,Y,Furnished,"{""O"":5,""C"":10}","['Iffco chowk metro station', 'Mg road metro s...","12 mtr wide road,back side18 mtr road,walking ...","['Vaastu Compliant', 'Private Garden / Terrace...",28.471107,77.075649,D91494562
773,"8 Bedroom House for sale in Greenwood City, Gu...",https://www.99acres.com/8-bhk-bedroom-independ...,NaN,33.0,₹4.13 L /sqyd,7200 sqft Super Area,NaN,412500.0,8,8,2.0,"Greenwood City, Gurgaon",NaN,North-West,"Park/Garden, Main Road, Sea facing",1,Y,Unfurnished,"{""O"":1,""C"":2}","['Huda city centre metro station', 'Axis bank ...","Sec 45 800sq yards, kothi for sell luxury corn...","['Maintenance Staff', 'Water Storage']",28.446127,77.062180,X90947736
786,5 Bedroom House for sale in Block A Greenwood ...,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,38.0,₹3.45 L /sqyd,9900 sqft Super Area,9500.0,345455.0,5,5,4.0,"Block A Greenwood City, Gurgaon",NaN,North-East,"Pool, Park/Garden, Club, Main Road",1,Y,Unfurnished,"{""O"":2,""C"":2}","['Huda city centre metro station', 'Axis bank ...",Greenwood city is a posh residential township ...,"['Centrally Air Conditioned', 'Security / Fire...",28.449291,77.065731,K88987524
793,29 Bedroom House for sale in Block A Greenwood...,https://www.99acres.com/29-bhk-bedroom-indepen...,NaN,45.0,₹4.22 L /sqyd,9603 sqft Super Area,NaN,421743.0,29,29,1.0,"Block A Greenwood City, Gurgaon",NaN,North-West,"Main Road, Park/Garden",2,Y,Furnished,"{""O"":15,""C"":15}","['Huda city centre metro station', 'Axis bank ...",Hotel 29 rooms fully furnished prime location ...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.449291,77.065731,G90334028
866,"7 Bedroom House for sale in Sector 33, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,unitech uniworld resorts,60.0,₹2.4 L /sqyd,22500 sqft Super Area,NaN,240000.0,7,8,4.0,"Sector 33, Gurgaon",NaN,North,"Pool, Main Road, Park/Garden",1,Y,Semi-Furnished,"{""O"":4,""C"":8}","['Millennium City Centre', 'Omaxe Celebration ...",Planning to buy an individual house in gurgaon...,none,28.428798,77.029648,Y91347426
937,"4 Bedroom House for sale in Malibu Town, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,42.0,₹3.19 L /sqyd,11840 sqft Super Area,NaN,319248.0,4,4,4.0,"Malibu Town, Gurgaon",NaN,0,NaN,1,NaN,0,"[""N""]","['Raheja Mall', 'Standard chartered ATM', 'Ici...","Located in malibu town, gurgaon, this 4 bhk in...",none,28.422656,77.045656,B87415998
1316,"7 Bedroom House for sale in Suncity, Gurgaon",https://www.99acres.com/7-bhk-bedroom-independ...,spacious villa,35.0,"₹25,000 /sqft",14000 sqft Builtup Area,12000.0,25000.0,7,8,4.0,"Suncity, Gurgaon",NaN,North-East,Main Road,1,NaN,Unfurnished,"{""O"":3,""C"":3}","['Sector 54 chowk metro station', 'Sector metr...",1000 sq yards luxury villa for sale in suncity...,"['Centrally Air Conditioned', 'Security / Fire...",28.436420,77.109900,I85792822
1335,"99 Bedroom House for sale in Sector 43, Gurgaon",https://www.99acres.com/99-bhk-bedroom-indepen...,NaN,40.0,₹5 L /sqyd,7200 sqft Super Area,NaN,500000.0,99,99,4.0,"Sector 43, Gurgaon",NaN,North-West,Park/Garden,6,NaN,Furnished,"{""O"":5,""C"":2}","['Sector 42-43 metro station', 'Sector 53-54 m...",Monthly rental 25 lakhs plus\nNewly constructe...,"['Private Garden / Terrace', 'Maintenance Staf...",28.453240,77.088103,W88617094
1375,"18 Bedroom House for sale in Sector 41, Gurgaon",https://www.99acres.com/18-bhk-bedroom-indepen...,NaN,31.8,₹6.36 L /sqyd,4500 sqft Super Area,NaN,636000.0,18,18,4.0,"Sector 41, Gurgaon",NaN,North-East,"Main Road, Sea facing, Others, Park/Garden",3,NaN,Furnished,"{""O"":6,""C"":4}","['Iffco chowk metro station', 'Punjab national...",18 set coliving and hotel clu pass available f...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.466746,77.059542,P91298738
1714,"30 Bedroom House for sale in Sector 27, Gurgaon",https://www.99acres.com/30-bhk-bedroom-indepen...,NaN,32.0,₹6.4 L /sqyd,4500 sqft Super Area,NaN,640000.0,30,30,4.0,"Sector 27, Gurgaon",NaN,North,Main Road,2,NaN,Furnished,"{""C"":3}","['Dlf phase 1 metro station', 'Sector 42-43 me...","This property is not just a house ,it is a mai...",NaN,28.465767,77.091674,P91056770
1720,"4 Bedroom House for sale in Sector 27, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,32.0,₹6.4 L /sqyd,4500 sqft Super Area,NaN,640000.0,4,4,3.0,"Sector 27, Gurgaon",NaN,0,NaN,2,NaN,Unfurnished,"{""O"":1,""C"":1}","['Dlf phase 1 metro station', 'Sector 42-43 me...",This 4 bhk house for sale in sector 27 gurgaon...,NaN,28.465767,77.091674,Z91103676
1729,"6 Bedroom House for sale in Sector 54, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,suncity township,38.0,₹7.57 L /sqyd,4518 sqft Super Area,NaN,756972.0,6,8,4.0,"Sector 54, Gurgaon",NaN,East,"Park/Garden, Main Road",6,NaN,Furnished,"{""O"":5,""C"":3}","['Sector 54 chowk metro station', 'Sector metr...",It is the most luxurious bungalow located on t...,NaN,28.433339,77.105472,Z63004198
1825,"5 Bedroom House for sale in Subhash Nagar, Gur...",https://www.99acres.com/5-bhk-bedroom-independ...,NaN,50.0,₹9 L /sqyd,5000 sqft Super Area,NaN,899993.0,5,2,2.0,"Subhash Nagar, Gurgaon",NaN,0,NaN,5,NaN,Semi-Furnished,"[""N""]","['Hanuman Mandir', 'Kharbanda Maternity and Nu...","Located in subhash nagar, gurgaon, this under-...",NaN,28.465706,77.024432,C88109246
1904,"4 Bedroom House for sale in Sector 15 Part 2, ...",https://www.99acres.com/4-bhk-bedroom-independ...,NaN,31.0,₹3.05 L /sqyd,9153 sqft Super Area,NaN,304818.0,4,5,4.0,"Sector 15 Part 2, Gurgaon",NaN,North,"Main Road, Park/Garden",3,Y,Unfurnished,"{""C"":3}","['Hanuman Mandir', 'State bank of india ATM', ...",Exclusive 1017 sq-Yard corner bungalow for sal...,NaN,28.459821,77.045160,O91430332

In [56]:
column_cleaning['price_in_cr'].quantile(
    [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
)

0.01     0.40703
0.05     0.80000
0.25     3.21750
0.50     6.60000
0.75    11.25000
0.95    21.00000
0.99    32.00000
Name: price_in_cr, dtype: float64

#### 3. Price Per Sqft

In [53]:
df_house['price_per_sqft'].value_counts()[:20]

price_per_sqft
₹4 L /sqyd       26
₹3.33 L /sqyd    23
₹3.5 L /sqyd     23
₹5 L /sqyd       21
₹2.5 L /sqyd     19
₹3 L /sqyd       17
₹3.7 L /sqyd     17
₹1.5 L /sqyd     16
₹3.42 L /sqyd    16
₹3.75 L /sqyd    15
₹4.17 L /sqyd    15
₹3.13 L /sqyd    14
₹1.8 L /sqyd     14
₹2 L /sqyd       13
₹2.75 L /sqyd    12
₹5.25 L /sqyd    12
₹4.5 L /sqyd     11
₹2.22 L /sqyd    11
₹4.33 L /sqyd    10
₹2.4 L /sqyd     10
Name: count, dtype: int64

In [57]:
column_cleaning['price_per_sqft']\
    .str.extract(r'/(.+)$', expand=False)\
    .str.strip()\
    .str.lower()\
    .value_counts(dropna=False)

price_per_sqft
sqyd    1867
sqft     156
NaN       15
Name: count, dtype: int64

In [58]:
column_cleaning = (
    df_house
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (~df_['price_in_cr'].str.contains('-', na=False))   # drop range listings (multi-unit projects)
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            4
        )
            )
    .assign(
        price_per_sqft=lambda df_: (
            df_['price_per_sqft']
            .str.split('₹')
            .str.get(1)
            .str.split('/')
            .str.get(0)
            .str.replace('L', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.strip()
            .pipe(pd.to_numeric, errors='coerce')
            .mul(
                np.where(
                    df_['price_per_sqft'].str.contains('L', na=False),
                    100000,
                    1
                )
            )
            .div(
                np.where(
                    df_['price_per_sqft'].str.contains('/sqyd', case=False, na=False),
                    9,
                    1
                )
            )
            .round()
            .astype('Int64')
        )
    )

)

In [59]:
column_cleaning['price_per_sqft']

0       40333
1       15556
2       19222
3       45556
4       41111
        ...
2049    15593
2050    15593
2051    12371
2052    12371
2053    35222
Name: price_per_sqft, Length: 2038, dtype: Int64

In [60]:
validation_df = pd.DataFrame({
    'original': df_house['price_per_sqft'],
    'converted': column_cleaning['price_per_sqft']
})

validation_df.sample(20, random_state=42)

            original  converted
1492   ₹34,570 /sqft      34570
543    ₹2.14 L /sqyd      23778
1406      ₹2 L /sqyd      22222
861     ₹2.7 L /sqyd      30000
1128   ₹1.56 L /sqyd      17333
614    ₹17,333 /sqft      17333
433    ₹4.18 L /sqyd      46444
611    ₹4.81 L /sqyd      53444
1422   ₹2.94 L /sqyd      32667
1085   ₹3.37 L /sqyd      37444
950    ₹2.43 L /sqyd      27000
2013   ₹1.32 L /sqyd      14667
1053   ₹2.08 L /sqyd      23111
1521   ₹3.58 L /sqyd      39778
188    ₹3.57 L /sqyd      39667
736    ₹2.29 L /sqyd      25444
1403      ₹6 L /sqyd      66667
1986   ₹1.02 L /sqyd      11333
1164   ₹1.55 L /sqyd      17222
1036  ₹15.67 L /sqyd     174111

In [61]:
column_cleaning['price_per_sqft'].describe()

count          2023.0
mean     42318.171033
std      56402.391474
min              45.0
25%           20000.0
50%           33333.0
75%           44778.0
max          833333.0
Name: price_per_sqft, dtype: Float64

- Max value is 8.3 lakh per sqft, which is unusually high and likely an outlier. This could be due to a data entry error or an exceptionally high-priced property. It would be advisable to investigate this specific entry further to determine its validity.

In [62]:
column_cleaning['price_per_sqft'].quantile(
    [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
)

0.01      5011.22
0.05      10006.5
0.25      20000.0
0.50      33333.0
0.75      44778.0
0.95      74410.7
0.99    357729.16
Name: price_per_sqft, dtype: Float64

In [64]:
validation_df = pd.DataFrame({
    'original': df_house['price_per_sqft'],
    'converted': column_cleaning['price_per_sqft']
})

validation_df.loc[
    (validation_df['converted'] < 1000) |
    (validation_df['converted'] > 50000)
].sort_values('converted')

            original  converted
1199      ₹404 /sqyd         45
1367    ₹5,165 /sqyd        574
1414    ₹6,429 /sqyd        714
588    ₹4.51 L /sqyd      50111
936    ₹4.52 L /sqyd      50222
1301   ₹4.53 L /sqyd      50333
487    ₹4.53 L /sqyd      50333
135    ₹4.53 L /sqyd      50333
1056   ₹4.54 L /sqyd      50444
568    ₹4.54 L /sqyd      50444
1868   ₹4.54 L /sqyd      50444
295    ₹4.55 L /sqyd      50556
1527   ₹4.56 L /sqyd      50667
1337   ₹4.56 L /sqyd      50667
946    ₹4.57 L /sqyd      50778
582    ₹4.58 L /sqyd      50889
691    ₹4.58 L /sqyd      50889
219    ₹4.58 L /sqyd      50889
1877   ₹4.58 L /sqyd      50889
365    ₹4.58 L /sqyd      50889
845    ₹4.58 L /sqyd      50889
1039   ₹4.58 L /sqyd      50889
139    ₹50,926 /sqft      50926
986    ₹4.59 L /sqyd      51000
1532    ₹4.6 L /sqyd      51111
65      ₹4.6 L /sqyd      51111
1380   ₹51,111 /sqft      51111
205     ₹4.6 L /sqyd      51111
187    ₹4.63 L /sqyd      51444
370    ₹4.64 L /sqyd      51556
1072   ₹4.64 L /sqyd      51556
788    ₹4.65 L /sqyd      51667
380    ₹4.66 L /sqyd      51778
144    ₹4.67 L /sqyd      51889
1526   ₹51,921 /sqft      51921
476    ₹4.68 L /sqyd      52000
485    ₹4.68 L /sqyd      52000
473    ₹52,018 /sqft      52018
469    ₹52,018 /sqft      52018
471    ₹52,018 /sqft      52018
165    ₹4.69 L /sqyd      52111
442     ₹4.7 L /sqyd      52222
1722    ₹4.7 L /sqyd      52222
1713    ₹4.7 L /sqyd      52222
439     ₹4.7 L /sqyd      52222
1966   ₹4.71 L /sqyd      52333
502    ₹4.72 L /sqyd      52444
508    ₹4.72 L /sqyd      52444
1878   ₹4.72 L /sqyd      52444
395    ₹4.72 L /sqyd      52444
1880   ₹4.72 L /sqyd      52444
372    ₹4.72 L /sqyd      52444
752    ₹4.73 L /sqyd      52556
776    ₹4.73 L /sqyd      52556
464    ₹4.74 L /sqyd      52667
1968   ₹4.74 L /sqyd      52667
896    ₹4.75 L /sqyd      52778
381    ₹4.75 L /sqyd      52778
1696   ₹4.75 L /sqyd      52778
1716   ₹4.75 L /sqyd      52778
1003   ₹4.77 L /sqyd      53000
431    ₹4.78 L /sqyd      53111
460    ₹4.78 L /sqyd      53111
992    ₹4.78 L /sqyd      53111
412    ₹4.78 L /sqyd      53111
475    ₹4.78 L /sqyd      53111
416    ₹4.78 L /sqyd      53111
376    ₹4.79 L /sqyd      53222
382    ₹4.79 L /sqyd      53222
364    ₹4.79 L /sqyd      53222
375    ₹4.79 L /sqyd      53222
505     ₹4.8 L /sqyd      53333
454     ₹4.8 L /sqyd      53333
1811    ₹4.8 L /sqyd      53333
450     ₹4.8 L /sqyd      53333
611    ₹4.81 L /sqyd      53444
1962   ₹4.81 L /sqyd      53444
134    ₹4.81 L /sqyd      53444
496    ₹4.81 L /sqyd      53444
503    ₹4.83 L /sqyd      53667
847    ₹4.83 L /sqyd      53667
1501   ₹4.83 L /sqyd      53667
943    ₹53,704 /sqft      53704
1956   ₹4.85 L /sqyd      53889
1384   ₹4.85 L /sqyd      53889
497    ₹4.86 L /sqyd      54000
493    ₹4.87 L /sqyd      54111
488    ₹4.87 L /sqyd      54111
506    ₹4.87 L /sqyd      54111
578    ₹4.88 L /sqyd      54222
122    ₹4.88 L /sqyd      54222
1200   ₹4.88 L /sqyd      54222
114    ₹4.88 L /sqyd      54222
1029    ₹4.9 L /sqyd      54444
1045   ₹4.91 L /sqyd      54556
1525   ₹4.92 L /sqyd      54667
492    ₹4.99 L /sqyd      55444
126       ₹5 L /sqyd      55556
143       ₹5 L /sqyd      55556
1583      ₹5 L /sqyd      55556
913       ₹5 L /sqyd      55556
1493      ₹5 L /sqyd      55556
1520      ₹5 L /sqyd      55556
1579      ₹5 L /sqyd      55556
495       ₹5 L /sqyd      55556
504       ₹5 L /sqyd      55556
782       ₹5 L /sqyd      55556
2034      ₹5 L /sqyd      55556
1335      ₹5 L /sqyd      55556
480       ₹5 L /sqyd      55556
481       ₹5 L /sqyd      55556
486       ₹5 L /sqyd      55556
1330      ₹5 L /sqyd      55556
1607      ₹5 L /sqyd      55556
116       ₹5 L /sqyd      55556
111       ₹5 L /sqyd      55556
265       ₹5 L /sqyd      55556
363       ₹5 L /sqyd      55556
353    ₹5.02 L /sqyd      55778
444    ₹5.03 L /sqyd      55889
778    ₹5.05 L /sqyd      56111
221    ₹5.06 L /sqyd      56222
410    ₹5.06 L /sqyd      56222
184    ₹5.06 L /sqyd      56222
466    ₹5.07 L /sqyd      56333
192    ₹5.07 L /sqyd      56333
1726   ₹5.08 L /sqyd      56444
1979   ₹5.13 L /sqyd      57000
383    ₹5.13 L /sqyd      57000
1503   ₹5.14 L /sqyd      57111
501    ₹5.14 L /sqyd      57111
479    ₹5.14 L /sqyd      57111
494    ₹5.14 L /sqyd      57111
639    ₹5.17 L /sqyd      57444
643    ₹5.17 L /sqyd      57444
1514   ₹5.17 L /sqyd      57444
233    ₹5.18 L /sqyd      57556
1395   ₹5.18 L /sqyd      57556
161    ₹5.18 L /sqyd      57556
388    ₹5.19 L /sqyd      57667
465    ₹5.19 L /sqyd      57667
483     ₹5.2 L /sqyd      57778
385    ₹5.21 L /sqyd      57889
373    ₹5.21 L /sqyd      57889
901    ₹5.21 L /sqyd      57889
1405   ₹5.25 L /sqyd      58333
1015   ₹5.25 L /sqyd      58333
1538   ₹5.25 L /sqyd      58333
425    ₹5.25 L /sqyd      58333
1721   ₹5.25 L /sqyd      58333
456    ₹5.25 L /sqyd      58333
115    ₹5.25 L /sqyd      58333
1917   ₹5.25 L /sqyd      58333
1918   ₹5.25 L /sqyd      58333
123    ₹5.25 L /sqyd      58333
173    ₹5.25 L /sqyd      58333
160    ₹5.25 L /sqyd      58333
470    ₹5.29 L /sqyd      58778
1718   ₹5.31 L /sqyd      59000
1719   ₹5.32 L /sqyd      59111
214    ₹5.32 L /sqyd      59111
1219   ₹5.32 L /sqyd      59111
810    ₹5.32 L /sqyd      59111
813    ₹5.32 L /sqyd      59111
907    ₹5.33 L /sqyd      59222
1937   ₹5.33 L /sqyd      59222
1989   ₹5.37 L /sqyd      59667
995    ₹5.37 L /sqyd      59667
1961   ₹5.39 L /sqyd      59889
1727   ₹5.42 L /sqyd      60222
1334   ₹5.42 L /sqyd      60222
704    ₹5.42 L /sqyd      60222
676    ₹5.42 L /sqyd      60222
1386   ₹5.42 L /sqyd      60222
1331   ₹5.42 L /sqyd      60222
1028   ₹5.45 L /sqyd      60556
689    ₹5.45 L /sqyd      60556
186    ₹5.45 L /sqyd      60556
893    ₹5.48 L /sqyd      60889
163    ₹5.49 L /sqyd      61000
1731    ₹5.5 L /sqyd      61111
702    ₹5.52 L /sqyd      61333
692    ₹61,350 /sqft      61350
406    ₹5.54 L /sqyd      61556
491    ₹5.56 L /sqyd      61778
915    ₹5.56 L /sqyd      61778
970    ₹5.56 L /sqyd      61778
262    ₹5.58 L /sqyd      62000
162     ₹5.6 L /sqyd      62222
626    ₹5.61 L /sqyd      62333
514    ₹5.62 L /sqyd      62444
890    ₹5.63 L /sqyd      62556
951    ₹5.63 L /sqyd      62556
1201   ₹5.69 L /sqyd      63222
1963   ₹5.71 L /sqyd      63444
650    ₹5.74 L /sqyd      63778
583    ₹5.75 L /sqyd      63889
1388   ₹5.75 L /sqyd      63889
822    ₹5.75 L /sqyd      63889
589     ₹5.8 L /sqyd      64444
1008   ₹5.82 L /sqyd      64667
1495   ₹5.82 L /sqyd      64667
190    ₹5.82 L /sqyd      64667
167    ₹5.83 L /sqyd      64778
124    ₹5.83 L /sqyd      64778
132    ₹5.83 L /sqyd      64778
150    ₹5.83 L /sqyd      64778
1541   ₹5.83 L /sqyd      64778
142    ₹5.83 L /sqyd      64778
1332   ₹5.83 L /sqyd      64778
411    ₹5.88 L /sqyd      65333
2032   ₹5.92 L /sqyd      65778
627    ₹5.98 L /sqyd      66444
1339      ₹6 L /sqyd      66667
628       ₹6 L /sqyd      66667
2030      ₹6 L /sqyd      66667
490       ₹6 L /sqyd      66667
979       ₹6 L /sqyd      66667
1403      ₹6 L /sqyd      66667
649       ₹6 L /sqyd      66667
940    ₹6.07 L /sqyd      67444
1333    ₹6.1 L /sqyd      67778
1050   ₹6.11 L /sqyd      67889
121    ₹6.11 L /sqyd      67889
1341   ₹6.13 L /sqyd      68111
145    ₹6.19 L /sqyd      68778
636    ₹6.22 L /sqyd      69111
681    ₹6.25 L /sqyd      69444
1216   ₹6.25 L /sqyd      69444
1967   ₹6.25 L /sqyd      69444
831    ₹6.25 L /sqyd      69444
1326   ₹6.26 L /sqyd      69556
1531   ₹6.33 L /sqyd      70333
678    ₹6.35 L /sqyd      70556
445    ₹6.36 L /sqyd      70667
1375   ₹6.36 L /sqyd      70667
1714    ₹6.4 L /sqyd      71111
1720    ₹6.4 L /sqyd      71111
945     ₹6.5 L /sqyd      72222
1964    ₹6.5 L /sqyd      72222
679    ₹6.54 L /sqyd      72667
2029   ₹6.56 L /sqyd      72889
1715   ₹6.56 L /sqyd      72889
987    ₹6.58 L /sqyd      73111
694    ₹6.67 L /sqyd      74111
140    ₹6.67 L /sqyd      74111
1732   ₹6.67 L /sqyd      74111
1735   ₹6.67 L /sqyd      74111
443     ₹6.7 L /sqyd      74444
1988   ₹6.71 L /sqyd      74556
1969   ₹6.71 L /sqyd      74556
899    ₹6.74 L /sqyd      74889
1327   ₹6.83 L /sqyd      75889
677     ₹6.9 L /sqyd      76667
423    ₹6.91 L /sqyd      76778
624    ₹6.93 L /sqyd      77000
1836   ₹6.99 L /sqyd      77667
1042   ₹7.12 L /sqyd      79111
2001    ₹7.2 L /sqyd      80000
749    ₹7.25 L /sqyd      80556
638    ₹7.33 L /sqyd      81444
154    ₹7.33 L /sqyd      81444
452    ₹7.33 L /sqyd      81444
699    ₹7.38 L /sqyd      82000
2031   ₹7.38 L /sqyd      82000
625    ₹7.39 L /sqyd      82111
648    ₹7.43 L /sqyd      82556
448     ₹7.5 L /sqyd      83333
455    ₹7.57 L /sqyd      84111
1729   ₹7.57 L /sqyd      84111
437    ₹7.57 L /sqyd      84111
1734   ₹7.76 L /sqyd      86222
897    ₹8.32 L /sqyd      92444
1733   ₹8.33 L /sqyd      92556
1740   ₹8.33 L /sqyd      92556
1688      ₹9 L /sqyd     100000
1825      ₹9 L /sqyd     100000
1768   ₹9.64 L /sqyd     107111
1850   ₹9.89 L /sqyd     109889
1854  ₹10.42 L /sqyd     115778
1415  ₹10.49 L /sqyd     116556
1899  ₹10.89 L /sqyd     121000
1404  ₹11.25 L /sqyd     125000
1692  ₹11.46 L /sqyd     127333
1623  ₹11.67 L /sqyd     129667
1165  ₹12.03 L /sqyd     133667
1615  ₹12.77 L /sqyd     141889
592   ₹13.03 L /sqyd     144778
1951   ₹13.5 L /sqyd     150000
1519   ₹13.5 L /sqyd     150000
1991   ₹13.5 L /sqyd     150000
1036  ₹15.67 L /sqyd     174111
1973  ₹15.99 L /sqyd     177667
2028     ₹16 L /sqyd     177778
313   ₹16.25 L /sqyd     180556
1792   ₹16.5 L /sqyd     183333
1172     ₹17 L /sqyd     188889
706    ₹17.4 L /sqyd     193333
352   ₹17.42 L /sqyd     193556
1169   ₹17.5 L /sqyd     194444
1978  ₹19.77 L /sqyd     219667
1418  ₹22.25 L /sqyd     247222
1426   ₹22.5 L /sqyd     250000
1193  ₹22.52 L /sqyd     250222
1189  ₹22.74 L /sqyd     252667
1138   ₹23.4 L /sqyd     260000
798    ₹23.4 L /sqyd     260000
1392  ₹23.75 L /sqyd     263889
1075  ₹23.96 L /sqyd     266222
2008  ₹24.33 L /sqyd     270333
1578  ₹24.44 L /sqyd     271556
259   ₹25.12 L /sqyd     279111
1874  ₹25.31 L /sqyd     281222
1983  ₹25.72 L /sqyd     285778
1573  ₹25.91 L /sqyd     287889
447   ₹26.97 L /sqyd     299667
769      ₹27 L /sqyd     300000
829   ₹27.38 L /sqyd     304222
1512  ₹27.47 L /sqyd     305222
241    ₹27.5 L /sqyd     305556
621   ₹27.95 L /sqyd     310556
1585     ₹28 L /sqyd     311111
1021  ₹28.12 L /sqyd     312444
991   ₹29.99 L /sqyd     333222
89    ₹31.45 L /sqyd     349444
80    ₹31.67 L /sqyd     351889
1479  ₹31.76 L /sqyd     352889
805   ₹32.14 L /sqyd     357111
14    ₹32.18 L /sqyd     357556
755    ₹32.2 L /sqyd     357778
1001   ₹32.4 L /sqyd     360000
415    ₹32.4 L /sqyd     360000
1806     ₹33 L /sqyd     366667
229   ₹33.03 L /sqyd     367000
917   ₹33.08 L /sqyd     367556
1855  ₹33.17 L /sqyd     368556
81    ₹33.33 L /sqyd     370333
1872  ₹33.37 L /sqyd     370778
407   ₹36.39 L /sqyd     404333
1030   ₹37.5 L /sqyd     416667
1431  ₹37.99 L /sqyd     422111
591   ₹38.46 L /sqyd     427333
292      ₹40 L /sqyd     444444
988   ₹40.48 L /sqyd     449778
1498  ₹42.73 L /sqyd     474778
620   ₹42.78 L /sqyd     475333
630   ₹43.95 L /sqyd     488333
482   ₹46.28 L /sqyd     514222
164   ₹55.64 L /sqyd     618222
1737     ₹75 L /sqyd     833333

In [65]:
column_cleaning.loc[
    column_cleaning['price_per_sqft'] < 1000
]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
1199,"3 Bedroom House for sale in Jharsa village, Gu...",https://www.99acres.com/3-bhk-bedroom-independ...,NaN,2.8,45,623999 sqft Super Area,NaN,404.0,3,2,2.0,"Jharsa village, Gurgaon",NaN,0,NaN,3,NaN,0,"[""N""]","['Rajiv Chowk Mosque', 'Axis bank ATM', 'State...","Available immediately, this 10+ year old 3 bhk...",none,28.442330,77.050800,D90345860
1367,"4 Bedroom House for sale in Sohna, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,vatika westi resort farm house,2.5,574,43560 sqft Super Area,NaN,5165.0,4,4,2.0,"Sohna, Gurgaon",NaN,0,NaN,1,NaN,0,NaN,"['Civil Hospital', 'Vardaan Hospital and Traum...",We are proud owners of house/villa available f...,none,28.249352,77.067276,T88555550
1414,"2 Bedroom House for sale in Sector 10A, Gurgaon",https://www.99acres.com/2-bhk-bedroom-independ...,lal kuan,0.4,714,5600 sqft Super Area,NaN,6429.0,2,1,0.0,"Sector 10A, Gurgaon",NaN,0,NaN,6,NaN,Unfurnished,"{""O"":1,""C"":1}",NaN,"Located in lal kuan, sector 10a, gurgaon, this...",none,77.026640,28.459500,I91175962

#### 4. Bedroom

In [73]:
column_cleaning['bedRoom'].describe()

count    2038.000000
mean        5.598135
std         4.485063
min         1.000000
25%         3.000000
50%         5.000000
75%         6.000000
max        99.000000
Name: bedRoom, dtype: float64

In [74]:
column_cleaning['bedRoom'].unique()

array([ 5,  4,  6,  8,  7,  3, 13,  9, 10, 19, 11,  2, 14, 17, 12, 20, 16,
       24, 18,  1, 22, 36, 21, 29, 26, 40, 15, 99, 28, 30, 63, 23, 25])

In [75]:
column_cleaning['bedRoom'].isnull().sum()

np.int64(0)

#### 5. Bathroom

In [76]:
column_cleaning['bathroom'].describe()

count    2038.000000
mean        5.525515
std         4.536341
min         0.000000
25%         3.000000
50%         4.000000
75%         6.000000
max        99.000000
Name: bathroom, dtype: float64

In [77]:
column_cleaning['bathroom'].unique()

array([ 7,  4,  6,  8,  0,  5,  1,  3, 10,  9, 13,  2, 19, 14, 17, 12, 11,
       16, 20, 24, 18, 22, 36, 15, 29, 26, 21, 40, 99, 28, 30, 63, 25])

In [78]:
column_cleaning['bathroom'].isnull().sum()

np.int64(0)

In [79]:
column_cleaning[column_cleaning['bathroom'] == 0]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
15,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.98,34887,3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,M91403820
17,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.98,34887,3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,D90868422
25,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.98,34887,3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,X91215798
104,"3 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,international city by sobha phase 1,11.00,34887,3153 sqft Builtup Area,NaN,34887.0,3,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,N91403818
107,"3 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,international city by sobha phase 1,11.00,34887,3153 sqft Builtup Area,NaN,34887.0,3,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,E91215796
108,"3 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,international city by sobha phase 1,11.00,34887,3153 sqft Builtup Area,NaN,34887.0,3,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,D90868420
469,"4 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar mgf marbella,29.16,52018,5605 sqft Builtup Area,NaN,52018.0,4,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,O91403096
471,"4 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar mgf marbella,29.16,52018,5605 sqft Builtup Area,NaN,52018.0,4,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,L91504084
473,"4 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar mgf marbella,29.16,52018,5605 sqft Builtup Area,NaN,52018.0,4,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,C91260538
561,"5 Bedroom House for sale in Sector 57, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,satya the legend,11.37,17511,6495 sqft Builtup Area,NaN,17511.0,5,0,NaN,"Sector 57, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Garari', 'Dreamz Cafe', 'Culinary Blend', 'D...","Satya the legend in sector-57 gurgaon, gurgaon...",none,28.419732,77.076766,Y91148124
712,"4 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,mapsko casa bella,3.89,10355,3754 sqft Builtup Area,NaN,10355.0,4,0,NaN,"Sector 82, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Vatika City Centre Mall', 'Aarvy Healthcare ...","Mapsko casa bella in sector-82, gurgaon by map...",none,28.393790,76.962990,H91437524
713,"4 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,mapsko casa bella,3.89,10355,3754 sqft Builtup Area,NaN,10355.0,4,0,NaN,"Sector 82, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Vatika City Centre Mall', 'Aarvy Healthcare ...","Mapsko casa bella in sector-82, gurgaon by map...",none,28.393790,76.962990,U91211782
1427,"3 Bedroom House for sale in Uppals Southend, G...",https://www.99acres.com/3-bhk-bedroom-independ...,uppal southend,4.04,14400,2808 sqft Superbuiltup Area,NaN,14400.0,3,0,NaN,"Uppals Southend, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Gurugram Public School', 'Sushant University...","Uppal southend in uppals southend, gurgaon by ...",none,28.409324,77.045716,I91097414
1429,"4 Bedroom House for sale in Uppals Southend, G...",https://www.99acres.com/4-bhk-bedroom-independ...,uppal southend,5.76,14400,4000 sqft Superbuiltup Area,NaN,14400.0,4,0,NaN,"Uppals Southend, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Gurugram Public School', 'Sushant University...","Uppal southend in uppals southend, gurgaon by ...",none,28.409324,77.045716,J91097420
1929,"5 Bedroom House for sale in Sector 99, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,assotech blith,6.32,11287,5595 sqft Builtup Area,NaN,11287.0,5,0,NaN,"Sector 99, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Dwarka Expressway', 'Ocus Medley Mall', 'The...",Assotech blith by assotech builders is a resid...,NaN,28.456319,76.961875,J91033042
1936,"5 Bedroom House for sale in Sector 99, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,assotech blith,6.99,12500,5595 sqft Builtup Area,NaN,12500.0,5,0,NaN,"Sector 99, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Dwarka Expressway', 'Ocus Medley Mall', 'The...",Assotech blith by assotech builders is a resid...,NaN,28.456319,76.961875,M82281516
2037,"4 Bedroom House for sale in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar emerald hills,3.55,17962,1975 sqft Builtup Area,NaN,17962.0,4,0,NaN,"Sector 65, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Pragyanam School', 'CK Birla Hospital, Gurga...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,28.404360,77.072284,V91641140
2038,"4 Bedroom House for sale in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar emerald hills,3.55,17962,1975 sqft Builtup Area,NaN,17962.0,4,0,NaN,"Sector 65, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Pragyanam School', 'CK Birla Hospital, Gurga...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,28.404360,77.072284,K91502068
2039,"4 Bedroom House for sale in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar emerald hills,3.55,17962,1975 sqft Builtup Area,NaN,17962.0,4,0,NaN,"Sector 65, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Pragyanam School', 'CK Birla Hospital, Gurga...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,28.404360,77.072284,P91402540
2047,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,U91316134
2048,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,Y91663054
2049,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,H91668606
2050,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,U91247428
2051,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,Z91333184
2052,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,A90966806

- Zero bathroom = missing due to parsing issue.

- We can fill using bedroom values when bathroom values is zero.

#### 6. Balcony

In [80]:
column_cleaning['balcony'].describe()

count    2013.000000
mean        3.017884
std         1.128731
min         0.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: balcony, dtype: float64

In [84]:
column_cleaning['balcony'].unique()

array([ 4.,  3.,  2., nan,  0.,  1.])

In [83]:
column_cleaning['balcony'].isnull().sum()

np.int64(25)

In [85]:
column_cleaning[column_cleaning['balcony'].isnull()]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
15,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.98,34887,3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,M91403820
17,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.98,34887,3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,D90868422
25,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.98,34887,3147 sqft Builtup Area,NaN,34887.0,4,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,X91215798
104,"3 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,international city by sobha phase 1,11.00,34887,3153 sqft Builtup Area,NaN,34887.0,3,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,N91403818
107,"3 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,international city by sobha phase 1,11.00,34887,3153 sqft Builtup Area,NaN,34887.0,3,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,E91215796
108,"3 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/3-bhk-bedroom-independ...,international city by sobha phase 1,11.00,34887,3153 sqft Builtup Area,NaN,34887.0,3,0,NaN,"Sector 109, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['The Shikshiyan School', 'Dharampeth Main Roa...","With just 6 villas per acre, international cit...",none,28.513368,76.996723,D90868420
469,"4 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar mgf marbella,29.16,52018,5605 sqft Builtup Area,NaN,52018.0,4,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,O91403096
471,"4 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar mgf marbella,29.16,52018,5605 sqft Builtup Area,NaN,52018.0,4,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,L91504084
473,"4 Bedroom House for sale in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar mgf marbella,29.16,52018,5605 sqft Builtup Area,NaN,52018.0,4,0,NaN,"Sector 66, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['NH 48', 'HUB 66', 'Park Hospital', 'Delhi Pu...","Emaar mgf marbella in sector-66, gurgaon by em...",none,28.399559,77.061027,C91260538
561,"5 Bedroom House for sale in Sector 57, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,satya the legend,11.37,17511,6495 sqft Builtup Area,NaN,17511.0,5,0,NaN,"Sector 57, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Garari', 'Dreamz Cafe', 'Culinary Blend', 'D...","Satya the legend in sector-57 gurgaon, gurgaon...",none,28.419732,77.076766,Y91148124
712,"4 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,mapsko casa bella,3.89,10355,3754 sqft Builtup Area,NaN,10355.0,4,0,NaN,"Sector 82, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Vatika City Centre Mall', 'Aarvy Healthcare ...","Mapsko casa bella in sector-82, gurgaon by map...",none,28.393790,76.962990,H91437524
713,"4 Bedroom House for sale in Sector 82, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,mapsko casa bella,3.89,10355,3754 sqft Builtup Area,NaN,10355.0,4,0,NaN,"Sector 82, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Vatika City Centre Mall', 'Aarvy Healthcare ...","Mapsko casa bella in sector-82, gurgaon by map...",none,28.393790,76.962990,U91211782
1427,"3 Bedroom House for sale in Uppals Southend, G...",https://www.99acres.com/3-bhk-bedroom-independ...,uppal southend,4.04,14400,2808 sqft Superbuiltup Area,NaN,14400.0,3,0,NaN,"Uppals Southend, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Gurugram Public School', 'Sushant University...","Uppal southend in uppals southend, gurgaon by ...",none,28.409324,77.045716,I91097414
1429,"4 Bedroom House for sale in Uppals Southend, G...",https://www.99acres.com/4-bhk-bedroom-independ...,uppal southend,5.76,14400,4000 sqft Superbuiltup Area,NaN,14400.0,4,0,NaN,"Uppals Southend, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Gurugram Public School', 'Sushant University...","Uppal southend in uppals southend, gurgaon by ...",none,28.409324,77.045716,J91097420
1929,"5 Bedroom House for sale in Sector 99, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,assotech blith,6.32,11287,5595 sqft Builtup Area,NaN,11287.0,5,0,NaN,"Sector 99, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Dwarka Expressway', 'Ocus Medley Mall', 'The...",Assotech blith by assotech builders is a resid...,NaN,28.456319,76.961875,J91033042
1936,"5 Bedroom House for sale in Sector 99, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,assotech blith,6.99,12500,5595 sqft Builtup Area,NaN,12500.0,5,0,NaN,"Sector 99, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Dwarka Expressway', 'Ocus Medley Mall', 'The...",Assotech blith by assotech builders is a resid...,NaN,28.456319,76.961875,M82281516
2037,"4 Bedroom House for sale in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar emerald hills,3.55,17962,1975 sqft Builtup Area,NaN,17962.0,4,0,NaN,"Sector 65, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Pragyanam School', 'CK Birla Hospital, Gurga...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,28.404360,77.072284,V91641140
2038,"4 Bedroom House for sale in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar emerald hills,3.55,17962,1975 sqft Builtup Area,NaN,17962.0,4,0,NaN,"Sector 65, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Pragyanam School', 'CK Birla Hospital, Gurga...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,28.404360,77.072284,K91502068
2039,"4 Bedroom House for sale in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,emaar emerald hills,3.55,17962,1975 sqft Builtup Area,NaN,17962.0,4,0,NaN,"Sector 65, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Pragyanam School', 'CK Birla Hospital, Gurga...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,28.404360,77.072284,P91402540
2047,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,U91316134
2048,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,Y91663054
2049,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,H91668606
2050,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,6,NaN,0,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,U91247428
2051,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,Z91333184
2052,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,0,NaN,5,NaN,0,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,A90966806

- Zero balcony = Missing due to parsing issue might have to fill manually for these 25 missing balcony values.

#### 7. Facing

In [86]:
column_cleaning['facing'].describe()

count           2038
unique             9
top       North-East
freq             501
Name: facing, dtype: object

In [87]:
column_cleaning['facing'].value_counts()

facing
North-East    501
North         435
0             402
East          270
South         140
North-West    116
South-East     71
West           53
South-West     50
Name: count, dtype: int64

In [89]:
column_cleaning['facing'].isnull().sum()

np.int64(0)

#### 8. Age Possession

In [90]:
column_cleaning['agePossession'].value_counts()

agePossession
1    693
2    563
3    403
6    324
5     53
0      2
Name: count, dtype: int64

In [91]:
column_cleaning['agePossession'].isnull().sum()

np.int64(0)

- Verified mapping from 99acres:
  - **0** = Undefined
  - **1** = 1 to 5 Year Old
  - **2** = 5 to 10 Year Old
  - **3** = 10+ Year Old
  - **5** = Under Construction
  - **6** = 0 to 1 Year Old (New)

#### 9. Carpet Area

In [93]:
column_cleaning['carpetArea'].describe()

count      398.000000
mean      2624.764724
std       2556.958847
min         10.110000
25%        450.000000
50%       1615.000000
75%       4200.000000
max      12000.000000
Name: carpetArea, dtype: float64

In [92]:
column_cleaning['carpetArea'].isnull().sum()

np.int64(1640)

#### 10. Furnishing

In [94]:
column_cleaning['furnishing'].unique()

array(['Semi-Furnished', 'Unfurnished', '0', 'Furnished'], dtype=object)

- 0 means missing values

#### 11. Overlooking

In [95]:
column_cleaning['overlooking'].value_counts()

overlooking
Main Road                                                 369
Others                                                    225
Park/Garden                                               194
Park/Garden, Main Road                                    127
Main Road, Park/Garden                                     55
Pool, Park/Garden, Club, Main Road, Others                 52
Pool, Park/Garden, Club, Main Road                         41
Park/Garden, Main Road, Others                             34
Park/Garden, Others                                        22
Main Road, Others                                          19
Pool, Park/Garden                                          19
Park/Garden, Club, Main Road                               17
Pool, Park/Garden, Club, Main Road, Others, Sea facing     15
Pool, Others, Park/Garden, Club, Main Road                 15
Others, Main Road                                          14
Pool, Park/Garden, Club                                    13
Park/Garden, Club                                          11
Others, Park/Garden                                        10
Pool, Park/Garden, Main Road                                9
Main Road, Club, Park/Garden, Pool                          7
Main Road, Others, Park/Garden                              7
Club                                                        7
Park/Garden, Pool, Club, Main Road, Others                  6
Main Road, Park/Garden, Club                                6
Park/Garden, Club, Pool                                     6
Pool, Park/Garden, Club, Others, Main Road, Sea facing      5
Others, Main Road, Club, Park/Garden, Pool                  5
Park/Garden, Main Road, Club                                5
Club, Main Road                                             5
Pool, Main Road                                             5
Park/Garden, Pool, Main Road                                4
Pool, Park/Garden, Main Road, Others                        4
Club, Park/Garden                                           4
Main Road, Club                                             4
Pool                                                        4
Pool, Park/Garden, Club, Others, Main Road                  4
Park/Garden, Club, Main Road, Others                        4
Park/Garden, Pool, Club, Main Road                          4
Park/Garden, Others, Main Road                              4
Pool, Park/Garden, Club, Main Road, Sea facing              4
Main Road, Club, Park/Garden                                4
Park/Garden, Pool                                           3
Pool, Park/Garden, Others, Main Road, Club                  3
Pool, Park/Garden, Main Road, Club                          3
Park/Garden, Main Road, Sea facing                          3
Pool, Club, Park/Garden, Main Road, Others                  2
Park/Garden, Pool, Club                                     2
Pool, Main Road, Sea facing                                 2
Park/Garden, Pool, Club, Main Road, Others, Sea facing      2
Pool, Club                                                  2
Pool, Club, Main Road                                       2
Park/Garden, Club, Others, Main Road, Pool                  2
Pool, Park/Garden, Club, Main Road, Sea facing, Others      2
Park/Garden, Club, Pool, Main Road                          2
Pool, Park/Garden, Main Road, Club, Others                  2
Park/Garden, Main Road, Others, Club, Sea facing, Pool      2
Club, Main Road, Park/Garden                                2
Main Road, Park/Garden, Others                              2
Park/Garden, Pool, Others                                   2
Park/Garden, Main Road, Others, Sea facing                  2
Park/Garden, Club, Main Road, Pool                          2
Pool, Park/Garden, Others                                   2
Others, Club, Main Road                                     2
Park/Garden, Club, Main Road, Others, Pool                  2
Club, Pool, Park/Garden                                     2
Pool, Club, Park/Garden, Main Road                          2
Park/Garden, Main Road, Pool                                2
Others, Main Road, Park/Garden                              2
Park/Garden, Club, Others, Main Road, Sea facing            2
Pool, Main Road, Park/Garden                                2
Club, Park/Garden, Main Road                                2
Others, Park/Garden, Main Road                              2
Pool, Park/Garden, Club, Others                             2
Club, Park/Garden, Pool, Main Road, Others                  2
Main Road, Others, Club, Park/Garden, Pool                  1
Others, Club, Park/Garden, Main Road                        1
Pool, Club, Main Road, Park/Garden, Others                  1
Club, Pool, Park/Garden, Main Road, Others                  1
Park/Garden, Pool, Main Road, Club, Others                  1
Park/Garden, Main Road, Pool, Club                          1
Pool, Main Road, Sea facing, Park/Garden, Club              1
Pool, Park/Garden, Club, Sea facing, Main Road, Others      1
Park/Garden, Main Road, Club, Pool, Others                  1
Park/Garden, Pool, Main Road, Club                          1
Park/Garden, Club, Others, Sea facing, Main Road, Pool      1
Pool, Park/Garden, Club, Others, Sea facing, Main Road      1
Club, Main Road, Sea facing                                 1
Park/Garden, Others, Main Road, Pool                        1
Park/Garden, Main Road, Others, Club, Pool                  1
Park/Garden, Club, Pool, Main Road, Sea facing, Others      1
Park/Garden, Pool, Main Road, Club, Sea facing, Others      1
Pool, Others, Park/Garden, Main Road, Club                  1
Park/Garden, Main Road, Sea facing, Others                  1
Main Road, Park/Garden, Sea facing                          1
Club, Park/Garden, Others, Pool, Main Road                  1
Park/Garden, Pool, Main Road, Others                        1
Club, Park/Garden, Pool                                     1
Pool, Main Road, Park/Garden, Others, Club, Sea facing      1
Main Road, Pool                                             1
Sea facing, Main Road, Pool, Park/Garden, Club              1
Others, Club, Pool                                          1
Park/Garden, Pool, Club, Others, Main Road, Sea facing      1
Club, Others, Park/Garden, Pool, Main Road, Sea facing      1
Pool, Club, Park/Garden, Others, Main Road, Sea facing      1
Others, Park/Garden, Club, Pool, Main Road                  1
Pool, Others, Park/Garden, Club                             1
Park/Garden, Others, Main Road, Sea facing                  1
Main Road, Others, Park/Garden, Club                        1
Pool, Others, Park/Garden                                   1
Others, Club, Main Road, Park/Garden, Pool                  1
Main Road, Sea facing                                       1
Park/Garden, Main Road, Club, Sea facing, Others            1
Main Road, Sea facing, Others                               1
Main Road, Pool, Park/Garden, Sea facing                    1
Others, Pool, Park/Garden, Club, Main Road, Sea facing      1
Park/Garden, Pool, Others, Main Road                        1
Park/Garden, Pool, Main Road, Others, Club, Sea facing      1
Pool, Main Road, Sea facing, Park/Garden, Others, Club      1
Pool, Main Road, Park/Garden, Others, Club                  1
Pool, Club, Park/Garden, Sea facing, Main Road, Others      1
Pool, Club, Park/Garden, Others, Main Road                  1
Club, Park/Garden, Others, Main Road, Pool                  1
Main Road, Park/Garden, Club, Others                        1
Pool, Others, Club, Park/Garden, Main Road                  1
Main Road, Sea facing, Others, Park/Garden                  1
Park/Garden, Main Road, Pool, Others                        1
Pool, Park/Garden, Main Road, Sea facing, Others, Club      1
Pool, Park/Garden, Others, Club, Sea facing, Main Road      1
Park/Garden, Club, Others, Main Road                        1
Club, Main Road, Park/Garden, Pool                          1
Club, Pool, Park/Garden, Others, Main Road, Sea facing      1
Pool, Club, Main Road, Park/Garden                          1
Pool, Club, Others, Sea facing, Main Road, Park/Garden      1
Main Road, Park/Garden, Pool, Club, Others                  1
Pool, Park/Garden, Others, Club, Main Road                  1
Pool, Main Road, Sea facing, Park/Garden                    1
Pool, Main Road, Park/Garden, Club                          1
Pool, Main Road, Sea facing, Others, Park/Garden, Club      1
Club, Main Road, Others                                     1
Park/Garden, Others, Club                                   1
Main Road, Club, Park/Garden, Pool, Others                  1
Main Road, Others, Sea facing, Park/Garden                  1
Park/Garden, Pool, Others, Sea facing, Main Road            1
Park/Garden, Main Road, Others, Pool                        1
Park/Garden, Others, Main Road, Club, Pool                  1
Pool, Park/Garden, Others, Main Road, Sea facing            1
Others, Main Road, Sea facing                               1
Park/Garden, Main Road, Club, Pool                          1
Park/Garden, Sea facing                                     1
Club, Pool                                                  1
Club, Park/Garden, Main Road, Pool                          1
Park/Garden, Pool, Club, Others, Main Road                  1
Club, Pool, Main Road                                       1
Pool, Main Road, Others, Park/Garden, Club                  1
Park/Garden, Pool, Club, Main Road, Sea facing, Others      1
Pool, Club, Park/Garden                                     1
Name: count, dtype: int64

In [96]:
column_cleaning['overlooking'].isnull().sum()

np.int64(517)

#### 12. Corner Property

In [97]:
column_cleaning['cornerProperty'].value_counts()

cornerProperty
Y    543
Name: count, dtype: int64

In [98]:
column_cleaning['cornerProperty'].isnull().sum()

np.int64(1495)

#### 13. Floor Number

In [99]:
column_cleaning['floorNum'].value_counts()[:20]

C:\Users\Jay Patel\AppData\Local\Temp\ipykernel_12184\1275185186.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  column_cleaning['floorNum'].value_counts()[:20]

Series([], Name: count, dtype: int64)

- Missing in floornum for independent houses, as it is not applicable. We can drop this column.

#### 14. Area With Type

In [100]:
column_cleaning['areaWithType'].value_counts()[:20]

areaWithType
900 sqft Super Area     112
540 sqft Super Area      96
3240 sqft Super Area     87
2700 sqft Super Area     79
4500 sqft Super Area     79
1449 sqft Super Area     61
2160 sqft Super Area     56
2367 sqft Super Area     55
2430 sqft Super Area     52
1440 sqft Super Area     50
4518 sqft Super Area     45
2250 sqft Super Area     34
1800 sqft Super Area     32
3600 sqft Super Area     32
594 sqft Super Area      27
5400 sqft Super Area     24
3078 sqft Super Area     22
1935 sqft Super Area     21
450 sqft Super Area      20
1836 sqft Super Area     19
Name: count, dtype: int64

#### 15. Address (Locality)

In [101]:
column_cleaning['address'].value_counts()[:20]

address
Sector 109, Gurgaon             107
Sector 48, Gurgaon               61
DLF Phase 2, Gurgaon             58
Palam Vihar, Gurgaon             58
Sector 46, Gurgaon               56
Nirvana Country, Gurgaon         47
Sector 66, Gurgaon               45
Sector 57, Gurgaon               44
DLF Phase 1, Gurgaon             44
Sector 40, Gurgaon               41
Sector 82, Gurgaon               41
Sushant Lok Phase 1, Gurgaon     38
Sector 33, Gurgaon               36
Sector 47, Gurgaon               35
Sector 45, Gurgaon               34
Sector 4, Gurgaon                33
Sector 52, Gurgaon               30
Sector 23, Gurgaon               27
DLF Phase 3, Gurgaon             27
Sector 71, Gurgaon               27
Name: count, dtype: int64

In [102]:
column_cleaning['address'].nunique()

199

#### 16. Parking

In [103]:
column_cleaning['parking'].value_counts()[:20]

parking
["N"]            254
{"O":1,"C":1}    229
{"C":2}          192
{"O":2,"C":2}    181
{"O":2}          175
{"O":1}          135
{"C":1}          129
{"O":1,"C":2}     99
{"O":3,"C":2}     71
{"O":3}           71
{"O":2,"C":1}     68
{"O":2,"C":3}     51
{"O":4}           39
{"C":3}           35
{"O":3,"C":3}     28
{"O":1,"C":3}     23
{"O":3,"C":1}     23
{"O":2,"C":4}     22
{"C":4}           16
{"O":5}           11
Name: count, dtype: int64

- Parking parsing (C=Covered, O=Open, N=None) will be done in feature engineering.

#### 17. Features, Description, Nearby, Lat/Long

In [104]:
print(f"Features nulls: {column_cleaning['features'].isnull().sum()}")
print(f"Description nulls: {column_cleaning['description'].isnull().sum()}")
print(f"NearbyLocations nulls: {column_cleaning['nearbyLocations'].isnull().sum()}")
print(f"Latitude nulls: {column_cleaning['latitude'].isnull().sum()}")
print(f"Longitude nulls: {column_cleaning['longitude'].isnull().sum()}")

Features nulls: 593
Description nulls: 0
NearbyLocations nulls: 61
Latitude nulls: 0
Longitude nulls: 0

### Final Cleaning Pipeline

In [106]:
AGE_POSSESSION_MAP = {
    0: 'Undefined', 1: '1 to 5 Year Old', 2: '5 to 10 Year Old',
    3: '10+ Year Old', 5: 'Under Construction', 6: '0 to 1 Year Old'
}


column_cleaning = (
    df_house
    .rename(columns={
    'price': 'price_in_cr',
    'area': 'price_per_sqft'})

    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
            )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
            )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (~df_['price_in_cr'].str.contains('-', na=False))   # drop range listings (multi-unit projects)
                    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            4
        )
            )
    .assign(
        price_per_sqft=lambda df_: (
            df_['price_per_sqft']
            .str.split('₹')
            .str.get(1)
            .str.split('/')
            .str.get(0)
            .str.replace('L', '', regex=False)
            .str.replace(',', '', regex=False)
            .str.strip()
            .pipe(pd.to_numeric, errors='coerce')
            .mul(
                np.where(
                    df_['price_per_sqft'].str.contains('L', na=False),
                    100000,
                    1
                )
            )
            .div(
                np.where(
                    df_['price_per_sqft'].str.contains('/sqyd', case=False, na=False),
                    9,
                    1
                )
            )
            .round()
            .astype('Int64')
        )
    
    , facing=lambda df_: df_['facing']
                                .replace('0', "Not Available")
                                .str
                                .lower()
    , furnishing=lambda df_: df_['furnishing']
                                .replace('0', "Not Available")
                                .str
                                .lower()
    , agePossession=lambda df_: df_['agePossession'].map(AGE_POSSESSION_MAP).fillna('Undefined')
    ))

print(f'Shape: {column_cleaning.shape}')
print(f'\nNull counts:')
print(column_cleaning.isnull().sum())
column_cleaning.head()

Shape: (2038, 25)

Null counts:
property_name         0
link                  0
society            1014
price_in_cr           0
price_per_sqft       15
areaWithType          0
carpetArea         1640
pricePerSqft         15
bedRoom               0
bathroom              0
balcony              25
address               0
floorNum           2038
facing                0
overlooking         517
agePossession         0
cornerProperty     1495
furnishing            0
parking              41
nearbyLocations      61
description           0
features            593
latitude              0
longitude             0
property_id           0
dtype: int64

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"5 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,sobha international city phase 4,14.50,40333,3600 sqft Super Area,NaN,362500.0,5,7,4.0,"Sector 109, Gurgaon",NaN,north,"Pool, Park/Garden, Club, Main Road",1 to 5 Year Old,Y,semi-furnished,"{""O"":1,""C"":3}","['Palam Vihar Vyapar kendra', 'Kalyan Hospital...",Check out this 5 bhk house for sale in sector ...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.513497,77.004111,L87277236
1,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 2,8.40,15556,5400 sqft Super Area,5175.0,140000.0,4,4,4.0,"Sector 109, Gurgaon",NaN,north-east,"Main Road, Others, Club, Park/Garden, Pool",1 to 5 Year Old,Y,unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city is a premium luxury v...,"['Centrally Air Conditioned', 'Security / Fire...",28.515220,76.997752,U90119426
2,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 2,10.35,19222,5400 sqft Super Area,NaN,172500.0,4,4,3.0,"Sector 109, Gurgaon",NaN,east,"Pool, Park/Garden, Club, Main Road, Others",1 to 5 Year Old,NaN,unfurnished,"{""O"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city | ready to move\n 4bh...,"['Security / Fire Alarm', 'Vaastu Compliant', ...",28.509743,77.005068,M77295073
3,"6 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,international city by sobha phase 2,20.50,45556,4500 sqft Super Area,490.0,410000.0,6,6,4.0,"Sector 109, Gurgaon",NaN,north-east,"Others, Main Road, Club, Park/Garden, Pool",1 to 5 Year Old,Y,unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city is a premium luxury v...,"['Centrally Air Conditioned', 'Security / Fire...",28.514088,77.003366,B90120220
4,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.00,41111,2430 sqft Super Area,180.0,370370.0,4,4,2.0,"Sector 109, Gurgaon",NaN,north,Main Road,1 to 5 Year Old,NaN,unfurnished,"{""O"":2}","['The Shikshiyan School', 'Dharampeth Main Roa...",The flat is over 270 sq.Yd. Super built up are...,"['Private Garden / Terrace', 'High Ceiling Hei...",28.511604,77.007325,T90277756

In [107]:
column_cleaning

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,pricePerSqft,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"5 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,sobha international city phase 4,14.50,40333,3600 sqft Super Area,NaN,362500.0,5,7,4.0,"Sector 109, Gurgaon",NaN,north,"Pool, Park/Garden, Club, Main Road",1 to 5 Year Old,Y,semi-furnished,"{""O"":1,""C"":3}","['Palam Vihar Vyapar kendra', 'Kalyan Hospital...",Check out this 5 bhk house for sale in sector ...,"['Vaastu Compliant', 'Private Garden / Terrace...",28.513497,77.004111,L87277236
1,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 2,8.40,15556,5400 sqft Super Area,5175.0,140000.0,4,4,4.0,"Sector 109, Gurgaon",NaN,north-east,"Main Road, Others, Club, Park/Garden, Pool",1 to 5 Year Old,Y,unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city is a premium luxury v...,"['Centrally Air Conditioned', 'Security / Fire...",28.515220,76.997752,U90119426
2,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 2,10.35,19222,5400 sqft Super Area,NaN,172500.0,4,4,3.0,"Sector 109, Gurgaon",NaN,east,"Pool, Park/Garden, Club, Main Road, Others",1 to 5 Year Old,NaN,unfurnished,"{""O"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city | ready to move\n 4bh...,"['Security / Fire Alarm', 'Vaastu Compliant', ...",28.509743,77.005068,M77295073
3,"6 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,international city by sobha phase 2,20.50,45556,4500 sqft Super Area,490.0,410000.0,6,6,4.0,"Sector 109, Gurgaon",NaN,north-east,"Others, Main Road, Club, Park/Garden, Pool",1 to 5 Year Old,Y,unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector 21 Metro Station', 'Pacific D2...",Sobha international city is a premium luxury v...,"['Centrally Air Conditioned', 'Security / Fire...",28.514088,77.003366,B90120220
4,"4 Bedroom House for sale in Sector 109, Gurgaon",https://www.99acres.com/4-bhk-bedroom-independ...,international city by sobha phase 1,10.00,41111,2430 sqft Super Area,180.0,370370.0,4,4,2.0,"Sector 109, Gurgaon",NaN,north,Main Road,1 to 5 Year Old,NaN,unfurnished,"{""O"":2}","['The Shikshiyan School', 'Dharampeth Main Roa...",The flat is over 270 sq.Yd. Super built up are...,"['Private Garden / Terrace', 'High Ceiling Hei...",28.511604,77.007325,T90277756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,not available,NaN,0 to 1 Year Old,NaN,not available,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,H91668606
2050,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,puri diplomatic greens,12.47,15593,8000 sqft Builtup Area,NaN,15593.0,5,0,NaN,"Sector 111, Gurgaon",NaN,not available,NaN,0 to 1 Year Old,NaN,not available,"[""N""]","['Park Hospital', 'Red Roses Public School', '...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,28.518764,77.027976,U91247428
2051,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,not available,NaN,Under Construction,NaN,not available,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,Z91333184
2052,"5 Bedroom House for sale in Sector 111, Gurgaon",https://www.99acres.com/5-bhk-bedroom-independ...,kashish manor one,6.93,12371,5600 sqft Builtup Area,NaN,12371.0,5,0,NaN,"Sector 111, Gurgaon",NaN,not available,NaN,Under Construction,NaN,not available,"[""N""]","['Park Hospital, Palam Vihar', 'Indira Gandhi ...","Kashish manor one in sector-111 gurgaon, gurga...",NaN,28.510350,77.020683,A90966806
2053,"6 Bedroom House for sale in Ardee City, Gurgaon",https://www.99acres.com/6-bhk-bedroom-independ...,NaN,5.10,35222,1449 sqft Super Area,120.0,316770.0,6,6,4.0,"Ardee City, Gurgaon",NaN,north-west,Main Road,5 to 10 Year Old,NaN,unfurnished,"{""O"":3,""C"":1}","['Huda city centre metro station', 'Hanuman Ma...",A ready to move house is available for sale. 2...,NaN,28.442230,77.078030,K91666140