In [ ]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
import json as json
pd.set_option('display.max_columns', 500)

### 1. Flats Data Loading

In [ ]:
df_flat = pd.read_csv('../../data/web_scraping/flats_gurgaon.csv')
df_flat.sample(15)

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
10776,"4 BHK Flat in Sector 54, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Crest,Price on Request,₹0 /sqft,4022 sqft Superbuiltup Area,NaN,4,5,4.0,"Sector 54, Gurgaon",16 of 38 Floors,North-East,"Park/Garden, Pool, Club, Main Road",1,Y,Furnished,"{""C"":2}","['Golf Course Road', 'Sector 53-54 Metro Stati...",Fully furnished super luxury apartment in the ...,"['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.444951,77.111544,T59551064
18145,"3 BHK Flat in Sector 103, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Indiabulls Centrum Park,1.95 Cr,"₹10,263 /sqft",1900 sqft Superbuiltup Area,1789.00,3,3,4.0,"Sector 103, Gurgaon",9 of 18 Floors,North-West,"Pool, Park/Garden, Club, Main Road",1,Y,Semi-Furnished,"{""C"":2}","['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",This is a north-West-Facing property. The floo...,"['Full Power Backup', 'Gurgaon Railway station...",28.497675,76.981636,H90957964
27717,"3 BHK Flat in Sector 36 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Signature Global Park 4,1.1 Cr,"₹10,176 /sqft",1081 sqft Superbuiltup Area,NaN,3,2,3.0,"Sector 36 Sohna, Gurgaon",4 of 4 Floors,East,Main Road,1,NaN,0,"[""N""]","['Badshahpur Sohna Rd Hwy', 'Vidya Niketan Sch...",The flat is facing the north direction. Contai...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.296569,77.064526,D91190104
14507,"3 BHK Flat in Sector 76, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Whiteland Blissville,2.18 Cr,"₹13,038 /sqft",1672 sqft Superbuiltup Area,NaN,3,3,4.0,"Sector 76, Gurgaon",1 of 4 Floors,North-East,"Main Road, Club, Park/Garden, Pool, Others",6,Y,Unfurnished,"{""O"":1,""C"":1}","['Govt. Stadium Hasanpur', 'NH 48', 'Aatish Ho...",Whiteland blissville enjoys a prime location w...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.393887,76.992553,K88413218
12293,"3 BHK Flat in Sector 66, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ireo Uptown,3.2 Cr,"₹17,094 /sqft",1872 sqft Superbuiltup Area,1500.00,3,3,4.0,"Sector 66, Gurgaon",8 of 23 Floors,North-East,"Pool, Park/Garden, Club",3,Y,Unfurnished,"{""O"":1,""C"":1}","['Shiksha Bharti Public School', 'Landmark Cyb...",This residential flat is north-East-Facing dir...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.402078,77.051667,E88797318
21339,"3 BHK Flat in Sector 67, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ireo Victory Valley,4.35 Cr,"₹18,239 /sqft",2385 sqft Superbuiltup Area,NaN,3,3,1.0,"Sector 67, Gurgaon",23 of 51 Floors,North-West,"Pool, Park/Garden, Club, Main Road",2,Y,Unfurnished,"{""C"":2}","['Sector 55-56 metro', 'AIPL Joy Street Mall',...",This property faces the north-West direction. ...,"['Full Power Backup', 'Visitor Parking Availab...",28.391640,77.065128,A90546454
1452,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Ashiana Anmol,1.4 Cr,"₹14,737 /sqft",1275 sqft Builtup Area,950.00,2,2,2.0,"Sohna, Gurgaon",10 of 14 Floors,North,NaN,2,NaN,Unfurnished,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",Park facing apartment with all the modern faci...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.286932,77.069609,P88373324
26986,"3 BHK Flat in Sector 43, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ansal Maple Heights,2.2 Cr,"₹16,479 /sqft",1335 sqft Superbuiltup Area,1195.00,3,3,2.0,"Sector 43, Gurgaon",7 of 14 Floors,North-East,"Park/Garden, Others",3,NaN,Unfurnished,"{""O"":1}","['Millennium City Centre', 'Ardee Mall', 'NH 4...",This complex location is prime location in gur...,"['Full Power Backup', '24*7 Water', 'Visitor P...",28.451953,77.080697,Y84466236
14699,"3 BHK Flat in Sector 111, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Puri Diplomatic Residences,4.05 Cr,"₹23,497 /sqft",2380 sqft Superbuiltup Area,1723.63,3,3,3.0,"Sector 111, Gurgaon",10 of 32 Floors,North-East,Pool,5,NaN,Unfurnished,"{""C"":3}","['Mount School', 'Monika Hospital', 'Dwarka Ex...",This under-Construction 3 bhk apartment spans ...,"['Full Power Backup', 'Centrally Air Condition...",28.525665,77.030733,F89506630
2856,"4 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Bestech Altura,3.34 Cr,"₹12,486 /sqft",2675 sqft Superbuiltup Area,2000.00,4,5,2.0,"Sector 79, Gurgaon",8 of 20 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",6,Y,Unfurnished,"{""C"":2}","['Mount Olympus Junior School', 'Miracles Apol...",Bestech altura is one of the most popular dest...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.356553,76.972930,L86618602
8854,"3 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,M3M Capital,2.69 Cr,"₹16,300 /sqft",1650 sqft Superbuiltup Area,1155.00,3,3,4.0,"Sector 113, Gurgaon",19 of 36 Floors,North-East,"Pool, Park/Garden",5,Y,Unfurnished,"{""C"":1}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",This residential flat is north-East-Facing dir...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.525769,77.027318,K91307718
12711,"3 BHK Flat in Sector 86, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,DLF The Skycourt,2.25 Cr,"₹11,664 /sqft",1929 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 86, Gurgaon",5 of 19 Floors,South,"Pool, Park/Garden, Main Road, Club",1,Y,Unfurnished,"{""C"":2}","['Holiday Inn Hotel Sector 90', 'Rao Bharat Si...",Dlf skycourt semi furnished flat,"['Full Power Backup', 'Centrally Air Condition...",28.404373,76.939876,O90091084
1197,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Eldeco Accolade,95 Lac,"₹7,486 /sqft",1269 sqft Superbuiltup Area,NaN,2,2,3.0,"Sohna, Gurgaon",15 of 19 Floors,0,NaN,1,NaN,Unfurnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...","Containing 2 bedroom(s), 2 bathrooms and 3 bal...",['Parking Available'],28.266652,77.064904,V91036456
1013,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Eldeco Acclaim,1.35 Cr,"₹10,638 /sqft",1269 sqft Superbuiltup Area,726.00,2,2,3.0,"Sohna, Gurgaon",5 of 18 Floors,East,"Pool, Park/Garden, Club, Main Road",1,NaN,Unfurnished,"{""C"":1}","['G D Goenka University', 'Fly India Adventure...",This residential flat is north-Facing directio...,"['Full Power Backup', 'Visitor Parking Availab...",28.464311,77.062587,K91238396
9496,"3 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Zenith,4.25 Cr,"₹18,008 /sqft",2360 sqft Carpet Area,2360.00,3,4,3.0,"Sector 89, Gurgaon",4 of 37 Floors,East,"Club, Main Road",5,NaN,Unfurnished,"{""C"":2}","['City Square', 'NH 352W', 'RPS International ...","Located in godrej zenith, sector 89, gurgaon, ...","['Full Power Backup', 'Visitor Parking Availab...",28.411256,76.952234,P90433106

In [150]:
df_flat.shape

(28531, 24)

In [106]:
df_flat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28531 entries, 0 to 28530
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    28531 non-null  object
 1   link             28531 non-null  object
 2   society          28516 non-null  object
 3   price            28531 non-null  object
 4   area             28149 non-null  object
 5   areaWithType     28531 non-null  object
 6   carpetArea       18216 non-null  float64
 7   bedRoom          28531 non-null  int64
 8   bathroom         28531 non-null  int64
 9   balcony          28521 non-null  float64
 10  address          28531 non-null  object
 11  floorNum         28531 non-null  object
 12  facing           28531 non-null  object
 13  overlooking      24550 non-null  object
 14  agePossession    28531 non-null  int64
 15  cornerProperty   18622 non-null  object
 16  furnishing       28531 non-null  object
 17  parking          28257 non-null  object
 18  nearbyLocations  28462 non-null  object
 19  description      28531 non-null  object
 20  features         27841 non-null  object
 21  latitude         28531 non-null  float64
 22  longitude        28531 non-null  float64
 23  property_id      28531 non-null  object
dtypes: float64(4), int64(3), object(17)
memory usage: 5.2+ MB

In [107]:
df_flat.describe(include='all')

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
count,28531,28531,28516,28531,28149,28531,1.821600e+04,28531.000000,28531.000000,28521.000000,28531,28531,28531,24550,28531.000000,18622,28531,28257,28462,28531,27841,28531.000000,28531.000000,28531
unique,549,28531,1298,1489,11689,3749,NaN,NaN,NaN,NaN,188,1180,9,683,NaN,1,4,63,895,26734,16378,NaN,NaN,28531
top,"3 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Godrej Air,2.5 Cr,"₹10,000 /sqft",2150 sqft Superbuiltup Area,NaN,NaN,NaN,NaN,"Sohna, Gurgaon",2 of 4 Floors,North,"Pool, Park/Garden, Club, Main Road, Others",NaN,Y,Unfurnished,"{""C"":1}","['Genesis Hospital', 'Iris Broadway', 'Euro In...",This property is very good becaouse of it's at...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",NaN,NaN,M89360483
freq,666,1,451,417,124,242,NaN,NaN,NaN,NaN,1110,691,8693,3346,NaN,18622,19764,9715,450,64,367,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.555156e+03,2.970909,3.173005,2.924231,NaN,NaN,NaN,NaN,2.961060,NaN,NaN,NaN,NaN,NaN,NaN,28.574551,76.766930,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.180501e+03,0.771056,1.088899,0.945782,NaN,NaN,NaN,NaN,2.030505,NaN,NaN,NaN,NaN,NaN,NaN,3.815680,3.479130,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,9.438000e+02,2.000000,2.000000,2.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.394920,76.969227,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.347000e+03,3.000000,3.000000,3.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.411562,77.010746,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.823500e+03,3.000000,4.000000,4.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,28.454369,77.065685,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,1.234567e+06,18.000000,18.000000,4.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,77.150639,77.150639,NaN

In [20]:
df_flat.head()

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Eldeco Accolade,1.25 Cr,"₹9,850 /sqft",1269 sqft Superbuiltup Area,726.0,2,2,4.0,"Sohna, Gurgaon",2 of 18 Floors,North-East,"Park/Garden, Main Road, Club, Pool, Others",1,Y,Semi-Furnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",The flat is north-East-Facing. The flat occupi...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.259939,77.064480,M89360483
1,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Signature Global Daxin Vistas,3 Cr,"₹19,243 /sqft",1559 sqft Builtup Area,NaN,3,3,2.0,"Sohna, Gurgaon",4 of 4 Floors,0,NaN,5,NaN,Furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...",The flat is over 1559 sq.Ft. Built up area and...,"['Full Power Backup', 'Visitor Parking Availab...",28.332976,77.067894,T91323470
2,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Eldeco Accolade,1.56 Cr,"₹10,744 /sqft",1452 sqft Superbuiltup Area,1000.0,2,2,4.0,"Sohna, Gurgaon",8 of 18 Floors,North,"Pool, Park/Garden, Club",1,Y,Unfurnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",It's spacious 2.5 bhk with an extremely open a...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.266652,77.064904,F89903984
3,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ashiana Anmol,2.16 Cr,"₹12,162 /sqft",1776 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",10 of 14 Floors,North-East,"Park/Garden, Main Road",6,Y,0,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. C...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286897,77.071375,Z90919772
4,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Central Park Flower Valley The Room,2.55 Cr,"₹14,254 /sqft",1789 sqft Builtup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 14 Floors,North,NaN,6,Y,Furnished,"{""C"":1}","['Huda Metro Station', 'Raheja Mall', 'Central...",For those who prefer high end living\nWelcome ...,"['Full Power Backup', 'Close to School', 'Cent...",28.284257,77.079086,H84077598

In [22]:
df_flat.duplicated(subset=['property_name', 'society','price','area']).sum()

np.int64(6909)

In [31]:
df_flat[df_flat.duplicated(subset=['property_name', 'society','price','area','floorNum','facing'],keep=False)].sort_values(by=['property_name', 'society','price','area'])

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
21724,"1 BHK Flat in Sector 63A, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,AIPL Joy Square,75 Lac,"₹10,823 /sqft",693 sqft Carpet Area,693.0,1,1,1.0,"Sector 63A, Gurgaon",3 of 9 Floors,0,NaN,6,NaN,0,"[""N""]","['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",Aipl brand name of belive in gurgaon,"['On-Call Maintenance Staff', 'Vaastu Compliant']",28.392385,77.092574,X86352404
21725,"1 BHK Flat in Sector 63A, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,AIPL Joy Square,75 Lac,"₹10,823 /sqft",693 sqft Carpet Area,693.0,1,1,1.0,"Sector 63A, Gurgaon",3 of 9 Floors,0,NaN,6,NaN,Furnished,"[""N""]","['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",Property in good location and very good builde...,"['Centrally Air Conditioned', 'On-Call Mainten...",28.392385,77.092574,R86203588
27759,"2 BHK Flat in DLF Phase 3, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Cyber City,32.95 Lac,"₹3,250 /sqft",1014 sqft Builtup Area,765.0,2,2,3.0,"DLF Phase 3, Gurgaon",14 of 14 Floors,North,"Pool, Park/Garden, Club, Main Road, Others",6,Y,Furnished,"{""O"":1}","['Dlf phase 3 metro station', 'Vodafone belved...",Terra castle\n\nProject overview\nAddress: Alw...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.494533,77.090266,Y90542882
27760,"2 BHK Flat in DLF Phase 3, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Cyber City,32.95 Lac,"₹3,250 /sqft",1014 sqft Builtup Area,765.0,2,2,3.0,"DLF Phase 3, Gurgaon",14 of 14 Floors,North,"Park/Garden, Pool, Club, Main Road, Others",6,Y,Furnished,"{""O"":1}","['Dlf phase 3 metro station', 'Vodafone belved...",Terra castle\n\nProject overview\nAddress: Alw...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.494533,77.090266,O89987224
26439,"2 BHK Flat in DLF Phase 4, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,DLF Regency Park 1,2.15 Cr,"₹18,696 /sqft",1150 sqft Superbuiltup Area,1020.0,2,2,2.0,"DLF Phase 4, Gurgaon",12 of 26 Floors,North-East,"Park/Garden, Others",3,NaN,Unfurnished,"{""C"":1}","['DPSG Sushant Lok', 'Sushant University', 'Pa...",Available for sale 2bedroom in dlf ragency par...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.460056,77.089036,M88293786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12893,"4 BHK Flat in Sector 86, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF New Town Heights 2,2.55 Cr,"₹10,787 /sqft",2364 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 86, Gurgaon",6 of 22 Floors,North,"Club, Pool",2,Y,Unfurnished,"{""C"":2}","['Bharat Ram Global School', 'Canara Bank ATM'...","9911 619690 .. Call for more details and visit,","['Full Power Backup', 'Visitor Parking Availab...",28.402874,76.938147,D90052204
25782,"4 BHK Flat in Sector 91, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF New Town Heights,2.45 Cr,"₹10,364 /sqft",2364 sqft Superbuiltup Area,2000.0,4,4,4.0,"Sector 91, Gurgaon",19 of 21 Floors,North,"Pool, Park/Garden, Club, Main Road, Others",3,Y,Unfurnished,"{""O"":1,""C"":2}","['KLAY Play School', 'RHM Public School', 'San...",Contact-9910-50-16-93 for more details or visi...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.401809,76.917039,N90628238
25798,"4 BHK Flat in Sector 91, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF New Town Heights,2.45 Cr,"₹10,364 /sqft",2364 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 91, Gurgaon",19 of 21 Floors,North,"Pool, Park/Garden, Club, Main Road, Others",3,Y,Unfurnished,"{""O"":1,""C"":2}","['KLAY Play School', 'RHM Public School', 'San...",Contact-99105-01693 for more details or visit ...,"['Full Power Backup', 'Centrally Air Condition...",28.402586,76.917022,P91481228
6266,"4 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Altura at DXP 92,2.35 Cr,"₹14,277 /sqft",2280 sqft Superbuiltup Area,1646.0,4,4,3.0,"Sector 92, Gurgaon",10 of 23 Floors,North,"Pool, Park/Garden, Club, Main Road, Others, Se...",6,NaN,Unfurnished,"{""O"":5,""C"":1}","['Sapphire 90 Mall', 'IMT Manesar', 'Dwarka Ex...","Available immediately, this brand-New 4 bhk fl...","['Full Power Backup', 'Visitor Parking Availab...",28.412987,76.913059,N91082562
6709,"4 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Altura at DXP 92,2.35 Cr,"₹14,277 /sqft",2280 sqft Superbuiltup Area,1646.0,4,5,3.0,"Sector 92, Gurgaon",10 of 23 Floors,North,"Pool, Park/Garden, Club, Main Road, Others, Se...",6,NaN,Unfurnished,"{""O"":10,""C"":1}","['Sapphire 90 Mall', 'IMT Manesar', 'Dwarka Ex...",Located on the 10th floor of a 23-Story high-R...,"['Full Power Backup', 'Visitor Parking Availab...",28.412987,76.913059,N91096872

### 2. Flats Data Cleaning

In [38]:
df_flat.columns

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'carpetArea', 'bedRoom', 'bathroom', 'balcony', 'address', 'floorNum',
       'facing', 'overlooking', 'agePossession', 'cornerProperty',
       'furnishing', 'parking', 'nearbyLocations', 'description', 'features',
       'latitude', 'longitude', 'property_id'],
      dtype='object')

In [39]:
df_flat.isnull().sum()

property_name          0
link                   0
society               15
price                  0
area                 382
areaWithType           0
carpetArea         10311
bedRoom                0
bathroom               0
balcony               10
address                0
floorNum               0
facing                 0
overlooking         3968
agePossession          0
cornerProperty      9891
furnishing             0
parking              272
nearbyLocations       67
description            0
features             686
latitude               0
longitude              0
property_id            0
dtype: int64

In [40]:
missing_summary = (
    df_flat
    .isnull()
    .sum()
    .pipe(lambda s: round((s / len(df_flat)) * 100, 2))
    .reset_index()
    .rename(columns={'index': 'Feature', 0: 'Missing_Percentage'})
    .sort_values(by='Missing_Percentage', ascending=False)
)

In [41]:
missing_summary

            Feature  Missing_Percentage
6        carpetArea               36.17
15   cornerProperty               34.70
13      overlooking               13.92
20         features                2.41
4              area                1.34
17          parking                0.95
18  nearbyLocations                0.24
2           society                0.05
9           balcony                0.04
7           bedRoom                0.00
1              link                0.00
3             price                0.00
0     property_name                0.00
5      areaWithType                0.00
11         floorNum                0.00
8          bathroom                0.00
14    agePossession                0.00
12           facing                0.00
10          address                0.00
16       furnishing                0.00
19      description                0.00
21         latitude                0.00
22        longitude                0.00
23      property_id                0.00

In [42]:
df_flat.shape

(28504, 24)

### 3. Cleaning Individual Columns

In [43]:
df_flat

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Eldeco Accolade,1.25 Cr,"₹9,850 /sqft",1269 sqft Superbuiltup Area,726.0,2,2,4.0,"Sohna, Gurgaon",2 of 18 Floors,North-East,"Park/Garden, Main Road, Club, Pool, Others",1,Y,Semi-Furnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",The flat is north-East-Facing. The flat occupi...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.259939,77.064480,M89360483
1,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Signature Global Daxin Vistas,3 Cr,"₹19,243 /sqft",1559 sqft Builtup Area,NaN,3,3,2.0,"Sohna, Gurgaon",4 of 4 Floors,0,NaN,5,NaN,Furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...",The flat is over 1559 sq.Ft. Built up area and...,"['Full Power Backup', 'Visitor Parking Availab...",28.332976,77.067894,T91323470
2,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Eldeco Accolade,1.56 Cr,"₹10,744 /sqft",1452 sqft Superbuiltup Area,1000.0,2,2,4.0,"Sohna, Gurgaon",8 of 18 Floors,North,"Pool, Park/Garden, Club",1,Y,Unfurnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",It's spacious 2.5 bhk with an extremely open a...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.266652,77.064904,F89903984
3,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ashiana Anmol,2.16 Cr,"₹12,162 /sqft",1776 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",10 of 14 Floors,North-East,"Park/Garden, Main Road",6,Y,0,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. C...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286897,77.071375,Z90919772
4,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Central Park Flower Valley The Room,2.55 Cr,"₹14,254 /sqft",1789 sqft Builtup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 14 Floors,North,NaN,6,Y,Furnished,"{""C"":1}","['Huda Metro Station', 'Raheja Mall', 'Central...",For those who prefer high end living\nWelcome ...,"['Full Power Backup', 'Close to School', 'Cent...",28.284257,77.079086,H84077598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28499,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,KW Royal Court,3.3 Cr,"₹10,252 /sqft",3219 sqft Superbuiltup Area,2500.0,4,5,1.0,"Sector 39, Gurgaon",9 of 12 Floors,North-East,"Park/Garden, Club",1,NaN,Unfurnished,"{""C"":2}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",2500 sqft carpet 4bhk+servant available for sa...,"['On-Call Maintenance Staff', 'Vaastu Complian...",28.441474,77.043613,K90588706
28500,"3 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Alira,7 Cr,"₹28,854 /sqft",2426 sqft Carpet Area,2426.0,3,4,2.0,"Sector 39, Gurgaon",33 of 33 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Rajiv Chowk Mosque', 'State bank of india AT...","Constructed on a carpet area of 2426 sq.Ft., t...",NaN,28.442331,77.049250,E90056680
28501,"2 BHK Flat in Saini Pura, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,bharat residency,70 Lac,"₹7,778 /sqft",900 sqft Carpet Area,900.0,2,2,1.0,"Saini Pura, Gurgaon",2 of 5 Floors,0,NaN,1,NaN,0,"[""N""]","['Rajiv Chowk Mosque', 'State bank of india AT...","Located in bharat residency, saini pura, gurga...",NaN,28.446360,77.051020,E89187547
28502,"2 BHK Flat in Jharsa, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Royal Blue City,1 Cr,"₹11,111 /sqft",900 sqft Carpet Area,100.0,2,2,1.0,"Jharsa, Gurgaon",2 of 4 Floors,East,Main Road,1,NaN,Unfurnished,"{""C"":1}","['IFFCO Chowk', '(HUDA City Centre) Rajiv', 'S...",A well-Maintained and spacious 2 bhk flat in a...,"['Full Power Backup', 'Close to Market', 'Gate...",28.443173,77.052033,O87439246
28503,"3 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,City Heights,2.55 Cr,"₹11,333 /sqft",2250 sqft Superbuiltup Area,2000.0,3,3,2.0,"Sector 39, Gurgaon",2 of 12 Floors,North-East,"Park/Garden, Main Road",2,Y,Unfurnished,"{""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",Looking for a 3 bhk property for sale in gurga...,"['North-East Facing', 'Wheel Chair Friendly', ...",28.440349,77.042917,A87227320

1) Society

In [44]:
df_flat['society'].value_counts()

society
Godrej Air               451
Godrej Meridien          370
Hero Homes               362
Ireo The Corridors       310
Elan The Presidential    309
                        ...
terra bhi                  1
Raheja Revanta             1
the first acre             1
tlc the first acre         1
Diamond court              1
Name: count, Length: 1277, dtype: int64

In [45]:
column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()))
column_cleaning['society'].value_counts()

society
godrej air                                       451
godrej meridien                                  370
hero homes                                       362
ireo the corridors                               310
elan the presidential                            309
                                                ...
cghs hewo apartment                                1
unitech the world spa                              1
sri navjyoti cghs limited                          1
sistal vihar society                               1
bang on nh-8, sector-1, imt manesar (gurgaon)      1
Name: count, Length: 1200, dtype: int64

In [46]:
column_cleaning['society'].isnull().sum()

np.int64(15)

In [47]:
column_cleaning[column_cleaning['society'].isnull()]

,property_name,link,society,price,area,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
9517,"4 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,NaN,1.8 Cr,"₹11,976 /sqft",1503 sqft Builtup Area,NaN,4,4,0.0,"Sector 89, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Orris Community Center', 'Indian Oil', 'Essa...","Containing 4 bedroom(s), 4 bathrooms , this fl...",NaN,28.418284,76.945704,B89922878
11606,"3 BHK Flat in Sector 69, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,5.28 Cr,"₹22,000 /sqft",2400 sqft Builtup Area,NaN,3,3,0.0,"Sector 69, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Looking for a 3 bhk property for sale in gurga...,NaN,28.395628,77.038365,V85227144
14087,"2 BHK Flat in Sector 108, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN,79 Lac,"₹8,778 /sqft",900 sqft Builtup Area,NaN,2,2,2.0,"Sector 108, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,['CHC Jhatikara'],"Containing 2 bedroom(s), 2 bathrooms and 2 bal...",NaN,28.514153,76.980012,V89362535
14983,"3 BHK Flat in Sector 111, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,3.84 Cr,"₹25,600 /sqft",1500 sqft Builtup Area,NaN,3,3,0.0,"Sector 111, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Palam Vihar Vyapar kendra', 'HUDA Sector 23 ...",The flat is over 1500 sq.Ft. Built up area and...,NaN,28.525049,77.032713,L90450858
15491,"1 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,NaN,72 Lac,"₹10,405 /sqft",692 sqft Builtup Area,NaN,1,1,0.0,"Sector 48, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Raheja Mall', 'Sri Radhe Krishna Temple', 'I...",This lovely 1 bhk apartment/flat in sector 48 ...,NaN,28.404552,77.043064,T86388006
18486,"1 BHK Flat in Sector 103, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,NaN,60 Lac,"₹16,854 /sqft",356 sqft Builtup Area,NaN,1,1,1.0,"Sector 103, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Furnished,"[""N""]","['Dr. Hitesh Dawar', 'Bhardwaj Hospital', 'R K...",N/a is one of the most popular destination for...,"['Ground Floor', 'Furnished']",28.495225,76.986900,H87290134
19690,"4 BHK Flat in Sector 90, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,NaN,4 Cr,"₹14,668 /sqft",2727 sqft Builtup Area,NaN,4,4,0.0,"Sector 90, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",The floor plan additionally contains 4 bedroom...,NaN,28.407152,76.936317,G90856032
21030,"5 BHK Flat in Sector 93, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,NaN,2.3 Cr,"₹10,698 /sqft",2150 sqft Builtup Area,NaN,5,5,0.0,"Sector 93, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Yadav Clinic', 'Orris Community Center', 'In...",The flat is over 2150 sq.Ft. Built up area and...,NaN,28.415064,76.932344,X90668926
21420,"2 BHK Flat in Sector 67, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN,80 Lac,"₹9,412 /sqft",850 sqft Builtup Area,NaN,2,2,0.0,"Sector 67, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Furnished,NaN,"['Sri Radhe Krishna Temple', 'Kamal Hospital a...",The floor plan additionally contains 2 bedroom...,NaN,28.383725,77.061876,Q89032984
22452,"3 BHK Flat in Sector 56, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,3.16 Cr,"₹15,682 /sqft",2015 sqft Builtup Area,NaN,3,3,0.0,"Sector 56, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,"[""N""]","['Sector metro station', 'Sector metro station...",The floor plan additionally contains 3 bedroom...,"['Ground Floor', 'Semi-Furnished']",28.423536,77.096291,B90062272
24599,"1 BHK Flat in Sector 72, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,NaN,3.7 Cr,"₹17,746 /sqft",2085 sqft Builtup Area,NaN,1,1,0.0,"Sector 72, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Raheja Mall', 'Icici bank ATM', 'Standard ch...",The flat occupies a built up area of 2085 sq.F...,NaN,28.417421,77.026406,W91011910
26635,"3 BHK Flat in Sector 110, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,90 Lac,"₹9,000 /sqft",1000 sqft Builtup Area,NaN,3,2,2.0,"Sector 110, Gurgaon",G of 1 Floors,North,NaN,6,Y,Unfurnished,"{""C"":1}","['Palam Vihar Vyapar kendra', 'Palam triangle'...","Constructed on a built up area of 1000 sq.Ft.,...","['Ground Floor', 'Newly Constructed', 'Corner ...",28.505202,77.016505,F89740336
27338,"3 BHK Flat in Sector 28, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,3.25 Cr,"₹18,056 /sqft",1800 sqft Builtup Area,NaN,3,3,0.0,"Sector 28, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Dlf phase 1 metro station', 'Mg road metro s...","Containing 3 bedroom(s), 3 bathrooms , this fl...",NaN,28.474112,77.086607,C90477638
27434,"4 BHK Flat in Sector 110 A, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,NaN,1.15 Cr,"₹7,667 /sqft",1500 sqft Builtup Area,NaN,4,4,1.0,"Sector 110 A, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Constructed on a built up area of 1500 sq.Ft.,...",NaN,28.517918,77.026196,D90649100
28178,"4 BHK Flat in Sector 50, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,NaN,4.65 Cr,"₹17,885 /sqft",2600 sqft Builtup Area,NaN,4,4,0.0,"Sector 50, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Raheja Mall', 'Radhakrishna Shani Mandir', '...","Situated in sector 50 gurgaon, n/a is a well p...",NaN,28.414924,77.063009,W86186662

### 2. Price

In [48]:
df_flat = df_flat.rename(columns ={
    'price' : 'price_in_cr',
    'area'  :'price_per_sqft'
})

In [49]:
column_cleaning = (df_flat.assign
                   (
                       price_in_cr = lambda df_:df_['price_in_cr']
                                            .str
                                            .strip()
                   ))
column_cleaning['price_in_cr'].unique()

array(['1.25 Cr', '3 Cr', '1.56 Cr', ..., '16.8 Cr', '15.85 Cr',
       '8.16 Cr'], shape=(1489,), dtype=object)

In [50]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
2.5 Cr      416
2 Cr        386
2.1 Cr      368
2.25 Cr     344
3 Cr        311
           ...
12.41 Cr      1
12.49 Cr      1
8.93 Cr       1
10.64 Cr      1
9.31 Cr       1
Name: count, Length: 1489, dtype: int64

In [51]:
column_cleaning['price_in_cr'].isnull().sum()

np.int64(0)

In [52]:
column_cleaning[column_cleaning['price_in_cr'] == 'Price on Request']

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
1241,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,HCBS Sports Ville,Price on Request,₹0 /sqft,675 sqft Carpet Area,675.0,2,2,1.0,"Sohna, Gurgaon",8 of 13 Floors,0,NaN,2,NaN,Furnished,"{""O"":1,""C"":1}","['The roadside cafe', 'GD Goenka Mess', 'ROyal...","Located in hcbs sports ville, sohna, this furn...","['Parking Available', 'Lift']",28.276076,77.056507,C91299072
2725,"2 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Supertech Araville,Price on Request,₹0 /sqft,1195 sqft Superbuiltup Area,NaN,2,2,2.0,"Sector 79, Gurgaon",9 of 24 Floors,0,NaN,1,NaN,Unfurnished,"{""C"":1}","['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",Residential apartment for sell.The property ha...,"['Full Power Backup', 'Gated Society', 'Parkin...",28.364233,76.981995,O90470870
7627,"3 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Orris Aster Court,Price on Request,₹0 /sqft,1675 sqft Superbuiltup Area,NaN,3,4,3.0,"Sector 85, Gurgaon",1 of 12 Floors,0,NaN,1,NaN,0,NaN,"['Dwarka Expressway', 'IGI', 'Domestic Airport...",We are the proud owners of this 3 bhk apartmen...,NaN,28.405743,76.953408,I87984366
9179,"3 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Zenith,Price on Request,₹0 /sqft,2400 sqft Carpet Area,2400.0,3,3,3.0,"Sector 89, Gurgaon",30 of 37 Floors,0,NaN,5,NaN,0,"[""N""]","['City Square', 'NH 352W', 'RPS International ...",The flat occupies a carpet area of 2400 sq.Ft....,NaN,28.411256,76.952234,S90011354
10776,"4 BHK Flat in Sector 54, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Crest,Price on Request,₹0 /sqft,4022 sqft Superbuiltup Area,NaN,4,5,4.0,"Sector 54, Gurgaon",16 of 38 Floors,North-East,"Park/Garden, Pool, Club, Main Road",1,Y,Furnished,"{""C"":2}","['Golf Course Road', 'Sector 53-54 Metro Stati...",Fully furnished super luxury apartment in the ...,"['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.444951,77.111544,T59551064
13438,"2 BHK Flat in Sector 81, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global Synera,Price on Request,₹0 /sqft,633 sqft Superbuiltup Area,539.0,2,2,1.0,"Sector 81, Gurgaon",4 of 15 Floors,North,"Park/Garden, Main Road, Club, Pool",5,NaN,Unfurnished,"{""C"":1}","['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...","A beautiful 2 bhk apartment in sector-81, gurg...","['24*7 Water', 'Visitor Parking Available', 'O...",28.385107,76.952121,X49862588
13472,"2 BHK Flat in Sector 81, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global City 81,Price on Request,₹0 /sqft,675 sqft Carpet Area,675.0,2,2,3.0,"Sector 81, Gurgaon",4 of 5 Floors,0,NaN,6,NaN,Furnished,"{""O"":1,""C"":1}","['New Galaxy Public School', 'Miracles Apollo ...",Property is in the prime location. Please cont...,"['Centrally Air Conditioned', 'Parking Availab...",28.389015,76.944043,J90600728
22636,"3 BHK Flat in Sector 56, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Rail Vihar CGHS,Price on Request,₹0 /sqft,1600 sqft Superbuiltup Area,NaN,3,3,2.0,"Sector 56, Gurgaon",3 of 4 Floors,North,"Main Road, Park/Garden",3,NaN,Furnished,"{""O"":1,""C"":1}","['Sector 54 Chowk', 'Metro World Mall', 'Gurug...",This is a residential apartment on sale in sec...,"['Full Power Backup', 'Centrally Air Condition...",28.430350,77.101332,W90073740
24212,"3 BHK Flat in Sector 80, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Conscient Parq,Price on Request,₹0 /sqft,2375 sqft Carpet Area,2375.0,3,3,3.0,"Sector 80, Gurgaon",19 of 30 Floors,0,NaN,5,NaN,0,"{""O"":1,""C"":1}","['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",The floor plan additionally contains 3 bedroom...,"['Parking Available', 'Separate entry for serv...",28.365864,76.955664,R90011404
24691,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Camellias,Price on Request,₹0 /sqft,7430 sqft Superbuiltup Area,NaN,4,7,3.0,"Sector 42, Gurgaon",15 of 38 Floors,North-East,"Park/Garden, Club, Pool",6,NaN,Semi-Furnished,"{""C"":2,""O"":0}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",This is a ready to move in 4 bhk flat for sale...,"['Visitor Parking Available', 'On-Call Mainten...",28.451320,77.100660,T51258728
24692,"5 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,DLF The Camellias,Price on Request,₹0 /sqft,13000 sqft Superbuiltup Area,NaN,5,6,4.0,"Sector 42, Gurgaon",38 of 38 Floors,North-East,"Park/Garden, Club, Pool",6,Y,Unfurnished,"{""C"":1}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",The camellias penthouse details dedicated rese...,"['Visitor Parking Available', 'Centrally Air C...",28.451320,77.100660,B51216362
24693,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Magnolias,Price on Request,₹0 /sqft,6400 sqft Superbuiltup Area,NaN,4,5,4.0,"Sector 42, Gurgaon",16 of 25 Floors,North-East,"Pool, Park/Garden, Club",1,Y,Unfurnished,"{""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",Ultra modern fully furnished super luxury apar...,"['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.453820,77.099560,W21677081
24748,"6 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/6-bhk-bedroom-apartmen...,DLF The Camellias,Price on Request,₹0 /sqft,11000 sqft Superbuiltup Area,NaN,6,7,4.0,"Sector 42, Gurgaon",12 of 38 Floors,North-East,"Pool, Park/Garden, Club, Main Road",6,Y,Semi-Furnished,"{""C"":5}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",Ultra modern super luxury society apartment in...,"['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.451320,77.100660,E58076644
24752,"5 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,DLF The Camellias,Price on Request,₹0 /sqft,9500 sqft Superbuiltup Area,NaN,5,7,3.0,"Sector 42, Gurgaon",25 of 38 Floors,North-East,"Pool, Park/Garden, Club",1,Y,Unfurnished,"{""C"":5}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",Super luxurious society apartment in the camel...,"['Pet Friendly', '24*7 Water', 'Visitor Parkin...",28.451320,77.100660,D57818872
24754,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Camellias,Price on Request,₹0 /sqft,7400 sqft Superbuiltup Area,NaN,4,6,4.0,"Sector 42, Gurgaon",25 of 38 Floors,North-East,"Park/Garden, Pool",6,NaN,Furnished,"{""C"":4}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",For sale - Higher floor ultra modern fully fur...,"['Visitor Parking Available', 'Centrally Air C...",28.451320,77.100660,Y51216482
24799,"5 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,DLF The Aralias,Price on Request,₹0 /sqft,10000 sqft Superbuiltup Area,NaN,5,6,4.0,"Sector 42, Gurgaon",16 of 17 Floors,North-East,"Pool, Park/Garden, Club, Main Road",2,Y,Unfurnished,"{""C"":5}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...","For sale - Penthouse, in dlf - The aralias, se...","['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.459190,77.102240,C58709034
25097,"2 BHK Flat in Sector 82, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,Mapsko Casa Bella,Price on Request,₹0 /sqft,1220 sqft Carpet Area,1220.0,2,2,4.0,"Sector 82, Gurgaon",G of 25 Floors,0,"Park/Garden, Pool, Club",2,Y,Unfurnished,"{""C"":1}","['Vatika City Centre Mall', 'Pataudi Road', 'B...",This 2-Bedroom ground-Floor home in mapsko cas...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.393790,76.962990,B87040494
25406,"4 BHK Flat in Gwal Pahari, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Paras Quartier,Price on Request,₹0 /sqft,5000 sqft Carpet Area,5000.0,4,5,2.0,"Gwal Pahari, Gurgaon",4 of 43 Floors,0,NaN,5,NaN,Semi-Furnished,"{""O"":1,""C"":1}","['ASF Insignia SEZ', 'Pathways School', 'Skyli...",Its under construction property,"['On-Call Maintenance Staff', 'Vaastu Complian...",28.437178,77.133522,O86076826
25408,"4 BHK Flat in Gwal Pahari, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,Krrish Provence Estate,Price on Request,₹0 /sqft,5800 sqft Builtup Area,NaN,4,5,1.0,"Gwal Pahari, Gurgaon",17 of 24 Floors,0,NaN,5,NaN,Semi-Furnished,"{""C"":3}","['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,28.429564,77.142776,H28672425
25553,"3 BHK Flat in Sector 95, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ROF Ananda,Price on Request,₹0 /sqft,730 sqft Builtup Area,NaN,3,1,0.0,"Sector 95, Gurgaon",G of 1 Floors,0,Main Road,1,NaN,Semi-Furnished,"[""N""]","['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...","Containing 3 bedroom(s), 1 bathroom , this fla...","['Gated Society', 'Overlooking Main Road']",77.080853,28.484814,C90465586
26724,"2 BHK Flat in Sector 99A, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,On request,Price on Request,₹0 /sqft,1253 sqft Carpet Area,1253.0,2,2,1.0,"Sector 99A, Gurgaon",1 of 19 Floors,0,Main Road,5,NaN,Semi-Furnished,"{""C"":1}",['Basai dhankot railway station'],The flat occupies a carpet area of 1253 sq.Ft....,"['Visitor Parking Available', 'Overlooking Mai...",28.456241,76.953943,W90467398
27791,"5 BHK Flat in DLF Phase 3, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,Ambience Caitriona,Price on Request,₹0 /sqft,13500 sqft Superbuiltup Area,NaN,5,6,4.0,"DLF Phase 3, Gurgaon",11 of 12 Floors,North-East,NaN,1,NaN,Unfurnished,"[""N""]","['Moulsari Avenue Metro Station', 'Phase 3, Cy...","Penthouse on sale, Caitriona 7 star living at ...","['Visitor Parking Available', 'On-Call Mainten...",28.502590,77.100084,Y25076161
27909,"3 BHK Flat in Palam Vihar, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,Ansal API Spanish Court,Price on Request,₹0 /sqft,1555 sqft Superbuiltup Area,NaN,3,3,3.0,"Palam Vihar, Gurgaon",2 of 2 Floors,0,NaN,3,NaN,Unfurnished,"{""O"":""1""}","['Palam Vihar Vyapar kendra', 'Palam triangle'...","With this property, exclusive terrace rights a...","['Top Floor', 'Pet Friendly', 'Visitor Parking...",28.512930,77.037736,Q90047122

In [53]:
column_cleaning[column_cleaning['price_in_cr'] == '25,000']

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
23445,"1 BHK Flat in Sector 99, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,Ocus Medley,"25,000","₹1,000 /sqft",25 sqft Carpet Area,25.0,1,1,1.0,"Sector 99, Gurgaon",1 of 1 Floors,North-East,NaN,6,NaN,Unfurnished,"[""N""]","['Shri Multispeciality Hospital', 'Basai dhank...",This newly constructed 1 bhk flat on the top f...,"['Modular Kitchen', 'Semi-Furnished']",28.46682,76.969474,V89144159

In [22]:
column_cleaning.shape

(28504, 24)

In [54]:
column_cleaning = (
    df_flat
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (df_['price_in_cr'] != '25,000')
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
)

In [55]:
column_cleaning['price_in_cr'].isnull().sum()

np.int64(0)

In [56]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
2.50     416
2.00     386
2.10     368
2.25     344
3.00     311
        ...
11.21      1
11.66      1
9.81       1
12.56      1
12.58      1
Name: count, Length: 1181, dtype: int64

In [57]:
column_cleaning['price_in_cr'].describe()

count    28480.000000
mean         3.717479
std          8.089988
min          0.120000
25%          1.680000
50%          2.500000
75%          4.000000
max       1000.000000
Name: price_in_cr, dtype: float64

In [58]:
column_cleaning[column_cleaning['price_in_cr']> 30]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
4186,"4 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,godrej meridien,40.60,₹1.49 L /sqft,2720 sqft Builtup Area,2040.0,4,4,4.0,"Sector 106, Gurgaon",8 of 34 Floors,North-East,Park/Garden,5,Y,Semi-Furnished,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",Godrej meridien is a luxury residential projec...,"['Full Power Backup', 'Visitor Parking Availab...",28.509519,76.988676,B91183864
9894,"5 BHK Flat in Sector 62, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,pioneer araya,35.00,"₹34,934 /sqft",10019 sqft Superbuiltup Area,NaN,5,8,4.0,"Sector 62, Gurgaon",34 of 34 Floors,North-East,"Pool, Park/Garden, Club",6,Y,Unfurnished,"{""C"":3}","['Paras Trinity Shopping Mall', 'Swastik Multi...",Penthouse with magnificent view available in p...,"['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.412644,77.088217,R52943616
10388,"4 BHK Flat in Sector 54, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the crest,32.00,"₹66,667 /sqft",4800 sqft Superbuiltup Area,4400.0,4,5,4.0,"Sector 54, Gurgaon",36 of 36 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",2,Y,Unfurnished,"{""O"":1,""C"":3}","['Golf Course Road', 'Sector 53-54 Metro Stati...",Crest penthouse available for sale,"['Full Power Backup', 'Visitor Parking Availab...",28.444951,77.111544,W91333518
15039,"4 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,central park resorts,32.00,"₹36,849 /sqft",8684 sqft Carpet Area,8684.0,4,6,2.0,"Sector 48, Gurgaon",16 of 17 Floors,North-East,"Pool, Club, Park/Garden, Main Road, Others",1,NaN,Unfurnished,"{""C"":2}","['Park Hospital', 'Omaxe Celebration Mall', 'G...",This is a north-East-Facing property. The floo...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.424673,77.034182,D90379760
15234,"4 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,central park resorts sky villas,32.00,"₹36,849 /sqft",8684 sqft Carpet Area,8684.0,4,7,4.0,"Sector 48, Gurgaon",16 of 16 Floors,North-East,Park/Garden,2,NaN,Unfurnished,"{""C"":3}","['Raheja Mall', 'SRS Cinemas', 'Hanuman Mandir...",Extraordinary sky villa with private pool and ...,"['Full Power Backup', 'G D Goenka and Vedanya ...",28.424092,77.035694,H90544300
15247,"4 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,central park resorts sky villas,34.90,"₹40,189 /sqft",8684 sqft Carpet Area,8684.0,4,7,4.0,"Sector 48, Gurgaon",16 of 18 Floors,North-East,Park/Garden,2,NaN,Furnished,"{""C"":3}","['Raheja Mall', 'SRS Cinemas', 'Hanuman Mandir...",This property faces the north-East direction. ...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.424092,77.035694,R91264880
15270,"5 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,central park resorts,39.20,"₹35,000 /sqft",11200 sqft Carpet Area,11200.0,5,5,3.0,"Sector 48, Gurgaon",17 of 17 Floors,North-East,"Park/Garden, Club, Main Road, Pool",1,NaN,Unfurnished,"{""C"":2}","['Park Hospital', 'Omaxe Celebration Mall', 'G...",Central park resorts is one of gurgaon's most ...,"['Top Floor', 'Full Power Backup', '24*7 Water...",28.424782,77.032571,E87869530
24613,"5 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,dlf the magnolias,85.00,"₹78,704 /sqft",10800 sqft Carpet Area,10800.0,5,5,2.0,"Sector 42, Gurgaon",8 of 24 Floors,North,"Pool, Park/Garden, Club, Others, Main Road, Se...",1,Y,Unfurnished,"{""O"":2,""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",Gorgeous 5 bedrooms with attached bathroom dup...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.460428,77.103181,R81172779
24614,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,72.00,"₹97,297 /sqft",7400 sqft Carpet Area,7400.0,4,4,2.0,"Sector 42, Gurgaon",36 of 38 Floors,North,"Park/Garden, Club, Others, Main Road, Sea faci...",1,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",This property faces the east direction. The fl...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.450864,77.100144,W88243130
24616,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,47.10,"₹73,594 /sqft",6400 sqft Superbuiltup Area,NaN,4,4,3.0,"Sector 42, Gurgaon",7 of 24 Floors,North-East,"Main Road, Pool, Club, Park/Garden, Others",2,Y,Unfurnished,"{""C"":2}","['Ambience Public School', 'Heritage Intl Xper...",This is a north-East-Facing property. The flat...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.458570,77.100309,B89686908
24617,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,35.00,"₹62,780 /sqft",5575 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 42, Gurgaon",6 of 17 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",3,Y,Unfurnished,"{""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...","Dlf the aralias in sector 42, gurgaon is a rea...","['Pet Friendly', 'Full Power Backup', 'Visitor...",28.459672,77.103250,M91024738
24618,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,39.00,"₹69,955 /sqft",5575 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 42, Gurgaon",7 of 17 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",3,Y,Unfurnished,"{""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...","Dlf the aralias in sector 42, gurgaon is a rea...","['Pet Friendly', 'Full Power Backup', 'Visitor...",28.459672,77.103250,G91025100
24619,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,38.00,"₹68,161 /sqft",5575 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 42, Gurgaon",12 of 17 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",3,Y,Unfurnished,"{""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...","Dlf the aralias in sector 42, gurgaon is a rea...","['Pet Friendly', 'Full Power Backup', 'Visitor...",28.459672,77.103250,X91024844
24620,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,32.00,"₹57,143 /sqft",5600 sqft Superbuiltup Area,NaN,4,6,4.0,"Sector 42, Gurgaon",13 of 17 Floors,East,Others,1,Y,Unfurnished,"{""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...","Dlf the aralias in sector 42, gurgaon is a rea...","['Full Power Backup', 'Centrally Air Condition...",28.459672,77.103250,Z90618416
24622,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,45.00,"₹70,313 /sqft",6400 sqft Superbuiltup Area,5500.0,4,4,4.0,"DLF Golf Course, Gurgaon",10 of 24 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",2,Y,Unfurnished,"{""O"":1,""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",This property faces the north-East direction. ...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.455642,77.099053,R88880594
24623,"3 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,dlf the camellias,71.00,"₹91,026 /sqft",7800 sqft Superbuiltup Area,NaN,3,4,3.0,"Sector 42, Gurgaon",1 of 38 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",1,Y,Furnished,"{""C"":4}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Visitor Parking Availab...",28.451180,77.099913,E88896008
24626,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,75.00,₹1.01 L /sqft,7400 sqft Superbuiltup Area,6000.0,4,8,4.0,"DLF Golf Course, Gurgaon",10 of 38 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",1,Y,Furnished,"{""O"":1,""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",Check out this 4 bhk apartment for sale in dlf...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.451320,77.100660,O86828534
24627,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,37.00,"₹66,071 /sqft",5600 sqft Superbuiltup Area,4000.0,4,6,4.0,"DLF Golf Course, Gurgaon",6 of 17 Floors,North-East,"Main Road, Club, Park/Garden, Pool, Others",3,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",Dlf the aralias is one of gurgaon's most sough...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.460203,77.103456,G86854006
24628,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,38.00,"₹64,571 /sqft",5885 sqft Carpet Area,5885.0,4,4,2.0,"Sector 42, Gurgaon",11 of 17 Floors,North,"Park/Garden, Club, Others, Main Road, Sea faci...",1,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",The flat is facing the east direction. Contain...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.459600,77.104094,B88240240
24629,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,37.50,"₹63,776 /sqft",5880 sqft Carpet Area,5880.0,4,4,2.0,"Sector 42, Gurgaon",10 of 17 Floors,North,"Park/Garden, Club, Others, Pool, Main Road, Se...",1,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",This is a east-Facing property. Containing 4 b...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.459594,77.103408,I88237478
24630,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,45.00,"₹70,313 /sqft",6400 sqft Superbuiltup Area,6200.0,4,4,3.0,"Sector 42, Gurgaon",8 of 24 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",2,Y,Unfurnished,"{""O"":2,""C"":3}","['Ambience Public School', 'Heritage Intl Xper...","Dlf the magnolias in sector 42, gurgaon is a r...","['Wheel Chair Friendly', 'Full Power Backup', ...",28.457478,77.100485,A89028936
24632,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,37.00,"₹66,071 /sqft",5600 sqft Superbuiltup Area,NaN,4,6,4.0,"Sector 42, Gurgaon",7 of 17 Floors,North-East,"Park/Garden, Pool, Club, Main Road, Others",1,Y,Unfurnished,"{""C"":4}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Visitor Parking Availab...",28.460128,77.102678,K88989662
24633,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,50.00,"₹78,125 /sqft",6400 sqft Superbuiltup Area,5000.0,4,4,4.0,"Sector 42, Gurgaon",21 of 24 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",1,Y,Unfurnished,"{""C"":4}","['Ambience Public School', 'Heritage Intl Xper...","Dlf the magnolias in sector 42, gurgaon is a r...","['Wheel Chair Friendly', 'Full Power Backup', ...",28.454164,77.098717,B89600522
24634,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,35.00,"₹60,345 /sqft",5800 sqft Superbuiltup Area,5600.0,4,6,4.0,"Sector 42, Gurgaon",5 of 17 Floors,East,"Pool, Park/Garden, Club, Main Road, Others",2,Y,Unfurnished,"{""O"":2,""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",Best deals by risemax realty pvt. Ltd.Ultra lu...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.457600,77.100441,C89029140
24639,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,70.00,"₹94,595 /sqft",7400 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 42, Gurgaon",12 of 38 Floors,North,"Pool, Park/Garden, Main Road, Others, Club, Se...",1,Y,Unfurnished,"{""C"":2}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",The flat is facing the east direction. The fla...,"['East Facing', 'Wheel Chair Friendly', 'Full ...",28.450637,77.101670,X89767868
24642,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,85.00,₹1.21 L /sqft,7000 sqft Carpet Area,7000.0,4,5,4.0,"Sector 42, Gurgaon",16 of 38 Floors,North-West,"Pool, Park/Garden, Club, Main Road",2,Y,Furnished,"{""O"":1,""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...","Available immediately, this 4 bhk flat on the ...","['Full Power Backup', 'Visitor Parking Availab...",28.451320,77.100660,Y91259860
24643,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,65.00,"₹84,416 /sqft",7700 sqft Carpet Area,7700.0,4,4,4.0,"Sector 42, Gurgaon",12 of 38 Floors,North,"Pool, Main Road, Others, Park/Garden",2,NaN,Unfurnished,"{""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",Desperate deal with flexible cheque and sale f...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.451253,77.101186,C90220282
24647,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,73.00,"₹98,649 /sqft",7400 sqft Carpet Area,7400.0,4,4,2.0,"Sector 42, Gurgaon",26 of 38 Floors,North,"Club, Main Road, Others, Pool, Sea facing, Par...",1,Y,Unfurnished,"{""O"":2,""C"":2}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",Luxury reaches its finest expression at dlf th...,"['East Facing', 'Wheel Chair Friendly', 'Pet F...",28.459575,77.104042,P85851392
24648,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,73.00,"₹98,649 /sqft",7400 sqft Superbuiltup Area,6000.0,4,8,4.0,"DLF Golf Course, Gurgaon",7 of 38 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",1,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",This lovely 4 bhk apartment/flat in dlf golf c...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.451320,77.100660,E86828030
24649,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,44.00,"₹68,750 /sqft",6400 sqft Superbuiltup Area,5200.0,4,4,4.0,"Sector 42, Gurgaon",5 of 24 Floors,East,"Pool, Park/Garden, Club, Main Road",3,NaN,Unfurnished,"{""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",This is a north-Facing property. Containing 4 ...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.453820,77.099560,N90014584
24650,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,37.00,"₹66,071 /sqft",5600 sqft Superbuiltup Area,4450.0,4,6,4.0,"Sector 42, Gurgaon",7 of 17 Floors,East,"Pool, Park/Garden, Club",3,NaN,Unfurnished,"{""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",This property faces the north direction. The f...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.459190,77.102240,H90014408
24651,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,71.00,"₹95,946 /sqft",7400 sqft Superbuiltup Area,6070.0,4,8,4.0,"Sector 42, Gurgaon",16 of 38 Floors,North-West,"Pool, Park/Garden, Club, Main Road",2,NaN,Unfurnished,"{""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",This is a north-West-Facing property. The flat...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.451320,77.100660,Z90015346
24652,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,43.00,"₹67,188 /sqft",6400 sqft Superbuiltup Area,5000.0,4,4,4.0,"DLF Golf Course, Gurgaon",12 of 24 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",3,Y,Unfurnished,"{""O"":1,""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",This lovely 4 bhk apartment/flat in dlf golf c...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.455419,77.098811,U86690078
24653,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,36.50,"₹65,179 /sqft",5600 sqft Superbuiltup Area,4290.0,4,6,4.0,"Sector 42, Gurgaon",9 of 17 Floors,South-East,"Pool, Park/Garden, Club, Main Road",3,Y,Unfurnished,"{""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",The flat is facing the south-East direction. T...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.459190,77.102240,S90925228
24654,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,43.75,"₹68,359 /sqft",6400 sqft Superbuiltup Area,4870.0,4,4,3.0,"Sector 42, Gurgaon",5 of 24 Floors,East,"Pool, Park/Garden, Club, Main Road",3,Y,Unfurnished,"{""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",The flat is north-Facing. The flat occupies a ...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.453820,77.099560,Q90924234
24655,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,39.00,"₹66,214 /sqft",5890 sqft Carpet Area,5890.0,4,4,2.0,"Sector 42, Gurgaon",12 of 17 Floors,North,"Park/Garden, Club, Others, Pool, Main Road, Se...",1,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",This residential flat is east-Facing direction...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.459864,77.103386,S88240362
24657,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,45.00,"₹70,313 /sqft",6400 sqft Superbuiltup Area,NaN,4,5,4.0,"Sector 42, Gurgaon",6 of 24 Floors,South,"Pool, Park/Garden, Club, Main Road, Others",2,Y,Unfurnished,"{""O"":2,""C"":4}","['Ambience Public School', 'Heritage Intl Xper...",This residential flat is west-Facing direction...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.453820,77.099560,N91217804
24658,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the magnolias,46.00,"₹71,875 /sqft",6400 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 42, Gurgaon",17 of 24 Floors,West,"Pool, Club, Others, Park/Garden, Main Road",3,Y,Furnished,"{""C"":3}","['Ambience Public School', 'Heritage Intl Xper...",This is a south-Facing property. Containing 4 ...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.453820,77.099560,E90326736
24659,"4 BHK Flat in Sector 42, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,70.50,"₹94,886 /sqft",7430 sqft Superbuiltup Area,5600.0,4,7,3.0,"Sector 42, Gurgaon",7 of 38 Floors,South,"Pool, Park/Garden, Club, Main Road",1,Y,Unfurnished,"{""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...",The flat is facing the west direction. The fla...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.451320,77.100660,Y90923720
24661,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the aralias,38.00,"₹67,857 /sqft",5600 sqft Superbuiltup Area,4000.0,4,6,4.0,"DLF Golf Course, Gurgaon",9 of 17 Floors,North-East,"Main Road, Club, Park/Garden, Pool, Others",3,Y,Unfurnished,"{""O"":1,""C"":3}","['DLF Linear Park', 'Shiv Nadar School', 'Le M...",This lovely 4 bhk apartment/flat in dlf golf c...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.459672,77.103250,C86853952
24664,"4 BHK Flat in DLF Golf Course, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,dlf the camellias,85.00,₹1.15 L /sqft,7400 sqft Superbuiltup Area,6000.0,4,8,4.0,"DLF Golf Course, Gurgaon",20 of 38 Floors,North-East,"Pool, Park/Garden, Club, Main Road, Others",1,Y,Furnished,"{""O"":1,""C"":3}","['DLF Golf and Country Club', 'Sector 42-43 Ra...","This beautiful 4 bhk flat in dlf golf course, ...","['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.451320,77.100660,S86828808

In [59]:
column_cleaning['price_in_cr'].quantile(
    [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
)

0.01     0.37
0.05     0.66
0.25     1.68
0.50     2.50
0.75     4.00
0.95     9.75
0.99    20.00
Name: price_in_cr, dtype: float64

### 3. Price Per Sqft

In [26]:
column_cleaning['price_per_sqft'].value_counts()

price_per_sqft
₹10,000 /sqft    124
₹20,000 /sqft    102
₹15,000 /sqft     93
₹16,000 /sqft     85
₹12,000 /sqft     78
                ...
₹78,411 /sqft      1
₹30,168 /sqft      1
₹4,331 /sqft       1
₹7,317 /sqft       1
₹8,561 /sqft       1
Name: count, Length: 11677, dtype: int64

In [31]:
column_cleaning['price_per_sqft']\
    .str.extract(r'/(.+)$', expand=False)\
    .str.strip()\
    .str.lower()\
    .value_counts(dropna=False)

price_per_sqft
sqft    28098
NaN       382
Name: count, dtype: int64

In [27]:
column_cleaning.loc[
    column_cleaning['price_per_sqft'].str.contains('1.49 L', na=False),
    
]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
4186,"4 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,godrej meridien,40.6,₹1.49 L /sqft,2720 sqft Builtup Area,2040.0,4,4,4.0,"Sector 106, Gurgaon",8 of 34 Floors,North-East,Park/Garden,5,Y,Semi-Furnished,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",Godrej meridien is a luxury residential projec...,"['Full Power Backup', 'Visitor Parking Availab...",28.509519,76.988676,B91183864
22614,"3 BHK Flat in Sector 56, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,pib gharonda apartment,2.5,₹1.49 L /sqft,168 sqft Carpet Area,168.0,3,2,4.0,"Sector 56, Gurgaon",2 of 3 Floors,South,NaN,2,NaN,Furnished,"{""C"":1}","['Sector metro station', 'Sector metro station...",The flat occupies a carpet area of 168 sq.Ft. ...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.425509,77.096995,T90669258

In [28]:
column_cleaning = (df_flat
                    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace("L","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()

)))
column_cleaning['price_per_sqft'].unique().tolist()

[9850.0,
 19243.0,
 10744.0,
 12162.0,
 14254.0,
 11670.0,
 11280.0,
 9929.0,
 11943.0,
 11460.0,
 10285.0,
 11486.0,
 11408.0,
 9291.0,
 13240.0,
 14143.0,
 10196.0,
 13974.0,
 14533.0,
 11526.0,
 9821.0,
 10368.0,
 11329.0,
 13061.0,
 10276.0,
 10612.0,
 11853.0,
 9898.0,
 10645.0,
 10452.0,
 17067.0,
 17829.0,
 9952.0,
 9810.0,
 10627.0,
 11492.0,
 9709.0,
 10565.0,
 10638.0,
 9976.0,
 9817.0,
 9955.0,
 17564.0,
 17388.0,
 9456.0,
 9621.0,
 9983.0,
 11149.0,
 11676.0,
 11657.0,
 10634.0,
 11146.0,
 9609.0,
 9123.0,
 8509.0,
 8561.0,
 17699.0,
 9069.0,
 13266.0,
 8407.0,
 11321.0,
 20356.0,
 10260.0,
 10603.0,
 9128.0,
 11500.0,
 10261.0,
 10150.0,
 11864.0,
 11120.0,
 15458.0,
 8401.0,
 13121.0,
 8719.0,
 11050.0,
 5538.0,
 11735.0,
 10008.0,
 18809.0,
 9746.0,
 18257.0,
 10244.0,
 10909.0,
 11342.0,
 9214.0,
 9889.0,
 10481.0,
 17812.0,
 8617.0,
 10108.0,
 11286.0,
 17949.0,
 17570.0,
 10097.0,
 11960.0,
 10597.0,
 11980.0,
 9994.0,
 10469.0,
 13636.0,
 9917.0,
 9915.0,
 8787.0,
 10824.0,
 9000.0,
 10976.0,
 21176.0,
 30769.0,
 8333.0,
 8835.0,
 8943.0,
 10708.0,
 11148.0,
 5895.0,
 5947.0,
 5684.0,
 5789.0,
 17668.0,
 10280.0,
 9713.0,
 10496.0,
 8421.0,
 10521.0,
 8934.0,
 10364.0,
 10417.0,
 9796.0,
 9530.0,
 20970.0,
 11561.0,
 8743.0,
 10067.0,
 10173.0,
 8982.0,
 11458.0,
 9854.0,
 10291.0,
 8752.0,
 8966.0,
 8948.0,
 9244.0,
 13415.0,
 11852.0,
 12333.0,
 13410.0,
 6048.0,
 5847.0,
 11037.0,
 11535.0,
 12115.0,
 11582.0,
 11353.0,
 11808.0,
 11551.0,
 11473.0,
 8239.0,
 8828.0,
 11523.0,
 10323.0,
 5780.0,
 12598.0,
 10652.0,
 5645.0,
 11047.0,
 13547.0,
 8857.0,
 9143.0,
 15084.0,
 10000.0,
 9667.0,
 13413.0,
 9828.0,
 11986.0,
 9822.0,
 9645.0,
 9732.0,
 8200.0,
 9257.0,
 14813.0,
 9750.0,
 12840.0,
 12766.0,
 8133.0,
 10800.0,
 8579.0,
 8800.0,
 10840.0,
 11979.0,
 9587.0,
 14079.0,
 9231.0,
 10805.0,
 8772.0,
 11287.0,
 17903.0,
 13807.0,
 13695.0,
 8591.0,
 8533.0,
 10433.0,
 13905.0,
 12418.0,
 12816.0,
 11968.0,
 6316.0,
 5716.0,
 10258.0,
 17308.0,
 17018.0,
 10465.0,
 7795.0,
 6842.0,
 6612.0,
 10867.0,
 6629.0,
 6400.0,
 6514.0,
 6743.0,
 10978.0,
 9474.0,
 8140.0,
 10983.0,
 13500.0,
 6667.0,
 6376.0,
 9299.0,
 9187.0,
 11914.0,
 10940.0,
 8539.0,
 5692.0,
 12241.0,
 12006.0,
 11320.0,
 11234.0,
 10301.0,
 9956.0,
 8067.0,
 13641.0,
 13527.0,
 8400.0,
 9364.0,
 14231.0,
 7949.0,
 5485.0,
 5737.0,
 6429.0,
 5862.0,
 9034.0,
 6000.0,
 6211.0,
 11299.0,
 16260.0,
 7048.0,
 7238.0,
 8028.0,
 5936.0,
 5833.0,
 5846.0,
 5385.0,
 9218.0,
 12535.0,
 12558.0,
 10806.0,
 30345.0,
 8073.0,
 8681.0,
 11020.0,
 8903.0,
 10334.0,
 13006.0,
 12755.0,
 8000.0,
 15092.0,
 5591.0,
 5650.0,
 5444.0,
 11945.0,
 5327.0,
 16814.0,
 12023.0,
 9524.0,
 10247.0,
 10918.0,
 10504.0,
 14662.0,
 8120.0,
 7760.0,
 7937.0,
 9104.0,
 11546.0,
 8744.0,
 14956.0,
 9698.0,
 7826.0,
 9948.0,
 9636.0,
 7940.0,
 9384.0,
 9076.0,
 5969.0,
 12012.0,
 9556.0,
 9320.0,
 9170.0,
 9735.0,
 15188.0,
 12274.0,
 14839.0,
 10331.0,
 7025.0,
 7719.0,
 11702.0,
 10936.0,
 8778.0,
 11967.0,
 8854.0,
 6857.0,
 11949.0,
 13559.0,
 10892.0,
 12809.0,
 9086.0,
 8726.0,
 10763.0,
 11111.0,
 6415.0,
 9563.0,
 11429.0,
 9396.0,
 11742.0,
 6662.0,
 11667.0,
 13959.0,
 7895.0,
 7647.0,
 6721.0,
 11279.0,
 11881.0,
 10741.0,
 8740.0,
 9053.0,
 9386.0,
 8971.0,
 6286.0,
 7649.0,
 11837.0,
 15234.0,
 12500.0,
 10492.0,
 15556.0,
 9739.0,
 6263.0,
 6105.0,
 8462.0,
 14050.0,
 11171.0,
 13566.0,
 9341.0,
 13381.0,
 10089.0,
 6783.0,
 13889.0,
 9528.0,
 11373.0,
 10811.0,
 10345.0,
 21432.0,
 12153.0,
 10156.0,
 8898.0,
 11440.0,
 10505.0,
 8316.0,
 17771.0,
 8636.0,
 7692.0,
 12298.0,
 6900.0,
 6784.0,
 11063.0,
 8426.0,
 7639.0,
 8804.0,
 5300.0,
 20833.0,
 11818.0,
 8836.0,
 12792.0,
 9180.0,
 9395.0,
 9836.0,
 6106.0,
 10864.0,
 10537.0,
 10116.0,
 10472.0,
 10414.0,
 13871.0,
 14634.0,
 12717.0,
 6737.0,
 11645.0,
 16589.0,
 8667.0,
 12349.0,
 13725.0,
 9664.0,
 9116.0,
 nan,
 9539.0,
 15000.0,
 11163.0,
 9657.0,
 10049.0,
 10714.0,
 29698.0,
 9066.0,
 11378.0,
 10574.0,
 5989.0,
 13548.0,
 9118.0,
 11613.0,
 14499.0,
 9310.0,
 7023.0,
 8491.0,
 14500.0,
 10839.0,
 8023.0,
 16712.0,
 10680.0,
 15204.0,
 13821.0,
 9470.0,
 9019.0,
 9500.0,
 13918.0,
 12593.0,
 8757.0,
 12479.0,
 10062.0,
 30894.0,
 35314.0,
 50320.0,
 10870.0,
 8912.0,
 11708.0,
 11422.0,
 9677.0,
 9098.0,
 10405.0,
 8532.0,
 9554.0,
 13312.0,
 3750.0,
 16126.0,
 16216.0,
 20182.0,
 4292.0,
 13090.0,
 8780.0,
 9485.0,
 17385.0,
 18781.0,
 6597.0,
 5333.0,
 23438.0,
 18987.0,
 36170.0,
 10661.0,
 8889.0,
 14374.0,
 13462.0,
 13724.0,
 16129.0,
 3608.0,
 8564.0,
 13544.0,
 12539.0,
 20000.0,
 8940.0,
 9038.0,
 10373.0,
 79086.0,
 10370.0,
 19251.0,
 10274.0,
 10526.0,
 11409.0,
 12488.0,
 9423.0,
 14479.0,
 11413.0,
 10726.0,
 11664.0,
 13136.0,
 5698.0,
 12903.0,
 4295.0,
 4667.0,
 4400.0,
 9266.0,
 13590.0,
 10701.0,
 13223.0,
 12692.0,
 12184.0,
 9454.0,
 10061.0,
 9459.0,
 3880.0,
 3134.0,
 8923.0,
 8844.0,
 10135.0,
 12864.0,
 7757.0,
 8184.0,
 9630.0,
 16179.0,
 9693.0,
 7361.0,
 11124.0,
 17633.0,
 5832.0,
 12228.0,
 10093.0,
 10960.0,
 10686.0,
 11405.0,
 9189.0,
 15041.0,
 43810.0,
 37736.0,
 8418.0,
 14541.0,
 9752.0,
 11474.0,
 10027.0,
 9967.0,
 8672.0,
 11512.0,
 8085.0,
 8213.0,
 8363.0,
 8092.0,
 8267.0,
 10772.0,
 10973.0,
 10788.0,
 4376.0,
 4306.0,
 9436.0,
 17144.0,
 6171.0,
 11264.0,
 11824.0,
 11655.0,
 12106.0,
 10431.0,
 10588.0,
 1040.0,
 15625.0,
 9541.0,
 10233.0,
 12281.0,
 5696.0,
 10604.0,
 9159.0,
 10473.0,
 27495.0,
 14628.0,
 18072.0,
 14566.0,
 7167.0,
 7543.0,
 4254.0,
 13333.0,
 11908.0,
 11704.0,
 11911.0,
 11870.0,
 11648.0,
 11780.0,
 11695.0,
 11626.0,
 11591.0,
 11337.0,
 11232.0,
 11086.0,
 10902.0,
 11209.0,
 11322.0,
 10984.0,
 11311.0,
 11170.0,
 11289.0,
 9493.0,
 9497.0,
 9383.0,
 9369.0,
 9511.0,
 9510.0,
 9503.0,
 9450.0,
 9342.0,
 10182.0,
 11484.0,
 11423.0,
 11750.0,
 11269.0,
 11397.0,
 9921.0,
 10779.0,
 11284.0,
 11421.0,
 38222.0,
 10858.0,
 11902.0,
 11438.0,
 11827.0,
 11559.0,
 12335.0,
 12887.0,
 11595.0,
 11668.0,
 8099.0,
 16618.0,
 9091.0,
 9808.0,
 10295.0,
 12351.0,
 19671.0,
 17104.0,
 11480.0,
 10625.0,
 8649.0,
 6834.0,
 11685.0,
 9065.0,
 9228.0,
 9140.0,
 8707.0,
 12288.0,
 8652.0,
 8546.0,
 14028.0,
 8627.0,
 11462.0,
 9176.0,
 8987.0,
 8050.0,
 11261.0,
 11415.0,
 12283.0,
 9303.0,
 11263.0,
 12261.0,
 8175.0,
 8852.0,
 13515.0,
 7814.0,
 8813.0,
 8306.0,
 8425.0,
 9289.0,
 14009.0,
 9009.0,
 8395.0,
 9122.0,
 10996.0,
 12094.0,
 14251.0,
 11042.0,
 9062.0,
 8185.0,
 11706.0,
 14268.0,
 8575.0,
 8516.0,
 12116.0,
 11921.0,
 9358.0,
 8244.0,
 9255.0,
 8522.0,
 8086.0,
 8623.0,
 9481.0,
 9355.0,
 9606.0,
 12475.0,
 13935.0,
 10110.0,
 8688.0,
 8989.0,
 13011.0,
 10554.0,
 7998.0,
 7721.0,
 8240.0,
 8913.0,
 8565.0,
 11078.0,
 10731.0,
 10830.0,
 9924.0,
 10180.0,
 8846.0,
 9847.0,
 9467.0,
 9611.0,
 9262.0,
 10580.0,
 3901.0,
 7348.0,
 11240.0,
 11191.0,
 10174.0,
 10366.0,
 11913.0,
 10886.0,
 10614.0,
 10253.0,
 10533.0,
 10534.0,
 10458.0,
 12080.0,
 8842.0,
 8455.0,
 10111.0,
 8211.0,
 7133.0,
 9196.0,
 8785.0,
 8351.0,
 14058.0,
 11024.0,
 9263.0,
 9767.0,
 8730.0,
 10764.0,
 9489.0,
 10413.0,
 9669.0,
 8238.0,
 11200.0,
 10610.0,
 8827.0,
 19063.0,
 18984.0,
 17859.0,
 17405.0,
 16227.0,
 16633.0,
 16734.0,
 17546.0,
 17039.0,
 18256.0,
 18905.0,
 19985.0,
 17800.0,
 18753.0,
 5563.0,
 11990.0,
 10087.0,
 17433.0,
 10756.0,
 16365.0,
 8070.0,
 10938.0,
 6167.0,
 8750.0,
 10478.0,
 10616.0,
 18838.0,
 5742.0,
 8970.0,
 8632.0,
 8805.0,
 13808.0,
 11585.0,
 14069.0,
 16498.0,
 9182.0,
 6526.0,
 11157.0,
 11488.0,
 11689.0,
 10854.0,
 13269.0,
 9668.0,
 9825.0,
 9353.0,
 9023.0,
 8230.0,
 7069.0,
 7139.0,
 6853.0,
 13924.0,
 12821.0,
 8960.0,
 4378.0,
 11250.0,
 4460.0,
 4212.0,
 4386.0,
 3500.0,
 19259.0,
 15238.0,
 4543.0,
 4497.0,
 4264.0,
 14408.0,
 5250.0,
 11552.0,
 17573.0,
 12024.0,
 12727.0,
 11628.0,
 12176.0,
 11126.0,
 10270.0,
 11370.0,
 11774.0,
 14556.0,
 11509.0,
 13915.0,
 17068.0,
 10933.0,
 11677.0,
 5914.0,
 8307.0,
 18519.0,
 6491.0,
 11796.0,
 12448.0,
 28736.0,
 12387.0,
 7207.0,
 7052.0,
 7081.0,
 14286.0,
 11178.0,
 3718.0,
 4679.0,
 12030.0,
 11442.0,
 8725.0,
 9335.0,
 16410.0,
 7579.0,
 8902.0,
 10060.0,
 7478.0,
 7240.0,
 6753.0,
 13442.0,
 8078.0,
 11918.0,
 10471.0,
 8897.0,
 10305.0,
 3062.0,
 7759.0,
 7931.0,
 11000.0,
 16744.0,
 72000.0,
 5590.0,
 6339.0,
 6072.0,
 5970.0,
 7550.0,
 7486.0,
 7838.0,
 10698.0,
 14064.0,
 15758.0,
 13549.0,
 9414.0,
 9747.0,
 7610.0,
 6553.0,
 7981.0,
 7514.0,
 8065.0,
 12190.0,
 11361.0,
 6183.0,
 9402.0,
 11858.0,
 7148.0,
 7463.0,
 14861.0,
 10990.0,
 12203.0,
 2.0,
 0.0,
 7218.0,
 7038.0,
 7762.0,
 7200.0,
 5765.0,
 7261.0,
 9781.0,
 8441.0,
 7868.0,
 8130.0,
 5084.0,
 4333.0,
 5336.0,
 11924.0,
 10081.0,
 15652.0,
 7498.0,
 11081.0,
 6250.0,
 9457.0,
 14516.0,
 11892.0,
 15032.0,
 8324.0,
 3842.0,
 15484.0,
 8542.0,
 7631.0,
 10010.0,
 6855.0,
 8235.0,
 7966.0,
 3250.0,
 6133.0,
 6057.0,
 8327.0,
 13115.0,
 15909.0,
 11364.0,
 10509.0,
 23030.0,
 7707.0,
 5800.0,
 7978.0,
 6336.0,
 15651.0,
 5156.0,
 14527.0,
 13722.0,
 4426.0,
 2985.0,
 6485.0,
 2361.0,
 3959.0,
 3588.0,
 4045.0,
 7451.0,
 4464.0,
 4862.0,
 4359.0,
 4393.0,
 9665.0,
 9542.0,
 11570.0,
 5736.0,
 5427.0,
 19363.0,
 10443.0,
 10760.0,
 7790.0,
 11940.0,
 8303.0,
 5175.0,
 6448.0,
 11154.0,
 9827.0,
 14194.0,
 8890.0,
 13089.0,
 10965.0,
 9160.0,
 10316.0,
 11076.0,
 7581.0,
 8545.0,
 6462.0,
 9778.0,
 13818.0,
 10750.0,
 7941.0,
 6329.0,
 11820.0,
 65000.0,
 10484.0,
 12941.0,
 22075.0,
 8024.0,
 9696.0,
 16949.0,
 ...]

In [29]:
column_cleaning['price_per_sqft'].value_counts()

price_per_sqft
10000.0    124
20000.0    102
15000.0     93
16000.0     85
12000.0     78
          ...
19767.0      1
19714.0      1
15748.0      1
19764.0      1
33888.0      1
Name: count, Length: 11679, dtype: int64

In [67]:
column_cleaning = (
    df_flat
    .assign(
        society=lambda df_: (
            df_['society']
            .str.strip()
            .str.lower()
        )
    )

    .assign(
        price_in_cr=lambda df_: (
            df_['price_in_cr']
            .str.strip()
        )
    )

    .loc[
        lambda df_: (
            df_['price_in_cr'].notna()
            & (df_['price_in_cr'] != 'Price on Request')
            & (df_['price_in_cr'] != '25,000')
        )
    ]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )

    .assign(
        price_per_sqft=lambda df_: (
            pd.to_numeric(
                df_['price_per_sqft']
                .str.split("₹")
                .str.get(1)
                .str.split("/")
                .str.get(0)
                .str.replace("L", "", regex=False)
                .str.replace(",", "", regex=False)
                .str.strip(),
                errors='coerce'
            )

            .mul(
                np.where(
                    df_['price_per_sqft'].str.contains("L", na=False),
                    100000,
                    1
                )
            )

            .div(
                np.where(
                    df_['price_per_sqft'].str.contains("/sqyd", na=False),
                    9,
                    1
                )
            )

            .round()
        )
    )
)

In [68]:
column_cleaning['price_per_sqft'].describe()

count    2.809800e+04
mean     1.651943e+04
std      1.371464e+04
min      2.000000e+00
25%      1.139900e+04
50%      1.419400e+04
75%      1.858275e+04
max      1.714000e+06
Name: price_per_sqft, dtype: float64

In [69]:
column_cleaning['price_per_sqft'].quantile(
    [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
)

0.01     5443.49
0.05     8266.70
0.25    11399.00
0.50    14194.00
0.75    18582.75
0.95    33194.50
0.99    53030.69
Name: price_per_sqft, dtype: float64

In [70]:
column_cleaning[column_cleaning['price_per_sqft'] < 1000]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
1239,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,super seven plots,0.75,2.0,4312440 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",4 of 13 Floors,0,NaN,6,NaN,0,NaN,"['Civil Hospital', 'Vardaan Hospital and Traum...",We are the proud owners of this 3 bhk apartmen...,NaN,28.251879,77.067100,W91350586
1406,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,hcbs sports ville,0.45,530.0,8490 sqft Builtup Area,NaN,2,2,2.0,"Sohna, Gurgaon",11 of 13 Floors,0,NaN,1,NaN,0,NaN,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",We are the proud owners of this 2 bhk apartmen...,NaN,28.276076,77.056507,T89276149

In [71]:
validation_df = pd.DataFrame({
    'original': df_flat['price_per_sqft'],
    'converted': column_cleaning['price_per_sqft']
})

validation_df

            original  converted
0       ₹9,850 /sqft     9850.0
1      ₹19,243 /sqft    19243.0
2      ₹10,744 /sqft    10744.0
3      ₹12,162 /sqft    12162.0
4      ₹14,254 /sqft    14254.0
...              ...        ...
28499  ₹10,252 /sqft    10252.0
28500  ₹28,854 /sqft    28854.0
28501   ₹7,778 /sqft     7778.0
28502  ₹11,111 /sqft    11111.0
28503  ₹11,333 /sqft    11333.0

[28504 rows x 2 columns]

- Looks like min sqft is 2, which is not possible.

### 3. Bedroom

In [72]:
column_cleaning['bedRoom'].describe()

count    28480.000000
mean         2.970330
std          0.765259
min          1.000000
25%          2.000000
50%          3.000000
75%          3.000000
max         10.000000
Name: bedRoom, dtype: float64

In [73]:
column_cleaning['bedRoom'].unique()

array([ 2,  3,  1,  4,  5,  6,  7,  8, 10])

In [74]:
column_cleaning['bedRoom'].isnull().sum()

np.int64(0)

### 4. Bathroom

In [75]:
column_cleaning['bathroom'].describe()

count    28480.000000
mean         3.172367
std          1.084104
min          0.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         10.000000
Name: bathroom, dtype: float64

In [76]:
column_cleaning['bathroom'].unique()

array([ 2,  3,  4,  1,  5,  6,  7,  8,  0,  9, 10])

In [77]:
column_cleaning['bathroom'].isnull().sum()

np.int64(0)

In [78]:
column_cleaning[column_cleaning['bathroom'] == 0]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
9426,"3 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,greenopolis,1.70,8687.0,1957 sqft Superbuiltup Area,NaN,3,0,NaN,"Sector 89, Gurgaon",10 of 25 Floors,0,NaN,0,NaN,0,"[""N""]","['RPS International School', 'EBD 89 Business ...",This flat lies on the 10th level of a 25 store...,NaN,28.422015,76.943177,K90836946
20116,"5 BHK Flat in Sector 70, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,tulip melrose,5.14,20903.0,2459 sqft Carpet Area,2459.0,5,0,NaN,"Sector 70, Gurgaon",1 of 39 Floors,0,NaN,5,NaN,0,"[""N""]","['Shri Ram School, Sector 70', 'Omaxe City Cen...",Book a spectacular property in Tulip Melrose t...,NaN,28.394681,77.015293,Z87435612

- Missing Bathroom values has been indicated using O. We will replace those Zero with the Bedroom equivalent.

### 5. Balcony

In [37]:
column_cleaning['balcony'].unique()

array([ 4.,  2.,  3.,  1.,  0., nan])

In [38]:
column_cleaning['balcony'].isnull().sum()

np.int64(10)

In [39]:
column_cleaning[column_cleaning['balcony'].isnull()]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
1231,"1 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,breez global heights,0.35,7463.0,469 sqft Carpet Area,469.00,1,1,NaN,"Sohna, Gurgaon",4 of 10 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Polaris Hospital', 'JMD Megapolis Business C...","Located in breez global heights, sohna, this 1...",NaN,28.285808,77.066673,O91391502
7580,"3 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,orris carnation residency,1.30,7903.0,1645 sqft Carpet Area,1645.00,3,3,NaN,"Sector 85, Gurgaon",12 of 12 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Walking distance to Children Park', 'Close t...",This unfurnished 3 bhk flat in orris carnation...,['Top Floor'],28.404439,76.950907,J91390932
7624,"2 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,pyramid heights,0.73,12349.0,591 sqft Carpet Area,591.15,2,2,NaN,"Sector 85, Gurgaon",2 of 14 Floors,0,NaN,0,NaN,0,"[""N""]","['Aanyaz Mall', 'Sector 86 Road', 'Dwarka Expy...","Location of property very good, near malls, sc...",NaN,28.407284,76.947824,B88201514
9426,"3 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,greenopolis,1.70,8687.0,1957 sqft Superbuiltup Area,NaN,3,0,NaN,"Sector 89, Gurgaon",10 of 25 Floors,0,NaN,0,NaN,0,"[""N""]","['RPS International School', 'EBD 89 Business ...",This flat lies on the 10th level of a 25 store...,NaN,28.422015,76.943177,K90836946
16787,"3 BHK Flat in Sector 84, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,spaze kalistaa,3.50,15909.0,2200 sqft Carpet Area,2200.00,3,3,NaN,"Sector 84, Gurgaon",18 of 23 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Huda Metro Station', 'Vatika Town Square-INX...","Offering immediate possession, this unfurnishe...",NaN,28.402240,76.979255,E91391382
17764,"3 BHK Flat in Sector 61, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,smart world orchard,2.80,17178.0,1630 sqft Carpet Area,1630.00,3,3,NaN,"Sector 61, Gurgaon",4 of 4 Floors,0,NaN,0,NaN,0,"[""N""]","['Magnum Global Park', 'Grand Hyatt Gurgaon', ...",The flat occupies a carpet area of 1630 sq.Ft....,NaN,28.409907,77.101081,C90382132
18423,"2 BHK Flat in Sector 103, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,indiabulls centrum park,1.55,10466.0,1481 sqft Superbuiltup Area,NaN,2,2,NaN,"Sector 103, Gurgaon",7 of 18 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...","Available immediately, this unfurnished 2 bhk ...",NaN,28.499023,76.983105,B91390850
20116,"5 BHK Flat in Sector 70, Gurgaon",https://www.99acres.com/5-bhk-bedroom-apartmen...,tulip melrose,5.14,20903.0,2459 sqft Carpet Area,2459.00,5,0,NaN,"Sector 70, Gurgaon",1 of 39 Floors,0,NaN,5,NaN,0,"[""N""]","['Shri Ram School, Sector 70', 'Omaxe City Cen...",Book a spectacular property in Tulip Melrose t...,NaN,28.394681,77.015293,Z87435612
21406,"4 BHK Flat in Sector 67, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m merlin,5.95,18594.0,3200 sqft Superbuiltup Area,NaN,4,4,NaN,"Sector 67, Gurgaon",6 of 21 Floors,0,NaN,2,NaN,Semi-Furnished,"[""N""]","['Alpine Convent School', 'MKD Hospital', 'Air...",Situated on the 6th floor of a 21-Story high-R...,NaN,28.389679,77.059355,P91391060
24165,"3 BHK Flat in Sector 71, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,chd avenue 71,1.56,10512.0,1484 sqft Carpet Area,1484.00,3,3,NaN,"Sector 71, Gurgaon",9 of 14 Floors,0,NaN,2,NaN,Semi-Furnished,"[""N""]","['Apna Mart', 'Rajiv Chowk', 'Medanta Hospital...","This unfurnished 3 bhk flat, spanning 1484 sqf...",NaN,28.416575,77.025941,Y91391082

In [40]:
column_cleaning[column_cleaning['balcony'] == 0]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
449,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,mvn athens,0.40,8316.0,481 sqft Builtup Area,NaN,2,2,0.0,"Sohna, Gurgaon",7 of 7 Floors,North,NaN,1,NaN,Semi-Furnished,"{""O"":1}","['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...",2bhk multistorey apartment for resale in mvn a...,"['Top Floor', 'Close to Market', 'Gated Societ...",77.085413,28.255046,Y68022294
695,"2 BHK Flat in Sector-35 Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,silverglades the melia,1.50,9967.0,1500 sqft Superbuiltup Area,NaN,2,2,0.0,"Sector-35 Sohna, Gurgaon",9 of 14 Floors,North,"Pool, Park/Garden, Club, Main Road, Others",6,Y,Unfurnished,"{""C"":1}","['Sohna Road', 'Shambhu Dayal High School', 'G...","Basic details\nLocation: Sector 35, sohna (Sou...","['Pet Friendly', 'Full Power Backup', 'Visitor...",28.281936,77.057485,B89770638
1228,"1 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,vatika westin sohna resort,1.20,10000.0,1200 sqft Carpet Area,1200.00,1,1,0.0,"Sohna, Gurgaon",L of 1 Floors,0,NaN,6,NaN,0,"[""N""]","['National Highway 919', 'Vedas International ...","Situated in vatika westin sohna resort, gurgao...","['Fitness Center/ Gym', 'Club house', 'Swimmin...",28.237599,77.149407,L91445318
1292,"1 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,gls arawali homes,0.52,11111.0,468 sqft Builtup Area,NaN,1,1,0.0,"Sohna, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Furnished,NaN,"['IGI Airport', 'Huda City Centre', 'Golf Cour...","Containing 1 bedroom(s), 1 bathroom , this fla...",NaN,77.084068,28.263281,L90690914
1493,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,trisara our homes 3,0.58,9221.0,629 sqft Builtup Area,NaN,2,2,0.0,"Sohna, Gurgaon",4 of 4 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Trisara our homes 3 is one of the most popular...,NaN,28.427528,77.041432,K87656456
1511,"1 BHK Flat in Sector-4 Sohna, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,ganga tathastu,0.61,17250.0,352 sqft Carpet Area,352.62,1,1,0.0,"Sector-4 Sohna, Gurgaon",G of 1 Floors,North,"Park/Garden, Pool, Main Road, Others, Club, Se...",5,Y,Semi-Furnished,"[""N""]","['Global City Centre', 'Damdama Lake Road', 'B...",1- Only ground floor society shop\n2-High stre...,"['Wheel Chair Friendly', 'Pet Friendly', '24*7...",28.255089,77.083194,A87196512
1586,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,silverglades the melia,1.40,9722.0,1440 sqft Carpet Area,1440.00,2,3,0.0,"Sohna, Gurgaon",4 of 14 Floors,North,NaN,2,NaN,0,"[""N""]","['Sohna Road', 'Shambhu Dayal High School', 'G...",This 2 bhk apartment is available for sale in ...,"['Full Power Backup', '24*7 Water', 'On-Call M...",28.281936,77.057485,Q85696820
2411,"2 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,bptp amstoria verti greens,3.05,18451.0,1653 sqft Builtup Area,NaN,2,2,0.0,"Sector 102, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Shri Multispeciality Hospital', 'Basai dhank...",The flat occupies a built up area of 1653 sq.F...,NaN,28.476391,76.971492,U90668452
3351,"3 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,bestech altura,2.73,16062.0,1700 sqft Builtup Area,NaN,3,3,0.0,"Sector 79, Gurgaon",G of 1 Floors,0,NaN,2,NaN,Semi-Furnished,NaN,"['Petrol Pump', 'Petrol Pump Indian Oil', 'Rao...","Containing 3 bedroom(s), 3 bathrooms , this fl...",NaN,28.356554,76.973297,Y90856582
3361,"4 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m antalya hills by m3m india pvt. ltd.,2.30,14007.0,1642 sqft Builtup Area,NaN,4,4,0.0,"Sector 79, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Constructed on a built up area of 1642 sq.Ft.,...",NaN,28.361788,76.979272,D90649096
3371,"2 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,supertech araville,0.90,6950.0,1295 sqft Builtup Area,NaN,2,2,0.0,"Sector 79, Gurgaon",12 of 18 Floors,0,Main Road,6,NaN,Semi-Furnished,"[""N""]",NaN,2bhk multistorey apartment for new property in...,"['Close to School', 'Close to Hospital', 'Clos...",76.981995,28.364233,H90487126
3372,"3 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej 101,1.60,10178.0,1572 sqft Builtup Area,NaN,3,2,0.0,"Sector 79, Gurgaon",10 of 10 Floors,0,NaN,6,NaN,Unfurnished,"{""C"":1}","['Naurangpur Road', 'NH 48', 'Miracles Apollo ...","Located in godrej 101, sector 79, gurgaon, thi...","['Top Floor', 'Full Power Backup', 'Visitor Pa...",28.363828,76.979311,F90486878
3471,"3 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m antalya hills,2.00,12845.0,1557 sqft Builtup Area,NaN,3,3,0.0,"Sector 79, Gurgaon",3 of 4 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['National Highway 48', 'Sapphire 83 Mall', 'M...",The flat occupies a built up area of 1557 sq.F...,NaN,28.357292,76.972610,H88547706
3472,"1 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,signature global city 79b,2.10,11469.0,1831 sqft Builtup Area,NaN,1,1,0.0,"Sector 79, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,NaN,The floor plan additionally contains 1 bedroom...,NaN,28.356718,76.982788,X88519442
3549,"2 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,godrej 101,1.80,12959.0,1389 sqft Builtup Area,NaN,2,2,0.0,"Sector 79, Gurgaon",1 of 14 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Vatika Town Square-INXT', 'Naurangpur Road',...","This 2 bhk flat is located in godrej 101, whic...",NaN,28.364526,76.981414,D85721434
3559,"2 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,m3m antalya hills,1.80,14575.0,1235 sqft Superbuiltup Area,NaN,2,2,0.0,"Sector 79, Gurgaon",3 of 4 Floors,0,NaN,5,NaN,0,"{""C"":1}","['National Highway 48', 'Sapphire 83 Mall', 'M...",We are the proud owners of this 2 bhk apartmen...,"['Full Power Backup', 'Visitor Parking Availab...",28.357310,76.972660,W84265050
4387,"3 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,paras dews,2.15,11622.0,1850 sqft Builtup Area,1760.00,3,3,0.0,"Sector 106, Gurgaon",16 of 24 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Dwarka Sector 21 Metro Station', 'Conscient ...",3bhk multistorey apartment for resale in paras...,NaN,28.499886,77.000302,I80629875
5241,"4 BHK Flat in Sector 65, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,emaar mgf emerald floors premier,3.80,19241.0,1975 sqft Superbuiltup Area,NaN,4,4,0.0,"Sector 65, Gurgaon",G of 4 Floors,North,"Pool, Park/Garden, Club, Main Road, Others",2,Y,Unfurnished,"{""C"":2}","['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...",The flat is facing the east direction. The fla...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.399273,77.070425,Y90219786
5277,"3 BHK Flat in Sector 65, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m golfestate,12.50,31172.0,4010 sqft Superbuiltup Area,NaN,3,4,0.0,"Sector 65, Gurgaon",8 of 19 Floors,0,NaN,1,NaN,Furnished,"{""C"":2}","['Shiksha Bharti Public School', 'Holiday Inn ...",We are the proud owners of this 3 bhk apartmen...,"['Centrally Air Conditioned', 'Parking Availab...",28.401137,77.064929,R75762187
6008,"3 BHK Flat in Surat Nagar Phase 1, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,elan residential,5.18,19185.0,2700 sqft Superbuiltup Area,1350.00,3,3,0.0,"Surat Nagar Phase 1, Gurgaon",25 of 30 Floors,0,NaN,5,NaN,0,"[""N""]","['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Spanning 2700 sqft, this 3 bhk flat in elan re...",NaN,28.484594,77.003677,T91263716
6085,"4 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,rising homes,2.05,9762.0,2100 sqft Super Area,NaN,4,3,0.0,"Sector 92, Gurgaon",3 of 18 Floors,0,NaN,1,NaN,Unfurnished,"{""C"":1}","['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",The flat occupies a built up area of 2090 sq.F...,"['Parking Available', 'Modular Kitchen', 'Fitn...",28.407854,76.915328,Z88224702
6738,"1 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,bestech park view sanskruti,3.25,13978.0,2325 sqft Builtup Area,NaN,1,1,0.0,"Sector 92, Gurgaon",G of 1 Floors,0,NaN,1,NaN,Unfurnished,NaN,"['Sapphire 93 Mall', 'Holiday Inn Sector 90', ...",The floor plan additionally contains 1 bedroom...,NaN,28.408808,76.927284,H90364652
6771,"2 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,gls south avenue,0.62,11012.0,563 sqft Carpet Area,563.00,2,2,0.0,"Sector 92, Gurgaon",G of 1 Floors,0,NaN,2,NaN,Semi-Furnished,NaN,"['Balaji Store', 'Signum Plaza 2 Mall', 'Grofe...","Constructed on a carpet area of 563 sq.Ft., th...",NaN,28.402763,76.910706,Q89742526
6911,"3 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,raheja navodaya,2.25,5625.0,4000 sqft Carpet Area,4000.00,3,4,0.0,"Sector 92, Gurgaon",G of 16 Floors,0,NaN,3,NaN,Unfurnished,"{""C"":1}","['Iris Broadway', 'Pataudi Road', 'Jyoti Publi...",Residential apartment for sell.Located in sect...,"['On-Call Maintenance Staff', 'Vaastu Complian...",28.407789,76.915274,G74729627
7356,"1 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,godrej air,1.00,10477.0,954 sqft Carpet Area,88.67,1,1,0.0,"Sector 85, Gurgaon",6 of 32 Floors,0,NaN,1,NaN,Semi-Furnished,"[""N""]","['Genesis Hospital', 'Iris Broadway', 'Euro In...",The flat is over 89 sq.M. Carpet area and come...,"['Vaastu Compliant', 'Power Back-up', 'Lift']",28.408646,76.951894,W91491472
8227,"4 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,navraj the kingstown heights,4.00,15444.0,2590 sqft Builtup Area,NaN,4,4,0.0,"Sector 37D, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Shri Balaji Hospital and Trauma Center', 'Ka...","Containing 4 bedroom(s), 4 bathrooms , this fl...",NaN,28.447800,76.970299,Y90810966
8249,"3 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,navraj the antalya,2.85,12667.0,2250 sqft Builtup Area,NaN,3,3,0.0,"Sector 37D, Gurgaon",1 of 5 Floors,0,Main Road,6,NaN,Unfurnished,"{""C"":1}","['Shri Balaji Hospital and Trauma Center', 'Ka...",This 3 bhk apartment is available for sale in ...,"['Visitor Parking Available', 'Close to School...",28.447800,76.970299,R90413366
8304,"2 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,signature global city,1.16,11470.0,1010 sqft Builtup Area,NaN,2,1,0.0,"Sector 37D, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,"[""N""]","['Euro International School', 'Dwarka Expressw...","Constructed on a built up area of 1010 sq.Ft.,...",['Ground Floor'],28.409611,76.914194,K88547718
8338,"3 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ramprastha skyz,1.75,10145.0,1725 sqft Builtup Area,NaN,3,3,0.0,"Sector 37D, Gurgaon",13 of 24 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['The Esplanade Mall', 'National Highway 248BB...",Located in the popular residential address of ...,NaN,76.972629,28.447710,C87289666
9140,"3 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m soulitude,2.00,13387.0,1494 sqft Builtup Area,NaN,3,3,0.0,"Sector 89, Gurgaon",4 of 5 Floors,North-East,"Park/Garden, Main Road",6,Y,Furnished,"{""C"":1}","['Dwarka Expressway', 'Genesis Hospital', 'Iri...","Three side open corner unit, park facing, east...","['Pet Friendly', 'Full Power Backup', 'Visitor...",28.417824,76.945281,Z91296102
9154,"3 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,tulip petals,1.75,11290.0,1550 sqft Superbuiltup Area,NaN,3,2,0.0,"Sector 89, Gurgaon",8 of 10 Floors,0,NaN,2,NaN,0,NaN,"['Pataudi Road', 'Saraswati Model School', 'Dw...",We are the proud owners of this 3 bhk apartmen...,NaN,28.425568,76.944321,F78769107
9484,"2 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,mrg the meridian,0.75,12000.0,625 sqft Superbuiltup Area,NaN,2,2,0.0,"Sector 89, Gurgaon",20 of 24 Floors,0,NaN,5,NaN,0,NaN,"['Signature Global Signum', 'Patanjali Store',...",We are the proud owners of this 2 bhk apartmen...,NaN,28.443118,76.986121,C83964754
9499,"2 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,mrg the meridian,0.85,13600.0,625 sqft Carpet Area,625.00,2,2,0.0,"Sector 89, Gurgaon",15 of 24 Floors,0,NaN,5,NaN,Semi-Furnished,"[""N""]","['Signature Global Signum', 'Patanjali Store',...",We are the proud owners of this 2 bhk apartmen...,"['Close to School', 'Close to Market', 'Close ...",28.443118,76.986121,K90372562
9517,"4 BHK Flat in Sector 89, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,NaN,1.80,11976.0,1503 sqft Builtup Area,NaN,4,4,0.0,"Sector 89, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Orris Community Center', 'Indian Oil', 'Essa...","Containing 4 bedroom(s), 4 bathrooms , this fl...",NaN,28.418284,76.945704,B89922878
10580,"3 BHK Flat in DLF Phase 5, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,dlf carlton estate,3.20,22890.0,1398 sqft Builtup Area,NaN,3,3,0.0,"DLF Phase 5, Gurgaon",11 of 19 Floors,East,Others,3,NaN,0,"[""N""]","['Club5', 'Haryana City Gas', 'Wellington Esta...",This property faces the north direction. Const...,"['Full Power Backup', 'Visitor Parking Availab...",28.449635,77.095411,O90658716
10730,"3 BHK Flat in DLF Phase 5, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,dlf carlton estate,3.30,23605.0,1398 sqft Builtup Area,NaN,3,3,0.0,"DLF Phase 5, Gurgaon",11 of 19 Floors,0,NaN,3,NaN,0,"[""N""]","['Club5', 'Haryana City Gas', 'Wellington Esta...","Containing 3 bedroom(s), 3 bathrooms , this fl...",NaN,28.449635,77.095411,R90912468
10740,"3 BHK Flat in DLF Phase 5, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,dlf carlton estate,3.45,24678.0,1398 sqft Builtup Area,NaN,3,3,0.0,"DLF Phase 5, Gurgaon",4 of 15 Floors,0,NaN,2,NaN,0,"[""N""]","['Club5', 'Haryana City Gas', 'Wellington Esta...","101 % confirm deal . "" exclusive deal "" , max ...",NaN,28.449635,77.095411,E8165183
11006,"3 BHK Flat in DLF Phase 5, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,dlf princeton estate,3.50,25641.0,1365 sqft Builtup Area,NaN,3,3,0.0,"DLF Phase 5, Gurgaon",5 of 5 Floors,0,NaN,2,NaN,0,"[""N""]","['Sector 42-43 Metro Station', 'Ardee Mall', '...","Located in phase v of dlf city, princeton comp...",NaN,28.448380,77.096330,T8112555
11136,"3 BHK Flat in Sector 69, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,smartworld sky arc,4.60,19533.0,2355 sqft Builtup Area,NaN,3,2,0.0,"Sector 69, Gurgaon",23 of 41 Floors,0,NaN,5,NaN,Semi-Furnished,"[""N""]","['Raheja Mall', 'Sri Radhe Krishna Temple', 'I...",Residential apartment\nThis is your chance to ...,NaN,28.397615,77.038255,Y86186738
11606,"3 BHK Flat in Sector 69, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,5.28,22000.0,2400 sqft Builtup Area,NaN,3,3,0.0,"Sector 69, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Looking for a 3 bhk property for sale in gurga...,NaN,28.395628,77.038365,V85227144
12597,"4 BHK Flat in Sector 66, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,smartworld the edition,6.30,20758.0,3035 sqft Builtup Area,NaN,4,3,0.0,"Sector 66, Gurgaon",24 of 24 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Best in class property available at sector 66 ...,NaN,28.397955,77.055318,W80449449
13525,"3 BHK Flat in Sector 81, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,bestech park view ananda,2.25,12431.0,1810 sqft Superbuiltup Area,1180.00,3,3,0.0,"Sector 81, Gurgaon",13 of 15 Floors,0,"Pool, Park/Garden, Club",1,NaN,Unfurnished,"{""O"":2}","['Miracles Apollo Cradle /Spectra Hospital', ""...","Offering 1810 sq.Ft., this semi-Furnished 3 bh...","['24*7 Water', 'Centrally Air Conditioned', 'O...",28.390872,76.952720,Z87202604
13546,"2 BHK Flat in Sector 81, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,signature global synera,0.72,12040.0,598 sqft Builtup Area,NaN,2,2,0.0,"Sector 81, Gurgaon",7 of 14 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Orris Community Center', 'HP Petrol Pump', '...",Check out this 2 bhk apartment for sale in sig...,NaN,28.388474,76.947084,O85397670
13607,"3 BHK Flat in Sector 81, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,bestech park view ananda,1.70,10334.0,1645 sqft Superbuiltup Area,NaN,3,2,0.0,"Sector 81, Gurgaon",G of 15 Floors,0,"Park/Garden, Club, Pool",1,NaN,Unfurnished,"{""C"":1}","['Miracles Apollo Cradle /Spectra Hospital', ""...","Park view ananda, an exquisite group housing p...","['24*7 Water', 'Centrally Air Conditioned', 'O...",28.390872,76.952720,M49370037
14218,"3 BHK Flat in Sector 76, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,whiteland the aspen,3.55,15502.0,2290 sqft Builtup Area,NaN,3,2,0.0,"Sector 76, Gurgaon",11 of 30 Floors,0,NaN,5,NaN,Unfurnished,"[""N""]","['Vega Schools', 'National Highway 48', 'Sapph...",3bhk multistorey apartment for resale in white...,NaN,28.394920,76.989360,R80351083
14531,"3 BHK Flat in Sector 76, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,whiteland blissville,1.72,10287.0,1672 sqft Builtup Area,NaN,3,3,0.0,"Sector 76, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Unfurnished,NaN,"['Govt. Stadium Hasanpur', 'NH 48', 'Aatish Ho...",Check out this 3 bhk apartment for sale in whi...,NaN,76.992553,28.393887,P80856849
14983,"3 BHK Flat in Sector 111, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,NaN,3.84,25600.0,1500 sqft Builtup Area,NaN,3,3,0.0,"Sector 111, Gurgaon",G of 1 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Palam Vihar Vyapar kendra', 'HUDA Sector 23 ...",The flat is over 1500 sq.Ft. Built up area and...,NaN,28.525049,77.032713,L90450858
14988,"3 BHK Flat in Sector 111, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m crown,3.22,17000.0,1895 sqft Builtup Area,NaN,3,3,0.0,"Sector 111, Gurgaon",3 of 24 Floors,0,NaN,6,NaN,Semi-Furnished,NaN,"['Park Hospital', 'Global Foyer Mall', 'Dwarka...","This 3 bhk flat is located in m3m crown, which...",NaN,28.524047,77.032158,P80901299
15036,"1 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,central park the room,1.95,24375.0,800 sqft Builtup Area,NaN,1,1,0.0,"Sector 48, Gurgaon",10 of 17 Floors,0,NaN,2,NaN,Furnished,"{""C"":1}","['Gurjar Samrat Jaipal Khatana Marg', 'NH 248A...",Fully serviced apartment...........,"['Full Power Backup', 'Centrally Air Condition...",28.423609,77.037188,C90070844
15245,"1 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,central park the room,2.65,19471.0,1361 sqft Superbuiltup Area,NaN,1,1,0.0,"Sector 48, Gurgaon",11 of 17 Floors,North,"Pool, Park/Garden, Club, Main Road, Sea facing...",1,Y,Furnished,"{""C"":2}","['Gurjar Samrat Jaipal Khatana Marg', 'NH 248A...",Located in the popular residential address of ...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.423174,77.037844,S87744718
15314,"1 BHK Flat in Sector 48, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,central park resorts,2.75,20355.0,1351 sqft Carpet Area,1351.00,1,1,0.0,"Sector 48, Gurgaon",7 of 17 Floors,0,NaN,2,Y,Furnished,"{""C"":1}","['Park Hospital', 'Omaxe Celebration Mall', 'G...","Constructed on a carpet area of 1351 sq.Ft., t...","['Pet Friendly', 'Visitor Parking Available', ...",28.424782,77.032571,X90240690

- Zero Balcony means No Balcony. So no need to do anything. We can keep it as it is.

### 6. Facing

In [41]:
column_cleaning['facing']

0        North-East
1                 0
2             North
3        North-East
4             North
            ...
28499    North-East
28500             0
28501             0
28502          East
28503    North-East
Name: facing, Length: 28480, dtype: object

In [42]:
column_cleaning['facing'].value_counts()

facing
North         8686
North-East    7891
0             4446
East          3644
South         1564
North-West    1024
West           518
South-East     465
South-West     242
Name: count, dtype: int64

In [43]:
column_cleaning['facing'].isnull().sum()

np.int64(0)

In [44]:
column_cleaning = (
    df_flat
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (df_['price_in_cr'] != '25,000')
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace("L","")
                    .str
                    .replace(",","")
                    .str 
                    .strip())
    ,facing  = lambda df_: df_['facing']
                                .replace('0',"Not Available")
                                .str
                                .lower()))
    

column_cleaning

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,eldeco accolade,1.25,9850.0,1269 sqft Superbuiltup Area,726.0,2,2,4.0,"Sohna, Gurgaon",2 of 18 Floors,north-east,"Park/Garden, Main Road, Club, Pool, Others",1,Y,Semi-Furnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",The flat is north-East-Facing. The flat occupi...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.259939,77.064480,M89360483
1,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global daxin vistas,3.00,19243.0,1559 sqft Builtup Area,NaN,3,3,2.0,"Sohna, Gurgaon",4 of 4 Floors,not available,NaN,5,NaN,Furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...",The flat is over 1559 sq.Ft. Built up area and...,"['Full Power Backup', 'Visitor Parking Availab...",28.332976,77.067894,T91323470
2,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,eldeco accolade,1.56,10744.0,1452 sqft Superbuiltup Area,1000.0,2,2,4.0,"Sohna, Gurgaon",8 of 18 Floors,north,"Pool, Park/Garden, Club",1,Y,Unfurnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",It's spacious 2.5 bhk with an extremely open a...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.266652,77.064904,F89903984
3,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiana anmol,2.16,12162.0,1776 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",10 of 14 Floors,north-east,"Park/Garden, Main Road",6,Y,0,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. C...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286897,77.071375,Z90919772
4,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,central park flower valley the room,2.55,14254.0,1789 sqft Builtup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 14 Floors,north,NaN,6,Y,Furnished,"{""C"":1}","['Huda Metro Station', 'Raheja Mall', 'Central...",For those who prefer high end living\nWelcome ...,"['Full Power Backup', 'Close to School', 'Cent...",28.284257,77.079086,H84077598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28499,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,kw royal court,3.30,10252.0,3219 sqft Superbuiltup Area,2500.0,4,5,1.0,"Sector 39, Gurgaon",9 of 12 Floors,north-east,"Park/Garden, Club",1,NaN,Unfurnished,"{""C"":2}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",2500 sqft carpet 4bhk+servant available for sa...,"['On-Call Maintenance Staff', 'Vaastu Complian...",28.441474,77.043613,K90588706
28500,"3 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej alira,7.00,28854.0,2426 sqft Carpet Area,2426.0,3,4,2.0,"Sector 39, Gurgaon",33 of 33 Floors,not available,NaN,1,NaN,Semi-Furnished,"[""N""]","['Rajiv Chowk Mosque', 'State bank of india AT...","Constructed on a carpet area of 2426 sq.Ft., t...",NaN,28.442331,77.049250,E90056680
28501,"2 BHK Flat in Saini Pura, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,bharat residency,0.70,7778.0,900 sqft Carpet Area,900.0,2,2,1.0,"Saini Pura, Gurgaon",2 of 5 Floors,not available,NaN,1,NaN,0,"[""N""]","['Rajiv Chowk Mosque', 'State bank of india AT...","Located in bharat residency, saini pura, gurga...",NaN,28.446360,77.051020,E89187547
28502,"2 BHK Flat in Jharsa, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,royal blue city,1.00,11111.0,900 sqft Carpet Area,100.0,2,2,1.0,"Jharsa, Gurgaon",2 of 4 Floors,east,Main Road,1,NaN,Unfurnished,"{""C"":1}","['IFFCO Chowk', '(HUDA City Centre) Rajiv', 'S...",A well-Maintained and spacious 2 bhk flat in a...,"['Full Power Backup', 'Close to Market', 'Gate...",28.443173,77.052033,O87439246
28503,"3 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,city heights,2.55,11333.0,2250 sqft Superbuiltup Area,2000.0,3,3,2.0,"Sector 39, Gurgaon",2 of 12 Floors,north-east,"Park/Garden, Main Road",2,Y,Unfurnished,"{""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",Looking for a 3 bhk property for sale in gurga...,"['North-East Facing', 'Wheel Chair Friendly', ...",28.440349,77.042917,A87227320

In [45]:
column_cleaning['facing'].value_counts()

facing
north            8686
north-east       7891
not available    4446
east             3644
south            1564
north-west       1024
west              518
south-east        465
south-west        242
Name: count, dtype: int64

### 7. Age possession

In [46]:
column_cleaning['agePossession'].value_counts()

agePossession
1    10608
6     5462
2     5406
5     4784
3     2073
0      147
Name: count, dtype: int64

In [47]:
column_cleaning['agePossession'].isnull().sum()

np.int64(0)

In [48]:
column_cleaning[column_cleaning['agePossession'] == 0]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
87,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global park,1.32,10909.0,1210 sqft Superbuiltup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 4 Floors,north-east,"Club, Park/Garden, Pool, Main Road",0,Y,Unfurnished,"{""O"":1,""C"":1}","['NH248A', 'K. R. Mangalam University', 'Sanji...",This property is very good becaouse of it's at...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.289722,77.064281,P89711214
107,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global park,1.65,13636.0,1210 sqft Superbuiltup Area,NaN,3,3,4.0,"Sohna, Gurgaon",2 of 4 Floors,north-east,"Main Road, Club, Park/Garden, Pool, Others",0,Y,Unfurnished,"{""O"":1,""C"":1}","['NH248A', 'K. R. Mangalam University', 'Sanji...",This property is very good becaouse of it's at...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.289722,77.064281,X89711122
213,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,silverglades the melia,1.32,8800.0,1500 sqft Superbuiltup Area,NaN,2,2,2.0,"Sohna, Gurgaon",10 of 14 Floors,north,"Pool, Park/Garden",0,Y,Unfurnished,"{""O"":1,""C"":2}","['Sohna Road', 'Shambhu Dayal High School', 'G...",This residential flat is east-Facing direction...,"['Full Power Backup', 'Centrally Air Condition...",28.281354,77.058684,L90470000
610,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global park,1.65,10645.0,1550 sqft Superbuiltup Area,NaN,3,2,4.0,"Sohna, Gurgaon",2 of 4 Floors,north-east,"Main Road, Club, Park/Garden, Pool",0,Y,Unfurnished,"{""O"":1,""C"":1}","['NH248A', 'K. R. Mangalam University', 'Sanji...",This property is very good becaouse of it's at...,"['Full Power Backup', 'Visitor Parking Availab...",28.288317,77.066043,Q89694966
740,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiana anmol,1.76,10233.0,1720 sqft Superbuiltup Area,NaN,3,3,2.0,"Sohna, Gurgaon",9 of 14 Floors,north-east,"Main Road, Club, Park/Garden, Pool",0,Y,Unfurnished,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",This property is very good becaouse of it's at...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.286932,77.069609,F89708154
2906,"3 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m golf hills,2.50,14988.0,1668 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 79, Gurgaon",12 of 29 Floors,north-east,NaN,0,Y,Unfurnished,"{""O"":2,""C"":1}","['S.R.S. Hospital and Critical Care Unit', 'Pe...",The flat is north-East-Facing. Containing 3 be...,"['Centrally Air Conditioned', 'Corner Property...",28.378664,76.993327,I90983310
2973,"3 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m golf hills,3.00,13274.0,2260 sqft Superbuiltup Area,1800.00,3,3,4.0,"Sector 79, Gurgaon",14 of 29 Floors,north-east,"Pool, Park/Garden, Club, Main Road",0,Y,Unfurnished,"{""C"":2}","['S.R.S. Hospital and Critical Care Unit', 'Pe...",Uniquely designed club accolade spread over 15...,"['Full Power Backup', 'Visitor Parking Availab...",28.378664,76.993327,Z90911578
2974,"4 BHK Flat in Sector 79, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m golf hills,5.50,20913.0,2630 sqft Superbuiltup Area,2000.00,4,4,4.0,"Sector 79, Gurgaon",27 of 29 Floors,north-east,"Pool, Park/Garden, Club, Main Road",0,Y,Unfurnished,"{""C"":2}","['S.R.S. Hospital and Critical Care Unit', 'Pe...",Uniquely designed club accolade spread over 15...,"['Full Power Backup', 'Visitor Parking Availab...",28.378664,76.993327,S90911444
3780,"3 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej meridien,2.96,15957.0,1855 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 106, Gurgaon",17 of 34 Floors,north-east,Park/Garden,0,Y,Unfurnished,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Visitor Parking Availab...",28.506740,76.990626,P89894056
3943,"4 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,godrej meridien,3.99,14669.0,2720 sqft Superbuiltup Area,2026.00,4,4,4.0,"Sector 106, Gurgaon",30 of 34 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""C"":2}","['Dwarka Expressway', 'Euro International Scho...",The flat is facing the north-East direction. T...,"['Full Power Backup', 'Centrally Air Condition...",28.509519,76.988676,B90281624
4156,"4 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,godrej meridien,4.00,14706.0,2720 sqft Superbuiltup Area,2026.00,4,4,4.0,"Sector 106, Gurgaon",26 of 34 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""C"":2}","['Dwarka Expressway', 'Euro International Scho...",The flat is facing the north-East direction. T...,"['Full Power Backup', 'Centrally Air Condition...",28.509519,76.988676,P90281454
4228,"4 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,godrej meridien,4.25,15625.0,2720 sqft Superbuiltup Area,NaN,4,4,3.0,"Sector 106, Gurgaon",15 of 34 Floors,north-east,Park/Garden,0,NaN,Unfurnished,"{""C"":2}","['Dwarka Expressway', 'Euro International Scho...",The flat is north-East-Facing. The flat occupi...,"['Full Power Backup', 'Centrally Air Condition...",28.509519,76.988676,D90831814
4229,"3 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej meridien,3.15,15734.0,2002 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 106, Gurgaon",12 of 34 Floors,north-east,Park/Garden,0,Y,Unfurnished,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Centrally Air Condition...",28.509519,76.988676,A90831410
4230,"3 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej meridien,2.95,15903.0,1855 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 106, Gurgaon",10 of 24 Floors,north-east,Park/Garden,0,NaN,Unfurnished,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",The flat is north-East-Facing. Constructed on ...,"['Full Power Backup', 'Centrally Air Condition...",28.509519,76.988676,Q90830456
4231,"3 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej meridien,2.51,15446.0,1625 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 106, Gurgaon",8 of 20 Floors,north-east,Park/Garden,0,Y,Unfurnished,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",This property faces the north-East direction. ...,"['Full Power Backup', 'Centrally Air Condition...",28.509519,76.988676,V90826268
4381,"4 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,paras dews,1.95,8280.0,2355 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 106, Gurgaon",G of 24 Floors,north,"Pool, Park/Garden, Club, Main Road",0,Y,Unfurnished,"{""C"":2}","['Dwarka Sector 21 Metro Station', 'Conscient ...","Call 95605 09397, exclusive and multiple deals...","['Ground Floor', 'Full Power Backup', 'Central...",28.499693,76.999962,R90169344
4898,"3 BHK Flat in Sector 65, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m heights,3.72,18111.0,2054 sqft Superbuiltup Area,1450.00,3,4,3.0,"Sector 65, Gurgaon",40 of 48 Floors,south,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""C"":1}","['M3m 65th Avenue Mall', 'DPS International Sc...",The flat is facing the west direction. The fla...,"['Pet Friendly', 'Full Power Backup', 'Central...",28.404994,77.065135,W91363232
5721,"2 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,godrej summit,1.05,8314.0,1269 sqft Superbuiltup Area,947.00,2,2,4.0,"Sector 104, Gurgaon",10 of 17 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""C"":1}","['Dhanwapur Road', 'Gurgaon Railway Station', ...",The flat is north-East-Facing. Containing 2 be...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.483790,76.000550,D91463910
5722,"2 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,godrej summit,1.18,8178.0,1446 sqft Superbuiltup Area,1057.00,2,2,4.0,"Sector 104, Gurgaon",7 of 17 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Semi-Furnished,"{""C"":1}","['Dhanwapur Road', 'Gurgaon Railway Station', ...",This is a north-East-Facing property. The floo...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.483790,76.000550,O91463780
5723,"3 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej summit,1.52,8398.0,1816 sqft Carpet Area,1816.00,3,4,4.0,"Sector 104, Gurgaon",12 of 17 Floors,north-east,"Park/Garden, Pool, Club, Main Road, Others",0,Y,Unfurnished,"{""C"":1}","['Dhanwapur Road', 'Gurgaon Railway Station', ...",This property faces the north-East direction. ...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.483790,76.000550,K91463638
5724,"2 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,godrej summit,1.05,8294.0,1269 sqft Superbuiltup Area,947.00,2,2,4.0,"Sector 104, Gurgaon",7 of 17 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""C"":1}","['Dhanwapur Road', 'Gurgaon Railway Station', ...",This property faces the north-East direction. ...,"['Pet Friendly', 'Full Power Backup', 'Visitor...",28.483790,76.000550,H91463530
6012,"1 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,zara aavaas,0.39,9750.0,400 sqft Carpet Area,400.00,1,2,2.0,"Sector 104, Gurgaon",2 of 3 Floors,not available,NaN,0,NaN,Unfurnished,"[""N""]","['Ardee Mall', 'Northern Peripheral Road', 'Mp...","Located in zara aavaas, sector 104, gurgaon, t...","['Pet Friendly', 'Close to Railway Station', '...",28.486490,77.001000,G90914048
6015,"3 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej summit,1.35,8197.0,1647 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 104, Gurgaon",6 of 17 Floors,north-east,NaN,0,NaN,Unfurnished,"{""C"":1}","['Dhanwapur Road', 'Gurgaon Railway Station', ...",This is a north-East-Facing property. The flat...,"['On-Call Maintenance Staff', 'Parking Availab...",28.483051,77.002923,Q90107980
6428,"3 BHK Flat in Sector 92, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,sare crescent parc,1.25,8509.0,1469 sqft Superbuiltup Area,NaN,3,3,2.0,"Sector 92, Gurgaon",6 of 23 Floors,not available,NaN,0,NaN,0,"[""N""]","['Pataudi Highway', 'GD International School',...",Constructed on a super built up area of 1469 s...,NaN,28.412704,76.914062,M90585966
7013,"2 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,godrej air,2.05,14747.0,1390 sqft Carpet Area,1390.16,2,2,1.0,"Sector 85, Gurgaon",21 of 32 Floors,south,"Pool, Park/Garden, Club, Main Road, Others, Se...",0,Y,Semi-Furnished,"{""C"":1}","['Genesis Hospital', 'Iris Broadway', 'Euro In...",Godrej air near to dwarka expressway.Containin...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.409770,76.950504,Y88422700
7159,"2 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,pyramid heights,0.70,11706.0,598 sqft Carpet Area,598.00,2,2,1.0,"Sector 85, Gurgaon",6 of 14 Floors,north,Main Road,0,Y,Unfurnished,"[""N""]","['Aanyaz Mall', 'Sector 86 Road', 'Dwarka Expy...","2bhk available for sale in pyramid heights, se...","['Corner Property', 'Overlooking Main Road', '...",28.406329,76.947819,K89732616
7223,"2 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,pyramid heights,0.68,11371.0,598 sqft Carpet Area,598.00,2,2,1.0,"Sector 85, Gurgaon",8 of 14 Floors,north,Main Road,0,Y,Unfurnished,"[""N""]","['Aanyaz Mall', 'Sector 86 Road', 'Dwarka Expy...","2bhk available for sale in pyramid heights, se...","['Corner Property', 'Overlooking Main Road', '...",28.405629,76.947626,N89732502
7624,"2 BHK Flat in Sector 85, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,pyramid heights,0.73,12349.0,591 sqft Carpet Area,591.15,2,2,NaN,"Sector 85, Gurgaon",2 of 14 Floors,not available,NaN,0,NaN,0,"[""N""]","['Aanyaz Mall', 'Sector 86 Road', 'Dwarka Expy...","Location of property very good, near malls, sc...",NaN,28.407284,76.947824,B88201514
7698,"3 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ramprastha the edge towers,1.55,7789.0,1990 sqft Superbuiltup Area,1600.00,3,4,4.0,"Sector 37D, Gurgaon",10 of 19 Floors,east,Park/Garden,0,Y,Semi-Furnished,"{""C"":""1""}","['Dwarka Expressway', 'Euro International Scho...",Ramprastha the edge towers is one of the most ...,"['Wheel Chair Friendly', 'Pet Friendly', 'Full...",28.446761,76.967714,G71303790
7750,"3 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,bptp spacio,1.65,12663.0,1303 sqft Superbuiltup Area,NaN,3,3,3.0,"Sector 37D, Gurgaon",7 of 19 Floors,north,Park/Garden,0,Y,Unfurnished,"{""C"":1}","['Gurgaon Dreamz Mall', 'Dwarka Expressway', '...",The flat is facing the east direction. Constru...,"['Full Power Backup', 'Centrally Air Condition...",28.454106,76.973978,W91162412
7778,"3 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ramprastha the edge towers,1.52,8444.0,1800 sqft Superbuiltup Area,NaN,3,3,4.0,"Sector 37D, Gurgaon",17 of 19 Floors,north-east,Park/Garden,0,Y,0,"{""C"":1}","['Dwarka Expressway', 'Euro International Scho...",This property faces the north-East direction. ...,"['Full Power Backup', 'Corner Property', 'Vaas...",28.447638,76.968964,K91434854
7829,"2 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,signature global the millennia,0.78,12000.0,650 sqft Carpet Area,650.00,2,2,4.0,"Sector 37D, Gurgaon",G of 14 Floors,not available,NaN,0,NaN,Unfurnished,"[""N""]","['The Esplanade Mall', 'The Signature Advanced...",A beautifully designed 2bhk featuring 4 balcon...,"['Vaastu Compliant', 'Modular Kitchen']",28.446539,76.979294,T90413026
7916,"3 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,navraj the analia,2.55,11313.0,2250 sqft Superbuiltup Area,NaN,3,4,3.0,"Sector 37D, Gurgaon",3 of 5 Floors,north-east,"Park/Garden, Club, Main Road, Pool",0,Y,Unfurnished,"{""C"":1}","['The Signature Advanced Super Speciality', 'M...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Visitor Parking Availab...",28.450858,76.973380,I89970582
7936,"4 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,ramprastha the edge towers,1.95,8159.0,2390 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 37D, Gurgaon",9 of 19 Floors,north-east,"Club, Park/Garden",0,Y,0,"{""C"":2}","['Dwarka Expressway', 'Euro International Scho...",The flat is north-East-Facing. Containing 4 be...,"['Full Power Backup', 'Corner Property', 'Vaas...",28.446516,76.968368,U90790076
8015,"2 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,signature global the millennia 3,0.67,11204.0,598 sqft Carpet Area,598.00,2,2,3.0,"Sector 37D, Gurgaon",13 of 19 Floors,not available,NaN,0,NaN,0,"[""N""]","['The Esplanade Mall', 'Dwarka Expressway', 'M...","Containing 2 bedroom(s), 2 bathrooms , this fl...",NaN,28.444440,76.966981,O89500906
8073,"2 BHK Flat in Sector 37D, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,bptp spacio,1.40,12975.0,1079 sqft Superbuiltup Area,NaN,2,2,4.0,"Sector 37D, Gurgaon",15 of 19 Floors,north,Park/Garden,0,NaN,Semi-Furnished,"{""C"":1}","['Gurgaon Dreamz Mall', 'Dwarka Expressway', '...",The flat is east-Facing. The floor plan additi...,"['Full Power Backup', 'Parking Available', 'Fi...",28.447830,76.970341,F91164064
8433,"4 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m capital,3.60,15666.0,2298 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 113, Gurgaon",12 of 36 Floors,north-west,"Main Road, Park/Garden, Pool, Club, Others",0,Y,Unfurnished,"{""C"":2}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",The flat is facing the north-West direction. C...,"['Full Power Backup', 'Centrally Air Condition...",28.525172,77.025319,T90828736
8434,"4 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m capital,3.20,15534.0,2060 sqft Carpet Area,2060.00,4,4,4.0,"Sector 113, Gurgaon",17 of 36 Floors,north-west,"Main Road, Others, Club, Park/Garden, Pool",0,Y,Unfurnished,"{""C"":1}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",This is a north-West-Facing property. Containi...,"['Full Power Backup', 'Centrally Air Condition...",28.522872,77.027478,U90828156
8486,"4 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m capital,3.35,16262.0,2060 sqft Carpet Area,2060.00,4,4,4.0,"Sector 113, Gurgaon",18 of 36 Floors,north-west,"Main Road, Club, Park/Garden, Pool, Others",0,Y,Unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",This residential flat is north-West-Facing dir...,"['Full Power Backup', 'Yashobhoomi Metro Stati...",28.524723,77.026006,M90498684
8487,"3 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m capital,2.65,15916.0,1665 sqft Carpet Area,1665.00,3,3,4.0,"Sector 113, Gurgaon",8 of 36 Floors,north-west,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""O"":2,""C"":1}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",The flat is north-West-Facing. The floor plan ...,"['Full Power Backup', 'Centrally Air Condition...",28.525313,77.025577,G90498512
8650,"4 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m capital,3.36,16311.0,2060 sqft Carpet Area,2060.00,4,4,4.0,"Sector 113, Gurgaon",14 of 36 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Centrally Air Condition...",28.525769,77.027318,F90695270
8651,"4 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,m3m capital,3.35,16262.0,2060 sqft Carpet Area,2060.00,4,4,4.0,"Sector 113, Gurgaon",18 of 36 Floors,north-east,"Park/Garden, Pool, Club, Main Road, Others",0,Y,Unfurnished,"{""O"":1,""C"":1}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",This residential flat is north-East-Facing dir...,"['Full Power Backup', 'Centrally Air Condition...",28.525769,77.027318,K90695094
8656,"3 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,m3m capital,3.96,24000.0,2400 sqft Superbuiltup Area,1650.00,3,3,4.0,"Sector 113, Gurgaon",29 of 36 Floors,north-east,"Club, Main Road, Pool",0,Y,Unfurnished,"{""C"":2}","['Dwarka Sector-25 Metro Station', 'Baghera Un...",Uniquely designed club accolade spread over 15...,"['Full Power Backup', 'Visitor Parking Availab...",28.525769,77.027318,R90911212
8749,"3 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,la vida by tata housing,4.02,14944.0,2690 sqft Superbuiltup Area,NaN,3,4,4.0,"Sector 113, Gurgaon",21 of 25 Floors,south-west,"Pool, Park/Garden, Club, Main Road, Others",0,Y,Unfurnished,"{""O"":1,""C"":2}","['Orchids The International School', 'Dwarka E...",This residential flat is south-West-Facing dir...,"['Full Power Backup', 'Centrally Air Condition...",28.532594,77.020297,B90651514

- Verified agePossession mapping from 99acres website:
  - **0** = Undefined  (ambiguous, only 147 rows)
  - **1** = 1 to 5 Year Old
  - **2** = 5 to 10 Year Old
  - **3** = 10+ Year Old
  - **5** = Under Construction
  - **6** = 0 to 1 Year Old (New)

- Parking codes (from RESERVED_PARKING JSON):
  - **C** = Covered parking (count)
  - **O** = Open parking (count)
  - **["N"]** = No reserved parking

In [49]:
AGE_POSSESSION_MAP = {
    0: 'Undefined', 1: '1 to 5 Year Old', 2: '5 to 10 Year Old',
    3: '10+ Year Old', 5: 'Under Construction', 6: '0 to 1 Year Old'
}

column_cleaning = (
    df_flat
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (df_['price_in_cr'] != '25,000')
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace("L","")
                    .str
                    .replace(",","")
                    .str 
                    .strip())
    ,facing  = lambda df_: df_['facing']
                                .replace('0',"Not Available")
                                .str
                                .lower()

    ,agePossession = lambda df_: df_['agePossession'].map(AGE_POSSESSION_MAP).fillna('Undefined')
    ))

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,eldeco accolade,1.25,9850.0,1269 sqft Superbuiltup Area,726.0,2,2,4.0,"Sohna, Gurgaon",2 of 18 Floors,north-east,"Park/Garden, Main Road, Club, Pool, Others",1,Y,Semi-Furnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",The flat is north-East-Facing. The flat occupi...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.259939,77.064480,M89360483
1,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global daxin vistas,3.00,19243.0,1559 sqft Builtup Area,NaN,3,3,2.0,"Sohna, Gurgaon",4 of 4 Floors,not available,NaN,5,NaN,Furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...",The flat is over 1559 sq.Ft. Built up area and...,"['Full Power Backup', 'Visitor Parking Availab...",28.332976,77.067894,T91323470
2,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,eldeco accolade,1.56,10744.0,1452 sqft Superbuiltup Area,1000.0,2,2,4.0,"Sohna, Gurgaon",8 of 18 Floors,north,"Pool, Park/Garden, Club",1,Y,Unfurnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",It's spacious 2.5 bhk with an extremely open a...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.266652,77.064904,F89903984
3,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiana anmol,2.16,12162.0,1776 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",10 of 14 Floors,north-east,"Park/Garden, Main Road",6,Y,0,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. C...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286897,77.071375,Z90919772
4,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,central park flower valley the room,2.55,14254.0,1789 sqft Builtup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 14 Floors,north,NaN,6,Y,Furnished,"{""C"":1}","['Huda Metro Station', 'Raheja Mall', 'Central...",For those who prefer high end living\nWelcome ...,"['Full Power Backup', 'Close to School', 'Cent...",28.284257,77.079086,H84077598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28499,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,kw royal court,3.30,10252.0,3219 sqft Superbuiltup Area,2500.0,4,5,1.0,"Sector 39, Gurgaon",9 of 12 Floors,north-east,"Park/Garden, Club",1,NaN,Unfurnished,"{""C"":2}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",2500 sqft carpet 4bhk+servant available for sa...,"['On-Call Maintenance Staff', 'Vaastu Complian...",28.441474,77.043613,K90588706
28500,"3 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej alira,7.00,28854.0,2426 sqft Carpet Area,2426.0,3,4,2.0,"Sector 39, Gurgaon",33 of 33 Floors,not available,NaN,1,NaN,Semi-Furnished,"[""N""]","['Rajiv Chowk Mosque', 'State bank of india AT...","Constructed on a carpet area of 2426 sq.Ft., t...",NaN,28.442331,77.049250,E90056680
28501,"2 BHK Flat in Saini Pura, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,bharat residency,0.70,7778.0,900 sqft Carpet Area,900.0,2,2,1.0,"Saini Pura, Gurgaon",2 of 5 Floors,not available,NaN,1,NaN,0,"[""N""]","['Rajiv Chowk Mosque', 'State bank of india AT...","Located in bharat residency, saini pura, gurga...",NaN,28.446360,77.051020,E89187547
28502,"2 BHK Flat in Jharsa, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,royal blue city,1.00,11111.0,900 sqft Carpet Area,100.0,2,2,1.0,"Jharsa, Gurgaon",2 of 4 Floors,east,Main Road,1,NaN,Unfurnished,"{""C"":1}","['IFFCO Chowk', '(HUDA City Centre) Rajiv', 'S...",A well-Maintained and spacious 2 bhk flat in a...,"['Full Power Backup', 'Close to Market', 'Gate...",28.443173,77.052033,O87439246
28503,"3 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,city heights,2.55,11333.0,2250 sqft Superbuiltup Area,2000.0,3,3,2.0,"Sector 39, Gurgaon",2 of 12 Floors,north-east,"Park/Garden, Main Road",2,Y,Unfurnished,"{""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",Looking for a 3 bhk property for sale in gurga...,"['North-East Facing', 'Wheel Chair Friendly', ...",28.440349,77.042917,A87227320

### 8. Carpet Area

In [50]:
column_cleaning['carpetArea']

0         726.0
1           NaN
2        1000.0
3           NaN
4           NaN
          ...
28499    2500.0
28500    2426.0
28501     900.0
28502     100.0
28503    2000.0
Name: carpetArea, Length: 28480, dtype: float64

In [51]:
column_cleaning['carpetArea'].isnull().sum()

np.int64(10296)

In [52]:
column_cleaning[column_cleaning['carpetArea'].isnull()]

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
1,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global daxin vistas,3.00,19243.0,1559 sqft Builtup Area,NaN,3,3,2.0,"Sohna, Gurgaon",4 of 4 Floors,not available,NaN,5,NaN,Furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...",The flat is over 1559 sq.Ft. Built up area and...,"['Full Power Backup', 'Visitor Parking Availab...",28.332976,77.067894,T91323470
3,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiana anmol,2.16,12162.0,1776 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",10 of 14 Floors,north-east,"Park/Garden, Main Road",6,Y,0,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. C...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286897,77.071375,Z90919772
4,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,central park flower valley the room,2.55,14254.0,1789 sqft Builtup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 14 Floors,north,NaN,6,Y,Furnished,"{""C"":1}","['Huda Metro Station', 'Raheja Mall', 'Central...",For those who prefer high end living\nWelcome ...,"['Full Power Backup', 'Close to School', 'Cent...",28.284257,77.079086,H84077598
5,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiana anmol,1.78,11670.0,1527 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",4 of 14 Floors,north-east,"Main Road, Park/Garden, Pool",6,Y,0,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. T...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286749,77.070620,K91303130
6,"3 BHK Flat in Sector-33 Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,godrej nature plus serenity,1.85,11280.0,1640 sqft Builtup Area,NaN,3,2,4.0,"Sector-33 Sohna, Gurgaon",11 of 26 Floors,not available,"Club, Park/Garden",5,NaN,Semi-Furnished,"{""C"":1}","['GD Goenka World School', 'KR Mangalam Univer...",Godrej nature plus sohna | 3 bhk 1640 sqft | 1...,"['Natural Light', 'Airy Rooms', 'Spacious Inte...",28.279354,77.067314,F90718582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28479,"4 BHK Flat in Sector 31, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,raheja atlantis,5.90,20048.0,2943 sqft Superbuiltup Area,NaN,4,6,4.0,"Sector 31, Gurgaon",7 of 11 Floors,north,"Park/Garden, Club, Pool",2,Y,Unfurnished,"{""C"":""2""}","['Huda Metro Station', 'Reliance Fresh, Indira...",Located in the popular residential address of ...,"['East Facing', 'Wheel Chair Friendly', 'Pet F...",28.453807,77.049250,M65346768
28482,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,sri navjyoti cghs limited,4.25,14655.0,2900 sqft Builtup Area,NaN,4,4,4.0,"Sector 39, Gurgaon",5 of 10 Floors,north-east,Park/Garden,3,NaN,Unfurnished,"{""O"":1,""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",This is a north-East-Facing property. The flat...,"['Full Power Backup', 'Centrally Air Condition...",28.442012,77.043646,J90924004
28485,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,kw royal court,2.70,8388.0,3219 sqft Superbuiltup Area,NaN,4,5,1.0,"Sector 39, Gurgaon",6 of 12 Floors,not available,Main Road,1,NaN,Unfurnished,"{""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",The flat occupies a super built up area of 321...,"['Full Power Backup', 'Centrally Air Condition...",28.441474,77.043613,V91485606
28491,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,hector trimurti heights,3.00,13636.0,2200 sqft Superbuiltup Area,NaN,4,3,4.0,"Sector 39, Gurgaon",8 of 12 Floors,north-west,NaN,2,NaN,0,"{""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",We are the proud owners of this 4 bhk apartmen...,"['On-Call Maintenance Staff', 'Parking Availab...",28.440905,77.043455,J86214746
28498,"4 BHK Flat in Sector 39, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,urban green,4.50,17308.0,2600 sqft Superbuiltup Area,NaN,4,4,4.0,"Sector 39, Gurgaon",2 of 12 Floors,north,"Park/Garden, Main Road",2,Y,Unfurnished,"{""O"":1,""C"":1}","['Raheja Mall', 'Rajiv Chowk Mosque', 'Icici b...",This 4 bhk flat on the 2nd floor of a 12-Story...,"['Full Power Backup', 'Visitor Parking Availab...",28.440964,77.042601,M90820762

### 9. Furnishing

In [53]:
column_cleaning['furnishing'].unique()

array(['Semi-Furnished', 'Furnished', 'Unfurnished', '0'], dtype=object)

In [ ]:
AGE_POSSESSION_MAP = {
    0: 'Undefined', 1: '1 to 5 Year Old', 2: '5 to 10 Year Old',
    3: '10+ Year Old', 5: 'Under Construction', 6: '0 to 1 Year Old'
}

column_cleaning = (
    df_flat
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (df_['price_in_cr'] != '25,000')
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            2
        )
    )
    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace("L","")
                    .str
                    .replace(",","")
                    .str 
                    .strip())
    ,facing  = lambda df_: df_['facing']
                                .replace('0',"Not Available")
                                .str
                                .lower()
    ,furnishing = lambda df_: df_['furnishing']
                                .replace('0',"Not Available")
                                .str
                                .lower()
    ,agePossession = lambda df_: df_['agePossession'].map(AGE_POSSESSION_MAP).fillna('Undefined')
    ))

### 10. Overlooking

In [ ]:
column_cleaning['overlooking'].value_counts()

In [ ]:
column_cleaning['overlooking'].isnull().sum()

- Overlooking is a multi-value field (e.g., Park/Garden, Main Road). ~14% missing. Values already mapped to readable names during scraping. Keep as-is for now — will one-hot encode during feature engineering.

### 11. AgePossession (add to pipeline)

In [ ]:
column_cleaning['agePossession'].value_counts()

agePossession
1 to 5 Year Old       10608
0 to 1 Year Old        5462
5 to 10 Year Old       5406
Under Construction     4784
10+ Year Old           2073
Undefined               147
Name: count, dtype: int64

In [ ]:
column_cleaning['agePossession'].unique()

array(['1 to 5 Year Old', 'Under Construction', '0 to 1 Year Old',
       'Undefined', '5 to 10 Year Old', '10+ Year Old'], dtype=object)

- 0 means undefined/not specified. Numeric values (1-10+) represent age in years. Under Construction and By <date> are possession status strings. This needs splitting into two concepts: property age (numeric) and possession status (ready/under construction).

### 12. Corner Property

In [58]:
column_cleaning['cornerProperty'].value_counts()

cornerProperty
Y    18606
Name: count, dtype: int64

In [59]:
column_cleaning['cornerProperty'].isnull().sum()

np.int64(9874)

- Binary feature: Y/N. ~35% missing (NaN). Keep as-is — useful for price prediction since corner properties command a premium.

### 13. Floor Number

In [60]:
column_cleaning['floorNum'].value_counts()

floorNum
2 of 4 Floors      686
3 of 4 Floors      529
1 of 4 Floors      475
7 of 14 Floors     410
8 of 14 Floors     405
                  ...
4 of 39 Floors       1
L of 13 Floors       1
B of 38 Floors       1
L of 38 Floors       1
33 of 33 Floors      1
Name: count, Length: 1179, dtype: int64

In [61]:
column_cleaning['floorNum'].unique()[:20]

array(['2 of 18 Floors', '4 of 4 Floors', '8 of 18 Floors',
       '10 of 14 Floors', '3 of 14 Floors', '4 of 14 Floors',
       '11 of 26 Floors', '11 of 18 Floors', '5 of 14 Floors',
       '8 of 14 Floors', '10 of 18 Floors', '9 of 14 Floors',
       '15 of 24 Floors', 'G of 4 Floors', '9 of 24 Floors',
       '6 of 14 Floors', '6 of 11 Floors', '5 of 11 Floors',
       '3 of 4 Floors', '25 of 25 Floors'], dtype=object)

- Format is X of Y Floors (e.g., 3 of 15 Floors). During FE, split into loor_number and 	otal_floors. Ground floor and top floor are important for price.

### 14. Area With Type

In [62]:
column_cleaning['areaWithType'].value_counts()[:20]

areaWithType
2150 sqft Superbuiltup Area    242
1950 sqft Superbuiltup Area    241
1930 sqft Superbuiltup Area    220
2450 sqft Superbuiltup Area    198
1900 sqft Superbuiltup Area    190
1650 sqft Superbuiltup Area    172
2400 sqft Superbuiltup Area    172
1704 sqft Superbuiltup Area    162
1689 sqft Superbuiltup Area    156
1750 sqft Superbuiltup Area    155
1910 sqft Superbuiltup Area    144
3950 sqft Superbuiltup Area    141
1550 sqft Superbuiltup Area    135
2100 sqft Superbuiltup Area    128
645 sqft Carpet Area           126
1565 sqft Superbuiltup Area    125
1450 sqft Superbuiltup Area    113
3577 sqft Superbuiltup Area    109
2350 sqft Superbuiltup Area    108
1850 sqft Superbuiltup Area    106
Name: count, dtype: int64

In [63]:
column_cleaning['areaWithType'].isnull().sum()

np.int64(0)

- Format: 1269 sqft Superbuiltup Area or 1559 sqft Builtup Area. Contains the numeric area + area type (Super Built-up / Built-up / Carpet / Plot). Will parse into rea_sqft (numeric) and rea_type (category) during FE.

### 15. Address (Locality)

In [64]:
column_cleaning['address'].value_counts()[:20]

address
Sohna, Gurgaon         1109
Sector 79, Gurgaon     1048
Sector 102, Gurgaon     924
Sector 106, Gurgaon     905
Sector 65, Gurgaon      831
Sector 92, Gurgaon      830
Sector 104, Gurgaon     764
Sector 37D, Gurgaon     732
Sector 85, Gurgaon      728
Sector 89, Gurgaon      646
Sector 113, Gurgaon     604
Sector 62, Gurgaon      573
Sector 54, Gurgaon      537
Sector 69, Gurgaon      526
Sector 81, Gurgaon      509
Sector 108, Gurgaon     499
Sector 66, Gurgaon      491
Sector 76, Gurgaon      480
Sector 86, Gurgaon      478
Sector 59, Gurgaon      464
Name: count, dtype: int64

In [65]:
column_cleaning['address'].nunique()

184

In [66]:
column_cleaning['address'].isnull().sum()

np.int64(0)

- Locality/sector name. Key feature for price prediction — location is the #1 factor. Check for inconsistent naming (e.g., Sector 49 vs Sector-49 Gurgaon).

### 16. Parking

In [67]:
column_cleaning['parking'].value_counts()[:20]

parking
{"C":1}              9696
{"C":2}              5866
{"O":1,"C":1}        5069
["N"]                2668
{"O":1}              1695
{"O":1,"C":2}        1328
{"C":3}               818
{"O":2,"C":2}         262
{"O":2}               164
{"O":2,"C":1}         107
{"O":1,"C":3}         104
{"C":4}                63
{"C":"1"}              58
{"C":"2"}              55
{"C":"3"}              34
{"O":2,"C":3}          30
{"C":1,"O":0}          21
{"O":"1","C":"1"}      21
{"O":"1"}              15
{"O":3}                13
Name: count, dtype: int64

In [68]:
column_cleaning['parking'].isnull().sum()

np.int64(271)

- JSON format like {"C":2} (covered) or {"O":1,"C":1} (open + covered). During FE, parse into covered_parking and open_parking numeric columns. Covered parking correlates with property value in Gurgaon.

### 17. Nearby Locations

In [69]:
column_cleaning['nearbyLocations'].value_counts()[:10]

nearbyLocations
['Genesis Hospital', 'Iris Broadway', 'Euro International School, Sector 84', 'Nakhrola Stadium', 'Garhi Harsaru Junction']                       450
['Dwarka Expressway', 'Euro International School, Sector- 109', 'Gurgaon Railway Station', 'Gurgaon Dreamz Mall', 'Dev Hospital']                 370
['Gurugram Global Heights School', 'The Esplanade Mall', 'Dwarka Expressway', 'Orient Bestech Business Tower', 'SGT University']                  362
['Lovely Public School', 'Southern Peripheral Road', 'Paras Trinity Mall', 'KIIT College of Engineering', 'PVR Drive in Theatre']                 310
['Conscient One', 'Euro International School', 'Gurgaon Old Railway', "Rion's Hospital", 'Dwarka Expressway']                                     308
['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. Sarkar Clinic', 'Sagar Clinic', 'Vijay Petrol Pump']                                                288
['Chintels Corporate Park', 'BSF Golf Course', 'Imperial Heritage School', 'Dronacharya Government College', 'Dwarka Sector 25 Metro Station']    282
['S.R.S. Hospital and Critical Care Unit', 'Petrol Pump Indian Oil', 'Petrol Pump Indian Oil', 'Haldiram']                                        277
['M3m 65th Avenue Mall', 'DPS International School', 'Golf Course Extension Road', 'Park Hospital', 'Lemon Tree Hotel']                           242
['Dwarka Sector-25 Metro Station', 'Baghera University', 'BSF Golf Course', 'Welcomhotel By ITC Hotels, Dwarka', 'Vardhman Mall']                 239
Name: count, dtype: int64

In [70]:
column_cleaning['nearbyLocations'].isnull().sum()

np.int64(67)

- List of nearby landmarks (schools, malls, metro stations). Useful for recommender module and analytics. Not directly useful for price model unless we extract proximity features.

### 18. Description

In [71]:
column_cleaning['description'].str.len().describe()

count    28480.000000
mean       650.444558
std        486.137819
min         30.000000
25%        361.000000
50%        647.000000
75%        808.000000
max       5000.000000
Name: description, dtype: float64

In [72]:
column_cleaning['description'].isnull().sum()

np.int64(0)

- Free text property description. Useful for recommender (text similarity) and analytics (word cloud). Not directly used in price model.

### 19. Features

In [73]:
column_cleaning['features'].value_counts()[:10]

features
['Pet Friendly', 'Full Power Backup', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Corner Property', 'Overlooking Park', 'Overlooking Main Road', 'Vaastu Compliant', 'Natural Light']         367
['Wheel Chair Friendly', 'Pet Friendly', 'Full Power Backup', '24*7 Water', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Corner Property', 'Overlooking Park', 'Overlooking Main Road']        191
['Wheel Chair Friendly', 'Pet Friendly', 'Full Power Backup', '24*7 Water', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Overlooking Park', 'Overlooking Main Road', 'Vaastu Compliant']       171
['Full Power Backup', 'Centrally Air Conditioned', 'Corner Property', 'Overlooking Main Road', 'Vaastu Compliant', 'Parking Available', 'Modular Kitchen', 'Fitness Center/ Gym', 'Club house', 'Swimming Pool Available']                167
['Wheel Chair Friendly', 'Pet Friendly', 'Full Power Backup', '24*7 Water', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Gated Society', 'Corner Property']                                    164
['Pet Friendly', 'Full Power Backup', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Overlooking Park', 'Overlooking Main Road', 'Vaastu Compliant', 'Natural Light', 'Airy Rooms']              145
['Full Power Backup', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Overlooking Main Road', 'Vaastu Compliant', 'Parking Available', 'Modular Kitchen', 'Fitness Center/ Gym', 'Club house']    129
['Pet Friendly', 'Full Power Backup', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Gated Society', 'Corner Property', 'Overlooking Park', 'Overlooking Main Road', 'Vaastu Compliant']         127
['Wheel Chair Friendly', 'Pet Friendly', 'Full Power Backup', '24*7 Water', 'Visitor Parking Available', 'Centrally Air Conditioned', 'On-Call Maintenance Staff', 'Overlooking Main Road', 'Vaastu Compliant', 'Parking Available']      111
['Parking Available']                                                                                                                                                                                                                     107
Name: count, dtype: int64

In [74]:
column_cleaning['features'].isnull().sum()

np.int64(683)

- List of amenities like ['Full Power Backup', 'Swimming Pool', 'Gym']. ~2.4% missing. During FE, can count total features or one-hot encode key amenities (lift, gym, pool, security). Useful for price and recommender.

### 20. Latitude & Longitude

In [75]:
print(f"Latitude  — min: {column_cleaning['latitude'].min()}, max: {column_cleaning['latitude'].max()}, nulls: {column_cleaning['latitude'].isnull().sum()}")
print(f"Longitude — min: {column_cleaning['longitude'].min()}, max: {column_cleaning['longitude'].max()}, nulls: {column_cleaning['longitude'].isnull().sum()}")

Latitude  — min: 0.0, max: 77.150639, nulls: 0
Longitude — min: 0.0, max: 77.150639, nulls: 0

In [76]:
# Quick sanity check: Gurgaon should be roughly lat 28.4-28.5, lon 76.9-77.1
outliers = column_cleaning[
    (column_cleaning['latitude'] < 28.0) | (column_cleaning['latitude'] > 29.0) |
    (column_cleaning['longitude'] < 76.5) | (column_cleaning['longitude'] > 77.5)
]
print(f"Potential geo outliers: {len(outliers)} rows")
if len(outliers) > 0:
    outliers[['property_name', 'address', 'latitude', 'longitude']].head(10)

Potential geo outliers: 325 rows

- Lat/Long are fully populated (0% missing). New feature not available in old project. Useful for:
  - **Price model**: distance-based features (distance to metro, NH8, city center)
  - **Analytics module**: geo-mapping, sector-wise visualization
  - **Recommender**: location proximity scoring

### Feature Review Summary

| Feature | Status | Action |
|---------|--------|--------|
| society | Cleaned | strip + lowercase |
| price_in_cr | Cleaned | Parsed Cr/Lac to numeric, dropped invalid |
| price_per_sqft | Cleaned | Parsed string to numeric |
| bedRoom | Clean | Already numeric |
| bathroom | Noted | 0 = missing, replace with bedRoom in FE |
| balcony | Clean | 0 = no balcony |
| facing | Cleaned | '0' to 'Not Available', lowercase |
| furnishing | Cleaned | '0' to 'Not Available', lowercase |
| agePossession | Review | 0 = undefined, mixed types (age vs possession date) |
| overlooking | Clean | Multi-value, already mapped |
| cornerProperty | Clean | Y/N binary, ~35% null |
| carpetArea | Noted | ~36% missing, keep as-is |
| floorNum | Review in FE | Parse 'X of Y Floors' into floor_number + total_floors |
| areaWithType | Review in FE | Parse into area_sqft + area_type |
| address | Review in FE | Standardize locality names |
| parking | Review in FE | Parse JSON into covered_parking + open_parking |
| nearbyLocations | Keep | For recommender/analytics |
| description | Keep | For recommender/analytics |
| features | Review in FE | Count or one-hot encode amenities |
| latitude/longitude | Clean | For geo features in FE |

### Final Cleaning Pipeline

In [ ]:
AGE_POSSESSION_MAP = {
    0: 'Undefined', 1: '1 to 5 Year Old', 2: '5 to 10 Year Old',
    3: '10+ Year Old', 5: 'Under Construction', 6: '0 to 1 Year Old'
}

column_cleaning = (
    df_flat
    .rename(columns ={
    'price' : 'price_in_cr',
    'area'  :'price_per_sqft'
                        })
                        
    .assign(
        society=lambda df_: df_['society']
            .str.strip()
            .str.lower()
    )

    .assign(
        price_in_cr=lambda df_: df_['price_in_cr']
            .str.strip()
    )

    .loc[lambda df_: (
        df_['price_in_cr'].notna() &
        (df_['price_in_cr'] != 'Price on Request') &
        (df_['price_in_cr'] != '25,000')
    )]

    .assign(
        price_in_cr=lambda df_: round(
            pd.to_numeric(
                df_['price_in_cr'].apply(
                    lambda value:
                        float(str(value).replace('Cr', '').strip())
                        if 'Cr' in str(value)
                        else float(str(value).replace('Lac', '').strip()) / 100
                )
            ),
            4
        )
    )
    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace("L","")
                    .str
                    .replace(",","")
                    .str 
                    .strip())
    ,facing  = lambda df_: df_['facing']
                                .replace('0',"Not Available")
                                .str
                                .lower()
    ,furnishing = lambda df_: df_['furnishing']
                                .replace('0',"Not Available")
                                .str
                                .lower()
    ,agePossession = lambda df_: df_['agePossession'].map(AGE_POSSESSION_MAP).fillna('Undefined')
    ))

column_cleaning

,property_name,link,society,price_in_cr,price_per_sqft,areaWithType,carpetArea,bedRoom,bathroom,balcony,address,floorNum,facing,overlooking,agePossession,cornerProperty,furnishing,parking,nearbyLocations,description,features,latitude,longitude,property_id
0,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,eldeco accolade,1.25,9850.0,1269 sqft Superbuiltup Area,726.0,2,2,4.0,"Sohna, Gurgaon",2 of 18 Floors,north-east,"Park/Garden, Main Road, Club, Pool, Others",1 to 5 Year Old,Y,semi-furnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",The flat is north-East-Facing. The flat occupi...,"['Wheel Chair Friendly', 'Full Power Backup', ...",28.259939,77.064480,M89360483
1,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,signature global daxin vistas,3.00,19243.0,1559 sqft Builtup Area,NaN,3,3,2.0,"Sohna, Gurgaon",4 of 4 Floors,not available,NaN,Under Construction,NaN,furnished,"{""C"":1}","['National Highway 248A', 'Tau Devilal Stadium...",The flat is over 1559 sq.Ft. Built up area and...,"['Full Power Backup', 'Visitor Parking Availab...",28.332976,77.067894,T91323470
2,"2 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,eldeco accolade,1.56,10744.0,1452 sqft Superbuiltup Area,1000.0,2,2,4.0,"Sohna, Gurgaon",8 of 18 Floors,north,"Pool, Park/Garden, Club",1 to 5 Year Old,Y,unfurnished,"{""C"":1}","['GD Goenka University', 'GD Goenka World Scho...",It's spacious 2.5 bhk with an extremely open a...,"['Full Power Backup', 'On-Call Maintenance Sta...",28.266652,77.064904,F89903984
3,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,ashiana anmol,2.16,12162.0,1776 sqft Superbuiltup Area,NaN,3,3,3.0,"Sohna, Gurgaon",10 of 14 Floors,north-east,"Park/Garden, Main Road",0 to 1 Year Old,Y,not available,"{""O"":1,""C"":1}","['Badshahpur Sohna Road Highway', 'K. R. Manga...",The flat is facing the north-East direction. C...,"['North-East Facing', 'Full Power Backup', 'Vi...",28.286897,77.071375,Z90919772
4,"3 BHK Flat in Sohna, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,central park flower valley the room,2.55,14254.0,1789 sqft Builtup Area,NaN,3,3,4.0,"Sohna, Gurgaon",3 of 14 Floors,north,NaN,0 to 1 Year Old,Y,furnished,"{""C"":1}","['Huda Metro Station', 'Raheja Mall', 'Central...",For those who prefer high end living\nWelcome ...,"['Full Power Backup', 'Close to School', 'Cent...",28.284257,77.079086,H84077598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28526,"2 BHK Flat in Rajendra Park, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,ganpati enclave,0.38,8444.0,450 sqft Carpet Area,450.0,2,2,1.0,"Rajendra Park, Gurgaon",4 of 4 Floors,not available,NaN,10+ Year Old,NaN,unfurnished,"{""O"":1,""C"":1}",NaN,Please actuall buyer hi call kare,"['Pet Friendly', '24*7 Water', 'On-Call Mainte...",77.026640,28.459500,U87418546
28527,"1 BHK Flat in Sector 105, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...,sagar homes,0.21,4403.0,477 sqft Carpet Area,53.0,1,1,1.0,"Sector 105, Gurgaon",1 of 4 Floors,north,NaN,1 to 5 Year Old,NaN,not available,"{""C"":1}","['Palam Vihar Vyapar kendra', 'Palam triangle'...",1bhk near dwarka expressway @21 lakh,"['Vaastu Compliant', 'Parking Available']",28.495935,77.014186,Q87156572
28528,"3 BHK Flat in Rajendra Park, Gurgaon",https://www.99acres.com/3-bhk-bedroom-apartmen...,milan apartment,0.70,5385.0,1300 sqft Superbuiltup Area,NaN,3,3,2.0,"Rajendra Park, Gurgaon",2 of 4 Floors,not available,NaN,1 to 5 Year Old,NaN,not available,NaN,"['BAPS SWAMINARAYAN TEMPLE', 'Swaminarayan', '...",We are the proud owners of this 3 bhk apartmen...,NaN,22.997709,72.559967,N85715090
28529,"2 BHK Flat in Rajendra Park, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,imperial homes,0.42,4941.0,850 sqft Superbuiltup Area,NaN,2,2,0.0,"Rajendra Park, Gurgaon",3 of 4 Floors,not available,NaN,1 to 5 Year Old,NaN,not available,"[""N""]","['Palam Vihar Vyapar kendra', 'Chintapurni Man...",We are the proud owners of this 2 bhk apartmen...,NaN,28.494560,77.007146,P84354758
28530,"4 BHK Flat in Sector 105, Gurgaon",https://www.99acres.com/4-bhk-bedroom-apartmen...,ats homecraft sanctury,3.00,16216.0,1850 sqft Builtup Area,NaN,4,4,4.0,"Sector 105, Gurgaon",G of 1 Floors,not available,NaN,0 to 1 Year Old,NaN,semi-furnished,NaN,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...",This beautiful 4 bhk flat in sector 105 gurgao...,NaN,28.497852,77.007484,D87008588

In [132]:
column_cleaning['areaWithType'].str.contains('Superbuiltup', case=False, na=False).sum()

np.int64(21570)

In [136]:
column_cleaning['areaWithType'].str.contains('Builtup', case=True, na=False).sum()

np.int64(1549)

## Removing Duplicate Listings

### What is the problem?
On 99acres, the same flat is often posted by several agents. So one real flat shows up as
many rows in our data. We want **one row per real flat**.

If we leave the duplicates in:
- **The score becomes fake.** The same flat can land in both training and test data, so the
  model has already "seen" the answer and looks better than it really is.
- **Popular flats get too much weight.** A flat posted 10 times pulls the model towards itself.

### Why is it tricky?
There is no flat number in our data (that is only on the detail page, which we did not scrape).
So we cannot be 100% sure two rows are the exact same flat. We have to decide using the columns
we do have. This means any rule we make can go wrong in two ways:
- Too strict -> real duplicates stay in.
- Too loose -> two different flats get merged into one (we lose real data).

So the goal is simply to make as few wrong calls as possible.

### How did we decide?
We tried different combinations of columns to define "same flat", then actually **looked at the
rows** each rule grouped together — and even opened a few listings on 99acres to check.

What we found:
- When we **left price out** of the rule, it merged flats whose carpet area and price were
  clearly different (for example, area 1100 vs 1400 sqft, price 2.05 vs 2.24 Cr). Those are
  **different flats**, so merging them throws away real information.
- When we **kept price in** the rule, the grouped rows had the same price, area and floor, and
  only small noise differed (a tiny carpet-area difference, or one agent writing a different
  facing). Those really are **the same flat reposted**.

The simple takeaway: **if two rows have the same details and the same price, treat them as the
same flat.** Price is the most reliable signal we have.

### What we use
We mark two rows as the same flat when these all match:
`property_name, society, price_in_cr, areaWithType, floorNum, facing, overlooking`

- **Price** is the strongest clue.
- **Society, area, floor, facing, overlooking** pin down the specific unit.
- We **leave out** columns agents fill inconsistently (bathroom, carpet area, furnishing) — using
  them would split the same flat into "different" rows and miss real duplicates.

### This is easy to change later
This rule is a safe, careful choice. After we build the model:
- If the score looks **too good to be true**, duplicates may still be leaking -> make the rule
  stricter.
- If it looks reasonable, we keep it.

It is a one-line change (`DEDUP_KEY` below), so we can adjust it any time.

In [152]:
from IPython.display import display

# Work on a copy of the cleaned data
df_dedupe = column_cleaning.copy()

# --- Chosen dedup key (Option A, refined) ---
# Rows with identical values for ALL these columns are treated as the SAME flat,
# reposted by different agents.
DEDUP_KEY = ['property_name', 'society', 'price_in_cr',
             'areaWithType', 'floorNum', 'facing', 'overlooking']

# How many rows would this key remove?
n_drop = df_dedupe.duplicated(subset=DEDUP_KEY).sum()
print(f"Total rows        : {len(df_dedupe)}")
print(f"Duplicates to drop: {n_drop} ({100 * n_drop / len(df_dedupe):.1f}%)")

Total rows        : 28507
Duplicates to drop: 74 (0.3%)

### Sanity check — look at the duplicate groups

Each group below is a set of rows that share the same `DEDUP_KEY`. Eyeball them: if the rows
are clearly the same flat (only price/agent text differs) the key is doing its job.

In [153]:
# Columns that make it easy to judge if two rows are the same flat
VIEW = ['society', 'areaWithType', 'floorNum', 'facing', 'overlooking',
        'bedRoom', 'bathroom', 'carpetArea', 'price_in_cr', 'property_name', 'link']

def show_duplicates(key=DEDUP_KEY, n_groups=8):
    """Print the first few groups of rows flagged as duplicates by `key`."""
    dupes = df_dedupe[df_dedupe.duplicated(subset=key, keep=False)]
    n_total = dupes.groupby(key, dropna=False).ngroups
    print(n_total, "duplicate groups,", len(dupes), "rows involved")
    print()
    for i, (_, group) in enumerate(dupes.groupby(key, dropna=False), start=1):
        if i > n_groups:
            break
        print(f"--- group {i}  ({len(group)} rows) ---")
        display(group[VIEW])

show_duplicates()

68 duplicate groups, 142 rows involved

--- group 1  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
21724,aipl joy square,693 sqft Carpet Area,3 of 9 Floors,not available,NaN,1,1,693.0,0.75,"1 BHK Flat in Sector 63A, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...
21725,aipl joy square,693 sqft Carpet Area,3 of 9 Floors,not available,NaN,1,1,693.0,0.75,"1 BHK Flat in Sector 63A, Gurgaon",https://www.99acres.com/1-bhk-bedroom-apartmen...

--- group 2  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
26640,my home,630 sqft Carpet Area,1 of 4 Floors,not available,Main Road,2,2,630.0,0.35,"2 BHK Flat in New Palam Vihar, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
26641,my home,630 sqft Carpet Area,1 of 4 Floors,not available,Main Road,2,2,630.0,0.35,"2 BHK Flat in New Palam Vihar, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

--- group 3  (3 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
1881,shapoorji pallonji joyville gurugram,1215 sqft Superbuiltup Area,5 of 14 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",2,2,859.0,2.0,"2 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
1884,shapoorji pallonji joyville gurugram,1215 sqft Superbuiltup Area,5 of 14 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",2,2,859.0,2.0,"2 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
1947,shapoorji pallonji joyville gurugram,1215 sqft Superbuiltup Area,5 of 14 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others",2,2,859.0,2.0,"2 BHK Flat in Sector 102, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

--- group 4  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
18146,indiabulls centrum park,1481 sqft Superbuiltup Area,6 of 10 Floors,north-east,NaN,2,2,1236.0,1.6,"2 BHK Flat in Sector 103, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
18285,indiabulls centrum park,1481 sqft Superbuiltup Area,6 of 10 Floors,north-east,NaN,2,2,1261.0,1.6,"2 BHK Flat in Sector 103, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

--- group 5  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
5625,hero homes,1099 sqft Superbuiltup Area,16 of 36 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others, Se...",2,2,782.36,1.65,"2 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
6052,hero homes,1099 sqft Superbuiltup Area,16 of 36 Floors,north-east,"Pool, Park/Garden, Club, Main Road, Others, Se...",2,2,782.36,1.65,"2 BHK Flat in Sector 104, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

--- group 6  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
4482,godrej meridien,1366 sqft Superbuiltup Area,11 of 34 Floors,north,"Pool, Park/Garden, Club, Main Road",2,2,817.0,1.95,"2 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
4483,godrej meridien,1366 sqft Superbuiltup Area,11 of 34 Floors,north,"Pool, Park/Garden, Club, Main Road",2,2,817.0,1.95,"2 BHK Flat in Sector 106, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

--- group 7  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
8535,m3m capital,1310 sqft Carpet Area,31 of 36 Floors,not available,NaN,2,2,1310.0,2.7,"2 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
8539,m3m capital,1310 sqft Carpet Area,31 of 36 Floors,not available,NaN,2,2,1310.0,2.7,"2 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

--- group 8  (2 rows) ---

,society,areaWithType,floorNum,facing,overlooking,bedRoom,bathroom,carpetArea,price_in_cr,property_name,link
8866,smartworld one dxp,1377 sqft Superbuiltup Area,10 of 29 Floors,north,Others,2,2,NaN,2.1,"2 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...
8869,smartworld one dxp,1377 sqft Superbuiltup Area,10 of 29 Floors,north,Others,2,2,NaN,2.1,"2 BHK Flat in Sector 113, Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...

### Apply deduplication

In [ ]:
before = len(column_cleaning)
flats_dedup = column_cleaning.drop_duplicates(subset=DEDUP_KEY, keep='first').reset_index(drop=True)
after = len(flats_dedup)

print(f"{before} -> {after} rows  ({before - after} duplicate repostings dropped)")
flats_dedup.head()