In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

C:\Users\Jay Patel\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

### 1. Flats Data Loading

In [3]:
df_flat = pd.read_csv(r"C:\Users\Jay Patel\Campusx\ml_projects\PropNavigator\data\web_scraping\residential_apartment.csv")
df_flat.sample(15)

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
1657,"3 BHK Flat in Sohna, Gurgaon",Ashiana Anmol,₹2.2 Cr,"₹11,677 /sqft","1,884 sqft (175 sqm) Super Built-up Area",E83996584,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,11st of 14 Floors,North-East,0 to 1 Year Old,"['1 Modular Kitchen', '1 Chimney', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Country Inn & Suites By Radisson', 'Asian Pu..."
1885,"3 BHK Flat in Sector 59, Gurgaon",Conscient Elevate,₹5.18 Cr,"₹22,570 /sqft","2,295 sqft (213 sqm) Super Built-up Area",U83504250,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,17th of 33 Floors,East,1 to 5 Year Old,"['1 Modular Kitchen', '5 AC', '1 Chimney', 'No...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Grand Hyatt Gurgaon', 'Paras Trinity Mall Se..."
440,"3 BHK Flat in Sector 61, Gurgaon",Smart World Orchard,₹2.7 Cr,"₹16,081 /sqft","1,679 sqft (156 sqm) Super Built-up Area",E83900490,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,2 Balconies,Others,1st of 4 Floors,North,0 to 1 Year Old,"['1 Exhaust Fan', '1 Stove', '8 Light', '6 AC'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Shalom Presidency School', 'Gurugram Railway..."
253,"3 BHK Flat in Sector 111, Gurgaon",Puri Diplomatic Greens,₹3.75 Cr,"₹17,045 /sqft","2,200 sqft (204 sqm) Super Built-up Area",V82788922,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,17th of 21 Floors,North,5 to 10 Year Old,"['1 Wardrobe', '5 Fan', '2 Geyser', '5 Light',...","['Water purifier', 'Centrally Air Conditioned'...","['Dreamz Mall', 'Indira Gandhi International A..."
1273,"3 BHK Flat in Sector 59, Gurgaon",Conscient Elevate,₹5.4 Cr,"₹23,529 /sqft","2,295 sqft (213 sqm) Super Built-up Area",T84476202,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,2 Balconies,Servant Room,15th of 33 Floors,North-East,0 to 1 Year Old,"['6 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Grand Hyatt Gurgaon', 'Paras Trinity Mall Se..."
0,"2 BHK Flat in Sector 112, Gurgaon",Tata Gurgaon Gateway,₹2.5 Cr,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'...","['Metro Hospital, Palam Vihar', 'Mount Carmel ..."
1515,"3 BHK Flat in Sector 79, Gurgaon",Supertech Araville,₹1.57 Cr,"₹10,466 /sqft","1,945 sqft (181 sqm) Super Built-up Area",J84762728,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,5th of 24 Floors,East,5 to 10 Year Old,"['1 Water Purifier', '4 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Petrol Pump Indian Oil', 'Rao Dhaba', 'Petro..."
222,"3 BHK Flat in Sector 106, Gurgaon",Godrej Meridien,₹3.1 Cr,"₹15,484 /sqft","2,002 sqft (186 sqm) Built-up Area",N84594254,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,12nd of 34 Floors,West,0 to 1 Year Old,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Infinity Business Park', 'Hamoni Golf Camp',..."
1193,"4 BHK Flat in Sector 77, Gurgaon",Emaar MGF Palm Hills,₹2.4 Cr,"₹12,307 /sqft","1,950 sqft (181 sqm) Super Built-up Area",L83484568,https://www.99acres.com/4-bhk-bedroom-apartmen...,4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room",2nd of 9 Floors,South-West,1 to 5 Year Old,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Dwarka Expressway', 'Narayana e Techno Schoo..."
940,"2 BHK Flat in Sector 104, Gurgaon",Puri Emerald Bay,₹2 Cr,"₹16,000 /sqft","1,550 sqft (144 sqm) Super Built-up Area",G84660058,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,Pooja Room,4th of 29 Floors,North-East,1 to 5 Year Old,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Water purifier', 'Centrally Air Conditioned'...","['Dwarka Expressway', 'The NorthCap University..."
863,"2 BHK Flat in Sector 104, Gurgaon",Hero Homes,₹1.62 Cr,"₹14,695 /sqft","1,099 sqft (102 sqm) Built-up Area",X83597242,https://www.99acres.com/2-bhk-bedroom-apartmen...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,6th of 26 Floors,North-West,0 to 1 Year Old,"['1 Water Purifier', '7 Light', '3 AC', '1 Mod...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Gurgaon Railway Station', 'SGT University', ..."
374,"3 BHK Flat in Sector 102, Gurgaon",Shapoorji Pallonji Joyville Gurugram,₹2.63 Cr,"₹14,200 /sqft","1,852 sqft (172 sqm) Super Built-up Area",A84134706,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,10th of 26 Floors,East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '3 Geyser', '1 Stove',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['The NorthCap University', 'IFFCO Chowk Metro..."
170,"3 BHK Flat in Sector 102, Gurgaon",Conscient Heritage Max,₹3.15 Cr,"₹14,657 /sqft","2,149 sqft (200 sqm) Super Built-up Area",G81233039,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room",10th of 25 Floors,NaN,5 to 10 Year Old,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Millennium City Centre Metro Station', 'Arya..."
159,"3 BHK Flat in Sector 109, Gurgaon",ATS Tourmaline,₹2.2 Cr,"₹12,571 /sqft","1,750 sqft (163 sqm) Super Built-up Area",B84277962,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3+ Balconies,Pooja Room,6th of 27 Floors,North-East,1 to 5 Year Old,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['The Northcap University', 'Global Foyer Mall..."
2195,"3 BHK Flat in Sector 69, Gurgaon",Tulip Yellow,₹2.45 Cr,"₹14,377 /sqft","1,704 sqft (158 sqm) Super Built-up Area",S83847678,https://www.99acres.com/3-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,9th of 26 Floors,East,0 to 1 Year Old,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Hyatt Regency Gurugram', 'De Adventure Park'..."

In [4]:
df_flat.shape

(2460, 17)

In [6]:
df_flat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       2460 non-null   object
 1   society             2460 non-null   object
 2   price               2460 non-null   object
 3   area                2460 non-null   object
 4   areawithtype        2460 non-null   object
 5   property_id         2460 non-null   object
 6   link                2460 non-null   object
 7   bedrooms            2460 non-null   object
 8   bathrooms           2460 non-null   object
 9   balcony             2460 non-null   object
 10  additional_room     1861 non-null   object
 11  floor_info          2460 non-null   object
 12  facing              2354 non-null   object
 13  property_age        2456 non-null   object
 14  furnishing_details  2057 non-null   object
 15  features            2457 non-null   object
 16  nearby_location     2460 non-null   object
dtypes: object(17)
memory usage: 326.8+ KB

In [5]:
df_flat.describe(include='all')

,property_name,society,price,area,areawithtype,property_id,link,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,furnishing_details,features,nearby_location
count,2460,2460,2460,2460,2460,2460,2460,2460,2460,2460,1861,2460,2354,2456,2057,2457,2460
unique,231,288,502,1898,767,2460,2460,6,7,5,71,570,8,4,1806,1330,678
top,"3 BHK Flat in Sector 102, Gurgaon",Hero Homes,₹2.5 Cr,"₹10,000 /sqft","2,150 sqft (200 sqm) Super Built-up Area",L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,2nd of 4 Floors,East,1 to 5 Year Old,[],"['Centrally Air Conditioned', 'Water purifier'...","['IFFCO Chowk Metro Station', 'The Esplanade M..."
freq,118,79,53,10,30,1,1,1490,982,914,852,44,764,1327,58,195,36

### 2. Flats Data Cleaning

In [6]:
df_flat.columns

Index(['property_name', 'society', 'price', 'area', 'areawithtype',
       'property_id', 'link', 'bedrooms', 'bathrooms', 'balcony',
       'additional_room', 'floor_info', 'facing', 'property_age',
       'furnishing_details', 'features', 'nearby_location'],
      dtype='object')

In [7]:
df_flat = df_flat[['property_id','link','property_name', 'society', 'price', 'area', 'areawithtype',
       'bedrooms', 'bathrooms', 'balcony', 'additional_room',
       'floor_info', 'facing', 'property_age', 'nearby_location',
       'furnishing_details', 'features']]

In [8]:
df_flat.isnull().sum()

property_id             0
link                    0
property_name           0
society                 0
price                   0
area                    0
areawithtype            0
bedrooms                0
bathrooms               0
balcony                 0
additional_room       599
floor_info              0
facing                106
property_age            4
nearby_location         0
furnishing_details    403
features                3
dtype: int64

In [9]:
missing_summary = (
    df_flat
    .isnull()
    .sum()
    .pipe(lambda s: round((s / len(df_flat)) * 100, 2))
    .reset_index()
    .rename(columns={'index': 'Feature', 0: 'Missing_Percentage'})
    .sort_values(by='Missing_Percentage', ascending=False)
)

In [10]:
missing_summary

               Feature  Missing_Percentage
10     additional_room               24.35
15  furnishing_details               16.38
12              facing                4.31
13        property_age                0.16
16            features                0.12
9              balcony                0.00
14     nearby_location                0.00
11          floor_info                0.00
0          property_id                0.00
1                 link                0.00
7             bedrooms                0.00
6         areawithtype                0.00
5                 area                0.00
4                price                0.00
3              society                0.00
2        property_name                0.00
8            bathrooms                0.00

In [11]:
df_flat.shape

(2460, 17)

### 3. Cleaning Individual Columns

1) Society

In [12]:
df_flat['society'].value_counts()

society
Hero Homes                                      79
Shapoorji Pallonji Joyville Gurugram            70
DLF The Ultima                                  65
Godrej Meridien                                 57
M3M Heights                                     56
Bestech Park View Grand Spa                     54
Ireo The Corridors                              52
Sobha City                                      46
Adani M2K Oyster Grande                         44
Experion Windchants                             44
M3M Golfestate                                  36
Puri Emerald Bay                                35
Smart World Gems                                33
DLF The Skycourt                                33
Emaar MGF Emerald Floors Premier                33
Conscient Elevate                               32
Emaar MGF The Palm Drive                        30
Tulip Yellow                                    29
Mahindra Aura                                   27
Chintels Serenity                               26
Smart World Orchard                             26
Tata Primanti                                   25
Conscient Heritage Max                          24
ATS Triumph                                     23
La Vida by Tata Housing                         23
ATS Tourmaline                                  22
DLF The Primus                                  22
DLF New Town Heights 2                          21
SS The Leaf                                     21
DLF Regal Gardens                               20
Bestech Park View Sanskruti                     20
Sare Homes                                      20
Emaar Palm Gardens                              20
Bestech Altura                                  20
Experion The Heartsong                          20
Emaar Imperial Gardens                          20
Ireo Skyon                                      19
Antriksh Heights                                19
Bestech Park View Ananda                        18
M3M Soulitude                                   18
Pareena Mi Casa                                 18
Unitech Fresco                                  18
Tulip Violet                                    18
Spaze Privy AT4                                 17
Tata Gurgaon Gateway                            17
Indiabulls Centrum Park                         17
Mapsko Royale Ville                             17
Mapsko Casa Bella                               16
Central Park Resorts                            16
Paras Dews                                      16
Paras Irene                                     15
Umang Winter Hills                              15
Tulip Purple                                    15
Pioneer Urban Presidia                          15
Vipul Lavanya                                   15
Puri Diplomatic Greens                          15
Central Park Flower Valley Aqua Front Towers    14
DLF Park Place                                  14
Eldeco Accolade                                 14
Indiabulls Enigma                               14
Emaar Mgf Palm Terraces Select                  14
M3M Woodshire                                   13
Greenopolis                                     13
Vatika The Seven Lamps                          13
Sare Crescent Parc                              12
Vatika Sovereign Park                           12
Emaar Gurgaon Greens                            12
Godrej Habitat                                  12
ATS Kocoon                                      11
Ireo Victory Valley                             11
Silverglades The Melia                          11
Spaze Privvy The Address                        11
Ashiana Anmol                                   11
Parsvnath Exotica                               11
Unitech Harmony                                 11
M3M Merlin                                      11
Bestech Park View Spa Next                      11
DLF New Town Heights 1                          11
Mapsko Mount Ville                              11
Pioneer Araya                                   11
ATS Marigold                                    10
Ireo The Grand Arch                             10
Emaar MGF Emerald Estate                        10
Eldeco Acclaim                                  10
Vatika City                                     10
Vatika Gurgaon 21                                9
Unitech Escape                                   9
Pareena Express Heights                          9
TARC Maceo                                       9
Emaar MGF Palm Hills                             9
Orris Aster Court                                9
Tulip Monsella                                   8
Orchid Petals                                    8
Shree Vardhman Victoria                          8
M3M The Marina                                   8
BPTP Park Serene                                 8
Bestech Park View Residency                      7
Microtek Greenburg                               7
Suncity Platinum Towers                          7
AIPL The Peaceful Homes                          7
Mapsko Paradise                                  7
The Close South                                  7
Bestech Park View City 2                         7
Alpha Corp GurgaonOne 84                         6
ROF Ananda                                       6
Lotus Elise                                      6
M3M Latitude                                     6
BPTP Freedom Park Life                           6
M3M Natura                                       6
Mahindra Luminare                                6
Orris Carnation Residency                        5
Parsvnath Green Ville                            5
Ramprastha The Edge Towers                       5
Signature Global Park                            5
Signature The Roselia                            5
Trump Tower                                      5
Cosmos Express 99                                5
DLF The Crest                                    5
Emaar Digihomes                                  5
Emaar Palm Heights                               5
Intelligentsia Apartment                         5
The Close North                                  5
Pareena Coban Residences                         5
Krisumi Waterfall Residences                     5
Brisk Lumbini Terrace Homes                      4
DLF Westend Heights                              4
SS The Coralwood                                 4
M3M Escala                                       4
DLF The Belaire                                  4
M3M Skywalk                                      4
DLF Regency Park 2                               4
Sare Petioles                                    4
Signature Global City                            4
Godrej Icon                                      4
ILD Greens                                       4
Ambience Creacions                               4
BPTP Park Generations                            4
Piedmont Taksila heights                         4
Spaze Kalistaa                                   4
Signature Global Orchard Avenue 2                4
Vatika Lifestyle Homes                           4
Imperia The Esfera                               4
Godrej Nature Plus                               4
Raheja Vedaanta                                  4
M3M Skycity                                      4
Bestech Park View City                           4
Sahara Grace                                     3
M3M Flora                                        3
Central Park 2 Bellevue                          3
SS Linden Floors                                 3
Bestech Park View Spa                            3
Navyug Apartments                                3
Godrej 101                                       3
DLF Carlton Estate                               3
ILD Grand                                        3
Ansal Harmony Homes                              3
Pyramid Fusion Homes                             3
BPTP Spacio                                      3
Suncity Vatsal Valley                            3
Pyramid Urban Homes                              3
Pyramid Urban                                    3
Krrish Provence Estate                           3
GPL Eden Heights                                 3
Tulip Orange                                     3
Unitech The Residences                           3
Ramprastha The View                              3
Emaar MGF The Enclave                            3
DLF Park Heights                                 2
Ramprastha Primera                               2
Suncity Avenue 76                                2
DLF Gardencity Enclave                           2
BPTP Terra                                       2
DLF Express Greens                               2
DLF Wellington Estate                            2
Ambience Lagoon                                  2
Anant Raj Estates                                2
Unitech Uniworld Gardens                         2
Raheja Atharva                                   2
AIPL Zen Residences                              2
Godrej Oasis                                     2
CHD Avenue 71                                    2
Pioneer Park                                     2
Godrej Frontier                                  2
Silverglades The Ivy                             2
Ardee City                                       2
Emaar MGF Palm Studios                           2
Ashiana Mulberry                                 2
Pivotal Devaan                                   2
Central Park Flower Valley Flamingo Floors       2
Landmark Towers                                  2
Vipul Greens                                     2
Emaar Mgf Emerald Floors                         2
MRG The Balcony                                  2
Millenium apartment                              2
Tulip Ace                                        2
Vatika City Homes                                2
Assotech Blith                                   2
Smart World Orchard Street                       2
Central Park Flower Valley                       2
Signature Global the Millennia                   1
Supertech Araville                               1
DLF Hamilton Court                               1
M3M St Andrews                                   1
Friends Apartment                                1
New Shivalik Apartments                          1
Karam Hi Dharam                                  1
Conscient Heritage One                           1
vigyan vihar sector 56                           1
Rose Apartment                                   1
Pyramid Elite                                    1
Godrej Summit                                    1
Sanskriti Apartments                             1
Raisina Residency                                1
Today Blossoms 1                                 1
Emaar MGF Palm Terraces                          1
Tulip Crimson                                    1
BPTP Park Prime                                  1
Dhoot Time Residency                             1
sector 70                                        1
DLF The Aralias                                  1
Sidhartha NCR One Phase 1                        1
Pyramid Heights                                  1
Breez Global Heights                             1
DLF Alameda                                      1
antriksh Heights                                 1
Viridian The Plaza 106                           1
DLF Ridgewood Estate                             1
Samanvay Apartment                               1
Prerna Society                                   1
sec-57                                           1
DLF Belvedere Park                               1
Vatika INXT Floors                               1
Emaar MGF The Vilas                              1
DLF Regency Park 1                               1
Vipul Belmonte                                   1
valley view estate                               1
Suncity Essel Towers                             1
Technocrat Society                               1
Adani Brahma Samsara                             1
CGHS Aravali Homes                               1
45 Pragati Hills                                 1
Vatika Sovereign Next                            1
Bestech Spa Signature                            1
Tulip Leaf                                       1
Himalayan Society                                1
Maxworth Premier Urban                           1
Oriental Valley CHS                              1
AWHO Devinder Vihar                              1
Pragati hills CGHS society                       1
Unitech Heritage City                            1
CGHS Agrim Apartment Block C, Sushant Lok 1      1
CGHS Joy Kunj                                    1
DLF Garden City Floors                           1
Sri Kirti Apartments                             1
Ireo Uptown                                      1
Tulip White                                      1
Signature Signum 81                              1
Signature Global City 37D Ph 2                   1
Amoda I, Birla Navya                             1
SS Cendana Reserve Collection                    1
Signature The Serenas                            1
DLF Richmond Park                                1
Bhagwanti Apartment                              1
Jnu Aravali Apartment                            1
Orchid Gardens                                   1
DLF Carlton Estate 4                             1
The Orchid Crescent                              1
M3M Capital                                      1
Paras Quartier                                   1
DLF Exclusive Floors                             1
Golden Apartment                                 1
CGHS HEWO Apartments                             1
Salcon The Verandas                              1
Emaar Emerald Hills                              1
Orris Aster Court Premier                        1
The Citizen                                      1
M3M Sierra 68                                    1
Krishna Apartments                               1
Abhinandan CGHS                                  1
Sare Crescent Parc Royal Greens Phase 1          1
Pyramid Square 67A                               1
DLF The Pinnacle                                 1
DLF Silver Oaks                                  1
Eros Wembley Estate                              1
Central Park                                     1
PIB Gharonda Apartment                           1
TDI Ourania                                      1
Unitech Uniworld City                            1
Name: count, dtype: int64

In [13]:
column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()))
column_cleaning['society'].value_counts()

society
hero homes                                      79
shapoorji pallonji joyville gurugram            70
dlf the ultima                                  65
godrej meridien                                 57
m3m heights                                     56
bestech park view grand spa                     54
ireo the corridors                              52
sobha city                                      46
adani m2k oyster grande                         44
experion windchants                             44
m3m golfestate                                  36
puri emerald bay                                35
smart world gems                                33
dlf the skycourt                                33
emaar mgf emerald floors premier                33
conscient elevate                               32
emaar mgf the palm drive                        30
tulip yellow                                    29
mahindra aura                                   27
chintels serenity                               26
smart world orchard                             26
tata primanti                                   25
conscient heritage max                          24
la vida by tata housing                         23
ats triumph                                     23
dlf the primus                                  22
ats tourmaline                                  22
ss the leaf                                     21
dlf new town heights 2                          21
emaar palm gardens                              20
sare homes                                      20
bestech park view sanskruti                     20
experion the heartsong                          20
dlf regal gardens                               20
bestech altura                                  20
emaar imperial gardens                          20
antriksh heights                                20
ireo skyon                                      19
bestech park view ananda                        18
unitech fresco                                  18
tulip violet                                    18
pareena mi casa                                 18
m3m soulitude                                   18
tata gurgaon gateway                            17
indiabulls centrum park                         17
spaze privy at4                                 17
mapsko royale ville                             17
paras dews                                      16
mapsko casa bella                               16
central park resorts                            16
puri diplomatic greens                          15
tulip purple                                    15
vipul lavanya                                   15
umang winter hills                              15
pioneer urban presidia                          15
paras irene                                     15
dlf park place                                  14
central park flower valley aqua front towers    14
emaar mgf palm terraces select                  14
eldeco accolade                                 14
indiabulls enigma                               14
vatika the seven lamps                          13
greenopolis                                     13
m3m woodshire                                   13
sare crescent parc                              12
vatika sovereign park                           12
emaar gurgaon greens                            12
godrej habitat                                  12
bestech park view spa next                      11
unitech harmony                                 11
parsvnath exotica                               11
silverglades the melia                          11
dlf new town heights 1                          11
ireo victory valley                             11
mapsko mount ville                              11
spaze privvy the address                        11
ats kocoon                                      11
pioneer araya                                   11
ashiana anmol                                   11
m3m merlin                                      11
emaar mgf emerald estate                        10
vatika city                                     10
ats marigold                                    10
ireo the grand arch                             10
eldeco acclaim                                  10
emaar mgf palm hills                             9
pareena express heights                          9
unitech escape                                   9
tarc maceo                                       9
orris aster court                                9
vatika gurgaon 21                                9
m3m the marina                                   8
bptp park serene                                 8
shree vardhman victoria                          8
orchid petals                                    8
tulip monsella                                   8
bestech park view city 2                         7
mapsko paradise                                  7
the close south                                  7
aipl the peaceful homes                          7
microtek greenburg                               7
suncity platinum towers                          7
bestech park view residency                      7
mahindra luminare                                6
m3m natura                                       6
rof ananda                                       6
alpha corp gurgaonone 84                         6
bptp freedom park life                           6
lotus elise                                      6
m3m latitude                                     6
signature the roselia                            5
the close north                                  5
intelligentsia apartment                         5
cosmos express 99                                5
krisumi waterfall residences                     5
dlf the crest                                    5
trump tower                                      5
emaar palm heights                               5
emaar digihomes                                  5
signature global park                            5
parsvnath green ville                            5
ramprastha the edge towers                       5
orris carnation residency                        5
pareena coban residences                         5
spaze kalistaa                                   4
dlf westend heights                              4
ss the coralwood                                 4
sare petioles                                    4
dlf regency park 2                               4
m3m escala                                       4
piedmont taksila heights                         4
bestech park view city                           4
imperia the esfera                               4
m3m skywalk                                      4
ild greens                                       4
raheja vedaanta                                  4
ambience creacions                               4
m3m skycity                                      4
godrej icon                                      4
signature global city                            4
signature global orchard avenue 2                4
brisk lumbini terrace homes                      4
vatika lifestyle homes                           4
bptp park generations                            4
dlf the belaire                                  4
godrej nature plus                               4
godrej 101                                       3
ild grand                                        3
ss linden floors                                 3
central park 2 bellevue                          3
dlf carlton estate                               3
emaar mgf the enclave                            3
bestech park view spa                            3
ramprastha the view                              3
unitech the residences                           3
bptp spacio                                      3
pyramid fusion homes                             3
pyramid urban homes                              3
suncity vatsal valley                            3
m3m flora                                        3
gpl eden heights                                 3
tulip orange                                     3
pyramid urban                                    3
navyug apartments                                3
krrish provence estate                           3
ansal harmony homes                              3
sahara grace                                     3
ambience lagoon                                  2
dlf express greens                               2
bptp terra                                       2
suncity avenue 76                                2
unitech uniworld gardens                         2
dlf park heights                                 2
aipl zen residences                              2
dlf gardencity enclave                           2
vipul greens                                     2
raheja atharva                                   2
chd avenue 71                                    2
pivotal devaan                                   2
dlf wellington estate                            2
godrej oasis                                     2
ardee city                                       2
tulip ace                                        2
pioneer park                                     2
smart world orchard street                       2
emaar mgf emerald floors                         2
ashiana mulberry                                 2
godrej frontier                                  2
ramprastha primera                               2
central park flower valley flamingo floors       2
silverglades the ivy                             2
mrg the balcony                                  2
vatika city homes                                2
anant raj estates                                2
assotech blith                                   2
millenium apartment                              2
emaar mgf palm studios                           2
central park flower valley                       2
landmark towers                                  2
breez global heights                             1
conscient heritage one                           1
sector 70                                        1
tulip crimson                                    1
sidhartha ncr one phase 1                        1
viridian the plaza 106                           1
dlf hamilton court                               1
signature global the millennia                   1
karam hi dharam                                  1
supertech araville                               1
emaar mgf the vilas                              1
friends apartment                                1
m3m st andrews                                   1
new shivalik apartments                          1
vatika inxt floors                               1
rose apartment                                   1
raisina residency                                1
sanskriti apartments                             1
dlf regency park 1                               1
pyramid heights                                  1
dlf ridgewood estate                             1
samanvay apartment                               1
prerna society                                   1
dlf the aralias                                  1
sec-57                                           1
dlf belvedere park                               1
dhoot time residency                             1
pyramid elite                                    1
bptp park prime                                  1
emaar mgf palm terraces                          1
today blossoms 1                                 1
vigyan vihar sector 56                           1
godrej summit                                    1
dlf alameda                                      1
pyramid square 67a                               1
valley view estate                               1
tdi ourania                                      1
dlf richmond park                                1
suncity essel towers                             1
signature the serenas                            1
signature signum 81                              1
technocrat society                               1
adani brahma samsara                             1
tulip white                                      1
cghs aravali homes                               1
vipul belmonte                                   1
45 pragati hills                                 1
vatika sovereign next                            1
bestech spa signature                            1
tulip leaf                                       1
ireo uptown                                      1
sri kirti apartments                             1
himalayan society                                1
dlf garden city floors                           1
cghs joy kunj                                    1
maxworth premier urban                           1
cghs agrim apartment block c, sushant lok 1      1
oriental valley chs                              1
unitech heritage city                            1
pragati hills cghs society                       1
jnu aravali apartment                            1
pib gharonda apartment                           1
bhagwanti apartment                              1
central park                                     1
orchid gardens                                   1
dlf carlton estate 4                             1
the orchid crescent                              1
m3m capital                                      1
paras quartier                                   1
dlf exclusive floors                             1
golden apartment                                 1
cghs hewo apartments                             1
salcon the verandas                              1
emaar emerald hills                              1
orris aster court premier                        1
the citizen                                      1
ss cendana reserve collection                    1
m3m sierra 68                                    1
krishna apartments                               1
abhinandan cghs                                  1
sare crescent parc royal greens phase 1          1
awho devinder vihar                              1
amoda i, birla navya                             1
dlf the pinnacle                                 1
signature global city 37d ph 2                   1
dlf silver oaks                                  1
eros wembley estate                              1
unitech uniworld city                            1
Name: count, dtype: int64

In [14]:
df_flat['society'].isna().sum()

0

### 2. Price

In [16]:
df_flat = df_flat.rename(columns ={
    'price' : 'price_in_cr',
    'area'  :'price_per_sqft'
})

In [17]:
df_flat['price_in_cr'].value_counts()

price_in_cr
₹2.5 Cr      53
₹2.4 Cr      53
₹2.1 Cr      49
₹2.6 Cr      46
₹2.3 Cr      37
             ..
₹10.65 Cr     1
₹68 Lac       1
₹4.07 Cr      1
₹19.85 Cr     1
₹3.07 Cr      1
Name: count, Length: 502, dtype: int64

In [18]:
column_cleaning = (df_flat.assign
                   (
                       price_in_cr = lambda df_:df_['price_in_cr']
                                            .str
                                            .replace('₹','')
                   ))
column_cleaning['price_in_cr'].unique()

array(['2.5 Cr', '1.29 Cr', '2.9 Cr', '2.65 Cr', '2.4 Cr', '3.5 Cr',
       '2.07 Cr', '4.29 Cr', '3.85 Cr', '2.45 Cr', '1.55 Cr', '7.55 Cr',
       '1.9 Cr', '4.85 Cr', '4.8 Cr', '4.15 Cr', '3.1 Cr', '2.1 Cr',
       '1.65 Cr', '2.55 Cr', '3.65 Cr', '4.26 Cr', '1.63 Cr', '8 Cr',
       '4.25 Cr', '2 Cr', '2.21 Cr', '1.56 Cr', '7.9 Cr', '5.22 Cr',
       '1.6 Cr', '3.45 Cr', '7.5 Cr', '2.84 Cr', '1.85 Cr', '2.93 Cr',
       '1.32 Cr', '1.96 Cr', '9.65 Cr', '4 Cr', '4.92 Cr', '7.99 Cr',
       '1.25 Cr', '4.7 Cr', '2.51 Cr', '1.3 Cr', '4.81 Cr', '4.67 Cr',
       '3.58 Cr', '2.25 Cr', '6.41 Cr', '8.25 Cr', '5.5 Cr', '2.85 Cr',
       '3.73 Cr', '2.46 Cr', '2.68 Cr', '4.06 Cr', '7.76 Cr', '2.63 Cr',
       '1.7 Cr', '3.9 Cr', '4.9 Cr', '2.35 Cr', '3.17 Cr', '3.6 Cr',
       '4.65 Cr', '7.88 Cr', '7.75 Cr', '10.2 Cr', '2.7 Cr', '3.7 Cr',
       '3.54 Cr', '6.35 Cr', '3 Cr', '1.35 Cr', '4.97 Cr', '2.95 Cr',
       '3.84 Cr', '5.9 Cr', '8.7 Cr', '1.42 Cr', '2.77 Cr', '2.69 Cr',
       '3.4 Cr', '13 Cr', '4.05 Cr', '2.44 Cr', '1.64 Cr', '2.2 Cr',
       '1.62 Cr', '3.05 Cr', '3.67 Cr', '2.05 Cr', '4.45 Cr', '1.95 Cr',
       '2.23 Cr', '3.49 Cr', '3.95 Cr', '3.75 Cr', '7.85 Cr', '3.2 Cr',
       '6.38 Cr', '5.2 Cr', '2.3 Cr', '4.11 Cr', '3.25 Cr', '1.76 Cr',
       '4.12 Cr', '2.37 Cr', '2.38 Cr', '5.32 Cr', '5.85 Cr', '2.72 Cr',
       '5.05 Cr', '4.07 Cr', '3.8 Cr', '3.46 Cr', '7.35 Cr', '2.48 Cr',
       '5.65 Cr', '2.6 Cr', '1.99 Cr', '1.84 Cr', '2.61 Cr', '3.11 Cr',
       '3.38 Cr', '3.15 Cr', '3.44 Cr', '10.5 Cr', '9.85 Cr', '2.75 Cr',
       '3.48 Cr', '12 Cr', '9.25 Cr', '7 Cr', '5.1 Cr', '4.35 Cr',
       '1.45 Cr', '1.38 Cr', '1.31 Cr', '1.4 Cr', '2.78 Cr', '4.5 Cr',
       '1.57 Cr', '7.28 Cr', '3.51 Cr', '4.49 Cr', '4.3 Cr', '2.52 Cr',
       '6.5 Cr', '1.61 Cr', '2.71 Cr', '1.12 Cr', '1.75 Cr', '1.78 Cr',
       '14 Cr', '2.15 Cr', '6.4 Cr', '1.91 Cr', '4.95 Cr', '4.38 Cr',
       '2.99 Cr', '1.17 Cr', '3.3 Cr', '5.7 Cr', '4.4 Cr', '3.88 Cr',
       '1.86 Cr', '3.16 Cr', '2.8 Cr', '4.75 Cr', '5.95 Cr', '2.01 Cr',
       '7.25 Cr', '5.25 Cr', '1.34 Cr', '10.25 Cr', '2.64 Cr', '3.26 Cr',
       '3.27 Cr', '2.91 Cr', '23.02 Cr', '3.19 Cr', '4.6 Cr', '12.9 Cr',
       '8.9 Cr', '1.27 Cr', '11 Cr', '2.56 Cr', '4.08 Cr', '2.54 Cr',
       '1.58 Cr', '9.5 Cr', '2.28 Cr', '8.3 Cr', '10 Cr', '3.55 Cr',
       '3.56 Cr', '1.54 Cr', '4.1 Cr', '1.8 Cr', '6.15 Cr', '6.25 Cr',
       '4.89 Cr', '3.68 Cr', '3.35 Cr', '6.3 Cr', '3.63 Cr', '3.32 Cr',
       '2.76 Cr', '14.95 Cr', '4.41 Cr', '4.99 Cr', '3.94 Cr', '4.69 Cr',
       '4.68 Cr', '5 Cr', '8.66 Cr', '1.43 Cr', '1.59 Cr', '1.37 Cr',
       '5.21 Cr', '3.41 Cr', '5.8 Cr', '2.18 Cr', '2.49 Cr', '1.2 Cr',
       '7.94 Cr', '1.89 Cr', '2.09 Cr', '9.8 Cr', '9 Cr', '3.64 Cr',
       '2.42 Cr', '1.98 Cr', '1.33 Cr', '1.48 Cr', '3.36 Cr', '5.15 Cr',
       '1.5 Cr', '2.12 Cr', '8.5 Cr', '9.4 Cr', '5.43 Cr', '4.56 Cr',
       '2.24 Cr', '3.66 Cr', '2.88 Cr', '10.75 Cr', '1.82 Cr', '5.45 Cr',
       '2.19 Cr', '6.45 Cr', '3.08 Cr', '5.55 Cr', '2.81 Cr', '65 Lac',
       '1.66 Cr', '3.92 Cr', '4.57 Cr', '1.44 Cr', '5.58 Cr', '2.97 Cr',
       '2.89 Cr', '4.86 Cr', '18 Cr', '3.61 Cr', '4.84 Cr', '5.18 Cr',
       '2.58 Cr', '4.71 Cr', '5.75 Cr', '4.16 Cr', '3.52 Cr', '1.52 Cr',
       '9.7 Cr', '3.28 Cr', '16.7 Cr', '2.62 Cr', '1.87 Cr', '2.26 Cr',
       '1.51 Cr', '8.2 Cr', '2.98 Cr', '7.4 Cr', '1.41 Cr', '11.5 Cr',
       '2.59 Cr', '6.1 Cr', '11.9 Cr', '1.39 Cr', '2.83 Cr', '3.43 Cr',
       '11.15 Cr', '1.15 Cr', '2.87 Cr', '2.22 Cr', '2.16 Cr', '2.33 Cr',
       '99 Lac', '7.2 Cr', '5.19 Cr', '3.39 Cr', '5.49 Cr', '1.92 Cr',
       '5.27 Cr', '5.3 Cr', '12.98 Cr', '5.35 Cr', '2.32 Cr', '2.41 Cr',
       '5.17 Cr', '7.48 Cr', '1.93 Cr', '15.9 Cr', '8.6 Cr', '10.8 Cr',
       '6.7 Cr', '4.77 Cr', '2.36 Cr', '3.18 Cr', '1.79 Cr', '7.3 Cr',
       '16 Cr', '3.09 Cr', '13.5 Cr', '1.77 Cr', '2.96 Cr', '4.2 Cr',
       '3.62 Cr', '2.14 Cr', '3.24 Cr', '3.21 Cr', '2.67 Cr', '90 Lac',
       '1.46 Cr', '1.68 Cr', '3.87 Cr', '3.42 Cr', '1.22 Cr', '2.02 Cr',
       '6.6 Cr', '1.09 Cr', '1.1 Cr', '2.27 Cr', '2.82 Cr', '86.75 Lac',
       '11.55 Cr', '8.11 Cr', '1.97 Cr', '7.95 Cr', '3.29 Cr', '23 Cr',
       '5.4 Cr', '1.74 Cr', '1.88 Cr', '4.53 Cr', '3.03 Cr', '3.81 Cr',
       '4.48 Cr', '10.99 Cr', '10.65 Cr', '1.49 Cr', '68 Lac', '2.03 Cr',
       '19.85 Cr', '2.17 Cr', '4.28 Cr', '16.25 Cr', '2.79 Cr', '2.39 Cr',
       '3.01 Cr', '78 Lac', '2.66 Cr', '1.47 Cr', '72.25 Lac', '60 Lac',
       '1.26 Cr', '8.55 Cr', '2.47 Cr', '6.11 Cr', '1.28 Cr', '1.81 Cr',
       '8.49 Cr', '3.96 Cr', '11.05 Cr', '72 Lac', '1.36 Cr', '75 Lac',
       '5.11 Cr', '8.75 Cr', '7.24 Cr', '55 Lac', '2.08 Cr', '7.87 Cr',
       '85 Lac', '6.75 Cr', '5.6 Cr', '7.15 Cr', '8.35 Cr', '9.96 Cr',
       '1.53 Cr', '73 Lac', '63.5 Lac', '1.67 Cr', '1.24 Cr', '87.45 Lac',
       '1.69 Cr', '6 Cr', '64 Lac', '7.6 Cr', '67 Lac', '1.72 Cr',
       '2.04 Cr', '3.02 Cr', '7.47 Cr', '1 Cr', '2.73 Cr', '2.34 Cr',
       '5.12 Cr', '2.31 Cr', '3.72 Cr', '2.57 Cr', '1.07 Cr', '1.05 Cr',
       '2.53 Cr', '70 Lac', '58.1 Lac', '86.5 Lac', '84.5 Lac',
       '66.4 Lac', '61.8 Lac', '65.25 Lac', '7.68 Cr', '3.99 Cr',
       '35.6 Cr', '3.69 Cr', '7.8 Cr', '1.18 Cr', '1.83 Cr', '3.57 Cr',
       '72.3 Lac', '1.19 Cr', '9.9 Cr', '19 Cr', '15.5 Cr', '7.1 Cr',
       '82 Lac', '3.79 Cr', '4.54 Cr', '2.11 Cr', '5.69 Cr', '78.5 Lac',
       '80 Lac', '6.9 Cr', '2.13 Cr', '2.74 Cr', '1.03 Cr', '4.03 Cr',
       '57.5 Lac', '67.9 Lac', '1.73 Cr', '4.37 Cr', '6.65 Cr', '12.5 Cr',
       '3.06 Cr', '1.94 Cr', '95 Lac', '97 Lac', '4.42 Cr', '5.29 Cr',
       '81.6 Lac', '5.16 Cr', '1.23 Cr', '15 Cr', '3.98 Cr', '62 Lac',
       '11.1 Cr', '9.49 Cr', '8.85 Cr', '1.02 Cr', '64.5 Lac', '7.81 Cr',
       '17 Cr', '8.97 Cr', '11.85 Cr', '8.45 Cr', '15.15 Cr', '18.9 Cr',
       '17.5 Cr', '7.05 Cr', '18.05 Cr', '15.95 Cr', '15.2 Cr', '1.04 Cr',
       '4.02 Cr', '8.4 Cr', '1.21 Cr', '4.55 Cr', '5.39 Cr', '3.07 Cr'],
      dtype=object)

In [19]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
2.5 Cr      53
2.4 Cr      53
2.1 Cr      49
2.6 Cr      46
2.3 Cr      37
            ..
10.65 Cr     1
68 Lac       1
4.07 Cr      1
19.85 Cr     1
3.07 Cr      1
Name: count, Length: 502, dtype: int64

In [25]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))
                    )
column_cleaning['price_in_cr'].unique()

array([ 2.5 ,  1.29,  2.9 ,  2.65,  2.4 ,  3.5 ,  2.07,  4.29,  3.85,
        2.45,  1.55,  7.55,  1.9 ,  4.85,  4.8 ,  4.15,  3.1 ,  2.1 ,
        1.65,  2.55,  3.65,  4.26,  1.63,  8.  ,  4.25,  2.  ,  2.21,
        1.56,  7.9 ,  5.22,  1.6 ,  3.45,  7.5 ,  2.84,  1.85,  2.93,
        1.32,  1.96,  9.65,  4.  ,  4.92,  7.99,  1.25,  4.7 ,  2.51,
        1.3 ,  4.81,  4.67,  3.58,  2.25,  6.41,  8.25,  5.5 ,  2.85,
        3.73,  2.46,  2.68,  4.06,  7.76,  2.63,  1.7 ,  3.9 ,  4.9 ,
        2.35,  3.17,  3.6 ,  4.65,  7.88,  7.75, 10.2 ,  2.7 ,  3.7 ,
        3.54,  6.35,  3.  ,  1.35,  4.97,  2.95,  3.84,  5.9 ,  8.7 ,
        1.42,  2.77,  2.69,  3.4 , 13.  ,  4.05,  2.44,  1.64,  2.2 ,
        1.62,  3.05,  3.67,  2.05,  4.45,  1.95,  2.23,  3.49,  3.95,
        3.75,  7.85,  3.2 ,  6.38,  5.2 ,  2.3 ,  4.11,  3.25,  1.76,
        4.12,  2.37,  2.38,  5.32,  5.85,  2.72,  5.05,  4.07,  3.8 ,
        3.46,  7.35,  2.48,  5.65,  2.6 ,  1.99,  1.84,  2.61,  3.11,
        3.38,  3.15,  3.44, 10.5 ,  9.85,  2.75,  3.48, 12.  ,  9.25,
        7.  ,  5.1 ,  4.35,  1.45,  1.38,  1.31,  1.4 ,  2.78,  4.5 ,
        1.57,  7.28,  3.51,  4.49,  4.3 ,  2.52,  6.5 ,  1.61,  2.71,
        1.12,  1.75,  1.78, 14.  ,  2.15,  6.4 ,  1.91,  4.95,  4.38,
        2.99,  1.17,  3.3 ,  5.7 ,  4.4 ,  3.88,  1.86,  3.16,  2.8 ,
        4.75,  5.95,  2.01,  7.25,  5.25,  1.34, 10.25,  2.64,  3.26,
        3.27,  2.91, 23.02,  3.19,  4.6 , 12.9 ,  8.9 ,  1.27, 11.  ,
        2.56,  4.08,  2.54,  1.58,  9.5 ,  2.28,  8.3 , 10.  ,  3.55,
        3.56,  1.54,  4.1 ,  1.8 ,  6.15,  6.25,  4.89,  3.68,  3.35,
        6.3 ,  3.63,  3.32,  2.76, 14.95,  4.41,  4.99,  3.94,  4.69,
        4.68,  5.  ,  8.66,  1.43,  1.59,  1.37,  5.21,  3.41,  5.8 ,
        2.18,  2.49,  1.2 ,  7.94,  1.89,  2.09,  9.8 ,  9.  ,  3.64,
        2.42,  1.98,  1.33,  1.48,  3.36,  5.15,  1.5 ,  2.12,  8.5 ,
        9.4 ,  5.43,  4.56,  2.24,  3.66,  2.88, 10.75,  1.82,  5.45,
        2.19,  6.45,  3.08,  5.55,  2.81,  0.65,  1.66,  3.92,  4.57,
        1.44,  5.58,  2.97,  2.89,  4.86, 18.  ,  3.61,  4.84,  5.18,
        2.58,  4.71,  5.75,  4.16,  3.52,  1.52,  9.7 ,  3.28, 16.7 ,
        2.62,  1.87,  2.26,  1.51,  8.2 ,  2.98,  7.4 ,  1.41, 11.5 ,
        2.59,  6.1 , 11.9 ,  1.39,  2.83,  3.43, 11.15,  1.15,  2.87,
        2.22,  2.16,  2.33,  0.99,  7.2 ,  5.19,  3.39,  5.49,  1.92,
        5.27,  5.3 , 12.98,  5.35,  2.32,  2.41,  5.17,  7.48,  1.93,
       15.9 ,  8.6 , 10.8 ,  6.7 ,  4.77,  2.36,  3.18,  1.79,  7.3 ,
       16.  ,  3.09, 13.5 ,  1.77,  2.96,  4.2 ,  3.62,  2.14,  3.24,
        3.21,  2.67,  0.9 ,  1.46,  1.68,  3.87,  3.42,  1.22,  2.02,
        6.6 ,  1.09,  1.1 ,  2.27,  2.82,  0.87, 11.55,  8.11,  1.97,
        7.95,  3.29, 23.  ,  5.4 ,  1.74,  1.88,  4.53,  3.03,  3.81,
        4.48, 10.99, 10.65,  1.49,  0.68,  2.03, 19.85,  2.17,  4.28,
       16.25,  2.79,  2.39,  3.01,  0.78,  2.66,  1.47,  0.72,  0.6 ,
        1.26,  8.55,  2.47,  6.11,  1.28,  1.81,  8.49,  3.96, 11.05,
        1.36,  0.75,  5.11,  8.75,  7.24,  0.55,  2.08,  7.87,  0.85,
        6.75,  5.6 ,  7.15,  8.35,  9.96,  1.53,  0.73,  0.64,  1.67,
        1.24,  1.69,  6.  ,  7.6 ,  0.67,  1.72,  2.04,  3.02,  7.47,
        1.  ,  2.73,  2.34,  5.12,  2.31,  3.72,  2.57,  1.07,  1.05,
        2.53,  0.7 ,  0.58,  0.86,  0.84,  0.66,  0.62,  7.68,  3.99,
       35.6 ,  3.69,  7.8 ,  1.18,  1.83,  3.57,  1.19,  9.9 , 19.  ,
       15.5 ,  7.1 ,  0.82,  3.79,  4.54,  2.11,  5.69,  0.8 ,  6.9 ,
        2.13,  2.74,  1.03,  4.03,  0.57,  1.73,  4.37,  6.65, 12.5 ,
        3.06,  1.94,  0.95,  0.97,  4.42,  5.29,  5.16,  1.23, 15.  ,
        3.98, 11.1 ,  9.49,  8.85,  1.02,  7.81, 17.  ,  8.97, 11.85,
        8.45, 15.15, 18.9 , 17.5 ,  7.05, 18.05, 15.95, 15.2 ,  1.04,
        4.02,  8.4 ,  1.21,  4.55,  5.39,  3.07])

In [22]:
column_cleaning['price_in_cr'].isnull().sum()

0

In [26]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
2.50     53
2.40     53
2.10     49
2.60     46
2.30     37
1.85     36
2.70     35
2.65     34
1.60     33
2.80     31
2.45     30
2.25     29
1.90     28
1.65     28
1.55     27
3.20     26
2.00     26
2.75     26
1.70     25
2.35     25
2.90     24
2.05     24
2.55     23
2.15     23
2.20     22
3.60     22
3.65     22
3.50     22
3.70     20
3.45     20
3.90     20
3.10     19
1.80     19
2.85     19
3.00     18
1.50     18
3.15     18
2.95     17
1.95     17
3.75     16
1.35     16
3.85     16
4.10     15
1.75     15
3.25     15
3.40     15
4.50     15
4.00     15
1.40     15
1.45     14
3.80     13
5.25     12
4.90     12
1.62     11
4.80     11
3.35     11
5.50     11
1.30     10
1.56     10
4.20     10
1.58     10
4.15     10
4.30     10
3.55     10
7.50      9
2.68      9
4.70      9
5.30      9
4.25      9
4.75      9
1.52      8
2.38      8
2.49      8
4.45      8
1.25      8
3.95      8
5.10      8
8.50      8
3.30      8
7.00      7
4.95      7
2.33      7
4.85      7
2.27      7
8.00      7
1.86      7
2.07      7
1.87      7
4.40      7
2.61      6
2.99      6
1.79      6
3.48      6
1.38      6
2.28      6
11.00     6
1.99      6
6.50      6
3.05      6
1.92      6
1.10      6
4.99      6
2.42      6
1.98      6
3.49      5
1.68      5
1.84      5
2.76      5
7.75      5
3.88      5
2.63      5
1.32      5
2.26      5
2.64      5
4.35      5
2.62      5
1.78      5
5.75      5
5.90      5
2.71      5
2.37      5
5.80      5
0.64      5
5.00      5
1.59      5
9.50      5
4.05      5
2.72      5
1.42      5
1.64      5
5.35      5
3.68      5
1.91      4
2.88      4
6.40      4
1.44      4
1.72      4
2.58      4
2.19      4
1.34      4
7.95      4
2.17      4
2.12      4
2.22      4
1.48      4
4.60      4
3.21      4
2.18      4
3.19      4
2.09      4
1.22      4
1.53      4
6.75      4
3.17      4
2.46      4
5.05      4
1.57      4
2.48      4
3.51      4
5.20      4
4.49      4
2.52      4
3.44      4
2.77      3
6.35      3
3.64      3
23.00     3
1.20      3
0.72      3
1.61      3
3.41      3
1.74      3
1.33      3
1.43      3
1.88      3
12.50     3
6.00      3
2.44      3
3.67      3
6.30      3
2.69      3
1.28      3
4.65      3
6.25      3
2.96      3
7.55      3
2.32      3
1.15      3
2.93      3
2.59      3
11.50     3
1.96      3
0.55      3
9.70      3
2.02      3
3.58      3
1.82      3
1.81      3
3.66      3
1.29      3
1.97      3
7.85      3
5.15      3
2.31      3
3.27      3
5.65      3
1.76      3
12.00     3
7.35      3
7.25      3
10.50     3
9.25      3
2.78      3
1.41      2
7.40      2
3.87      2
13.50     2
6.10      2
3.69      2
1.18      2
5.70      2
1.51      2
1.31      2
1.36      2
7.99      2
9.85      2
2.51      2
4.16      2
4.81      2
6.60      2
2.08      2
5.18      2
3.16      2
1.39      2
1.00      2
3.79      2
2.87      2
16.00     2
4.29      2
3.18      2
2.36      2
14.00     2
2.39      2
1.05      2
8.60      2
3.62      2
1.93      2
0.70      2
2.34      2
2.41      2
4.26      2
12.98     2
1.63      2
3.24      2
0.75      2
7.90      2
3.39      2
7.20      2
0.62      2
5.22      2
2.16      2
2.84      2
0.82      2
6.15      2
2.89      2
0.68      2
3.32      2
3.46      2
3.56      2
3.01      2
2.82      2
1.24      2
9.80      2
1.26      2
1.89      2
2.03      2
5.60      2
4.11      2
1.27      2
2.56      2
1.49      2
5.40      2
2.54      2
0.78      2
5.32      2
4.12      2
13.00     2
10.00     2
2.91      2
2.47      2
3.36      2
3.63      2
2.66      2
8.25      2
0.87      2
3.73      2
1.66      2
0.65      2
2.81      2
0.67      2
3.08      2
6.90      2
3.03      2
3.38      2
5.45      2
5.95      2
10.75     2
2.01      2
3.11      2
2.74      2
10.25     2
1.54      2
7.15      1
5.12      1
1.69      1
1.67      1
2.73      1
7.60      1
7.47      1
0.73      1
8.35      1
0.85      1
3.02      1
2.04      1
7.87      1
9.96      1
5.29      1
3.72      1
11.85     1
4.42      1
8.75      1
5.16      1
1.23      1
15.00     1
3.98      1
11.10     1
9.49      1
8.85      1
1.02      1
7.81      1
17.00     1
8.97      1
8.45      1
0.95      1
15.15     1
18.90     1
17.50     1
7.05      1
18.05     1
15.95     1
15.20     1
1.04      1
4.02      1
8.40      1
1.21      1
4.55      1
5.39      1
0.97      1
1.94      1
2.57      1
9.90      1
1.07      1
2.53      1
0.58      1
0.86      1
0.84      1
0.66      1
7.68      1
3.99      1
35.60     1
7.80      1
1.83      1
3.57      1
1.19      1
19.00     1
3.06      1
15.50     1
7.10      1
4.54      1
2.11      1
5.69      1
0.80      1
2.13      1
1.03      1
4.03      1
0.57      1
1.73      1
4.37      1
6.65      1
7.24      1
2.24      1
5.11      1
5.21      1
4.08      1
8.30      1
4.89      1
14.95     1
4.41      1
3.94      1
4.69      1
4.68      1
8.66      1
1.37      1
7.94      1
18.00     1
9.00      1
9.40      1
5.43      1
4.56      1
6.45      1
5.55      1
3.92      1
4.57      1
5.58      1
2.97      1
8.90      1
12.90     1
23.02     1
3.26      1
2.21      1
9.65      1
4.92      1
4.67      1
6.41      1
4.06      1
7.76      1
7.88      1
10.20     1
3.54      1
4.97      1
3.84      1
8.70      1
2.23      1
6.38      1
5.85      1
4.07      1
7.28      1
1.12      1
4.38      1
1.17      1
4.86      1
3.61      1
11.05     1
10.99     1
0.90      1
1.46      1
3.42      1
1.09      1
11.55     1
8.11      1
3.29      1
4.53      1
3.81      1
4.48      1
10.65     1
4.84      1
19.85     1
4.28      1
16.25     1
2.79      1
1.47      1
0.60      1
8.55      1
6.11      1
8.49      1
3.96      1
2.67      1
2.14      1
1.77      1
3.09      1
4.71      1
3.52      1
3.28      1
16.70     1
8.20      1
2.98      1
11.90     1
2.83      1
3.43      1
11.15     1
0.99      1
5.19      1
5.49      1
5.27      1
5.17      1
7.48      1
15.90     1
10.80     1
6.70      1
4.77      1
7.30      1
3.07      1
Name: count, dtype: int64

In [88]:
column_cleaning['price_in_cr'].isnull().sum()

0

In [89]:
column_cleaning['price_in_cr'].value_counts()

price_in_cr
1.25     83
2.50     81
1.50     75
2.10     75
1.60     75
         ..
3.96      1
11.05     1
5.11      1
8.75      1
5.88      1
Name: count, Length: 584, dtype: int64

In [27]:
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,"₹15,822 /sqft","1,580 sqft (147 sqm) Super Built-up Area",2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,"₹10,254 /sqft","1,565 sqft (145 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,"₹10,653 /sqft","2,722 sqft (253 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,"₹20,075 /sqft","1,852 sqft (172 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,"₹11,851 /sqft","2,025 sqft (188 sqm) Super Built-up Area",3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,"₹11,257 /sqft","3,198 sqft (297 sqm) Super Built-up Area",4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,"₹13,673 /sqft","1,704 sqft (158 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,"₹14,038 /sqft","1,852 sqft (172 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,"₹10,459 /sqft","1,960 sqft (182 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,"₹8,739 /sqft","2,746 sqft (255 sqm) Super Built-up Area",4 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

### 3. Price Per Sqft

In [28]:
column_cleaning['price_per_sqft'].value_counts()

price_per_sqft
₹10,000 /sqft    10
₹20,000 /sqft     9
₹12,000 /sqft     7
₹16,000 /sqft     7
₹11,044 /sqft     7
                 ..
₹11,933 /sqft     1
₹14,695 /sqft     1
₹11,913 /sqft     1
₹11,313 /sqft     1
₹8,739 /sqft      1
Name: count, Length: 1898, dtype: int64

In [33]:
column_cleaning = (df_flat
                    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()

)))
column_cleaning['price_per_sqft'].unique().tolist()

[15822,
 10254,
 10653,
 20075,
 11851,
 14209,
 12834,
 24137,
 17107,
 20704,
 12222,
 17753,
 10000,
 15573,
 10270,
 22407,
 22911,
 20028,
 11397,
 12000,
 10515,
 11538,
 16139,
 13129,
 21707,
 10910,
 22093,
 32475,
 20211,
 11456,
 9043,
 12490,
 15094,
 13476,
 15470,
 13746,
 10626,
 15142,
 13894,
 13234,
 10729,
 24807,
 12028,
 17558,
 16860,
 9850,
 19583,
 13287,
 11524,
 16747,
 16260,
 11044,
 17023,
 13204,
 17034,
 21339,
 19469,
 15183,
 26252,
 17829,
 20163,
 10709,
 16610,
 19406,
 20269,
 16374,
 19044,
 14166,
 18536,
 20059,
 17061,
 11036,
 14860,
 12291,
 9026,
 17357,
 16595,
 11514,
 16224,
 16145,
 30088,
 14558,
 11790,
 16349,
 13308,
 48940,
 19150,
 16172,
 12195,
 17305,
 12516,
 15245,
 19171,
 21071,
 9520,
 25625,
 8947,
 14398,
 11503,
 11171,
 14827,
 14258,
 26041,
 12715,
 14319,
 10977,
 9072,
 18407,
 8350,
 14377,
 31490,
 11221,
 16442,
 18995,
 17580,
 11801,
 15881,
 15772,
 9180,
 14348,
 11560,
 11404,
 16369,
 19315,
 17857,
 16564,
 16537,
 17127,
 20392,
 21099,
 15333,
 23690,
 15226,
 20519,
 14672,
 10731,
 15975,
 11703,
 11753,
 12666,
 13982,
 18932,
 15546,
 17685,
 43572,
 20871,
 19720,
 15567,
 16244,
 23520,
 14028,
 18931,
 20208,
 13089,
 20411,
 12571,
 15950,
 12066,
 16885,
 14962,
 13539,
 16012,
 15534,
 18490,
 14876,
 14657,
 12932,
 10472,
 18984,
 36199,
 22000,
 10998,
 20338,
 10638,
 14758,
 13318,
 24271,
 23663,
 26819,
 17757,
 11571,
 15524,
 10175,
 18912,
 9471,
 14084,
 8522,
 16489,
 22916,
 9865,
 13728,
 12182,
 13029,
 15254,
 8219,
 18599,
 14479,
 11068,
 15016,
 17380,
 15633,
 15574,
 16463,
 16559,
 15518,
 14253,
 21026,
 18672,
 14545,
 16216,
 10401,
 15488,
 23214,
 15118,
 19811,
 15484,
 20000,
 9253,
 14111,
 8800,
 14906,
 15920,
 16690,
 20511,
 12973,
 9523,
 18000,
 15343,
 11596,
 14446,
 40816,
 11324,
 15739,
 26854,
 25610,
 16326,
 14091,
 19465,
 14090,
 20454,
 13157,
 11664,
 18998,
 13500,
 14505,
 17045,
 14054,
 17235,
 21500,
 16562,
 17661,
 18025,
 14740,
 11556,
 16703,
 9256,
 11755,
 16641,
 17812,
 18257,
 12317,
 11923,
 13649,
 16063,
 17062,
 18469,
 15699,
 16101,
 15811,
 18463,
 11255,
 16181,
 23389,
 16466,
 15044,
 14954,
 12983,
 30944,
 8333,
 13684,
 20588,
 19370,
 11138,
 25561,
 13120,
 12380,
 13082,
 12820,
 16000,
 13612,
 13594,
 14890,
 19032,
 13731,
 14634,
 15363,
 17356,
 8532,
 11642,
 12601,
 19615,
 15393,
 17022,
 16279,
 39800,
 11395,
 23174,
 16086,
 11458,
 14889,
 19632,
 15503,
 27652,
 26253,
 8048,
 17705,
 29858,
 11666,
 15156,
 9006,
 13007,
 12810,
 16307,
 9645,
 10161,
 15282,
 18642,
 12410,
 12371,
 10981,
 19242,
 9813,
 11627,
 25000,
 13255,
 25801,
 22321,
 9285,
 34349,
 12345,
 13345,
 13383,
 13915,
 14000,
 13015,
 11250,
 26295,
 8750,
 16129,
 14285,
 10943,
 16975,
 12337,
 10335,
 14200,
 10373,
 15850,
 24140,
 11515,
 15960,
 20416,
 12592,
 19047,
 17309,
 17523,
 19787,
 11726,
 22211,
 16741,
 13698,
 21603,
 15293,
 15196,
 8637,
 24166,
 16483,
 8405,
 15197,
 9890,
 12649,
 18379,
 12939,
 17021,
 19403,
 14704,
 16801,
 33200,
 19732,
 12752,
 19588,
 7843,
 11378,
 13678,
 21012,
 26263,
 19182,
 20913,
 17828,
 14255,
 13980,
 17406,
 19774,
 16949,
 9141,
 7777,
 12958,
 9166,
 10642,
 11871,
 14376,
 19847,
 18654,
 16081,
 23770,
 13537,
 12674,
 12790,
 17208,
 11482,
 17120,
 16903,
 13918,
 16438,
 19189,
 27455,
 12250,
 13768,
 8864,
 10219,
 15280,
 15461,
 16500,
 11942,
 7709,
 13673,
 18500,
 9386,
 20999,
 17374,
 10848,
 14103,
 10362,
 36242,
 12969,
 12758,
 19551,
 10838,
 19908,
 12081,
 13816,
 15373,
 23758,
 19090,
 19212,
 16225,
 21282,
 13033,
 13607,
 16210,
 14302,
 19981,
 10338,
 9379,
 10323,
 17351,
 15246,
 15510,
 11796,
 35300,
 17634,
 15384,
 15789,
 16832,
 9265,
 14920,
 14801,
 10484,
 13392,
 11083,
 10954,
 16800,
 13095,
 30429,
 22440,
 21530,
 14707,
 17667,
 24646,
 9860,
 20379,
 25036,
 21601,
 14003,
 17217,
 12906,
 12482,
 14363,
 16527,
 17054,
 12811,
 18333,
 16057,
 13200,
 15757,
 18139,
 9432,
 15530,
 20360,
 13141,
 7692,
 17447,
 17166,
 30590,
 29292,
 21052,
 15454,
 24786,
 10816,
 15832,
 15985,
 8310,
 11023,
 17590,
 21784,
 21081,
 33121,
 11010,
 12091,
 14534,
 10614,
 20621,
 14444,
 14797,
 16325,
 16751,
 11779,
 14375,
 18936,
 23285,
 30401,
 10086,
 13603,
 18666,
 13732,
 11278,
 20700,
 11111,
 12500,
 14985,
 18706,
 11188,
 22200,
 9708,
 16440,
 13351,
 16565,
 18721,
 16717,
 11917,
 11325,
 19746,
 7852,
 9728,
 15140,
 15000,
 13761,
 10298,
 14073,
 9923,
 14575,
 8997,
 10087,
 20491,
 19168,
 13725,
 12158,
 9986,
 26995,
 16120,
 29037,
 14892,
 14716,
 12962,
 18030,
 20909,
 15643,
 15896,
 16698,
 11340,
 17848,
 13870,
 13740,
 18075,
 18445,
 13959,
 20742,
 14948,
 15703,
 25714,
 19459,
 16846,
 17213,
 25963,
 13127,
 23950,
 8533,
 22875,
 23150,
 9108,
 11835,
 19388,
 15235,
 16852,
 12333,
 11417,
 10332,
 10813,
 18838,
 13763,
 15625,
 14017,
 31414,
 11828,
 20821,
 14814,
 12972,
 8749,
 9000,
 9002,
 11353,
 16472,
 13421,
 12732,
 17500,
 16917,
 31446,
 13045,
 11602,
 13233,
 13195,
 17130,
 22622,
 18095,
 19011,
 18639,
 18096,
 13823,
 14693,
 14489,
 15555,
 8381,
 24343,
 14504,
 15350,
 15637,
 15452,
 16939,
 10833,
 14455,
 12727,
 16612,
 28613,
 14577,
 18111,
 13529,
 14563,
 27669,
 30438,
 15474,
 23846,
 11033,
 9200,
 53474,
 12146,
 14696,
 12186,
 19430,
 15390,
 15306,
 18743,
 9456,
 9935,
 12696,
 26086,
 8273,
 7862,
 14150,
 22586,
 38139,
 18656,
 24553,
 18939,
 14117,
 14360,
 9469,
 12530,
 24790,
 8813,
 8902,
 10105,
 9764,
 14705,
 8290,
 11290,
 12857,
 10374,
 32857,
 16358,
 16203,
 30116,
 23506,
 14414,
 13388,
 8272,
 14338,
 18565,
 26562,
 15922,
 8942,
 14058,
 12172,
 11792,
 9824,
 12894,
 13380,
 12325,
 12428,
 10901,
 14175,
 15588,
 18223,
 15976,
 26484,
 14626,
 12232,
 15867,
 12590,
 12632,
 18559,
 15422,
 22443,
 22008,
 19825,
 17015,
 13593,
 15676,
 7936,
 25048,
 15123,
 14498,
 18202,
 23209,
 9084,
 8493,
 14712,
 13000,
 15683,
 14741,
 15073,
 16251,
 13207,
 11313,
 11913,
 14695,
 11933,
 18622,
 22227,
 12780,
 20711,
 12063,
 12285,
 19731,
 11679,
 19899,
 17842,
 9629,
 19251,
 20833,
 24169,
 15436,
 28947,
 12072,
 19771,
 24835,
 19607,
 17926,
 9194,
 17619,
 19245,
 21336,
 23093,
 25984,
 8652,
 15988,
 18065,
 8230,
 11600,
 39755,
 8965,
 8618,
 14679,
 19411,
 14268,
 10446,
 18680,
 10828,
 10740,
 11462,
 18800,
 21028,
 26093,
 14578,
 10817,
 16064,
 12301,
 15429,
 11860,
 13877,
 9144,
 13499,
 19290,
 8579,
 8883,
 11345,
 12451,
 18235,
 11809,
 17904,
 34945,
 11092,
 10541,
 18624,
 24840,
 26932,
 25868,
 11689,
 18143,
 12872,
 10153,
 24105,
 20229,
 24618,
 14379,
 13947,
 24149,
 19272,
 13171,
 12165,
 15414,
 11474,
 18416,
 22643,
 18855,
 18951,
 10344,
 9925,
 19710,
 11379,
 10244,
 10591,
 32778,
 24455,
 34115,
 24277,
 25059,
 17000,
 20098,
 16597,
 18987,
 11420,
 13469,
 11084,
 11919,
 11320,
 25363,
 18727,
 19393,
 14555,
 10434,
 12094,
 19053,
 13591,
 10914,
 20300,
 33928,
 8808,
 19444,
 17250,
 29829,
 19429,
 19914,
 24589,
 14201,
 8903,
 10206,
 17082,
 16049,
 13888,
 12206,
 22163,
 21794,
 17354,
 29609,
 11718,
 11328,
 17777,
 16005,
 10622,
 15806,
 19505,
 10482,
 11448,
 15939,
 9217,
 37520,
 15889,
 16902,
 10500,
 10559,
 20882,
 10327,
 12178,
 13745,
 14627,
 16501,
 14812,
 10621,
 11398,
 18792,
 8081,
 14917,
 22820,
 20310,
 15970,
 9576,
 14416,
 11826,
 15202,
 9599,
 8894,
 10020,
 7978,
 28448,
 15593,
 11734,
 8795,
 12258,
 15909,
 12164,
 12653,
 23567,
 17238,
 17399,
 14291,
 13727,
 16849,
 14333,
 16213,
 18708,
 24421,
 17451,
 23076,
 18644,
 8826,
 12264,
 15013,
 11959,
 14863,
 25298,
 14194,
 25433,
 12416,
 16065,
 21353,
 8857,
 10880,
 16551,
 13321,
 12230,
 8354,
 14933,
 12280,
 18888,
 8286,
 12960,
 12946,
 11004,
 15509,
 14465,
 12916,
 16297,
 16498,
 36308,
 11875,
 10987,
 14293,
 13061,
 19037,
 16887,
 12824,
 ...]

In [34]:
column_cleaning['price_per_sqft'].value_counts()

price_per_sqft
10000    10
20000     9
12000     7
16000     7
11044     7
         ..
11933     1
14695     1
11913     1
11313     1
8739      1
Name: count, Length: 1898, dtype: int64

In [35]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))

    .assign(price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()
                    )))
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3 Bedrooms,3 Bathrooms,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

### 3. Bedroom

In [37]:
column_cleaning['bedrooms']

0       2 Bedrooms
1       3 Bedrooms
2       4 Bedrooms
3       3 Bedrooms
4       3 Bedrooms
           ...
2455    4 Bedrooms
2456    3 Bedrooms
2457    3 Bedrooms
2458    3 Bedrooms
2459    4 Bedrooms
Name: bedrooms, Length: 2460, dtype: object

In [38]:
column_cleaning['bedrooms'].unique()

array(['2 Bedrooms', '3 Bedrooms', '4 Bedrooms', '5 Bedrooms',
       '6 Bedrooms', '1 Bedroom'], dtype=object)

In [39]:
column_cleaning['bedrooms'].isnull().sum()

0

In [40]:
column_cleaning['bedrooms'].str.split(" ").str.get(0)

0       2
1       3
2       4
3       3
4       3
       ..
2455    4
2456    3
2457    3
2458    3
2459    4
Name: bedrooms, Length: 2460, dtype: object

In [41]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))

    .assign(
        price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()
                    ))
                    
    .assign(
        bedrooms = lambda df_: pd.to_numeric (df_['bedrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                ))
)
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2,2 Bathrooms,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3,3 Bathrooms,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4,4 Bathrooms,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3,3 Bathrooms,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3,4 Bathrooms,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4,5 Bathrooms,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3,3 Bathrooms,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3,3 Bathrooms,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3,3 Bathrooms,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

### 4. Bathroom

In [42]:
column_cleaning['bathrooms'].unique()

array(['2 Bathrooms', '3 Bathrooms', '4 Bathrooms', '5 Bathrooms',
       '6 Bathrooms', '7 Bathrooms', '1 Bathroom'], dtype=object)

In [43]:
column_cleaning['bathrooms'].str.split(" ").str.get(0)

0       2
1       3
2       4
3       3
4       4
       ..
2455    5
2456    3
2457    3
2458    3
2459    5
Name: bathrooms, Length: 2460, dtype: object

In [44]:
column_cleaning['bathrooms'].isnull().sum()

0

In [46]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))

    .assign(
        price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()
                    ))
                    
    .assign(
        bedrooms = lambda df_: pd.to_numeric (df_['bedrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                ))
    
    .assign(
        bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                ))
)
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2,2,2 Balconies,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3,3,3 Balconies,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4,4,2 Balconies,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3 Balconies,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3,4,3+ Balconies,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4,5,3+ Balconies,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3,3,3+ Balconies,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3 Balconies,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3,3,3 Balconies,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4,5,3+ Balconies,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

### 5. Balcony

In [47]:
column_cleaning['balcony'].unique()

array(['2 Balconies', '3 Balconies', '3+ Balconies', 'No Balcony',
       '1 Balcony'], dtype=object)

In [48]:
column_cleaning['balcony'].str.split(" ").str.get(0)

0        2
1        3
2        2
3        3
4       3+
        ..
2455    3+
2456    3+
2457     3
2458     3
2459    3+
Name: balcony, Length: 2460, dtype: object

In [60]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))

    .assign(
        price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()
                    ))
                    
    .assign(
        bedrooms = lambda df_: pd.to_numeric (df_['bedrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                ))
    
    .assign(
        bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                ))
    .assign(balcony = lambda df_: df_['balcony']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                .replace("No", 0))
)
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2,2,2,Study Room,5th of 24 Floors,North-East,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3,3,3,NaN,Ground of 13 Floors,North-West,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4,4,2,"Servant Room,Store Room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,NaN,12nd of 26 Floors,North-East,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3,4,3+,Servant Room,7th of 14 Floors,North-East,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4,5,3+,Servant Room,5th of 24 Floors,North-West,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3,3,3+,Pooja Room,3rd of 26 Floors,North-East,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,NaN,14th of 26 Floors,North-East,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3,3,3,NaN,6th of 20 Floors,North-West,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4,5,3+,"Servant Room,Pooja Room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

In [61]:
column_cleaning['balcony'].unique()

array(['2', '3', '3+', 0, '1'], dtype=object)

In [62]:
column_cleaning['balcony'].isnull().sum()

0

### 6. Additional Room

In [63]:
column_cleaning['additional_room'].value_counts()

additional_room
Servant Room                                            852
Study Room                                              157
Others                                                  145
Pooja Room                                              134
Study Room,Servant Room                                  78
Pooja Room,Servant Room                                  75
Store Room                                               73
Servant Room,Study Room                                  41
Servant Room,Pooja Room                                  37
Pooja Room,Study Room,Servant Room,Store Room            29
Servant Room,Store Room                                  25
Servant Room,Others                                      18
Servant Room,Study Room,Pooja Room,Store Room            13
Study Room,Others                                        12
Pooja Room,Store Room,Study Room,Servant Room            11
Servant Room,Pooja Room,Study Room,Store Room             7
Pooja Room,Study Room,Servant Room                        7
Study Room,Pooja Room,Servant Room                        7
Pooja Room,Store Room                                     7
Pooja Room,Study Room                                     6
Others,Servant Room                                       6
Study Room,Pooja Room                                     6
Study Room,Store Room                                     6
Pooja Room,Servant Room,Study Room,Others                 5
Study Room,Pooja Room,Store Room,Servant Room             5
Pooja Room,Servant Room,Study Room,Store Room             5
Others,Study Room                                         5
Pooja Room,Study Room,Servant Room,Others                 5
Store Room,Servant Room                                   5
Pooja Room,Others                                         5
Servant Room,Study Room,Pooja Room                        4
Servant Room,Pooja Room,Study Room,Others                 4
Servant Room,Pooja Room,Study Room                        4
Pooja Room,Servant Room,Store Room                        4
Others,Store Room                                         3
Store Room,Study Room                                     3
Servant Room,Store Room,Pooja Room                        3
Servant Room,Study Room,Pooja Room,Others                 3
Pooja Room,Servant Room,Study Room                        3
Pooja Room,Store Room,Study Room                          3
Study Room,Servant Room,Others                            3
Pooja Room,Servant Room,Others,Study Room                 2
Store Room,Study Room,Pooja Room                          2
Study Room,Servant Room,Pooja Room,Store Room             2
Study Room,Others,Servant Room,Pooja Room                 2
Study Room,Pooja Room,Servant Room,Store Room             2
Servant Room,Store Room,Study Room,Pooja Room             2
Study Room,Servant Room,Store Room                        2
Study Room,Store Room,Pooja Room,Servant Room             1
Study Room,Pooja Room,Store Room                          1
Store Room,Servant Room,Pooja Room                        1
Others,Servant Room,Study Room,Pooja Room,Store Room      1
Store Room,Pooja Room,Study Room                          1
Pooja Room,Study Room,Store Room,Servant Room             1
Servant Room,Pooja Room,Store Room                        1
Servant Room,Others,Pooja Room,Study Room                 1
Pooja Room,Servant Room,Others                            1
Store Room,Pooja Room                                     1
Servant Room,Store Room,Pooja Room,Study Room             1
Study Room,Servant Room,Pooja Room                        1
Pooja Room,Study Room,Store Room                          1
Pooja Room,Servant Room,Store Room,Study Room             1
Pooja Room,Study Room,Others                              1
Servant Room,Pooja Room,Store Room,Study Room             1
Servant Room,Others,Study Room                            1
Servant Room,Study Room,Store Room                        1
Pooja Room,Study Room,Others,Servant Room                 1
Others,Pooja Room                                         1
Study Room,Servant Room,Store Room,Pooja Room             1
Others,Servant Room,Study Room,Pooja Room                 1
Servant Room,Others,Study Room,Pooja Room,Store Room      1
Name: count, dtype: int64

In [64]:
column_cleaning['additional_room'].isnull().sum()

599

In [65]:
column_cleaning['additional_room'].fillna('not available')

0                    Study Room
1                 not available
2       Servant Room,Store Room
3                 not available
4                  Servant Room
                 ...
2455               Servant Room
2456                 Pooja Room
2457              not available
2458              not available
2459    Servant Room,Pooja Room
Name: additional_room, Length: 2460, dtype: object

In [66]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))

    .assign(
        price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()
                    )
                    
        ,
        bedrooms = lambda df_: pd.to_numeric (df_['bedrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                )
    
        ,
        bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                )
        ,
        balcony = lambda df_: df_['balcony']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                .replace("No", 0)
        ,
        additional_room =  lambda df_: df_['additional_room']
                                .fillna('not available')
                                .str
                                .lower()
                                )
)
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2,2,2,study room,5th of 24 Floors,North-East,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3,3,3,not available,Ground of 13 Floors,North-West,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4,4,2,"servant room,store room",3rd of 4 Floors,North-East,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,not available,12nd of 26 Floors,North-East,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3,4,3+,servant room,7th of 14 Floors,North-East,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4,5,3+,servant room,5th of 24 Floors,North-West,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3,3,3+,pooja room,3rd of 26 Floors,North-East,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,not available,14th of 26 Floors,North-East,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3,3,3,not available,6th of 20 Floors,North-West,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4,5,3+,"servant room,pooja room",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

### 7. Facing

In [67]:
column_cleaning['facing']

0       North-East
1       North-West
2       North-East
3       North-East
4       North-East
           ...
2455    North-West
2456    North-East
2457    North-East
2458    North-West
2459    North-East
Name: facing, Length: 2460, dtype: object

In [68]:
column_cleaning['facing'].value_counts()

facing
East          764
North-East    685
North         438
West          171
North-West    115
South          65
South-East     64
South-West     52
Name: count, dtype: int64

In [69]:
column_cleaning['facing'].isnull().sum()

106

In [71]:
# --- column cleaning pipeline ---

column_cleaning = (
    df_flat
    .assign(
        society = lambda df_: df_['society']
            .str
            .strip()
            .str
            .lower()
            )

    
    .assign(
        price_in_cr = lambda df_:df_['price_in_cr']
            .str
            .replace('₹','')
            )

    .assign(
        price_in_cr = lambda df_: round(pd.to_numeric(df_['price_in_cr']
            .apply(lambda value: (float(str(value)
            .replace('Cr', '')
            .strip()) if 'Cr' in str(value)
            else float(str(value)
            .replace('Lac', '')
            .strip()) / 100
            ) if value not in ['Price on Request', None, np.nan] else np.nan
                    ))
            ,2))

    .assign(
        price_per_sqft = lambda df_:pd.to_numeric(df_['price_per_sqft']
                    .str
                    .split("₹")
                    .str
                    .get(1)
                    .str
                    .replace("/sqft","")
                    .str
                    .replace(",","")
                    .str 
                    .strip()
                    )
                    
        ,
        bedrooms = lambda df_: pd.to_numeric (df_['bedrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                )
    
        ,
        bathrooms = lambda df_: pd.to_numeric(df_['bathrooms']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                )
        ,
        balcony = lambda df_: df_['balcony']
                                .str
                                .split(" ")
                                .str
                                .get(0)
                                .replace("No", 0)
        ,
        additional_room =  lambda df_: df_['additional_room']
                                .fillna('not available')
                                .str
                                .lower()
                                
        ,
        facing  = lambda df_: df_['facing']
                                .fillna("not available")
                                .str
                                .lower())
)
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2,2,2,study room,5th of 24 Floors,north-east,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3,3,3,not available,Ground of 13 Floors,north-west,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4,4,2,"servant room,store room",3rd of 4 Floors,north-east,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,not available,12nd of 26 Floors,north-east,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3,4,3+,servant room,7th of 14 Floors,north-east,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4,5,3+,servant room,5th of 24 Floors,north-west,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3,3,3+,pooja room,3rd of 26 Floors,north-east,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,not available,14th of 26 Floors,north-east,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3,3,3,not available,6th of 20 Floors,north-west,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4,5,3+,"servant room,pooja room",Ground of 14 Floors,north-east,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."

In [72]:
column_cleaning.isnull().sum()

property_id             0
link                    0
property_name           0
society                 0
price_in_cr             0
price_per_sqft          0
areawithtype            0
bedrooms                0
bathrooms               0
balcony                 0
additional_room         0
floor_info              0
facing                  0
property_age            4
nearby_location         0
furnishing_details    403
features                3
dtype: int64

In [73]:
column_cleaning

,property_id,link,property_name,society,price_in_cr,price_per_sqft,areawithtype,bedrooms,bathrooms,balcony,additional_room,floor_info,facing,property_age,nearby_location,furnishing_details,features
0,L84924514,https://www.99acres.com/2-bhk-bedroom-apartmen...,"2 BHK Flat in Sector 112, Gurgaon",tata gurgaon gateway,2.50,15822,"1,580 sqft (147 sqm) Super Built-up Area",2,2,2,study room,5th of 24 Floors,north-east,0 to 1 Year Old,"['Metro Hospital, Palam Vihar', 'Mount Carmel ...","['3 Wardrobe', '1 Water Purifier', '4 Fan', '3...","['Centrally Air Conditioned', 'Water purifier'..."
1,W81100115,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 37C, Gurgaon",ramprastha the view,1.29,10254,"1,565 sqft (145 sqm) Super Built-up Area",3,3,3,not available,Ground of 13 Floors,north-west,1 to 5 Year Old,"['Elan Miracle Mall', 'Holiday Inn Gurugram Se...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s..."
2,M80850013,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 84, Gurgaon",ss linden floors,2.90,10653,"2,722 sqft (253 sqm) Super Built-up Area",4,4,2,"servant room,store room",3rd of 4 Floors,north-east,0 to 1 Year Old,"['AapnoGhar', 'Modern Public School-kherki Dau...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Lift(s)', 'High Ceiling Height', 'Separate e..."
3,Q85232920,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.65,20075,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,not available,12nd of 26 Floors,north-east,1 to 5 Year Old,"['Hyatt Place Gurgaon Udyog Vihar', 'The Espla...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
4,K85040518,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",emaar imperial gardens,2.40,11851,"2,025 sqft (188 sqm) Super Built-up Area",3,4,3+,servant room,7th of 14 Floors,north-east,1 to 5 Year Old,"['Sunrise University', 'Country Inn & Suites b...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,G81998138,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 102, Gurgaon",adani m2k oyster grande,3.60,11257,"3,198 sqft (297 sqm) Super Built-up Area",4,5,3+,servant room,5th of 24 Floors,north-west,1 to 5 Year Old,"['Gurgaon', 'SGT University', 'Indira Gandhi A...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '25 Lig...","['Centrally Air Conditioned', 'Water purifier'..."
2456,P84081948,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 69, Gurgaon",tulip yellow,2.33,13673,"1,704 sqft (158 sqm) Super Built-up Area",3,3,3+,pooja room,3rd of 26 Floors,north-east,0 to 1 Year Old,"['Hyatt Regency Gurugram', 'De Adventure Park'...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
2457,W78586891,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 102, Gurgaon",shapoorji pallonji joyville gurugram,2.60,14038,"1,852 sqft (172 sqm) Super Built-up Area",3,3,3,not available,14th of 26 Floors,north-east,0 to 1 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['3 Wardrobe', '3 Fan', '3 Light', '1 Modular ...","['Security / Fire Alarm', 'Intercom Facility',..."
2458,O24958549,https://www.99acres.com/3-bhk-bedroom-apartmen...,"3 BHK Flat in Sector 82, Gurgaon",mapsko casa bella,2.05,10459,"1,960 sqft (182 sqm) Super Built-up Area",3,3,3,not available,6th of 20 Floors,north-west,1 to 5 Year Old,"['SkyJumper Trampoline Park', 'Pataudi Road', ...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
2459,P84214334,https://www.99acres.com/4-bhk-bedroom-apartmen...,"4 BHK Flat in Sector 107, Gurgaon",m3m woodshire,2.40,8739,"2,746 sqft (255 sqm) Super Built-up Area",4,5,3+,"servant room,pooja room",Ground of 14 Floors,north-east,1 to 5 Year Old,"['Skylark Cricket Academy', 'Signum 107', 'The...","['8 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Centrally Air Conditioned', 'Water purifier'..."